### ISSUE TITLE
Provide self-contained source tarball

### ISSUE THREAD

**Issue by jeremyevans** [jruby/jruby#1101]
Before 1.7.5, the jruby src tarball included pretty much all of the dependencies needed to build jruby (only external dependencies were java and ant).  Starting with 1.7.5, the jruby src tarball does not contain the dependencies needed to built jruby. Instead, maven will download the dependencies at runtime.

This causes issues when network access is not available at build time.  When packaging software on OpenBSD, all distribution files are checksummed, and network access is not available during build time for security and consistency reasons.  The only way to build jruby with these restrictions is to download all the dependencies by running a full build of jruby outside of the packaging system, then tar up the maven repository.  When building jruby inside the packaging system, untar that maven repository (treated as another checksummed distribution tarball), and then run maven in offline mode with that repository. While this works, it's much more difficult than it was before.

The other advantage I can see to shipping a self-contained source tarball is that it requires a smaller download for the builder.  jruby 1.7.4 src tarball is about 26M, and 1.7.5 is about 13M.  However, the tarball of build dependencies that maven downloads while building jruby is about 33M, so in total you have to download a lot more with jruby 1.7.5 than you did with jruby 1.7.4.

**Comment by jtarchie** [comment]
We are trying to build JRuby, specifically with reproducible builds, which are byte-for-byte duplicates each time we compile.

To minimize the interactions with external I/O, we'd like to bundle all the packages needed for JRuby with our source. Our current build commands:

```
mvn dependency:go-offline
mvn -o
```

This fails with:

```
INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] JRuby
[INFO] JRuby Core
[INFO] JRuby Truffle
[INFO] JRuby Lib Setup
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby 9.0.4.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ jruby-parent ---
[WARNING] The POM for org.apache.maven.enforcer:enforcer-api:jar:1.0 is missing, no dependency information available
[WARNING] The POM for org.apache.maven.enforcer:enforcer-rules:jar:1.0 is missing, no dependency information available
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-parent ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jruby-parent ---
[WARNING] The POM for org.codehaus.plexus:plexus-utils:jar:3.0.5 is missing, no dependency information available
[WARNING] The POM for org.codehaus.plexus:plexus-digest:jar:1.0 is missing, no dependency information available
[INFO] Installing /tmp/x86_64-linux-gnu/ports/jruby/9.0.4.0_ruby-2.2.2/jruby-9.0.4.0/.polyglot.pom.rb to /root/.m2/repository/org/jruby/jruby-parent/9.0.4.0/jruby-parent-9.0.4.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby Core 9.0.4.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ jruby-core ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-core ---
[INFO]
[INFO] --- maven-antrun-plugin:1.7:run (default) @ jruby-core ---
[WARNING] The POM for org.apache.maven:maven-plugin-api:jar:2.0.11 is missing, no dependency information available
[WARNING] The POM for org.apache.maven:maven-project:jar:2.0.11 is missing, no dependency information available
[WARNING] The POM for org.apache.maven:maven-artifact:jar:2.0.11 is missing, no dependency information available
[WARNING] The POM for org.apache.ant:ant:jar:1.8.2 is missing, no dependency information available
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JRuby .............................................. SUCCESS [  0.738 s]
[INFO] JRuby Core ......................................... FAILURE [  0.332 s]
[INFO] JRuby Truffle ...................................... SKIPPED
[INFO] JRuby Lib Setup .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.901 s
[INFO] Finished at: 2015-11-17T19:42:40+00:00
[INFO] Final Memory: 22M/52M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project jruby-core: Error executing ant tasks: org/apache/tools/ant/launch/Locator: org.apache.tools.ant.launch.Locator -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project jruby-core: Error executing ant tasks: org/apache/tools/ant/launch/Locator
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error executing ant tasks: org/apache/tools/ant/launch/Locator
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:360)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/launch/Locator
	at org.apache.tools.ant.util.FileUtils.fromURI(FileUtils.java:1231)
	at org.apache.tools.ant.Location.<init>(Location.java:90)
	at org.apache.tools.ant.Location.<init>(Location.java:73)
	at org.apache.tools.ant.helper.ProjectHelper2$ProjectHandler.onStartElement(ProjectHelper2.java:729)
	at org.apache.tools.ant.helper.ProjectHelper2$RootHandler.startElement(ProjectHelper2.java:600)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:614)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3135)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:307)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:178)
	at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:82)
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:264)
	... 22 more
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Locator
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 44 more
[ERROR]
```

I am providing this information as a placeholder. We are currently trying to track down the issue, but if anyone happens to Google this, and find answers with the same stack trace.

**Comment by enebo** [comment]
@jtarchie can you try this with master now and see if this got better?  Ruby+Truffle is no longer part of our build so the place it failed in your output no longer exists.

**Comment by jtarchie** [comment]
@flavorjones, there is an update to this. Are you able to follow up?

**Comment by flavorjones** [comment]
@jtarchie You bet.

**Comment by headius** [comment]
I don't think there's anything else to do here.

JRuby's "dist" source tarball does include all sources from a git checkout, and can be built with Maven. Maven itself provides other mechanisms for pre-fetching dependencies, so this tarball can be post-processed into an "all-in-one" if necessary.

The other JRuby artifacts contain fully-built forms of JRuby and the fully-built JRuby distribution, which will work without further builds on whatever lowest Java version it supports (currently 1.8 for the 9.4.x series).

It is not typical for Java projects to publish source tarballs that contain jars, because those jars would still need to be verified against a trusted source, and it's better in that case to just fetch them from that source. That's what Maven does during its build.
