### ISSUE TITLE
"Your jruby version is 1.7.6.dev, but your Gemfile specified jruby 1.7.6"

### ISSUE THREAD

**Issue by JasonLunn** [jruby/jruby#1152]
After upgrading to jruby-1.7.6, warbler deployment to Tomcat dies on startup:

```
2013-10-23 10:43:45,929 INFO  jruby.rack:42 {} [localhost-startStop-1]: jruby 1.7.6.dev (1.9.3p392) 2013-10-22 17b3966 on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-462-11M4609 [darwin-x86_64]
2013-10-23 10:43:46,014 INFO  jruby.rack:42 {} [localhost-startStop-1]: using a shared (threadsafe!) runtime
2013-10-23 10:43:50,946 ERROR jruby.rack:54 {} [localhost-startStop-1]: initialization failed
org.jruby.rack.RackInitializationException: Your jruby version is 1.7.6.dev, but your Gemfile specified jruby 1.7.6
	from /usr/local/rvm/gems/jruby-1.7.6@global/gems/bundler-1.3.5/lib/bundler/definition.rb:361:in `validate_ruby!'
	from /usr/local/rvm/gems/jruby-1.7.6@global/gems/bundler-1.3.5/lib/bundler.rb:116:in `setup'
	from /usr/local/rvm/gems/jruby-1.7.6@global/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `(root)'
	from org/jruby/RubyKernel.java:1082:in `require'
	from jar:file:/opt/apache-tomcat-7.0.42/webapps/ROOT/WEB-INF/lib/gems-gems-jruby-jars-1.7.6-lib-jruby-stdlib-complete-1.7.6.dev.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29) ~[gems-gems-jruby-rack-1.1.13.2-lib-jruby-rack-1.1.13.2.jar:na]
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98) ~[gems-gems-jruby-rack-1.1.13.2-lib-jruby-rack-1.1.13.2.jar:na]
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50) ~[gems-gems-jruby-rack-1.1.13.2-lib-jruby-rack-1.1.13.2.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939) [catalina.jar:7.0.42]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434) [catalina.jar:7.0.42]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.42]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.42]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.42]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633) [catalina.jar:7.0.42]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976) [catalina.jar:7.0.42]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1653) [catalina.jar:7.0.42]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_65]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_65]
	at java.lang.Thread.run(Thread.java:695) [na:1.6.0_65]

```

**Comment by rtyler** [comment]
I believe this can be safely closed, I've used warbler with pretty much every release of the past year successfully :P
