### ISSUE TITLE
Open3.capture3 error on Windows

### ISSUE THREAD

**Issue by ndrluis** [jruby/jruby#1187]
Ubuntu Raring + Ruby 2.0 MRI

```
vagrant@vagrant-ubuntu-raring-64:~$ irb
2.0.0p247 :001 > require 'open3'
 => true
2.0.0p247 :002 > o, e, s = Open3.capture3("ruby -wc", stdin_data: "puts 1")
 => ["Syntax OK\n", "", #<Process::Status: pid 9819 exit 0>]
```

jruby 1.7.6 (2.0.0p195) 2013-10-22 6004147 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_17-b02 [Windows 7-amd64]

```
irb(main):001:0> require 'open3'
true
irb(main):002:0> o, e, s = Open3.capture3("jruby -wc", stdin_data: "puts 1")
IOError: Cannot run program "jruby -wc" (in directory "c:\jruby-1.7.6"): CreateProcess error=2, The system cannot find the file specified.
    from org/jruby/RubyIO.java:4337:in `popen3'
    from C:/jruby-1.7.6/lib/ruby/1.9/open3.rb:74:in `popen3'
    from C:/jruby-1.7.6/lib/ruby/1.9/open3.rb:272:in `capture3'
    from (irb):2:in `evaluate'
    from org/jruby/RubyKernel.java:1121:in `eval'
    from org/jruby/RubyKernel.java:1517:in `loop'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from C:\jruby-1.7.6\/bin/jirb_swing:53:in `(root)'
```

**Comment by enebo** [comment]
Still an issue on 1.7 and 9.x

**Comment by headius** [comment]
FWIW this is fine with 9.x on UNIX, probably because it's doing real native process logic for e.g. `spawn`, used heavily by `open3`. Getting native process logic in for Windows would likely fix this.
