### ISSUE TITLE
relative_path_from returns errors for "C:/" and "C:\\"

### ISSUE THREAD

**Issue by sanelson2000** [jruby/jruby#1227]
This appears to be an old issue which has resurfaced:
[JRUBY-3621](https://jira.codehaus.org/browse/JRUBY-3621)

I am running JRuby 1.7.6 on Windows.

```
>> Pathname.new('C:/').relative_path_from(Pathname.new("C:\\test"))
ArgumentError: different prefix: "C:/" and "C:\\temp"
    from C:/jruby/jruby-1.7.6/lib/ruby/1.9/pathname.rb:465:in `relative_path_from'
    from (irb):3:in `evaluate'
    from org/jruby/RubyKernel.java:1121:in `eval'
    from org/jruby/RubyKernel.java:1517:in `loop'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from C:/jruby/jruby-1.7.6/lib/ruby/gems/shared/gems/railties-4.0.1/lib/rails/commands/console.rb:90:in `start'
    from C:/jruby/jruby-1.7.6/lib/ruby/gems/shared/gems/railties-4.0.1/lib/rails/commands/console.rb:9:in `start'
    from C:/jruby/jruby-1.7.6/lib/ruby/gems/shared/gems/railties-4.0.1/lib/rails/commands.rb:62:in `(root)'
    from org/jruby/RubyKernel.java:1082:in `require'
    from C:/workspaces/balancedinsight/consensus/script/rails:1:in `(root)'
    from org/jruby/RubyKernel.java:1101:in `load'
    from -e:1:in `(root)'
```

**Comment by enebo** [comment]
This works on JRuby 9.x and we are EOLing 1.7.x soon and won't be fixing this there.
