### ISSUE TITLE
Lazy load Digest::SHA256 is not thread safe

### ISSUE THREAD

**Issue by vinayshastry** [jruby/jruby#1279]
Hi,

Recently we observed that our production log has load error for Digest::SHA256 resulting in,

NotImplementedError: the Digest::SHA256() function is unimplemented on this machine

This is reproducible on master with the following change,

1. Add sleep into RubyDigest so that it takes a while to assign metadata,
on 413f5dd19f861fea53d2a3e7133e852db69aea5f, at line 228 of RubyDigest, insert snippet,
```java
try {
            System.out.println("sleep 10 seonds before instance v set");
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
```
2. Run the following ruby script,
```ruby
require 'digest'
threads = []
100.times do
  threads << (Thread.new do
    begin
      Digest::SHA256.new
    rescue Exception => e
      puts "[DEBUG]e => #{e.inspect}"
    end
  end)
end
threads.each(&:join)
```

I have attached an image of the RubyDigest with sleep code.

![screen shot 2013-11-27 at 2 15 59 pm](https://f.cloud.github.com/assets/596787/1635559/953e3108-57b1-11e3-8348-2b59ad18ebaa.png)

Thanks,
Vinay.

**Comment by headius** [comment]
Still an issue, but appears to be differently broken:

```
```

The following patch fixes it but I have no investigated whether there's a bug (e.g. in our locking multi-thread require) we should fix.

```diff
diff --git a/lib/ruby/stdlib/digest.rb b/lib/ruby/stdlib/digest.rb
index d6daf36..2625f31 100644
--- a/lib/ruby/stdlib/digest.rb
+++ b/lib/ruby/stdlib/digest.rb
@@ -6,22 +6,24 @@ module Digest
   REQUIRE_MUTEX = Mutex.new
 
   def self.const_missing(name) # :nodoc:
-    case name
-    when :SHA256, :SHA384, :SHA512
-      lib = 'digest/sha2.so'
-    else
-      lib = File.join('digest', name.to_s.downcase)
-    end
+    Digest::REQUIRE_MUTEX.synchronize do
+      case name
+      when :SHA256, :SHA384, :SHA512
+        lib = 'digest/sha2.so'
+      else
+        lib = File.join('digest', name.to_s.downcase)
+      end
 
-    begin
-      require lib
-    rescue LoadError
-      raise LoadError, "library not found for class Digest::#{name} -- #{lib}", caller(1)
-    end
-    unless Digest.const_defined?(name)
-      raise NameError, "uninitialized constant Digest::#{name}", caller(1)
+      begin
+        require lib
+      rescue LoadError
+        raise LoadError, "library not found for class Digest::#{name} -- #{lib}", caller(1)
+      end
+      unless Digest.const_defined?(name)
+        raise NameError, "uninitialized constant Digest::#{name}", caller(1)
+      end
+      Digest.const_get(name)
     end
-    Digest.const_get(name)
   end
 
   class ::Digest::Class
```

**Comment by headius** [comment]
Fixed for 9k and 1.7.

**Comment by perlun** [comment]
Incredibly weird - I just saw this when building a Docker image. Here is the backtrace:

## Backtrace

```
NotImplementedError: the Digest::SHA256() function is unimplemented on this machine
  org/jruby/RubyClass.java:232:in `allocate'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/rubygems_gem_installer.rb:28:in `block in validate_bundler_checksum'
  org/jruby/RubyIO.java:1156:in `open'
  org/jruby/RubyKernel.java:306:in `open'
  /opt/jruby/lib/ruby/stdlib/rubygems/package/file_source.rb:30:in `with_read_io'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/rubygems_gem_installer.rb:27:in `validate_bundler_checksum'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/rubygems_gem_installer.rb:17:in `pre_install_checks'
  /opt/jruby/lib/ruby/stdlib/rubygems/installer.rb:281:in `install'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/source/rubygems.rb:136:in `block in install'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/rubygems_integration.rb:195:in `preserve_paths'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/source/rubygems.rb:135:in `install'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/installer/gem_installer.rb:55:in `install'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/installer/parallel_installer.rb:115:in `block in worker_pool'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/worker.rb:63:in `apply_func'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/worker.rb:58:in `block in process_queue'
  org/jruby/RubyKernel.java:1292:in `loop'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/worker.rb:55:in `process_queue'
  /opt/jruby/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/worker.rb:89:in `block in create_threads'
```

## Environment

```
Bundler   1.15.4
Rubygems  2.6.13
Ruby      2.3.3p0 (2017-09-06 revision 56859) [java]
GEM_HOME  /build/ruby/vendor/bundle/jruby/2.3.0
GEM_PATH
Git       not installed
Platform  universal-java-1.8
OpenSSL   JRuby-OpenSSL 0.9.21
```

The Dockerfile has this `FROM` line:

`FROM jruby:9.1.13-jre as jruby-builder`

I can very well create a new GitHub issue for this if you like, but it _feels_ like it's the original problem coming back somehow... so we could as well reopen this one.

**Comment by perlun** [comment]
(I only saw this one single time. Subsequent times it has worked flawlessly.)
