### ISSUE TITLE
Return values from Java are converted to Ruby even if you're not using them

### ISSUE THREAD

**Issue by trejkaz** [jruby/jruby#1407]
Something I found quite by accident while benchmarking a method of ours. We had a test along these lines:

```
method = :whatever
10_000_000.times do
  obj.send(method)
end
```

I was profiling to see where it was spending its time and over 90% of the time, it was here:

```
"SwingWorker-pool-14-thread-3@10177" daemon prio=5 tid=0x72 nid=NA runnable
java.lang.Thread.State: RUNNABLE
      at java.lang.System.identityHashCode(System.java:-1)
      at org.jruby.javasupport.util.ObjectProxyCache.hash(ObjectProxyCache.java:174)
      at org.jruby.javasupport.util.ObjectProxyCache.getOrCreate(ObjectProxyCache.java:163)
      at org.jruby.javasupport.Java.getInstance(Java.java:392)
      at org.jruby.javasupport.Java.getInstance(Java.java:371)
      at org.jruby.javasupport.JavaUtil.convertJavaToUsableRubyObject(JavaUtil.java:167)
      at org.jruby.javasupport.JavaMethod.convertReturn(JavaMethod.java:517)
      at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441)
      at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:304)
      at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:52)
      at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:113)
      at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:81)
      at org.jruby.RubyClass.finvoke(RubyClass.java:527)
      at org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1504)
      at org.jruby.RubyKernel.send19(RubyKernel.java:2240)
      at org.jruby.RubyKernel$INVOKER$s$send19.call(RubyKernel$INVOKER$s$send19.gen:-1)
      at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:350)
      at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
      at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
```

It seems like JRuby is spending over 90% of the time preparing the return value so that the Ruby script can use it, even though the script doesn't use it.

**Comment by enebo** [comment]
We do detect unused values in our IR but our IR knows nothing of Java Integration features so our ability to detect this now is not there.
