### ISSUE TITLE
File.chmod on Windows network UNC path throws Errno::ERSCH

### ISSUE THREAD

**Issue by rearadmiral** [jruby/jruby#1479]
Even though chmod on Windows is a no-op according to what I read, recent versions of jruby throw an "Errno::ERSCH No such process" error when calling this on a UNC network path.  They used to run without error.  The actual usage is coming from a file attachment gem we're using.

I reproduced it in IRB:

```
Welcome to the JRuby IRB Console [1.7.9 (1.8.7)]
irb(main):003:0> path = "\\\\10.38.6.252\\tmp\\test.txt"
"\\\\10.38.6.252\\mingle09data\\tmp\\test.txt"
irb(main):004:0> File.exist? path
true
irb(main):005:0> File.chmod 420, path
Errno::ESRCH: No such process - No message available
    from org/jruby/RubyFile.java:590:in `chmod'
    from (irb):5:in `evaluate'
    from org/jruby/RubyKernel.java:1114:in `eval'
    from C:/jruby-1.7.9/lib/ruby/1.8/irb.rb:158:in `eval_input'
    from C:/jruby-1.7.9/lib/ruby/1.8/irb.rb:271:in `signal_status'
    from C:/jruby-1.7.9/lib/ruby/1.8/irb.rb:155:in `eval_input'
    from org/jruby/RubyKernel.java:1519:in `loop'
    from org/jruby/RubyKernel.java:1268:in `catch'
    from C:/jruby-1.7.9/lib/ruby/1.8/irb.rb:154:in `eval_input'
    from C:/jruby-1.7.9/lib/ruby/1.8/irb.rb:71:in `start'
    from org/jruby/RubyKernel.java:1268:in `catch'
    from C:/jruby-1.7.9/lib/ruby/1.8/irb.rb:70:in `start'
    from C:\jruby-1.7.9\/bin/jirb_swing:53:in `(root)'
```

I verified it works fine in 1.7.2:

```
Welcome to the JRuby IRB Console [1.7.2 (1.8.7)]
irb(main):001:0> path = "\\\\10.38.6.252\\tmp\\test.txt"
irb(main):002:0> File.exist? path
true
irb(main):003:0> File.chmod 420, path
0
```

If I map the above path to drive Z:, it throws no error.

```
Welcome to the JRuby IRB Console [1.7.9 (1.8.7)]
irb(main):001:0> path = "Z:\\test.txt"
"Z:\\test.txt"
irb(main):002:0> File.exist? path
true
irb(main):003:0> File.chmod 420, path
1
```

**Comment by kares** [comment]
@MSNexploder any chance you could check if its still an issue on Windows for us ?

**Comment by MSNexploder** [comment]
Sure!

Looks like this is working using 9.1.9.0 on Windows 7 (x64):
```
path = "\\\\192.168.2.104\\stefan\\Desktop\\test.txt"
File.exist? path # => true
File.chmod 420, path # => 1
```
and file permissions did indeed change

**Comment by kares** [comment]
:yellow_heart: :yum: :blue_heart: :blush:
