### ISSUE TITLE
Unusual linkage error in data race regression spec

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1518]
Saw this on a local run of test:extended on OpenJDK8 (on jruby-1_7). Worth investigating; could be some issue with how we're loading jitted methods that's logging errors but not breaking anything. The spec involved was added for #999.

```
Exception in thread "RubyThread-3570: /Users/headius/projects/jruby-1.7/spec/regression/GH-999_colon2_data_race_spec.rb:41" java.lang.RuntimeException: com.headius.invokebinder.InvalidTransformException: java.lang.IllegalAccessException: no such method: rubyjit.#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940.__file__(#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940,ThreadContext,IRubyObject,Block)IRubyObject/invokeStatic
    at org.jruby.runtime.invokedynamic.InvocationLinker.createRubyHandle(InvocationLinker.java:1689)
    at org.jruby.runtime.invokedynamic.InvocationLinker.access$900(InvocationLinker.java:75)
    at org.jruby.runtime.invokedynamic.InvocationLinker$RubyCallGenerator.generate(InvocationLinker.java:715)
    at org.jruby.runtime.invokedynamic.InvocationLinker.tryDispatchDirect(InvocationLinker.java:765)
    at org.jruby.runtime.invokedynamic.InvocationLinker.getTarget(InvocationLinker.java:775)
    at org.jruby.runtime.invokedynamic.InvocationLinker.invocationFallback(InvocationLinker.java:137)
    at rubyjit.Object$$casething_92757ec4b8ad88bbfdd34ae731998b74d8a09528681842940.__file__(/Users/headius/projects/jruby-1.7/spec/regression/GH-999_colon2_data_race_spec.rb:33)
    at rubyjit.Object$$casething_92757ec4b8ad88bbfdd34ae731998b74d8a09528681842940.__file__(/Users/headius/projects/jruby-1.7/spec/regression/GH-999_colon2_data_race_spec.rb)
    at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
    at org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:130)
    at org.jruby.runtime.Block.yieldSpecific(Block.java:111)
    at org.jruby.RubyFixnum.times(RubyFixnum.java:275)
    at org.jruby.RubyFixnum$INVOKER$i$0$0$times.call(RubyFixnum$INVOKER$i$0$0$times.gen)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    at org.jruby.runtime.Block.call(Block.java:101)
    at org.jruby.RubyProc.call(RubyProc.java:290)
    at org.jruby.RubyProc.call(RubyProc.java:228)
    at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.headius.invokebinder.InvalidTransformException: java.lang.IllegalAccessException: no such method: rubyjit.#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940.__file__(#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940,ThreadContext,IRubyObject,Block)IRubyObject/invokeStatic
    at com.headius.invokebinder.Binder.invokeStaticQuiet(Binder.java:1079)
    at org.jruby.runtime.invokedynamic.InvocationLinker.createRubyHandle(InvocationLinker.java:1678)
    ... 32 more
Caused by: java.lang.IllegalAccessException: no such method: rubyjit.#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940.__file__(#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940,ThreadContext,IRubyObject,Block)IRubyObject/invokeStatic
    at java.lang.invoke.MemberName.makeAccessException(MemberName.java:872)
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:993)
    at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1377)
    at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:774)
    at com.headius.invokebinder.Binder.invokeStatic(Binder.java:1055)
    at com.headius.invokebinder.Binder.invokeStaticQuiet(Binder.java:1077)
    ... 33 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "rubyjit.#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940.__file__(Lrubyjit/#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940;Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/Block;)Lorg/jruby/runtime/builtin/IRubyObject;" the class loader (instance of org/jruby/util/ClassCache$OneShotClassLoader) of the current class, rubyjit/Object$$casething_92757ec4b8ad88bbfdd34ae731998b74d8a09528681842940, and the class loader (instance of org/jruby/util/ClassCache$OneShotClassLoader) for the method's defining class, rubyjit/#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940, have different Class objects for the type rubyjit/#<Class:0x667be900>$$value_ecbb46495ee673a8527e741a16144e7e91fe3273681842940 used in the signature
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
    at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
    ... 37 more
```

**Comment by cristim** [comment]
Are there any updates on this issue?

I recently updated to java 1.8 and I started getting this error.

I'm still running jruby-1.7.12 but I could update if there's a fix in a newer release.
