### ISSUE TITLE
JRuby > 1.7.0 doesn't work with Oanda FXClient

### ISSUE THREAD

**Issue by josacar** [jruby/jruby#1553]
When using [oanda](http://www.oanda.com/) [fxclient](http://fxtrade.oanda.ca/trade-forex/api/) Java libraries, an exception is thrown when getting `EventManager` from `RateTable`.

Using [provided jar](http://dynamic-api.oanda.com/oanda_fxtrade_implementation.jar) and this code:

```ruby
require 'java'
require 'oanda_fxtrade_implementation.jar'
 
fxclient = com.oanda.fxtrade.api.API.createFXGame
fxclient.with_keep_alive_thread = true
fxclient.with_rate_thread = true
fxclient.login 'xxxxx', 'xxxx'
fxclient.rate_table.event_manager
```

The following exception is thrown:

```
Class.java:-2:in `getDeclaringClass': java.lang.IncompatibleClassChangeError: com.oanda.fxtrade.api.implementation.RateTable and com.oanda.fxtrade.api.implementation.RateTable$c disagree on InnerClasses attribute
	from Class.java:1123:in `getEnclosingClass'
	from Class.java:1267:in `getSimpleBinaryName'
	from Class.java:1159:in `getSimpleName'
	from JavaClass.java:743:in `setupProxy'
	from Java.java:574:in `createProxyClass'
	from Java.java:502:in `createProxyClassForClass'
	from JavaSupport.java:154:in `computeValue'
	from JavaSupport.java:151:in `computeValue'
	from MapBasedClassValue.java:18:in `get'
	from JavaSupport.java:207:in `getProxyClassFromCache'
	from Java.java:450:in `getProxyClass'
	from Java.java:389:in `getInstance'
	from Java.java:371:in `getInstance'
	from JavaUtil.java:167:in `convertJavaToUsableRubyObject'
	from JavaMethod.java:517:in `convertReturn'
	from JavaMethod.java:441:in `invokeDirectWithExceptionHandling'
	from JavaMethod.java:304:in `invokeDirect'
	from InstanceMethodInvoker.java:52:in `call'
	from AliasMethod.java:56:in `call'
	from CachingCallSite.java:306:in `cacheAndCall'
	from CachingCallSite.java:136:in `call'
	from a.rb:8:in `__file__'
	from a.rb:-1:in `load'
	from Ruby.java:811:in `runScript'
	from Ruby.java:804:in `runScript'
	from Ruby.java:673:in `runNormally'
	from Ruby.java:522:in `runFromMain'
	from Main.java:395:in `doRunFromMain'
	from Main.java:290:in `internalRun'
	from Main.java:217:in `run'
	from Main.java:197:in `main'
```

The equivalent Java code works as expected:

```java
import com.oanda.fxtrade.api.API;
import com.oanda.fxtrade.api.FXClient;
import com.oanda.fxtrade.api.SessionDisconnectedException;
import com.oanda.fxtrade.api.InvalidUserException;
import com.oanda.fxtrade.api.InvalidPasswordException;
import com.oanda.fxtrade.api.SessionException;
import com.oanda.fxtrade.api.MultiFactorAuthenticationException;
 
class OandaRunner {
  public static void main (String args[]){
    try {
      FXClient fxclient = com.oanda.fxtrade.api.API.createFXGame();
      fxclient.setWithKeepAliveThread(true);
      fxclient.setWithRateThread(true);
      fxclient.login("xxx", "xxx");
      fxclient.getRateTable().getEventManager();
    } catch ( InvalidUserException iue ) {
    } catch ( SessionDisconnectedException sde ) {
    } catch ( InvalidPasswordException ipe ) {
    } catch ( SessionException se ) {
    } catch ( MultiFactorAuthenticationException mfae ) {
    }
  }
}
```

The client is working with Jruby 1.6.x series and 1.7.0. With >= 1.7.1 it breaks when calling `event_manager`.

Tested with OpenJDK 6 and Oracle JDK 7.

**Comment by josacar** [comment]
```
$ bin/peertransfer_exchange
/bin/sh: cannot create tmp/pids/exchange.pid: Directory nonexistent
[daemon-kit]: DaemonKit (0.1.8.2) booting in production mode
[daemon-kit]: Setting up trap for USR1
The signal USR1 is in use by the JVM and will not work correctly on this platform
[daemon-kit]: Setting up trap for USR2
[daemon-kit]: Setting up trap for HUP
[daemon-kit]: Setting up trap for INT
[daemon-kit]: Setting up trap for TERM
[daemon-kit]: DaemonKit (0.1.8.2) booted, now running peertransfer_exchange
API proxy version          : 2.6.2
API implementation jar     : http://dynamic-api.oanda.com/oanda_fxtrade_implementation.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2015-07-26 00:30:57.597 +0000 I [main] Connection manager: using proxy=none for connection to fxserver02-cr.oanda.com on port=9700
2015-07-26 00:30:57.599 +0000 I [main] - connecting to fxserver02-cr.oanda.com/204.93.159.166: 9700
2015-07-26 00:30:58.108 +0000 I [main] sent seqid=0 /fxtrade/cr/LoginRequest at 1437870657 in 127 ms
2015-07-26 00:30:58.212 +0000 I [DispatcherThread] received seqid=0 /fxtrade/cr/LoginReply sendtime=1437870658 uniqueMsgId=CRgamecs01_175548658195284
2015-07-26 00:30:58.333 +0000 I [main] sent seqid=1 /fxtrade/fxe/UserDataRequest at 1437870658 in 109 ms
2015-07-26 00:30:58.388 +0000 I [DispatcherThread] received seqid=1 /fxtrade/fxe/FXEResponse sendtime=1437870658 uniqueMsgId=CRgamecs01_175548658419698
2015-07-26 00:30:58.690 +0000 I [main] sent seqid=2 /fxtrade/fxe/SymbolsRequest at 1437870658 in 1 ms
2015-07-26 00:30:58.757 +0000 I [DispatcherThread] received seqid=2 /fxtrade/fxe/FXEResponse sendtime=1437870658 uniqueMsgId=CRgamecs01_175548658768052
2015-07-26 00:30:58.901 +0000 I [main] sent seqid=3 /fxtrade/fxe/StreamRequest at 1437870658 in 1 ms
2015-07-26 00:30:58.945 +0000 I [DispatcherThread] received seqid=3 /fxtrade/fxe/FXEResponse sendtime=1437870658 uniqueMsgId=CRgamecs01_175548658977856
2015-07-26 00:30:59.050 +0000 I [main] sent seqid=4 /fxtrade/notification/NotificationRegistration at 1437870659 in 12 ms
2015-07-26 00:30:59.135 +0000 I [DispatcherThread] received seqid=4 /fxtrade/notification/NotificationRegistrationReply sendtime=1437870659
2015-07-26 00:30:59.145 +0000 I [main] sent seqid=5 /fxtrade/fxe/GetInstrumentMarginRateRequest at 1437870659 in 0 ms
2015-07-26 00:30:59.191 +0000 I [DispatcherThread] received seqid=5 /fxtrade/fxe/FXEResponse sendtime=1437870659 uniqueMsgId=CRgamecs01_175548659223978
2015-07-26 00:30:59.212 +0000 I [KeepAliveThread] sent seqid=6 /fxtrade/cr/PingRequest at 1437870659 in 12 ms
2015-07-26 00:30:59.218 +0000 I [PollThread] sent seqid=7 /fxtrade/fxe/StreamRequest at 1437870659 in 1 ms
2015-07-26 00:30:59.255 +0000 I [DispatcherThread] received seqid=6 /fxtrade/cr/PingReply sendtime=1437870659 uniqueMsgId=CRgamecs01_175548659290959
2015-07-26 00:30:59.294 +0000 I [DispatcherThread] received seqid=7 /fxtrade/fxe/FXEResponse sendtime=1437870659 uniqueMsgId=CRgamecs01_175548659327890
oanda_subscriber.rb:36: Tracking 20: ["eur/eur", "eur/usd", "eur/jpy", "eur/gbp", "gbp/usd", "usd/jpy", "usd/sgd", "usd/mxn", "usd/try", "usd/hkd", "usd/sar", "usd/cad", "aud/usd", "usd/chf", "nzd/usd", "usd/zar", "usd/usd", "usd/krw", "usd/inr", "usd/brl"] currencies.
2015-07-26 00:31:02.262 +0000 I [KeepAliveThread] sent seqid=8 /fxtrade/cr/PingRequest at 1437870662 in 0 ms
2015-07-26 00:31:02.303 +0000 I [DispatcherThread] received seqid=8 /fxtrade/cr/PingReply sendtime=1437870662 uniqueMsgId=CRgamecs01_175548662342443
2015-07-26 00:31:05.306 +0000 I [KeepAliveThread] sent seqid=9 /fxtrade/cr/PingRequest at 1437870665 in 0 ms
2015-07-26 00:31:05.349 +0000 I [DispatcherThread] received seqid=9 /fxtrade/cr/PingReply sendtime=1437870665 uniqueMsgId=CRgamecs01_175548665386845
2015-07-26 00:31:08.351 +0000 I [KeepAliveThread] sent seqid=10 /fxtrade/cr/PingRequest at 1437870668 in 0 ms
2015-07-26 00:31:08.393 +0000 I [DispatcherThread] received seqid=10 /fxtrade/cr/PingReply sendtime=1437870668 uniqueMsgId=CRgamecs01_175548668435318
2015-07-26 00:31:11.395 +0000 I [KeepAliveThread] sent seqid=11 /fxtrade/cr/PingRequest at 1437870671 in 0 ms
2015-07-26 00:31:11.434 +0000 I [DispatcherThread] received seqid=11 /fxtrade/cr/PingReply sendtime=1437870671 uniqueMsgId=CRgamecs01_175548671477607
2015-07-26 00:31:14.436 +0000 I [KeepAliveThread] sent seqid=12 /fxtrade/cr/PingRequest at 1437870674 in 1 ms
2015-07-26 00:31:14.476 +0000 I [DispatcherThread] received seqid=12 /fxtrade/cr/PingReply sendtime=1437870674 uniqueMsgId=CRgamecs01_175548674520290
2015-07-26 00:31:17.480 +0000 I [KeepAliveThread] sent seqid=13 /fxtrade/cr/PingRequest at 1437870677 in 1 ms
2015-07-26 00:31:17.537 +0000 I [DispatcherThread] received seqid=13 /fxtrade/cr/PingReply sendtime=1437870677 uniqueMsgId=CRgamecs01_175548677582347
2015-07-26 00:31:20.540 +0000 I [KeepAliveThread] sent seqid=14 /fxtrade/cr/PingRequest at 1437870680 in 1 ms
2015-07-26 00:31:20.581 +0000 I [DispatcherThread] received seqid=14 /fxtrade/cr/PingReply sendtime=1437870680 uniqueMsgId=CRgamecs01_175548680625197
2015-07-26 00:31:23.587 +0000 I [KeepAliveThread] sent seqid=15 /fxtrade/cr/PingRequest at 1437870683 in 1 ms
2015-07-26 00:31:23.631 +0000 I [DispatcherThread] received seqid=15 /fxtrade/cr/PingReply sendtime=1437870683 uniqueMsgId=CRgamecs01_175548683679366
2015-07-26 00:31:26.633 +0000 I [KeepAliveThread] sent seqid=16 /fxtrade/cr/PingRequest at 1437870686 in 0 ms
2015-07-26 00:31:26.674 +0000 I [DispatcherThread] received seqid=16 /fxtrade/cr/PingReply sendtime=1437870686 uniqueMsgId=CRgamecs01_175548686721917
^C[daemon-kit]: Running signal traps for INT
2015-07-26 00:31:26.963 +0000 I [DispatcherThread] OFacade.DispatcherThread.run: Stopping normally Socket closed
[daemon-kit]: Running shutdown hooks
[daemon-kit]: Shutting down peertransfer_exchange
```

**Comment by josacar** [comment]
Need to test when market is open :8ball:

**Comment by BanzaiMan** [comment]
I just tested it with 1.7.13 (the oldest release I have), 1.7.21, and master (@4fa224f), and they all work.

```sh-session
$ jruby -v -I. jruby-1553.rb
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b25 +jit [darwin-x86_64]
API proxy version          : 2.6.2
API implementation jar     : http://dynamic-api.oanda.com/oanda_fxtrade_implementation.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2015-07-26 01:09:41.556 -0400 I [main] Connection manager: using proxy=none for connection to fxserver02-cr.oanda.com on port=9700
2015-07-26 01:09:41.557 -0400 I [main] - connecting to fxserver02-cr.oanda.com/204.93.159.166: 9700
2015-07-26 01:09:42.102 -0400 I [main] sent seqid=0 /fxtrade/cr/LoginRequest at 1437887381 in 245 ms
2015-07-26 01:09:42.169 -0400 I [DispatcherThread] received seqid=0 /fxtrade/cr/LoginReply sendtime=1437887382 uniqueMsgId=CRgamecs01_175565382126388
2015-07-26 01:09:42.169 -0400 W [DispatcherThread] OFacade.read HEADER ERROR: errorId=CRgamecs01.chi.oanda.com1437887382138 on request=/fxtrade/cr/LoginRequest seqId=0 response=/fxtrade/cr/LoginReply
2015-07-26 01:09:42.177 -0400 I [DispatcherThread] OFacade.DispatcherThread.run: Stopping normally Socket closed
java/lang/reflect/Method.java:497:in `invoke': com.oanda.fxtrade.api.SessionDisconnectedException: Authentication failed: due to exception
        from jruby-1553.rb:7:in `(root)'
        from jruby-1553.rb:7:in `(root)'
Caused by:
null:-1:in `a': com.oanda.fxtrade.api.InvalidUserException: Authentication failed: Invalid username or password
        from null:-1:in `a'
        from null:-1:in `login'
        from null:-1:in `login'
        from null:-1:in `login'
        from null:-1:in `login'
        from NativeMethodAccessorImpl.java:-2:in `invoke0'
        from NativeMethodAccessorImpl.java:62:in `invoke'
        from DelegatingMethodAccessorImpl.java:43:in `invoke'
        from Method.java:497:in `invoke'
        from JavaMethod.java:471:in `invokeDirectWithExceptionHandling'
        from JavaMethod.java:329:in `invokeDirect'
        from InstanceMethodInvoker.java:56:in `call'
        from CachingCallSite.java:346:in `cacheAndCall'
        from CachingCallSite.java:204:in `call'
        from jruby-1553.rb:7:in `__file__'
        from jruby-1553.rb:-1:in `load'
        from Ruby.java:867:in `runScript'
        from Ruby.java:860:in `runScript'
        from Ruby.java:729:in `runNormally'
        from Ruby.java:578:in `runFromMain'
        from Main.java:395:in `doRunFromMain'
        from Main.java:290:in `internalRun'
        from Main.java:217:in `run'
        from Main.java:197:in `main'
```

`IncompatibleClassChangeError` usually means something broke binary compatibility on your machine. When I get it, I usually have had to recompile JRuby, but that may not be the issue for you (as I doubt you would be compiling JRuby from source).

**Comment by josacar** [comment]
With last jar works fine, closing this for now. Thanks!
