### ISSUE TITLE
Rails alias_attribute: JRuby has wrong encoding of string in regexp

### ISSUE THREAD

**Issue by jenslukowski** [jruby/jruby#1562]
To reproduce:
Create a rails 4.0.2 app with h2 and JRuby-1.7.11

schema.rb

``` ruby
ActiveRecord::Schema.define do
  create_table 'tables', primary_key: 'id', force: true do |t|
    t.decimal 'umlautä', precision: 4
  end
end
```

seeds.rb

``` ruby
Table.create(id: 1, umlautä: 1)
Table.create(id: 2, umlaut: 2)
```

model/table.rb

``` ruby
class Table < ActiveRecord::Base
    alias_attribute :umlaut, 'umlautä'
end
```

Running rake db:reset throws an exception

```
invalid byte sequence in US-ASCII
org/jruby/RubyRegexp.java:1674:in `=~'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:409:in `match'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:358:in `attribute_method_matcher'
org/jruby/RubyEnumerable.java:573:in `detect'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:358:in `attribute_method_matcher'
org/jruby/ext/thread_safe/JRubyCacheBackendLibrary.java:132:in `compute_if_absent'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:353:in `attribute_method_matcher'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:476:in `match_attribute_method?'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:438:in `method_missing'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/attribute_methods.rb:155:in `method_missing'
/.rvm/gems/jruby-1.7.11/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:387:in `umlaut='
org/jruby/RubyKernel.java:1965:in `public_send'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/attribute_assignment.rb:29:in `assign_attributes'
org/jruby/RubyHash.java:1339:in `each'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/core.rb:460:in `init_attributes'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/core.rb:185:in `initialize'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/inheritance.rb:27:in `new'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/persistence.rb:36:in `create'
/osscontribs/bugs/bug/db/seeds.rb:12:in `(root)'
org/jruby/RubyKernel.java:1101:in `load'
/.rvm/gems/jruby-1.7.11/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:1:in `(root)'
/.rvm/gems/jruby-1.7.11/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/.rvm/gems/jruby-1.7.11/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/.rvm/gems/jruby-1.7.11/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/.rvm/gems/jruby-1.7.11/gems/railties-4.0.2/lib/rails/engine.rb:540:in `load_seed'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/tasks/database_tasks.rb:154:in `load_seed'
org/jruby/RubyProc.java:271:in `call'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:181:in `(root)'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyProc.java:271:in `call'
/.rvm/gems/jruby-1.7.11/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:140:in `(root)'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1101:in `load'
```

**Comment by enebo** [comment]
No idea what is up here (US-ASCII could easily be an extension using 1.8 native extension string constructor -- but I would not bet my life on that).  I just tested against master and can confirm this happens for both 9k and 1.7.x.

**Comment by aviddiviner** [comment]
I just encountered this error running my rspecs after updating a few dependencies. Setting my locales fixed it for me:

```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

**Comment by headius** [comment]
This is quite old and dates back to before the transition to JRuby 9k, which fixed nearly all encoding-related oddities. I'm going to call this one invalid.

If anyone has a similar issue on a newer JRuby+Rails combination, please open a new bug.
