### ISSUE TITLE
Error with Spree on jRuby 1.7.11 - NameError: uninitialized constant Rails::Application::Railties

### ISSUE THREAD

**Issue by Allanon29** [jruby/jruby#1568]
Hi Guys,

When I try to run the generator "rails g spree:install" I get the following error:
NameError: uninitialized constant Rails::Application::Railties

This also happens if I go to MRI ruby, generate my app there, then come back to jRuby to run it. 

It is caused by this
specific commit to spree_auth_devise:
https://github.com/spree/spree_auth_devise/commit/d7cefcfd54955ab67060f551c99091b5bc5d9208

I’ve also opened a github issue on spree_auth_devise here:
https://github.com/spree/spree_auth_devise/issues/169

Jdutil, the author of the commit above was kind enough to answer, and he
told me that the issue is specifically related to this change:
https://github.com/spree/spree_auth_devise/blob/master/lib/spree/auth/engine.rb#L52-L62
But he doesn’t understand (and me neither) why it causes this error in
jRuby 1.7.11 (when it runs perfectly on ruby 2.1.0) when I try to start
rails with rails s or run rails g spree:install

```
/Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/engine.rb:53:in `backend_available?': uninitialized constant Rails::Application::Railties (NameError)
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/engine.rb:64:in `Engine'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/engine.rb:6:in `Auth'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/engine.rb:5:in `Spree'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/engine.rb:4:in `(root)'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/devise.rb:1:in `(root)'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree/auth/devise.rb:20:in `(root)'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree_auth_devise.rb:1:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree_auth_devise.rb:1:in `(root)'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree_auth_devise.rb:2:in `each'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/bundler/gems/spree_auth_devise-9d52fb1626e5/lib/spree_auth_devise.rb:2:in `(root)'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler/runtime.rb:1:in `each'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler/runtime.rb:1:in `(root)'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler.rb:131:in `tap'
    from /Users/Mate/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/bundler-1.5.3/lib/bundler.rb:131:in `require'
    from bin/rails:4:in `require'
    from bin/rails:4:in `(root)'
```

Any ideas why this happens and a possible solution?

**Comment by kares** [comment]
actually ended up as a fix elsewhere - should not be relevant here at JRuby's
