### ISSUE TITLE
Seeing undefined method `_validation_callbacks' with Rails 4.0.4

### ISSUE THREAD

**Issue by webandtech** [jruby/jruby#1593]
Not sure if this is a jruby or rails bug. After updating my gems to Rails 4.0.4 and re-running my integration tests, I intermittently see errors like the ones below. It seems to be related to my before_validation callbacks in my ActiveRecord models.

Downgrading to Rails 4.0.3 fixes the error.

```
Undefined method _run__1942824238__validation__callbacks for class 'User' (NameError)
```

```
undefined method `_validation_callbacks' for #<Class:0x56275160> (NoMethodError)
```

```
ERROR -- : Undefined method _validation_callbacks for 'User' (NameError)
org/jruby/RubyModule.java:2297:in `undef_method'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/core_ext/module/remove_method.rb:4:in `remove_possible_method'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/core_ext/class/attribute.rb:86:in `_validation_callbacks='
org/jruby/RubyModule.java:2304:in `module_eval'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/core_ext/class/attribute.rb:85:in `_validation_callbacks='
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:454:in `set_callback'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:0:in `__update_callbacks'
org/jruby/RubyArray.java:1613:in `each'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:402:in `__update_callbacks'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:447:in `set_callback'
/Users/asevers/.rvm/gems/jruby-1.7.11@frederick/gems/activemodel-4.0.4/lib/active_model/validations/callbacks.rb:60:in `before_validation'
```

**Comment by kares** [comment]
@atambo is correct, this is really a Rails issue - whether they guarantee thread-safety with validations.
likely not the AR model is not designed for sharing models between threads, you've just been 'lucky'.
