### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by alexfalkowski** [jruby/jruby#1674]
Not sure if there are any issues reported and I thought I would raise it. When moving to JRuby 1.7.12 (could  ot be related to JRuby?) 

I get the following error:

org.jruby.rack.RackInitializationException: load error: jopenssl/load -- java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/jruby/ext/openssl/ASN1$ASN1Data.toASN1()Lorg/bouncycastle/asn1/ASN1Encodable; @126: invokespecial
  Reason:
    Type 'org/bouncycastle/asn1/DLSequence' (current frame, stack[3]) is not assignable to 'org/bouncycastle/asn1/ASN1Encodable'
  Current Frame:
    bci: @126
    flags: { }
    locals: { 'org/jruby/ext/openssl/ASN1$ASN1Data', 'org/jruby/runtime/ThreadContext', integer, 'org/jruby/runtime/builtin/IRubyObject', 'org/jruby/RubyArray', 'org/bouncycastle/asn1/ASN1EncodableVector' }
    stack: { uninitialized 112, uninitialized 112, integer, 'org/bouncycastle/asn1/DLSequence' }
  Bytecode:
    0000000: 2ab6 0003 b600 0d4c 2a2b 1212 b600 13b8
    0000010: 000b 3d2a 2b12 14b6 0013 4e2d c100 1599
    0000020: 0080 2a2b 1214 b600 13c0 0015 3a04 1904
    0000030: b600 1604 a400 4ebb 0017 59b7 0018 3a05
    0000040: 1904 b600 193a 0619 06be 3607 0336 0815
    0000050: 0815 07a2 001d 1906 1508 323a 0919 0519
    0000060: 09c0 001a b600 1bb6 001c 8408 01a7 ffe2
    0000070: bb00 1d59 1cbb 001e 5919 05b7 001f b700
    0000080: 20b0 bb00 1d59 1c19 04b6 0021 03b9 0022
    0000090: 0200 c000 1ac0 001a b600 1bb7 0020 b0bb
    00000a0: 001d 591c 2dc0 001a b600 1bb7 0020 b0  
  Stackmap Table:
    full_frame(@79,{Object[#110],Object[#111],Integer,Object[#112],Object[#113],Object[#114],Object[#115],Integer,Integer},{})
    chop_frame(@112,3)
    chop_frame(@130,1)
    chop_frame(@159,1)
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/jruby-openssl-0.9.4/lib/openssl.rb:1:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/activesupport-4.0.4/lib/active_support/key_generator.rb:1:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/activesupport-4.0.4/lib/active_support/key_generator.rb:2:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails/application.rb:1:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails/application.rb:3:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails.rb:1:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails.rb:9:in`(root)'
    from org/jruby/RubyKernel.java:1065:in `require'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/actionpack-4.0.4/lib/action_controller/railtie.rb:1:in`(root)'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/actionpack-4.0.4/lib/action_controller/railtie.rb:1:in `(root)'
    from /tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/config/application.rb:1:in`(root)'
    at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
    at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98)
    at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:788)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:434)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:780)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:284)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1322)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:732)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:490)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:155)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
    at org.eclipse.jetty.server.Server.start(Server.java:342)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
    at org.eclipse.jetty.server.Server.doStart(Server.java:290)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
    at org.eclipse.jetty.runner.Runner.run(Runner.java:519)
    at org.eclipse.jetty.runner.Runner.main(Runner.java:567)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/jruby/ext/openssl/ASN1$ASN1Data.toASN1()Lorg/bouncycastle/asn1/ASN1Encodable; @126: invokespecial
  Reason:
    Type 'org/bouncycastle/asn1/DLSequence' (current frame, stack[3]) is not assignable to 'org/bouncycastle/asn1/ASN1Encodable'
  Current Frame:
    bci: @126
    flags: { }
    locals: { 'org/jruby/ext/openssl/ASN1$ASN1Data', 'org/jruby/runtime/ThreadContext', integer, 'org/jruby/runtime/builtin/IRubyObject', 'org/jruby/RubyArray', 'org/bouncycastle/asn1/ASN1EncodableVector' }
    stack: { uninitialized 112, uninitialized 112, integer, 'org/bouncycastle/asn1/DLSequence' }
  Bytecode:
    0000000: 2ab6 0003 b600 0d4c 2a2b 1212 b600 13b8
    0000010: 000b 3d2a 2b12 14b6 0013 4e2d c100 1599
    0000020: 0080 2a2b 1214 b600 13c0 0015 3a04 1904
    0000030: b600 1604 a400 4ebb 0017 59b7 0018 3a05
    0000040: 1904 b600 193a 0619 06be 3607 0336 0815
    0000050: 0815 07a2 001d 1906 1508 323a 0919 0519
    0000060: 09c0 001a b600 1bb6 001c 8408 01a7 ffe2
    0000070: bb00 1d59 1cbb 001e 5919 05b7 001f b700
    0000080: 20b0 bb00 1d59 1c19 04b6 0021 03b9 0022
    0000090: 0200 c000 1ac0 001a b600 1bb7 0020 b0bb
    00000a0: 001d 591c 2dc0 001a b600 1bb7 0020 b0  
  Stackmap Table:
    full_frame(@79,{Object[#110],Object[#111],Integer,Object[#112],Object[#113],Object[#114],Object[#115],Integer,Integer},{})
    chop_frame(@112,3)
    chop_frame(@130,1)
    chop_frame(@159,1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/jruby-openssl-0.9.4/lib/openssl.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/activesupport-4.0.4/lib/active_support/key_generator.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/activesupport-4.0.4/lib/active_support/key_generator.rb:2)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails/application.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails/application.rb:3)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails.rb:9)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/actionpack-4.0.4/lib/action_controller/railtie.rb:1)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/actionpack-4.0.4/lib/action_controller/railtie.rb:1)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/config/application.rb:1)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/jruby/ext/openssl/ASN1$ASN1Data.toASN1()Lorg/bouncycastle/asn1/ASN1Encodable; @126: invokespecial
  Reason:
    Type 'org/bouncycastle/asn1/DLSequence' (current frame, stack[3]) is not assignable to 'org/bouncycastle/asn1/ASN1Encodable'
  Current Frame:
    bci: @126
    flags: { }
    locals: { 'org/jruby/ext/openssl/ASN1$ASN1Data', 'org/jruby/runtime/ThreadContext', integer, 'org/jruby/runtime/builtin/IRubyObject', 'org/jruby/RubyArray', 'org/bouncycastle/asn1/ASN1EncodableVector' }
    stack: { uninitialized 112, uninitialized 112, integer, 'org/bouncycastle/asn1/DLSequence' }
  Bytecode:
    0000000: 2ab6 0003 b600 0d4c 2a2b 1212 b600 13b8
    0000010: 000b 3d2a 2b12 14b6 0013 4e2d c100 1599
    0000020: 0080 2a2b 1214 b600 13c0 0015 3a04 1904
    0000030: b600 1604 a400 4ebb 0017 59b7 0018 3a05
    0000040: 1904 b600 193a 0619 06be 3607 0336 0815
    0000050: 0815 07a2 001d 1906 1508 323a 0919 0519
    0000060: 09c0 001a b600 1bb6 001c 8408 01a7 ffe2
    0000070: bb00 1d59 1cbb 001e 5919 05b7 001f b700
    0000080: 20b0 bb00 1d59 1c19 04b6 0021 03b9 0022
    0000090: 0200 c000 1ac0 001a b600 1bb7 0020 b0bb
    00000a0: 001d 591c 2dc0 001a b600 1bb7 0020 b0  
  Stackmap Table:
    full_frame(@79,{Object[#110],Object[#111],Integer,Object[#112],Object[#113],Object[#114],Object[#115],Integer,Integer},{})
    chop_frame(@112,3)
    chop_frame(@130,1)
    chop_frame(@159,1)
    at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/jruby-openssl-0.9.4/lib/openssl.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/jruby-openssl-0.9.4/lib/openssl.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/activesupport-4.0.4/lib/active_support/key_generator.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/activesupport-4.0.4/lib/active_support/key_generator.rb:2)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails/application.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails/application.rb:3)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/railties-4.0.4/lib/rails.rb:9)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/actionpack-4.0.4/lib/action_controller/railtie.rb:1)
    at RUBY.(root)(/tmp/jetty-0.0.0.0-8094-medical_alarms_register.war-_medical_alarms_register-any-/webapp/WEB-INF/gems/gems/actionpack-4.0.4/lib/action_controller/railtie.rb:1)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(org/eclipse/jetty/server/handler/ContextHandler.java:788)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(org/eclipse/jetty/servlet/ServletContextHandler.java:434)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(org/eclipse/jetty/server/handler/ContextHandler.java:780)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(org/eclipse/jetty/servlet/ServletContextHandler.java:284)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(org/eclipse/jetty/webapp/WebAppContext.java:1322)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(org/eclipse/jetty/server/handler/ContextHandler.java:732)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(org/eclipse/jetty/webapp/WebAppContext.java:490)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:69)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(org/eclipse/jetty/util/component/ContainerLifeCycle.java:118)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(org/eclipse/jetty/util/component/ContainerLifeCycle.java:100)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(org/eclipse/jetty/server/handler/AbstractHandler.java:60)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(org/eclipse/jetty/server/handler/ContextHandlerCollection.java:155)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:69)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(org/eclipse/jetty/util/component/ContainerLifeCycle.java:118)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(org/eclipse/jetty/util/component/ContainerLifeCycle.java:100)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(org/eclipse/jetty/server/handler/AbstractHandler.java:60)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:69)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(org/eclipse/jetty/util/component/ContainerLifeCycle.java:118)
    at org.eclipse.jetty.server.Server.start(org/eclipse/jetty/server/Server.java:342)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(org/eclipse/jetty/util/component/ContainerLifeCycle.java:100)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(org/eclipse/jetty/server/handler/AbstractHandler.java:60)
    at org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:290)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:69)
    at org.eclipse.jetty.runner.Runner.run(org/eclipse/jetty/runner/Runner.java:519)
    at org.eclipse.jetty.runner.Runner.main(org/eclipse/jetty/runner/Runner.java:567)
    at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
    at org.tanukisoftware.wrapper.WrapperSimpleApp.run(org/tanukisoftware/wrapper/WrapperSimpleApp.java:290)
    at java.lang.Thread.run(java/lang/Thread.java:744)

**Comment by obfuscoder** [comment]
You have probably a dependency to bouncycastle 1.52. JRuby is compatible with version 1.47.

**Comment by sdaubin** [comment]
compile 'org.jruby:jruby:1.7.19'
    compile 'org.bouncycastle:bcpkix-jdk15on:1.50'
    compile 'org.bouncycastle:bcprov-jdk15on:1.50'

**Comment by sdaubin** [comment]
maybe try downgrading bouncy castle?

**Comment by kares** [comment]
expected to be working fine in latest 9K/1.7 ... (9.1.7.0/1.7.26)
