### ISSUE TITLE
SSLError: no cipher suites in common

### ISSUE THREAD

**Issue by Zapotek** [jruby/jruby#1690]
Hey guys,

There's inconsistent behaviour between MRI and JRuby when it comes to SSL.
## Reproduce with:

``` ruby
require 'socket'
require 'openssl'

def start_server( host, port )
    s = TCPServer.new( host, port )

    context                 = OpenSSL::SSL::SSLContext.new
    context.key             = OpenSSL::PKey::RSA.new( 2048 )
    context.cert            = OpenSSL::X509::Certificate.new
    context.cert.subject    = OpenSSL::X509::Name.new( [['CN', 'localhost']] )
    context.cert.issuer     = context.cert.subject
    context.cert.public_key = context.key
    context.cert.not_before = Time.now
    context.cert.not_after  = Time.now + 60 * 60 * 24
    context.verify_mode     = OpenSSL::SSL::VERIFY_NONE

    OpenSSL::SSL::SSLServer.new( s, context )
end

def connect( host, port )
    context = OpenSSL::SSL::SSLContext.new
    context.verify_mode = OpenSSL::SSL::VERIFY_NONE

    s = OpenSSL::SSL::SSLSocket.new( TCPSocket.new( host, port ), context )
    s.sync_close = true
    s.connect
    s
end

address = ['127.0.0.1', 7331]

server = start_server( *address )

Thread.new do
    begin
        server.accept
        p 'accepted'
    rescue => e
        p e
        # #<OpenSSL::SSL::SSLError: no cipher suites in common>

        puts e.backtrace.join("\n")
        # org/jruby/ext/openssl/SSLSocket.java:216:in `accept'
        # /home/zapotek/.rvm/rubies/jruby-1.7.12/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:164:in `accept'
        # tmp/jruby_openssl.rb:36:in `(root)'
        # org/jruby/ext/openssl/SSLSocket.java:170:in `connect': Socket closed (OpenSSL::SSL::SSLError)
        # from tmp/jruby_openssl.rb:26:in `connect'
        # from tmp/jruby_openssl.rb:44:in `(root)'

    end
end

connect( *address )
```

Ruby 2.1.1 works and echoes the expected:

```
"accepted"
```

JRuby (`jruby 1.7.12 (2.0.0p195) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.6.0_32-b05 [linux-amd64]`) errors out with:

```
#<OpenSSL::SSL::SSLError: no cipher suites in common>
org/jruby/ext/openssl/SSLSocket.java:216:in `accept'
/home/zapotek/.rvm/rubies/jruby-1.7.12/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:164:in `accept'
tmp/jruby_openssl.rb:36:in `(root)'
org/jruby/ext/openssl/SSLSocket.java:170:in `connect': Socket closed (OpenSSL::SSL::SSLError)
        from tmp/jruby_openssl.rb:26:in `connect'
        from tmp/jruby_openssl.rb:44:in `(root)'
```

Let me know if you need more feedback.

Cheers

**Comment by kares** [comment]
unable to run this with MRI (tried all the way back to 1.9.3) - maybe we need a better example code :
```
SSL_connect returned=1 errno=0 state=error: ASN1 lib (OpenSSL::SSL::SSLError)
```
