### ISSUE TITLE
ArrayIndexOutOfBoundsException raises when Combining specific args with required

### ISSUE THREAD

**Issue by taichi** [jruby/jruby#1692]
ArrayIndexOutOfBoundsException raises when Combining specific args with required.

i use
* jruby-complete-1.7.12
* JDK1.7.0_21 or JDK1.8.0

code is 

```java
import org.jruby.Ruby;
import org.jruby.RubyClass;
import org.jruby.RubyObject;
import org.jruby.anno.JRubyMethod;
import org.jruby.javasupport.JavaEmbedUtils;
import org.jruby.runtime.ObjectAllocator;
import org.jruby.runtime.builtin.IRubyObject;

public class Bug extends RubyObject {
	
	public Bug(Ruby r, RubyClass rc) {
		super(r, rc);
	}

	@JRubyMethod(required=1)
	public void test(IRubyObject a, IRubyObject[] args) {}
	
	public static void main(String[] args) {
		Ruby r =JavaEmbedUtils.initialize(new java.util.ArrayList<>());
		r.defineClass("Bug", r.getObject(), new ObjectAllocator() {
			@Override
			public IRubyObject allocate(Ruby runtime, RubyClass klazz) {
				return new Bug(runtime, klazz);
			}
		}).defineAnnotatedMethods(Bug.class);
	}
}
```

this code happen to ArrayIndexOutOfBoundsException

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jruby.org.objectweb.asm.Frame.a(Unknown Source)
	at org.jruby.org.objectweb.asm.Frame.a(Unknown Source)
	at org.jruby.org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.jruby.compiler.impl.SkinnyMethodAdapter.end(SkinnyMethodAdapter.java:563)
	at org.jruby.compiler.impl.SkinnyMethodAdapter.end(SkinnyMethodAdapter.java:540)
	at org.jruby.internal.runtime.methods.InvocationMethodFactory.addAnnotatedMethodInvoker(InvocationMethodFactory.java:1529)
	at org.jruby.internal.runtime.methods.InvocationMethodFactory.getAnnotatedMethodClass(InvocationMethodFactory.java:845)
	at org.jruby.internal.runtime.methods.InvocationMethodFactory.getAnnotatedMethod(InvocationMethodFactory.java:894)
	at org.jruby.RubyModule.defineAnnotatedMethod(RubyModule.java:805)
	at org.jruby.RubyModule.defineAnnotatedMethod(RubyModule.java:768)
	at org.jruby.anno.TypePopulator$DefaultTypePopulator.populate(TypePopulator.java:103)
	at org.jruby.RubyModule.defineAnnotatedMethodsIndividually(RubyModule.java:762)
	at org.jruby.RubyModule.defineAnnotatedMethods(RubyModule.java:633)
	at Bug.main(Bug.java:20)
Exception in thread "main" org.jruby.exceptions.RaiseException: (LoadError) -1
```

**Comment by kares** [comment]
this is actually how the extension API works (even in 9K) - you get all of the arguments in a single [array] when it's part of the method signature ... but you can use over-loads to handle cases [based on argument count](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/src/java/arjdbc/jdbc/RubyJdbcConnection.java#L1231-L1254) ... if that helps
