### ISSUE TITLE
Fails to load gems when "#" in path

### ISSUE THREAD

**Issue by mckramer** [jruby/jruby#1739]
With tomcat, you can specify a hash ("#") in the war file name or directory to specify a web application not in the top level folder.  E.g. `$TOMCAT_HOME/webapps/foo#bar` would be available at `http://localhost/foo/bar`.  However, jruby seems to have an issue loading the gem dependencies when the hash appears in the path.

I was originally using jruby v1.7.10, but upgraded to 11 and 12 to test as well.  Here are the outcomes of trying to run the following script:

``` ruby
require 'rubygems'
require 'sass'
```

...with the following Maven dependencies:

``` xml
<dependency>
    <groupId>org.jruby</groupId>
    <artifactId>jruby-complete</artifactId>
    <!-- Toggling this between 10, 11, and 12 patch releases. -->
    <version>1.7.10</version>
</dependency>
<dependency>
    <groupId>org.jszip.gems</groupId>
    <artifactId>sass-lang</artifactId>
    <version>3.2.5</version>
</dependency>
```
### `foo-bar`

All good.
### `foo#bar`

```
Caused by: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- sass
    at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
    at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1264)
    at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1257)
    at com.foo.bar.SassCompiler.initialize(SassCompiler.java:38)
    at com.foo.bar.SassCompiler.<init>(SassCompiler.java:22)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
    ... 29 more
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- sass
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1083)
    at RUBY.require(jar:file:/C:/dev/apache-tomcat-7.0.53/webapps/foo%23bar/WEB-INF/lib/jruby-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
    at RUBY.(root)(<script>:2)
```

My first thought was that this might be related to #1248.  So, I tested the webapp with a space, and saw the following:
### `foo bar`

```
Caused by: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- jar:file:C:/dev/apache-tomcat-7.0.53/webapps/foo%20bar/WEB-INF/lib/sass-lang-3.2.5.jar!/gems/sass-3.2.5/lib/sass/../sass
    at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
    at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1264)
    at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1257)
    at com.foo.bar.SassCompiler.initialize(SassCompiler.java:38)
    at com.foo.bar.SassCompiler.<init>(SassCompiler.java:22)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
    ... 29 more
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- jar:file:C:/dev/apache-tomcat-7.0.53/webapps/foo%20bar/WEB-INF/lib/sass-lang-3.2.5.jar!/gems/sass-3.2.5/lib/sass/../sass
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1083)
    at RUBY.require(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo bar/WEB-INF/lib/jruby-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
    at RUBY.(root)(jar:file:C:/dev/apache-tomcat-7.0.53/webapps/foo%20bar/WEB-INF/lib/sass-lang-3.2.5.jar!/gems/sass-3.2.5/lib/sass/version.rb:5)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1083)
    at RUBY.(root)(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo bar/WEB-INF/lib/jruby-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)
    at RUBY.require(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo bar/WEB-INF/lib/jruby-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1083)
    at RUBY.(root)(jar:file:C:/dev/apache-tomcat-7.0.53/webapps/foo%20bar/WEB-INF/lib/sass-lang-3.2.5.jar!/gems/sass-3.2.5/lib/sass.rb:9)
    at RUBY.(root)(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo bar/WEB-INF/lib/jruby-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)
```

This is a different error, but I thought the fix that made it into jruby 1.7.11 might fix the problem.  So, then I tried with a newer version:
## jruby 1.7.11

(I get the same results with 1.7.12 as well.)
### `foo-bar`

All good.
### `foo bar`

All good.
### `foo#bar`

No luck with this version.  Instead I see a different error message, where it seems to choke on `rubygems`.

```
Caused by: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `name' for nil:NilClass
    at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
    at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1264)
    at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1257)
    at com.foo.bar.SassCompiler.initialize(SassCompiler.java:38)
    at com.foo.bar.SassCompiler.<init>(SassCompiler.java:22)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
    ... 29 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `name' for nil:NilClass
    at RUBY._resort!(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:717)
    at org.jruby.RubyArray.sort!(org/jruby/RubyArray.java:3363)
    at RUBY._resort!(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:716)
    at RUBY._all(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:665)
    at RUBY.each(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:855)
    at org.jruby.RubyEnumerable.find(org/jruby/RubyEnumerable.java:594)
    at RUBY.find_by_path(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:887)
    at RUBY.try_activate(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems.rb:186)
    at RUBY.require(file:/C:/dev/apache-tomcat-7.0.53/webapps/foo#bar/WEB-INF/lib/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:132)
    at RUBY.(root)(<script>:2)
```

I would expect jruby to be able to load with a path containing `#`.  I believe that there is some special behavior with `#` in certain OS's, but I am not sure if that is the reason why this is not loading properly.  Or there might be a spot that needs to be escaped?

I have not had a chance to dig through the source, but I will give it a go when I get a chance.

**Comment by neeravsv30** [comment]
Do we have any update on this? Can this be solved without using defined Context of Tomcat?

**Comment by kares** [comment]
@neeravsv30 maybe you should first confirm if this is still an issue with latest JRuby 1.7/9K
... also seems like the issue is/was Windows specific?
