### ISSUE TITLE
NullPointerException in IRClosure

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1741]
Got the exception below when using master in Ruboto today.  I can probably find which source file was loaded if it would be helpful.

```
java.lang.NullPointerException
   at org.jruby.ir.IRClosure.<init>(IRClosure.java:64)
   at org.jruby.ir.IREvalScript.<init>(IREvalScript.java:32)
   at org.jruby.ir.IRBuilder.buildEvalRoot(IRBuilder.java:3220)
   at org.jruby.ir.interpreter.Interpreter.interpretCommonEval(Interpreter.java:135)
   at org.jruby.ir.interpreter.Interpreter.interpretSimpleEval(Interpreter.java:163)
   at org.jruby.ir.interpreter.Interpreter.evalSimple(Interpreter.java:733)
   at org.jruby.RubyBasicObject.evalUnder(RubyBasicObject.java:1798)
   at org.jruby.RubyBasicObject.specificEval(RubyBasicObject.java:1748)
   at org.jruby.RubyBasicObject.instance_eval19(RubyBasicObject.java:1581)
   at org.jruby.RubyBasicObject$INVOKER$i$instance_eval19.call(RubyBasicObject$INVOKER$i$instance_eval19.gen)
   at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrThreeBlock.call(JavaMethod.java:519)
   at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:180)
   at org.jruby.RubyClass.finvoke(RubyClass.java:662)
   at org.jruby.runtime.Helpers.invoke(Helpers.java:542)
   at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callEachType(EmbedRubyObjectAdapterImpl.java:353)
   at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:306)
   at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.runRubyMethod(EmbedRubyObjectAdapterImpl.java:278)
   at org.jruby.embed.ScriptingContainer.runRubyMethod(ScriptingContainer.java:1528)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at org.ruboto.JRubyAdapter.runRubyMethod(JRubyAdapter.java:51)
   at org.ruboto.test.InstrumentationTestRunner.loadScript(InstrumentationTestRunner.java:171)
   at org.ruboto.test.InstrumentationTestRunner.getAllTests(InstrumentationTestRunner.java:100)
   at android.test.InstrumentationTestRunner.getTestSuite(InstrumentationTestRunner.java:580)
   at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:360)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4335)
   at android.app.ActivityThread.access$1500(ActivityThread.java:135)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5017)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kares** [comment]
let's call this one resolved by now :older_man:
