### ISSUE TITLE
`pop` isn't applied before `*args`

### ISSUE THREAD

**Issue by tenderlove** [jruby/jruby#1759]
I have no idea what is wrong, but here is a test case! :heart:

``` ruby
require 'minitest/autorun'

class ARGTest < MiniTest::Test
  def omg a, b, c, &block
    [a, b, c, block]
  end

  def test_sadness
    list = [1, 2, nil, nil]
    expected = list.dup
    assert_equal expected, omg(*list, &list.pop)
  end
end
```

On MRI:

```
ruby 2.2.0dev (2014-06-05 trunk 46358) [x86_64-darwin13]
Run options: --seed 20700

# Running:

.

Finished in 0.001214s, 823.7232 runs/s, 823.7232 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

On JRuby:

```
jruby 1.7.12 (1.9.3p392) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_45-b18 [darwin-x86_64]
Run options: --seed 2766

# Running:

E

Finished in 0.030000s, 33.3333 runs/s, 0.0000 assertions/s.

  1) Error:
ARGTest#test_sadness:
ArgumentError: wrong number of arguments calling `omg` (4 for 3)
    test2.rb:11:in `test_sadness'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by rtyler** [comment]
This is broken in JRuby 9k and 1.7.21:


```
➜  1759  ruby -v test.rb 
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 OpenJDK 64-Bit Server VM 25.45-b02 on 1.8.0_45-internal-b14 +jit [linux-amd64]
/home/tyler/.rvm/gems/jruby-9.0.0.0@rubygems/gems/minitest-5.8.0/lib/minitest.rb:47: warning: (...) interpreted as grouped expression
Run options: --seed 48718

# Running:

E

Finished in 0.020471s, 48.8507 runs/s, 0.0000 assertions/s.

  1) Error:
ARGTest#test_sadness:
ArgumentError: wrong number of arguments (4 for 3)
    test.rb:11:in `test_sadness'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
➜  1759  
```

```
➜  1759  ruby -v test.rb
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on OpenJDK 64-Bit Server VM 1.8.0_45-internal-b14 +jit [linux-amd64]
Run options: --seed 56350

# Running:

E

Finished in 0.009000s, 111.1111 runs/s, 0.0000 assertions/s.

  1) Error:
ARGTest#test_sadness:
ArgumentError: wrong number of arguments calling `omg` (4 for 3)
    test.rb:11:in `test_sadness'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
➜  1759  


```
