### ISSUE TITLE
Concurrency issues when preparing IR for interpretation

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1793]
Saw this during a spec run today. Actually fired a few times in the same run. This is running with JIT enabled; it's possible the JIT's re-tweaking of the IR is conflicting here?

```
2014-07-05T20:43:41.598-05:00: IRScope: Error linearizing cfg: 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at org.jruby.ir.util.EdgeTypeIterator.hasNext(EdgeTypeIterator.java:28)
	at org.jruby.ir.util.Vertex.getFirstEdge(Vertex.java:161)
	at org.jruby.ir.util.Vertex.getIncomingSourceDataOfType(Vertex.java:115)
	at org.jruby.ir.representations.CFG.getIncomingSourceOfType(CFG.java:177)
	at org.jruby.ir.representations.CFGLinearizer.linearizeInner(CFGLinearizer.java:56)
	at org.jruby.ir.representations.CFGLinearizer.linearizeInner(CFGLinearizer.java:73)
	at org.jruby.ir.representations.CFGLinearizer.linearizeInner(CFGLinearizer.java:64)
	at org.jruby.ir.representations.CFGLinearizer.linearizeInner(CFGLinearizer.java:68)
	at org.jruby.ir.representations.CFGLinearizer.linearizeInner(CFGLinearizer.java:64)
	at org.jruby.ir.representations.CFGLinearizer.linearize(CFGLinearizer.java:44)
	at org.jruby.ir.IRScope.buildLinearization(IRScope.java:1083)
	at org.jruby.ir.IRScope.setupLinearization(IRScope.java:669)
	at org.jruby.ir.IRScope.prepareInstructionsForInterpretation(IRScope.java:491)
	at org.jruby.ir.IRScope.prepareForInterpretation(IRScope.java:635)
	at org.jruby.ir.IRScope.getInstrsForInterpretation(IRScope.java:1064)
	at org.jruby.ir.interpreter.Interpreter.interpret(Interpreter.java:570)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:693)
	at org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:47)
```

**Comment by enebo** [comment]
This has been solved for now.  Closing.
