### ISSUE TITLE
Unknown exception during test:mri

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1836]
Going to start filing these intermittent failures so they're not lost to time and ignored.

Running test:mri with today's build:

```
OpenSSL::TestSSL#test_multibyte_read_write
Exception in thread "Ruby-0-Thread-109: /Users/headius/projects/jruby/test/mri/openssl/utils.rb:291" java.lang.NullPointerException
    at org.jruby.util.io.OpenFile.channel(OpenFile.java:2092)
    at org.jruby.RubyIO.getChannel(RubyIO.java:310)
    at org.jruby.RubyThread.select(RubyThread.java:1422)
    at org.jruby.ext.socket.RubyTCPServer.accept(RubyTCPServer.java:149)
    at org.jruby.ext.socket.RubyTCPServer$INVOKER$i$0$0$accept.call(RubyTCPServer$INVOKER$i$0$0$accept.gen)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
    at org.jruby.ir.interpreter.Interpreter.processCall(Interpreter.java:377)
    at org.jruby.ir.interpreter.Interpreter.interpret(Interpreter.java:617)
    at org.jruby.ir.interpreter.Interpreter.INTERPRET_METHOD(Interpreter.java:709)
    at org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:119)
    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:202)
    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
    at org.jruby.ir.interpreter.Interpreter.processCall(Interpreter.java:377)
    at org.jruby.ir.interpreter.Interpreter.interpret(Interpreter.java:617)
    at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:692)
    at org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:47)
    at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:75)
    at org.jruby.runtime.Block.yieldSpecific(Block.java:116)
    at org.jruby.RubyKernel.loop(RubyKernel.java:1252)
    at org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
    at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:474)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)
    at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:425)
    at org.jruby.ir.interpreter.Interpreter.processCall(Interpreter.java:393)
    at org.jruby.ir.interpreter.Interpreter.interpret(Interpreter.java:617)
    at org.jruby.ir.interpreter.Interpreter.INTERPRET_METHOD(Interpreter.java:709)
    at org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:119)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)
    at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:425)
    at org.jruby.ir.interpreter.Interpreter.processCall(Interpreter.java:393)
    at org.jruby.ir.interpreter.Interpreter.interpret(Interpreter.java:617)
    at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:692)
    at org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:47)
    at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)
    at org.jruby.runtime.Block.call(Block.java:106)
    at org.jruby.RubyProc.call(RubyProc.java:294)
    at org.jruby.RubyProc.call(RubyProc.java:220)
    at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
    at java.lang.Thread.run(Thread.java:745)
```

This is obviously related to the IO rewrite in 9k, but I'm unclear how it would happen. Needs more investigation.

**Comment by etehtsea** [comment]
Don't seem to be an issue anymore?

**Comment by kares** [comment]
@etehtsea definitely, lets call it a day :wink:
