### ISSUE TITLE
Ruby exceptions passing through Java Integration and back remain wrapped

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1839]
This is either a problem with JI (my area) or IR (@enebo or @subbuss).

It appears that exceptions raised by Ruby code called by Java code called through Java integration (a Ruby exception that passes through a JI call on its way out) remain wrapped and are presented to rescue blocks as the wrapped RaiseException rather than the contained Ruby exception.

```
 $ jruby -J-classpath test/target/test-classes/ -S rspec spec/java_integration/exceptions/rescue_spec.rb 
.................FF

Failures:

  1) A ruby exception raised through java and back to ruby its class and message is preserved
     Failure/Error: e.message.should == "it comes from ruby"
       expected: "it comes from ruby"
            got: "org.jruby.exceptions.RaiseException: (RuntimeError) it comes from ruby" (using ==)
     # ./spec/java_integration/exceptions/rescue_spec.rb:208:in `(root)'

  2) A ruby exception raised through java and back to ruby via a different thread its class and message is preserved
     Failure/Error: e.message.should == "it comes from ruby"
       expected: "it comes from ruby"
            got: "org.jruby.exceptions.RaiseException: (RuntimeError) it comes from ruby" (using ==)
     # ./spec/java_integration/exceptions/rescue_spec.rb:222:in `(root)'
```

This happens regardless of JIT status, and since I have not done anything with JI and exceptions recently I suspect this is a flaw in how IR handles unwrapping exceptions for rescue.

**Comment by headius** [comment]
This has to be fixed. We'd see a lot more issues with our ruby kernel or the JI specs if it wasn't.
