### ISSUE TITLE
IRClosure creation requires lexical parent to be interpreted

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1970]
Currently IRClosure needs to access its lexically enclosing scope as an IRScope. Jitted code bodies currently do not preserve the IRScope they were compiled from. Because IRClosure is used as the scope form for eval'ed strings, we cannot currently JIT methods that contain eval... it leads to an NPE in IRClosure like this:

```
java.lang.NullPointerException
    at org.jruby.ir.IRClosure.<init>(IRClosure.java:49)
    at org.jruby.ir.IREvalScript.<init>(IREvalScript.java:33)
    at org.jruby.ir.IRBuilder.buildEvalRoot(IRBuilder.java:3177)
    at org.jruby.ir.interpreter.Interpreter.interpretCommonEval(Interpreter.java:82)
    at org.jruby.ir.interpreter.Interpreter.interpretSimpleEval(Interpreter.java:113)
    at org.jruby.ir.interpreter.Interpreter.evalSimple(Interpreter.java:713)
    at org.jruby.RubyBasicObject.evalUnder(RubyBasicObject.java:1845)
    at org.jruby.RubyBasicObject.specificEval(RubyBasicObject.java:1824)
    at org.jruby.RubyModule.module_eval(RubyModule.java:2400)
...
```

I'm not sure how best to remedy this. For now I am re-disabling JIT of methods containing eval.

**Comment by headius** [comment]
Circling back to this for IR bug review...

This is still an issue, but it's not a 9k showstopper. We *will* make blocks jit independently, but it requires much deeper work to separate the block's pre/post state from the method's pre/post state (frames, scopes, etc). We could JIT the block with no optimizations, just using the interpreter instructions as-is, but that greatly diminishes the value of jitting blocks in the first place.

In any case, this is not going to happen for 9k final, so I'll bump it.
