### ISSUE TITLE
json/ext not thread safe (jruby 1.7.16) (test case included)

### ISSUE THREAD

**Issue by hwinkler** [jruby/jruby#2013]
(n.b. if I am misusing the ScriptingContainer in the sample code below... I'd be grateful to learn that.)

The default json module (json/ext), when run on multiple threads, will frequently raise an exception:

```
NameError: uninitialized constant JSON::Ext::Parser
  const_missing at org/jruby/RubyModule.java:2723
            Ext at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json/ext.rb:16
           JSON at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json/ext.rb:12
         (root) at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json/ext.rb:9
        require at org/jruby/RubyKernel.java:1065
         (root) at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
        require at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
           JSON at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json.rb:58
        require at org/jruby/RubyKernel.java:1065
         (root) at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json.rb:54
         (root) at /Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
org.jruby.embed.EvalFailedException: (NameError) uninitialized constant JSON::Ext::Parser
    at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
    at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1317)
    at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1310)
    at repro.ThreadunsafeJson$1.run(ThreadunsafeJson.java:29)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JSON::Ext::Parser
    at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:2723)
    at RUBY.Ext(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json/ext.rb:16)
    at RUBY.JSON(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json/ext.rb:12)
    at RUBY.(root)(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json/ext.rb:9)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)
    at RUBY.require(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
    at RUBY.JSON(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json.rb:58)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
    at RUBY.(root)(/Users/hwinkler/jruby-repro/lib/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/json.rb:54)
```

The following test case  will  sometimes fail, printing out the stack trace to the console. It fails about 50% of the time on my laptop.

``` java
package repro;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import org.jruby.embed.LocalContextScope;
import org.jruby.embed.ScriptingContainer;

public class ThreadunsafeJson {

  public static void main(String[] args) throws InterruptedException {
    final int numThreads = 2;
    ExecutorService executor = Executors.newFixedThreadPool(numThreads);
    for (int i = 0; i < numThreads; i++) {

      executor.submit(new Runnable() {

        @Override
        public void run() {
          ScriptingContainer container = new ScriptingContainer(LocalContextScope.THREADSAFE);

          try {
            container.runScriptlet("require 'json'\n");
          } catch (Exception e) {
            e.printStackTrace();
          }
        }
      });
    }
    executor.shutdown();
    executor.awaitTermination(10, TimeUnit.SECONDS);
  }

}
```

**Comment by kares** [comment]
sounds like an old issue, affecting JRuby 1.7 ... closing as defunct
