### ISSUE TITLE
Flaky tests on Travis

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#2250]
I've seen the following tests fail sporadically over the course of today:

```
PHASE='-Prake -Dtask=spec:regression'

[exec] Failures:
[exec]
[exec] 1) A fiber that is running while its resuming thread receives an exception receives that exception
[exec] Failure/Error: fiber_exceptions.size.should == 100
[exec] expected: 100
[exec] got: 99 (using ==)
[exec] # ./spec/regression/GH-1463_exceptions_propagate_through_fibers_spec.rb:37:in `(root)'
```

```
PHASE='-Prake -Dtask=test:mri'

[exec] 1) Error:
[exec] TestSignal#test_signal:
[exec] RuntimeError: Interrupt
[exec] /home/travis/build/jruby/jruby/test/mri/ruby/test_signal.rb:18:in `test_signal'
[exec] org/jruby/RubyProc.java:285:in `call'
```

```
PHASE='-Prake -Dtask=spec:regression'

[exec] Failures:
[exec]
[exec] 1) A fiber that is running while its resuming thread receives an exception receives that exception
[exec] Failure/Error: expect(thread_exceptions).to eq []
[exec]
[exec] expected: []
[exec] got: [#<ThreadError: interrupted in SizedQueue#pop>, #<ThreadError: interrupted in SizedQueue#pop>]
[exec]
[exec] (compared using ==)
[exec]
[exec] Diff:
[exec] @@ -1,2 +1,3 @@
[exec] -[]
[exec] +[#<ThreadError: interrupted in SizedQueue#pop>,
[exec] + #<ThreadError: interrupted in SizedQueue#pop>]
[exec] # ./spec/regression/GH-1463_exceptions_propagate_through_fibers_spec.rb:42:in `(root)'
```

I didn't see an easy way to tag them out for now.  But it'd be nice to keep the builds green if the failures are benign.  Some of the Fiber ones might be legitimate, however.

**Comment by nirvdrum** [comment]
These specs have been passing for a while now.  Closing.
