### ISSUE TITLE
openssl net-ssh camellia192 tests fails with jruby9k

### ISSUE THREAD

**Issue by mfazekas** [jruby/jruby#2515]
net-ssh master fails on travis-ci with jruby-head.
I haven't looked in details but looks like the ivlen returned is 8 for camellia-192-cbc and it should be 16?

https://travis-ci.org/mfazekas/net-ssh/jobs/48157060

```
Cipher: camellia192-cbc@openssh.org camellia-192-cbc ivlen:8 keylen:24
E
================================================================================
Error: test_camellia192_cbc_for_decryption(Transport::TestCipherFactory)
: OpenSSL::Cipher::CipherError: IV must be 16 bytes long.
org/jruby/ext/openssl/Cipher.java:1086:in `update'
/home/travis/build/mfazekas/net-ssh/test/transport/test_cipher_factory.rb:437:in `decrypt'
/home/travis/build/mfazekas/net-ssh/test/transport/test_cipher_factory.rb:266:in `test_camellia192_cbc_for_decryption'
     263:         assert_equal CAMELLIA192_CBC, encrypt("camellia192-cbc@openssh.org")
     264:       end
     265:       def test_camellia192_cbc_for_decryption
  => 266:         assert_equal TEXT, decrypt("camellia192-cbc@openssh.org", CAMELLIA192_CBC)
     267:       end
     268:     end
     269: 
================================================================================
Cipher: camellia192-cbc@openssh.org camellia-192-cbc ivlen:8 keylen:24
E
================================================================================
Error: test_camellia192_cbc_for_encryption(Transport::TestCipherFactory)
: OpenSSL::Cipher::CipherError: IV must be 16 bytes long.
org/jruby/ext/openssl/Cipher.java:1086:in `update'
/home/travis/build/mfazekas/net-ssh/test/transport/test_cipher_factory.rb:430:in `encrypt'
/home/travis/build/mfazekas/net-ssh/test/transport/test_cipher_factory.rb:263:in `test_camellia192_cbc_for_encryption'
     260:     if_supported?("camellia192-cbc@openssh.org") do
     261:       CAMELLIA192_CBC = "\x82\xB2\x03\x90\xFA\f2\xA0\xE3\xFA\xF2B\xAB\xDBX\xD5\x04z\xD4G\x19\xB8\xAB\v\x85\x84\xCD:.\xBA\x9Dd\xD5(\xEB.\n\xAA]\xCB\xF3\x0F4\x8Bd\xF8m\xC9!\xE2\xA1=\xEBY\xA6\x83\x86\n\x13\e6\v\x06\xBBNJg\xF2-\x14',[\xC1\xB1.\x85\xF3\xC6\xBF\x1Ff\xCE\x87'\x9C\xB2\xC8!\xF3|\xE2\xD2\x9E\x96\xA1"
     262:       def test_camellia192_cbc_for_encryption
  => 263:         assert_equal CAMELLIA192_CBC, encrypt("camellia192-cbc@openssh.org")
     264:       end
     265:       def test_camellia192_cbc_for_decryption
     266:         assert_equal TEXT, decrypt("camellia192-cbc@openssh.org", CAMELLIA192_CBC)
```

**Comment by mkristian** [comment]
this looks more like a bug in jruby-openssl-0.9.6.gem which ships with
jruby-9k.

should fail with jruby-1.7.x and jruby-openssl-0.9.6 in the same manner.

looking at https://www.rfc-editor.org/rfc/rfc3657.txt I would say the IV
should be 16 bytes long !?

**Comment by mfazekas** [comment]
with jruby 1.7.18 (1.9.3p551) the tests are passing, as we skip camellia tests there: https://travis-ci.org/mfazekas/net-ssh/jobs/48157062 i guess that's with old version of the gem
