### ISSUE TITLE
error with bin/jruby -S gem install asd

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2623]
```
$ bin/jruby -S gem install asd --backtrace
ERROR:  Could not find a valid gem 'asd' (>= 0) in any repository
ERROR:  While executing gem ... (NoMethodError)
    undefined method `+' for nil:NilClass
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/text.rb:60:in `levenshtein_distance_CLOSURE_1_CLOSURE_2__levenshtein_distance_CLOSURE_1_1'
	org/jruby/RubyString.java:5277:in `each_char'
	org/jruby/RubyEnumerator.java:299:in `each'
	org/jruby/RubyEnumerator.java:443:in `each_with_index'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/text.rb:58:in `levenshtein_distance_CLOSURE_1__levenshtein_distance_0'
	org/jruby/RubyString.java:5277:in `each_char'
	org/jruby/RubyEnumerator.java:299:in `each'
	org/jruby/RubyEnumerator.java:443:in `each_with_index'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/text.rb:55:in `__script__'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/spec_fetcher.rb:194:in `suggest_gems_from_name'
	org/jruby/RubyArray.java:2306:in `map'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/spec_fetcher.rb:191:in `suggest_gems_from_name'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/command.rb:164:in `show_lookup_failure'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:306:in `install_gems'
	org/jruby/RubyArray.java:1569:in `each'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:295:in `install_gems'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:202:in `execute'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/command.rb:307:in `invoke_with_build_args'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/command_manager.rb:168:in `process_args'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/command_manager.rb:138:in `run'
	/home/christian/projects/active/maven/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:54:in `run'
	/home/christian/projects/active/maven/jruby/bin/jgem:21:in `(root)'
	org/jruby/RubyKernel.java:984:in `load'
	/home/christian/projects/active/maven/jruby/bin/gem:4:in `__script__'
```

this could be due to the psych be a default gem now or in general psych related or nothing to do with psych. I came across it while investigating a regression due to psych now being a default gem.

**Comment by enebo** [comment]
@mkristian This might be changes we made to IR recently (which will be changed very soon).   Please run 'JRUBY_OPTS=-X-C  -S jruby -S gem install asdf' and see if this error goes away.  We have a race between interp and JIT again.  I am fixing this now but we have decided to make some larger fixes because we keep introducing races every few months.

**Comment by mkristian** [comment]
yes, indeed - this jruby opts did help. and it was only one of a few
"strange" things I saw while debugging - like an unrelated "p 'something'"
did make the error disappear.

but still see the regression from
here: fffd2b6ca46004e497af0a22e9711ea8903a2cd3
but will wait to invest until those races are gone.

**Comment by headius** [comment]
This should be working just fine with newly-landed IR improvements. Worked for me locally (in as much as it only reported the missing gem and not the `+` error).
