### ISSUE TITLE
ppc64le mvn -Ptest fails on tip of jruby master branch.

### ISSUE THREAD

**Issue by ralphbellofatto** [jruby/jruby#2706]
we got a snapshot of the tip of the master jruby branch to test running on ppc64le.

```
[tulgpu002 jruby] $ uname -a
Linux tulgpu002 3.16.0-30-generic #40-Ubuntu SMP Mon Jan 12 22:07:11 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux

git clone https://github.com/jruby/jruby.git
cd jruby/
mvn compile
mvn test

mvn -Ptest
```
When we ran "mvn -Ptest" as suggested in the BUILDING.md file we get the following error summary:

```
Test results :

Failed tests:
  TestRuby.testPrintErrorShouldPrintErrorMessageAndStacktraceWhenBacktraceIsPresent:169 expected:<[]Line 1: A message (N...> but was:<[io/console on JRuby shells out to stty for most operations
]Line 1: A message (N...>

Tests run: 362, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JRuby ............................................. SUCCESS [0.643s]
[INFO] JRuby Core ........................................ FAILURE [4:12.958s]
[INFO] JRuby Truffle ..................................... SKIPPED
[INFO] JRuby Lib Setup ................................... SKIPPED
[INFO] JRuby Integration Tests ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:13.960s
[INFO] Finished at: Sun Mar 15 18:54:50 EDT 2015
[INFO] Final Memory: 18M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project jruby-core: There are test failures.

```

the complete output here:
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jruby:jruby-tests:jar:9.0.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for org.jruby:requireTest:jar should not point at files within the project directory, ${project.basedir}/jruby/requireTest-1.0.jar will be unresolvable by dependent projects @ line 60, column 19
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JRuby
[INFO] JRuby Core
[INFO] JRuby Truffle
[INFO] JRuby Lib Setup
[INFO] JRuby Integration Tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby 9.0.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jruby-parent ---
[INFO] Installing /gpfs/DDNgpfs1/ralphbel/jruby/pom.xml to /gpfs/DDNgpfs1/ralphbel/.m2/repository/org/jruby/jruby-parent/9.0.0.0-SNAPSHOT/jruby-parent-9.0.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby Core 9.0.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-core ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (jruby-revision) @ jruby-core ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd /gpfs/DDNgpfs1/ralphbel/jruby/core && git rev-parse --verify --short=7 HEAD
[INFO] Working directory: /gpfs/DDNgpfs1/ralphbel/jruby/core
[INFO] Storing buildNumber: 57d168b at timestamp: 1426459837991
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd /gpfs/DDNgpfs1/ralphbel/jruby/core && git rev-parse --verify --short=7 HEAD
[INFO] Working directory: /gpfs/DDNgpfs1/ralphbel/jruby/core
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jruby-core ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 36 resources
[INFO] Copying 1 resource
[INFO] Copying 1 resource to /gpfs/DDNgpfs1/ralphbel/jruby/core/src/main/java
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (anno) @ jruby-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jruby-core ---
[INFO] Compiling 1 source file to /gpfs/DDNgpfs1/ralphbel/jruby/core/target/classes
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-populators) @ jruby-core ---
[INFO] Source directory: /gpfs/DDNgpfs1/ralphbel/jruby/core/target/generated-sources added.
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (invoker-generator) @ jruby-core ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (populators) @ jruby-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (eclipse-hack) @ jruby-core ---
[INFO] Not compiling main sources
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jruby-core ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jruby-core ---
[INFO] Compiling 93 source files to /gpfs/DDNgpfs1/ralphbel/jruby/core/target/test-classes
[WARNING] /gpfs/DDNgpfs1/ralphbel/jruby/core/src/test/java/org/jruby/embed/ScriptingContainerTest.java:[48,24] [deprecation] ChannelDescriptor in org.jruby.util.io has been deprecated
[WARNING] /gpfs/DDNgpfs1/ralphbel/jruby/core/src/test/java/org/jruby/test/TestMethodFactories.java:[90,60] [deprecation] RUBY1_8 in CompatVersion has been deprecated
[WARNING] /gpfs/DDNgpfs1/ralphbel/jruby/core/src/test/java/org/jruby/test/TestMethodFactories.java:[94,60] [deprecation] RUBY1_9 in CompatVersion has been deprecated
[WARNING] /gpfs/DDNgpfs1/ralphbel/jruby/core/src/test/java/org/jruby/test/TestRuby.java:[107,11] [deprecation] setCextEnabled(boolean) in RubyInstanceConfig has been deprecated
[WARNING] /gpfs/DDNgpfs1/ralphbel/jruby/core/src/test/java/org/jruby/util/JRubyThreadContextTest.java:[154,5] [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
[WARNING] /gpfs/DDNgpfs1/ralphbel/jruby/core/src/test/java/org/jruby/runtime/profile/ProfilingTest.java:[46,31] [deprecation] getProfiledMethods() in Ruby has been deprecated
[INFO] 
[INFO] --- maven-surefire-plugin:2.15:test (default-test) @ jruby-core ---
[INFO] Surefire report directory: /gpfs/DDNgpfs1/ralphbel/jruby/core/target/surefire-reports
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.15/surefire-junit4-2.15.pom
3/3 KB   
         
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.15/surefire-junit4-2.15.pom (3 KB at 11.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.15/surefire-providers-2.15.pom
3/3 KB   
         
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.15/surefire-providers-2.15.pom (3 KB at 54.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.15/surefire-junit4-2.15.jar
3/63 KB   
7/63 KB   
11/63 KB   
13/63 KB   
17/63 KB   
21/63 KB   
25/63 KB   
29/63 KB   
33/63 KB   
34/63 KB   
38/63 KB   
42/63 KB   
46/63 KB   
50/63 KB   
54/63 KB   
58/63 KB   
59/63 KB   
63/63 KB   
63/63 KB   
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.15/surefire-junit4-2.15.jar (63 KB at 713.9 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jruby.test.MainTestSuite
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi5438825070510719238.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 183, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 129.238 sec <<< FAILURE! - in org.jruby.test.MainTestSuite
testPrintErrorShouldPrintErrorMessageAndStacktraceWhenBacktraceIsPresent(org.jruby.test.TestRuby)  Time elapsed: 0.4 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<[]Line 1: A message (N...> but was:<[io/console on JRuby shells out to stty for most operations
]Line 1: A message (N...>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at org.jruby.test.TestRuby.testPrintErrorShouldPrintErrorMessageAndStacktraceWhenBacktraceIsPresent(TestRuby.java:169)

Running org.jruby.util.RandomTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.1 sec - in org.jruby.util.RandomTest
Running org.jruby.util.SipHashInlineTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec - in org.jruby.util.SipHashInlineTest
Running org.jruby.util.RubyTimeOutputFormatterTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.083 sec - in org.jruby.util.RubyTimeOutputFormatterTest
Running org.jruby.util.log.ParameterizedWriterTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec - in org.jruby.util.log.ParameterizedWriterTest
Running org.jruby.util.log.StandardErrorLoggerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.085 sec - in org.jruby.util.log.StandardErrorLoggerTest
Running org.jruby.util.MurmurHashTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec - in org.jruby.util.MurmurHashTest
Running org.jruby.util.ShellLauncherTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi6305311379443217319.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.753 sec - in org.jruby.util.ShellLauncherTest
Running org.jruby.util.URLResourceTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.388 sec - in org.jruby.util.URLResourceTest
Running org.jruby.util.JRubyThreadContextTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi1660965171730099061.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.643 sec - in org.jruby.util.JRubyThreadContextTest
Running org.jruby.util.JarResourceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.292 sec - in org.jruby.util.JarResourceTest
Running org.jruby.embed.internal.ThreadSafeLocalContextProviderTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi8301003628134238544.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.47 sec - in org.jruby.embed.internal.ThreadSafeLocalContextProviderTest
Running org.jruby.embed.internal.SingleThreadLocalContextProviderTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi2566019027049583719.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.007 sec - in org.jruby.embed.internal.SingleThreadLocalContextProviderTest
Running org.jruby.embed.internal.BiVariableMapTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi5879682143065028905.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.801 sec - in org.jruby.embed.internal.BiVariableMapTest
Running org.jruby.embed.jsr223.JRubyCompiledScriptTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi4084933548195530705.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.474 sec - in org.jruby.embed.jsr223.JRubyCompiledScriptTest
Running org.jruby.embed.jsr223.JRubyEngineFactoryTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.949 sec - in org.jruby.embed.jsr223.JRubyEngineFactoryTest
Running org.jruby.embed.ConstantCompilationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.047 sec - in org.jruby.embed.ConstantCompilationTest
Running org.jruby.embed.util.SystemPropertyCatcherTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.27 sec - in org.jruby.embed.util.SystemPropertyCatcherTest
Running org.jruby.embed.ReaderInputStreamTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.27 sec - in org.jruby.embed.ReaderInputStreamTest
Running org.jruby.embed.ParentClassLoaderTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi8926192936289034861.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.01 sec - in org.jruby.embed.ParentClassLoaderTest
Running org.jruby.embed.ScriptingContainerTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi4786592591543298762.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 84, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.331 sec - in org.jruby.embed.ScriptingContainerTest
Running org.jruby.embed.IsolatedScriptingContainerTest
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/jffi5613398407306051452.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.588 sec - in org.jruby.embed.IsolatedScriptingContainerTest

Results :

Failed tests: 
  TestRuby.testPrintErrorShouldPrintErrorMessageAndStacktraceWhenBacktraceIsPresent:169 expected:<[]Line 1: A message (N...> but was:<[io/console on JRuby shells out to stty for most operations
]Line 1: A message (N...>

Tests run: 362, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JRuby ............................................. SUCCESS [0.643s]
[INFO] JRuby Core ........................................ FAILURE [4:12.958s]
[INFO] JRuby Truffle ..................................... SKIPPED
[INFO] JRuby Lib Setup ................................... SKIPPED
[INFO] JRuby Integration Tests ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:13.960s
[INFO] Finished at: Sun Mar 15 18:54:50 EDT 2015
[INFO] Final Memory: 18M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project jruby-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /gpfs/DDNgpfs1/ralphbel/jruby/core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jruby-core
```

**Comment by ralphbellofatto** [comment]
Adding the -X option we get the following telemetry:

```
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-ppc64el/jre
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "3.16.0-30-generic", arch: "ppc64", family: "unix"
```

**Comment by lbianc** [comment]
Fix for this issue: https://github.com/jruby/jruby/pull/2871
