### ISSUE TITLE
[Truffle] Array#hash error with recursive arrays

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2757]
I get the following error when running the following code:
Code:
``` ruby
a = [1, 'two', 3.0]
5.times { a << a }
a
a.hash
```
Expected (hash value):
```
170595643093628540
```
Actual:
```
core:/core/rubinius/common/array.rb:138:in `initialize':  (Thread::InnerRecursionDetected)
	from core:/core/rubinius/common/array.rb:138:in `raise'
	from core:/core/rubinius/common/array.rb:138:in `hash'
	from core:/core/rubinius/common/array.rb:145:in `block in hash'
	from core:/core/rubinius/common/array.rb:145:in `each'
	from core:/core/rubinius/common/array.rb:145:in `hash'
	from rang.rb:4:in `<main>'
```

**Comment by chrisseaton** [comment]
Must be a problem with our `recursive_objects` stuff - I'm going to take a guess something to do with the exceptions as we don't have much that exercises that.
