### ISSUE TITLE
jruby 9000 FreeBSD TestFileUtils#test_chmod_symbol_mode fails

### ISSUE THREAD

**Issue by bgalbrecht** [jruby/jruby#2792]
After building jruby 9000 on FreeBSD 10.1 release, when running 
bin/jruby -S rake test:mri

I get the following error:
[2287/6445] TestFileUtils#test_chmod_symbol_mode = 0.01 s                                     
  1) Error:
TestFileUtils#test_chmod_symbol_mode:
SystemCallError: Unknown error - No message available
    org/jruby/RubyFile.java:581:in `chmod'
    /usr/home/bruce/jruby-dev/jruby/lib/ruby/stdlib/fileutils.rb:1354:in `chmod'
    /usr/home/bruce/jruby-dev/jruby/lib/ruby/stdlib/fileutils.rb:1009:in `block in chmod'
    org/jruby/RubyArray.java:1570:in `each'
    /usr/home/bruce/jruby-dev/jruby/lib/ruby/stdlib/fileutils.rb:1008:in `chmod'
    /usr/home/bruce/jruby-dev/jruby/test/mri/fileutils/test_fileutils.rb:1001:in `test_chmod_symbol_mode'

**Comment by bgalbrecht** [comment]
bin/jruby -v
jruby 9.0.0.0-SNAPSHOT (2.2.1) 2015-04-01 dc85f30 OpenJDK 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 +jit [FreeBSD-amd64]

**Comment by headius** [comment]
I don't have a FreeBSD instance handy. Can you run this again with -Xbacktrace.style=raw and gist the result? We do use native calls to chmod...perhaps this is another case of FreeBSD having it in an unusual library?

**Comment by bgalbrecht** [comment]
https://gist.github.com/bgalbrecht/d0e9c7d1a475089f2646

chmod is in libc and the api is:
     #include <sys/stat.h>

     int
     chmod(const char *path, mode_t mode);

     int
     fchmod(int fd, mode_t mode);

     int
     lchmod(const char *path, mode_t mode);

     int
     fchmodat(int fd, const char *path, mode_t mode, int flag);

where mode_t is defined as an unsigned 16 bit integer:
/usr/include/sys/_types.h:typedef       __uint16_t      __mode_t;

**Comment by headius** [comment]
Ahh well if mode_t is 16-bit uint that could explain it. jnr-posix, through which we call chmod, currently uses a 32-bit signed int (Java int) for the signature.

**Comment by headius** [comment]
Hmm... well we do have a test for fchmod in jnr-posix and that appears to be passing just fine.

**Comment by headius** [comment]
If you would like to help move this along, a test for jnr-posix's chmod would help us determine if the problem is there or in JRuby's use of jnr-posix's chmod.
