### ISSUE TITLE
[Truffle] method_added needed for MRI tests

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2820]
The following error occurs when trying to run an MRI test.
Command:
```
jruby -X+T test/mri/runner.rb -v --color=never --tty=no -q -- ruby/test_alias.rb
```
Error:
```
jruby -X+T test/mri/runner.rb -v --color=never --tty=no -q -- ruby/test_alias.rb
/Users/brandonfish/Documents/jruby-mine/test/mri/lib/minitest/unit.rb:1389:in `(singleton-def)': undefined method `method_added' for #<Class:0x114> (NoMethodError)
	from /Users/brandonfish/Documents/jruby-mine/test/mri/lib/minitest/unit.rb:1388:in `TestCase'
	from /Users/brandonfish/Documents/jruby-mine/test/mri/lib/minitest/unit.rb:1242:in `Unit'
	from /Users/brandonfish/Documents/jruby-mine/test/mri/lib/minitest/unit.rb:746:in `MiniTest'
	from /Users/brandonfish/Documents/jruby-mine/test/mri/lib/minitest/unit.rb:12:in `<main>'
	from /Users/brandonfish/Documents/jruby-mine/test/mri/lib/test/unit.rb:5:in `<main>'
	from test/mri/runner.rb:7:in `<main>'

```

**Comment by chrisseaton** [comment]
There are quite a lot of these hook methods that we don't call yet.

**Comment by bjfish** [comment]
The method might be able to be added here with the actual hooks just to get the some tests to run.

**Comment by eregon** [comment]
I'll do it.

**Comment by bjfish** [comment]
This method has been added here https://github.com/jruby/jruby/commit/70a63303888211e670ed395d8209d2d5a40ee228 which resolves the error above.

**Comment by eregon** [comment]
Awesome!

**Comment by bjfish** [comment]
The hooks still need to be called if you want to look at that @eregon , I only added the method

**Comment by eregon** [comment]
Fixed.
