### ISSUE TITLE
[Truffle] Dir.mktmpdir required for a lot of MRI tests

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2837]
For reference, here is a patch of changes to temporarily workaround this issue (you may need to adjust tmp var to your local `echo $TMPDIR`): 
https://gist.github.com/bjfish/013d9e650f9b17799dbf

Expected:
```
ruby -e 'require "tmpdir"; tmpdir = Dir.mktmpdir("autoload"); puts "Done"'
Done
```
Actual
```
~/Documents/jruby/bin/jruby -X+T -e 'require "tmpdir"; tmpdir = Dir.mktmpdir("autoload"); puts "Done"'
/Users/brandonfish/Documents/jruby/lib/ruby/truffle/mri/../../stdlib/tmpdir.rb:93:in `mkdir': wrong number of arguments (2 for 1) (ArgumentError)
	from /Users/brandonfish/Documents/jruby/lib/ruby/truffle/mri/../../stdlib/tmpdir.rb:93:in `block in mktmpdir'
	from /Users/brandonfish/Documents/jruby/lib/ruby/truffle/mri/../../stdlib/tmpdir.rb:146:in `create'
	from /Users/brandonfish/Documents/jruby/lib/ruby/truffle/mri/../../stdlib/tmpdir.rb:93:in `mktmpdir'
	from -e:1:in `<main>'

```

**Comment by chrisseaton** [comment]
Fixed in b67e232d94b24ab0c1ef1a0ff6c842c68d728b00
