### ISSUE TITLE
activesupport 4.2.1 breaks timeout.rb on jruby 1.7.19 and 1.7.20

### ISSUE THREAD

**Issue by ggayan** [jruby/jruby#2940]
Hey people,

I've just reported an issue on Adhearsion when using the latest gem versions: https://github.com/adhearsion/adhearsion/issues/549

What I found is that in the context of our adhearsion app, Celluloid crashes un jruby when upgrading to activesupport 4.2.1, but not on MRI. Moving back to 4.1.0 solves the problem.

I'm still trying to reduce the issue to a simple case, but this is what I've found so far:

https://gist.github.com/ggayan/5c90f10c59c4c747b6be

Any insights are greatly appreciated.

NOTE: MRI 1.9.3 as well as 2.1.5 works.

**Comment by kares** [comment]
as notes by @enebo already on the gist, there's probably another runtime-exception the NPE hides
... likely [related to the argument passed](https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/ext/timeout/Timeout.java#L123-L128) to `timeout` besides figuring out what changed in AS 4.2.x you could try a simple patch to figure out the timeout argument passed : 

```ruby
require 'timeout'
Timeout.module_eval do
  class << self
    alias_method :_timeout_impl, :timeout
    def timeout(*args, &block)
      puts "Timeout.timeout(#{args.inspect})"
      _timeout_impl(*args, &block)
    end
  end
end
```

**Comment by ggayan** [comment]
Thanks, I'll try that

**Comment by ggayan** [comment]
@kares: I got `Timeout.timeout([45 seconds])`. It is the expected value

**Comment by kares** [comment]
@ggayan or not .. seems like an AS::Duration rather than a Fixnum could you inspect the class and caller e.g. `puts " ... timeout(#{args.inspect}) #{args.first.class} \n  #{caller.join("  \n")}"`

**Comment by ggayan** [comment]
Gotcha!

```
... timeout([45 seconds]) ActiveSupport::Duration
 /Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/future-resource-1.1.0/lib/future-resource.rb:64:in `resource'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/punchblock-2.6.0/lib/punchblock/command_node.rb:29:in `response'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/adhearsion-2.6.0/lib/adhearsion/call.rb:462:in `write_and_await_response'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/future.rb:14:in `new'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `initialize'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `create'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/Users/ggayan/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `create_with_logging_context'
```

**Comment by ggayan** [comment]
I guess that I was giving a wrong argument to `Timeout`, which expects a Fixnum or a Float.

**Comment by kares** [comment]
re-opening as we still need to find the route cause for this : 

```
jruby-1.7.20 :001 > require 'rails'
 => true 
jruby-1.7.20 :002 > require 'rails/all'
 => true 
jruby-1.7.20 :003 > ActiveSupport::VERSION::STRING
 => "4.1.10" 
jruby-1.7.20 :004 > Timeout.timeout(5.seconds) { puts 'holla!'; sleep(6) }
NameError: uninitialized constant Timeout
	from org/jruby/RubyModule.java:2733:in `const_missing'
	from (irb):4:in `evaluate'
	from org/jruby/RubyKernel.java:1111:in `eval'
	from org/jruby/RubyKernel.java:1511:in `loop'
	from org/jruby/RubyKernel.java:1274:in `catch'
	from org/jruby/RubyKernel.java:1274:in `catch'
	from /opt/local/rvm/rubies/jruby-1.7.20/bin/irb:13:in `(root)'
jruby-1.7.20 :005 > require 'timeout'
 => true 
jruby-1.7.20 :006 > Timeout.timeout(5.seconds) { puts 'holla!'; sleep(6) }
holla!
Timeout::Error: execution expired
	from org/jruby/RubyKernel.java:835:in `sleep'
	from (irb):6:in `evaluate'
	from org/jruby/ext/timeout/Timeout.java:126:in `timeout'
	from (irb):6:in `evaluate'
	from org/jruby/RubyKernel.java:1111:in `eval'
	from org/jruby/RubyKernel.java:1511:in `loop'
	from org/jruby/RubyKernel.java:1274:in `catch'
	from org/jruby/RubyKernel.java:1274:in `catch'
	from /opt/local/rvm/rubies/jruby-1.7.20/bin/irb:13:in `(root)'
jruby-1.7.20 :007 > 
```

```
jruby-1.7.20 :001 > require 'rails'
 => true 
jruby-1.7.20 :002 > require 'rails/all'
 => true 
jruby-1.7.20 :003 > ActiveSupport::VERSION::STRING
 => "4.2.1" 
jruby-1.7.20 :004 > require 'timeout'
 => true 
jruby-1.7.20 :005 > Timeout.timeout(5.seconds) { puts 'holla!'; sleep(6) }
Java::JavaLang::NullPointerException: 
	from org.jruby.ext.timeout.Timeout.killTimeoutThread(Timeout.java:219)
	from org.jruby.ext.timeout.Timeout.timeout(Timeout.java:128)
	from org.jruby.ext.timeout.Timeout$INVOKER$s$timeout.call(Timeout$INVOKER$s$timeout.gen)
	from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)
	from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)
	from org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)
	from org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)
	from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	from org.jruby.ast.RootNode.interpret(RootNode.java:129)
	from org.jruby.evaluator.ASTInterpreter.INTERPRET_EVAL(ASTInterpreter.java:95)
	from org.jruby.evaluator.ASTInterpreter.evalWithBinding(ASTInterpreter.java:184)
	from org.jruby.RubyKernel.evalCommon(RubyKernel.java:1148)
	from org.jruby.RubyKernel.eval19(RubyKernel.java:1111)
	from org.jruby.RubyKernel$INVOKER$s$0$3$eval19.call(RubyKernel$INVOKER$s$0$3$eval19.gen)
	from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:180)
	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
... 115 levels...
```
... it's probably a 4.2 "bug" of how Duration is converted or `timeout` patched

**Comment by kares** [comment]
turns out there's difference between 4.1 and 4.2 around the type of argument passed to `timeout` :
```
4.2.1
Timeout.timeout([5 seconds]) ActiveSupport::Duration 
 timeout_bug.rb:22:in `<main>'
holla!
timeout_bug.rb:22:in `sleep': execution expired (Timeout::Error)
	from timeout_bug.rb:22:in `block in <main>'
	from timeout_bug.rb:9:in `timeout'
	from timeout_bug.rb:22:in `<main>'
kares@sputnik:~/workspace/oss/jruby$ 
kares@sputnik:~/workspace/oss/jruby$ 
kares@sputnik:~/workspace/oss/jruby$ ruby timeout_bug.rb 4.1.10
4.1.10
Timeout.timeout([5 seconds]) Fixnum 
 timeout_bug.rb:22:in `<main>'
holla!
timeout_bug.rb:22:in `sleep': execution expired (Timeout::Error)
	from timeout_bug.rb:22:in `block in <main>'
	from timeout_bug.rb:9:in `timeout'
	from timeout_bug.rb:22:in `<main>'
```
after https://github.com/jruby/jruby/commit/1e2d2dd1a667d4b7fb8f826f4d9b1d05a1eff41d the underlying issue reveals itself (on JRuby) :
```
4.2.1
Timeout.timeout([5 seconds]) ActiveSupport::Duration 
 timeout_bug.rb:22:in `(root)'
TypeError: can't convert ActiveSupport::Duration into Float
  timeout at org/jruby/ext/timeout/Timeout.java:122
  timeout at timeout_bug.rb:9
```
