### ISSUE TITLE
[Truffle] Issue with zsuper calls and optional arguments

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#2947]
Truffle currently will not pass the default values for optional arguments up to `super` calls.  E.g.,

```
class A
  def m(x, y, z)
    p "A#m(#{x}, #{y}, #{z})"
  end
end

class B < A
  def m(x, y, z = nil)
    super
    p "B#m(#{x}, #{y}, #{z})"
  end
end

B.new.m(5, 4, 3)
B.new.m(5, 4)
```

Running in MRI we get:

```
> ruby -v zsuper.rb 
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
A#m(5, 4, 3)
B#m(5, 4, 3)
A#m(5, 4, )
B#m(5, 4, )
```

In JRuby+Truffle, we get:

```
> bin/jruby -X+T -v zsuper.rb 
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-05-14 5ed91b4 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [linux-amd64]
A#m(5, 4, 3)
B#m(5, 4, 3)
zsuper.rb:2:in `m': wrong number of arguments (2 for 3) (ArgumentError)
	from zsuper.rb:9:in `m'
	from zsuper.rb:15:in `<main>'
```

**Comment by chrisseaton** [comment]
Specs in d265a61f98c7caa26f778155d9795ebe7aac0f90

**Comment by chrisseaton** [comment]
Fixed in various commits. There are still limitations if we have both rest arguments and named args, and probably also with unnamed rest args, but these are now documented in failing specs.
