### ISSUE TITLE
JRuby 9.0.0.0.pre2 raises "NameError: uninitialized class variable @@PREFIX_MAP in Object", doesn't occur in Ruby 2.2.x

### ISSUE THREAD

**Issue by garysweaver** [jruby/jruby#3042]
Have a project with the following in the Gemfile:

```ruby
gem 'rails-units', '~> 1.6.0', github: 'garysweaver/rails-units'
```

In Rails, when it hits `Bundler.require(:default, Rails.env)` in application.rb, it spews:

```
$ rake test
rake aborted!
NameError: uninitialized class variable @@PREFIX_MAP in Object
.../.rvm/gems/jruby-9.0.0.0.pre2@.../bundler/gems/rails-units-20913bc1b887/lib/rails_units/unit.rb:123:in `block in setup'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../bundler/gems/rails-units-20913bc1b887/lib/rails_units/unit.rb:122:in `block in setup'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../bundler/gems/rails-units-20913bc1b887/lib/rails_units/unit.rb:118:in `setup'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../bundler/gems/rails-units-20913bc1b887/lib/rails_units/unit.rb:1272:in `<top>'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/activesupport-4.../lib/active_support/dependencies.rb:1:in `block in (root)'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/activesupport-4.../lib/active_support/dependencies.rb:229:in `require'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/activesupport-4.../lib/active_support/dependencies.rb:214:in `load_dependency'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/activesupport-4.../lib/active_support/dependencies.rb:229:in `<top>'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../bundler/gems/rails-units-20913bc1b887/lib/rails-units.rb:12:in `block in (root)'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/bundler-1.10.3/lib/bundler/runtime.rb:1:in `block in (root)'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `require'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `require'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `<top>'
.../.rvm/gems/jruby-9.0.0.0.pre2@.../gems/bundler-1.10.3/lib/bundler.rb:134:in `<top>'
.../config/application.rb:10:in `(root)'
.../Rakefile:1:in `(root)'
.../Rakefile:5:in `block in (root)'
```

It doesn't raise this in Ruby 2.2.x or JRuby 1.7.20, so it's a bit odd.

**Comment by enebo** [comment]
Reduced test case:
```ruby
class Foo
  @@A = {}

  def self.setup
    for name in [1] do
      for value in [1] do
        p @@A
      end
    end
  end
end

Foo.setup
```
Looks like we are counting for scopes in our calculation for cvars?  Only one for loop is fine.  for in Ruby is over time becoming increasingly esoteric so I suspect we lack some coverage here...

**Comment by subbuss** [comment]
@garysweaver please verify fix. Thanks.
