### ISSUE TITLE
[Truffle] module_eval missing constant error

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3052]
Found in RSS lib,
Example
```ruby
module ExampleModule
   class Element
   end

   module_eval(<<-HEREDOC
   class Test < Element
      def hello
        puts "Hello"
      end
   end
   HEREDOC
   )
end
ExampleModule::Test.new.hello
```
Expected
```
$ ruby modeval.rb 
Hello
```
Actual
```
$ ~/Documents/jruby/bin/jruby -X+T modeval.rb 
(eval):2:in `const_missing': uninitialized constant Element (NameError)
	from (eval):2:in `<main>'
	from modeval.rb:5:in `ExampleModule'
	from modeval.rb:1:in `<main>'
````

**Comment by eregon** [comment]
I guess we should preserve lexical scope across eval.

**Comment by chrisseaton** [comment]
Simple test case:

```ruby
module ExampleModule
   FOO = 14
   p module_eval("FOO")
end
```

**Comment by eregon** [comment]
Fixed.

**Comment by chrisseaton** [comment]
Please add truffle-dev to any closed PRs or issues.
