### ISSUE TITLE
[Truffle] Requiring paths with . for current directory doesn't work

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3079]
```
$ cat a.rb 
require("./b.rb")
$ cat b.rb 
puts("hi")
$ ruby2.1 a.rb                                                                                
hi
$ ../work/jruby/bin/jruby a.rb 
hi
$ ../work/jruby/bin/jruby -X+T -J-server a.rb 
a.rb:1:in `require': cannot load such file -- ./b.rb (LoadError)
        from a.rb:1:in `<main>'
```

**Comment by eregon** [comment]
Quick and probably good fix would be to expand relative to CWD if it start with "./".

**Comment by eregon** [comment]
Should be good now.
