### ISSUE TITLE
[Truffle] Resolution of core files consider wrong files and dirs

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#3144]
``` bash
$ mkdir -p core/hash/bla
$  bin/jruby -X+T -e 'p :hi'    
core:/core/hash:1:in `method_missing': undefined local variable or method `bla' for Object (NameError)
    from core:/core/hash:1:in `<main>'
    from core:/core.rb:136:in `<main>'
Truffle internal error: org.jruby.truffle.runtime.control.TruffleFatalException: couldn't load the core library
org.jruby.truffle.runtime.control.TruffleFatalException: couldn't load the core library
    at org.jruby.truffle.runtime.core.CoreLibrary.initializeAfterMethodsAdded(CoreLibrary.java:589)
...
```

And it even gets to a NoMethodError with the name of the first directory entry?
`core:/core.rb:136` is

``` ruby
require_relative 'core/hash' # Our changes
```

**Comment by eregon** [comment]
It now fails in a different way:
```
$ jt ruby --jexceptions -e "require_relative 'core/hash'"
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.jruby.truffle.core.kernel.KernelNodes$RequireRelativeNode.dirname(KernelNodes.java:1330)
	at org.jruby.truffle.core.kernel.KernelNodes$RequireRelativeNode.getFullPath(KernelNodes.java:1322)
	at org.jruby.truffle.core.kernel.KernelNodes$RequireRelativeNode.requireRelative(KernelNodes.java:1298)
```
