### ISSUE TITLE
[Truffle] Error on build

### ISSUE THREAD

**Issue by brauliobo** [jruby/jruby#3305]
`jt build` run:
```
[INFO] JRuby
[INFO] JRuby Core
[INFO] JRuby Truffle
[INFO] JRuby Lib Setup
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby 9.0.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby Core 9.0.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jruby.jcodings:jcodings:jar:1.0.13-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JRuby .............................................. SUCCESS [  0.505 s]
[INFO] JRuby Core ......................................... FAILURE [  0.538 s]
[INFO] JRuby Truffle ...................................... SKIPPED
[INFO] JRuby Lib Setup .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.452 s
[INFO] Finished at: 2015-09-02T22:05:16-03:00
[INFO] Final Memory: 10M/210M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jruby-core: Could not resolve dependencies for project org.jruby:jruby-core:jar:9.0.0.0-SNAPSHOT: Failure to find org.jruby.jcodings:jcodings:jar:1.0.13-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jruby-core
FAILED (pid 28099 exit 1): mvn package
```

**Comment by nirvdrum** [comment]
@brauliobo Can you please try pulling from master and seeing if you have the same problem?  I think all the SNAPSHOT dependencies were deleted when JRuby 9.0.0.0 was released.  Current master is 9.0.2.0-SNAPSHOT, so you've missed a couple releases.

**Comment by brauliobo** [comment]
oops, just did a fetch and forgot to pull :P.
sorry and thanks!

**Comment by brauliobo** [comment]
after the pull there is now another problem:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby 9.0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ jruby-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby Core 9.0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ jruby-core ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-core ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (jruby-revision) @ jruby-core ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd /home/braulio/Projects/others/jruby/core && git rev-parse --verify --short=7 HEAD
[INFO] Working directory: /home/braulio/Projects/others/jruby/core
[INFO] Storing buildNumber: aae72b5 at timestamp: 1441315137430
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd /home/braulio/Projects/others/jruby/core && git rev-parse --verify --short=7 HEAD
[INFO] Working directory: /home/braulio/Projects/others/jruby/core
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jruby-core ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 36 resources
[INFO] Copying 1 resource
[INFO] Copying 1 resource to /home/braulio/Projects/others/jruby/core/src/main/java
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (anno) @ jruby-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jruby-core ---
[INFO] Compiling 1 source file to /home/braulio/Projects/others/jruby/core/target/classes
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-populators) @ jruby-core ---
[INFO] Source directory: /home/braulio/Projects/others/jruby/core/target/generated-sources added.
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (invoker-generator) @ jruby-core ---
Exception in thread "main" java.lang.NoSuchFieldError: classLoader
        at org.jruby.internal.runtime.methods.DumpingInvocationMethodFactory.endClass(DumpingInvocationMethodFactory.java:64)
        at org.jruby.internal.runtime.methods.InvocationMethodFactory.getAnnotatedMethodClass(InvocationMethodFactory.java:432)
        at org.jruby.anno.InvokerGenerator.main(InvokerGenerator.java:83)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JRuby .............................................. SUCCESS [  0.464 s]
[INFO] JRuby Core ......................................... FAILURE [  3.527 s]
[INFO] JRuby Truffle ...................................... SKIPPED
[INFO] JRuby Lib Setup .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.819 s
[INFO] Finished at: 2015-09-03T18:19:00-03:00
[INFO] Final Memory: 35M/351M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (invoker-generator) on project jruby-core: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jruby-core
FAILED (pid 7793 exit 1): ./mvnw package
```

**Comment by chrisseaton** [comment]
Did you try cleaning `./mvnw -Pclean` and `./mvnw clean`? It looks like something isn't being recompiled. JRuby usually builds very reliably (tests sometimes fail but it always builds).

**Comment by brauliobo** [comment]
@chrisseaton it now compiles, thanks!
