### ISSUE TITLE
got error while ruby -v for jruby 1.7.1

### ISSUE THREAD

**Issue by rajcybage** [jruby/jruby#3385]
````
rajarshi@rajarshi-X200CA:~$ ruby -v
jruby 1.7.0.preview2 (1.9.3p203) 2012-08-07 4a6bb0a on OpenJDK 64-Bit Server VM 1.7.0_79-b14 [linux-amd64]
2015-10-11T12:09:01.240+05:30: Ruby: org.objectweb.asm.ClassReader
java.lang.ClassNotFoundException: org.objectweb.asm.ClassReader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.jruby.util.JRubyClassLoader.findClass(JRubyClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.jruby.javasupport.JavaSupport.loadJavaClass(JavaSupport.java:156)
	at org.jruby.javasupport.JavaSupport.loadJavaClassVerbose(JavaSupport.java:165)
	at org.jruby.javasupport.JavaClass.forNameVerbose(JavaClass.java:1194)
	at org.jruby.javasupport.Java.getProxyOrPackageUnderPackage(Java.java:940)
	at org.jruby.javasupport.Java.get_proxy_or_package_under_package(Java.java:969)
	at org.jruby.javasupport.JavaUtilities.get_proxy_or_package_under_package(JavaUtilities.java:54)
	at org.jruby.javasupport.JavaUtilities$INVOKER$s$2$0$get_proxy_or_package_under_package.call(JavaUtilities$INVOKER$s$2$0$get_proxy_or_package_under_package.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:201)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:158)
	at org.jruby.javasupport.util.RuntimeHelpers$MethodMissingMethod.call(RuntimeHelpers.java:489)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.callMethodMissing(CachingCallSite.java:379)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:289)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:63)
	at org.jruby.ast.ConstDeclNode.interpret(ConstDeclNode.java:97)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:226)
	at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:123)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:113)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_CLASS(ASTInterpreter.java:104)
	at org.jruby.evaluator.ASTInterpreter.evalClassDefinitionBody(ASTInterpreter.java:271)
	at org.jruby.ast.ModuleNode.interpret(ModuleNode.java:120)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:120)
	at org.jruby.Ruby.runInterpreter(Ruby.java:807)
	at org.jruby.Ruby.loadFile(Ruby.java:2571)
	at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:66)
	at org.jruby.runtime.load.LoadService.loadFromClassLoader(LoadService.java:348)
	at org.jruby.ext.jruby.JRubyLibrary.load(JRubyLibrary.java:80)
	at org.jruby.runtime.load.LoadService.reflectedLoad(LoadService.java:590)
	at org.jruby.ext.LateLoadingLibrary.load(LateLoadingLibrary.java:48)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:895)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:533)
	at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:417)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:381)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:1032)
	at org.jruby.RubyKernel.require19(RubyKernel.java:1024)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:327)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:120)
	at org.jruby.Ruby.runInterpreter(Ruby.java:807)
	at org.jruby.Ruby.loadFile(Ruby.java:2571)
	at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:66)
	at org.jruby.runtime.load.LoadService.load(LoadService.java:327)
	at org.jruby.RubyKernel.loadCommon(RubyKernel.java:1058)
	at org.jruby.RubyKernel.load19(RubyKernel.java:1050)
	at org.jruby.RubyKernel$INVOKER$s$0$1$load19.call(RubyKernel$INVOKER$s$0$1$load19.gen)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:120)
	at org.jruby.Ruby.runInterpreter(Ruby.java:807)
	at org.jruby.Ruby.loadFile(Ruby.java:2571)
	at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:66)
	at org.jruby.runtime.load.LoadService.loadFromClassLoader(LoadService.java:348)
	at org.jruby.Ruby.initRubyKernel(Ruby.java:1579)
	at org.jruby.Ruby.init(Ruby.java:1133)
	at org.jruby.Ruby.newInstance(Ruby.java:264)
	at org.jruby.Main.internalRun(Main.java:249)
	at org.jruby.Main.run(Main.java:231)
	at org.jruby.Main.run(Main.java:215)
	at org.jruby.Main.main(Main.java:195)

````

**Comment by mkristian** [comment]
you version is kind of old, please use any of the recent jruby versions: 9.0.1.0 or 1.7.22
