### ISSUE TITLE
Pathname#relative_path_from with korean characters fails with: "no implicit conversion from nil to integer"

### ISSUE THREAD

**Issue by rtyler** [jruby/jruby#3424]
```
An error occurred: no implicit conversion from nil to integer
org/jruby/RubyString.java:2834:in `[]'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/pathname.rb:48:in `chop_basename'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/pathname.rb:103:in `cleanpath_aggressive'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/pathname.rb:91:in `cleanpath'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/pathname.rb:493:in `relative_path_from'
/home/tyler/source/github/jenkinsci/jenkins.io/build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/page_loader.rb:39:in `block in load_all'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/pathname.rb:551:in `block in find'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/find.rb:48:in `block in find'
org/jruby/RubyKernel.java:1098:in `catch'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/find.rb:47:in `block in find'
org/jruby/RubyArray.java:1560:in `each'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/find.rb:42:in `find'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/pathname.rb:551:in `find'
build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/page_loader.rb:25:in `load_all'
build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/engine.rb:265:in `load_pages'
build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/engine.rb:69:in `run'
build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/cli/generate.rb:21:in `run'
build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:125:in `invoke_generate'
build/tmp/asciidoctor/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:49:in `invoke!'
build/tmp/asciidoctor/gems/awestruct-0.5.5/bin/awestruct:9:in `<top>'
org/jruby/RubyKernel.java:957:in `load'
build/tmp/asciidoctor/bin/awestruct:23:in `<top>'
```

**Comment by rtyler** [comment]
I'm a bit lost as to how to create a reproduction case for this, given the challenges I'm having getting these damned unicode strings from one place to another (lol linux).

This was reproduced on JRuby 9.0.1.0 and 9.0.3.0. This same codebase and directory structure worked just fine under JRuby 1.7.22

**Comment by sprkweb** [comment]
I have the same issue. JRuby 9.0.5.0 and 9.1.7.0, Linux. Cyrillic characters.
The error is shown when I use `bundler install`.
Places which call the method are https://github.com/bundler/bundler/blob/master/lib/bundler/source/path.rb#L136 and https://github.com/bundler/bundler/blob/master/lib/bundler/env.rb#L47
The paths are `/mnt/hdd/Проекты/Текущие/tarona/Gemfile` and `/mnt/hdd/Проекты/Текущие/tarona`

**Comment by headius** [comment]
Confirmed with Cyrillic characters on OS X with master:

```
$ jruby -rpathname -e 'Pathname.new("/Users/headius/Текущие/blah").relative_path_from("/Users")'
TypeError: no implicit conversion from nil to integer
                    [] at org/jruby/RubyString.java:2995
         chop_basename at /Users/headius/projects/jruby/lib/ruby/stdlib/pathname.rb:44
  cleanpath_aggressive at /Users/headius/projects/jruby/lib/ruby/stdlib/pathname.rb:109
             cleanpath at /Users/headius/projects/jruby/lib/ruby/stdlib/pathname.rb:87
    relative_path_from at /Users/headius/projects/jruby/lib/ruby/stdlib/pathname.rb:505
                <main> at -e:1
```
