### ISSUE TITLE
Passing a ruby class as a java.lang.Class into Java land

### ISSUE THREAD

**Issue by carlosmrce** [jruby/jruby#3454]
//Job.java
    package br.eti.mribeiro;
    
    public interface Job {
    	void teste();
    }

    //Teste.java
    package br.eti.mribeiro;
    
    public class Teste {
    	public void executaJob(Class<? extends Job> classe){
    		try {
    			Job job = classe.newInstance();
    			job.teste();
    		} catch (InstantiationException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		} catch (IllegalAccessException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}
    		
    	}
    }

    #jruby_teste.rb
    require File.join(File.dirname(File.expand_path(__FILE__)), 'teste_jruby.jar')
    
    java_import 'br.eti.mribeiro.Job'
    java_import 'br.eti.mribeiro.Teste'
    
    class TesteJob
      include Job
      def teste
        puts "123456"
      end
    end
    Teste.new.executaJob(TesteJob.class)

I guess the code above is pretty self explaining, i hava a Ruby class that implements a Java interface, and i want to pass that class back to another Java class. However, when a execute the ruby code i get the following error: 

    java.lang.InstantiationException: org.jruby.RubyClass
            at java.lang.Class.newInstance(Class.java:359)
            at br.eti.mribeiro.Teste.executaJob(Teste.java:6)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:606)
            at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:452)
            at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:313)
            at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
            at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
            at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
            at teste.invokeOther18:executaJob(teste.rb)
            at teste.RUBY$script(teste.rb:14)
            at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
            at org.jruby.ir.Compiler$1.load(Compiler.java:111)
            at org.jruby.Ruby.runScript(Ruby.java:822)
            at org.jruby.Ruby.runScript(Ruby.java:814)
            at org.jruby.Ruby.runNormally(Ruby.java:752)
            at org.jruby.Ruby.runFromMain(Ruby.java:574)
            at org.jruby.Main.doRunFromMain(Main.java:409)
            at org.jruby.Main.internalRun(Main.java:304)
            at org.jruby.Main.run(Main.java:231)
            at org.jruby.Main.main(Main.java:200)

Shouldn't this work?

ps: teste_jruby.jar is a jar file i exported with the java code.

Thanks,
Carlos.

**Comment by kares** [comment]
unfortunately, java support currently does not go that far - you can not instantiate a Ruby defined class on Java's side as `class.newInstance()` ... probably possible to implement to some extent although its tricky.

**Comment by carlosmrce** [comment]
Ouch!!! This will force me to write a bunch of messy java-ruby bridges. The lack of this feature basically males impossible to use a bunch of java libraries from ruby. Looking forward to this being implemented.

**Comment by kimptoc** [comment]
You could write your Teste class in Ruby and then your code would work like this:

   Teste.new.executaJob(TesteJob) # don't specify .class

But I guess it depends what else you are doing as to whether that is valid.

**Comment by carlosmrce** [comment]
@kimptoc i get the same error!

**Comment by kimptoc** [comment]
@carlosmrce hmm - worked for me :) .  The Ruby Teste class I used was something like this:

```
class Teste 
    def executaJob(classe)
        begin
            Job job = classe.new
            job.teste
        rescue Exception => e
           puts e.message
        end
    end
end
```

**Comment by kares** [comment]
also, should be able to "over-come" the limitation by forcing a Java-class to be generated for the Ruby one:
```ruby
class TesteJob
  include Job
  def teste
    puts "123456"
  end
end
teste_jclass = TesteJob.become_java!
Teste.new.executaJob( teste_jclass )
# teste_jclass.newInstance works fine
```

**Comment by kimptoc** [comment]
become_java! - interesting, thanks for that. https://github.com/jruby/jruby/wiki/GeneratingJavaClasses

**Comment by carlosmrce** [comment]
Thanks a lot for the tip @kares !!! Solved the problem for me!

**Comment by kares** [comment]
still would be useful to get this working better out-of-the box (without explicit `become_java!`)

**Comment by carlosmrce** [comment]
@kares  I got another error

C:\>jruby teste.rb
rubyobj.TesteJob
br/eti/mribeiro/Teste.java:8:in `executaJob': java.lang.AbstractMethodError: rubyobj.TesteJob.teste()V
        from java/lang/reflect/Method.java:497:in `invoke'
        from teste.rb:15:in `<top>'
        from java/lang/invoke/MethodHandle.java:625:in `invokeWithArguments'

It breaks on the line 'job.teste();'
