### ISSUE TITLE
IllegalArgumentException when using Fiddle to 

### ISSUE THREAD

**Issue by npomf** [jruby/jruby#3477]
Using the `fiddle` stdlib library from Ruby 2.2.2, the following error is raised:

`Java::JavaLang::IllegalArgumentException: Invalid parameter type: VOID`

This is presumably during the process of mapping a foreign function's signature against the loaded library (in this case, `OpenGL32.dll`).  The function signatures have been written to as closely match the OpenGL 4.5 spec as possible.  An example is provided below:

```ruby
extern 'void glTexImage2D( GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, void* )'
```

This function returns `void` (no value) and takes a number of parameters whose types are aliases of normal C types.  These aliases are defined before any function is loaded via the overwritten `extern()` method of the `Fiddle::Importer` implementation.

Though not listed in the stack trace in the next section, my best estimate is that the error occurs in or around the marked section of code:

```ruby
def self.extern( signature, *opts )

    # **** LIKELY SUSPECT A ****
    sym, returns, args = parse_signature( signature, @type_alias )
    name = sym.gsub( /@.+/, '')
    opt = parse_bind_options( opts )

    # **** LIKELY SUSPECT B ****
    fptr = import_function( sym, returns, args, opt[ :call_type ]) rescue procaddr( name, returns, args )

    # get invocation location
    file, line = caller.first.scan( /^(.+?):(\d+)/ ).map {|(f, l)| [f, l ? l.to_i - 2 : nil] }.flatten

    # register function
    GL_FUNCTIONS_MAP[ name.to_sym ] = fptr
    module_eval( %Q{
        def #{name}( *args, &block )
            GL_FUNCTIONS_MAP[ :#{name} ].call( *args, &block )
        end
    }, file || __FILE__, line || __LINE__ + 3 )
    module_function( name )

    # return pointer
    fptr
end

# Define the ProcAddress loader for Windows and Linux systems, and load the remote procedure into a new `Fiddle::Function`.
def self.procaddr( name, returns, args )
    if @@procaddr.nil?
        func = case @@platform
            when Platform::Windows then 'wglGetProcAddress'
            when Platform::Linux then 'glXGetProcAddress'
            when Platform::Macintosh then raise NotImplementedError, "#{name}() is not implemented on your system"
        end

        # **** LIKELY SUSPECT C ****
        @@procaddr = Fiddle::Function.new( handler[ func ], [Fiddle::TYPE_VOIDP], Fiddle::TYPE_VOIDP )
    end
    Fiddle::Function.new( @@procaddr.call( name ), args, returns )
end
```

(Full source code is available [here](https://github.com/npomf/neon/blob/master/lib/opengl/gl_core.rb))

**Possible analysis**

* For item **A**, the arguments are parsed using Fiddle's internal parsing mechanism, which could choke on the VOID type declaration as listed above.
* Item **B** attempts to import the function using the mapped types for the arguments, and results in a similar scenario.  However, on failure to find the function (due to function loading behaviors), it will invoke `procaddr()` to bind from.
* In item **C**, we use the proc address specified by the loading function in the platform-specific library.  This will then bind the function through the loading function, which is declared with the argument and return value, `Fiddle::TYPE_VOIDP` ([documentation](http://ruby-doc.org/stdlib-2.2.2/libdoc/fiddle/rdoc/Fiddle.html#TYPE_VOIDP)).  This is analogous to the C-type, `void*`.

However, as the error indicates a parameter type of VOID, it is likely that **A** is producing the identifier `Fiddle::TYPE_VOID` for `void*` rather than the correct `Fiddle::TYPE_VOIDP`.

**Notice**

It is unclear if this is the correct behavior or not, though I suspect it may be incorrect.  No such error is caused when the same operation is performed in Ruby 2.2.2

**JIRB output**

The following is produced with `$DEBUG = true` and `$VERBOSE = true` in JIRB.

```
irb(main):003:0> load 'lib/opengl.rb'
D:/JRuby/lib/ruby/stdlib/fiddle/import.rb:215: warning: instance variable @type_alias not initialized
D:/JRuby/lib/ruby/stdlib/fiddle/import.rb:215: warning: instance variable @type_alias not initialized
Java::JavaLang::IllegalArgumentException: Invalid parameter type: VOID
        from org.jruby.ext.ffi.jffi.DefaultMethodFactory.getMarshaller(DefaultMethodFactory.java:244)
        from org.jruby.ext.ffi.jffi.DefaultMethodFactory.getMarshaller(DefaultMethodFactory.java:151)
        from org.jruby.ext.ffi.jffi.DefaultMethodFactory.createMethod(DefaultMethodFactory.java:59)
        from org.jruby.ext.ffi.jffi.MethodFactory.createDynamicMethod(MethodFactory.java:27)
        from org.jruby.ext.ffi.jffi.Function.createDynamicMethod(Function.java:168)
        from org.jruby.ext.ffi.jffi.Function.<init>(Function.java:53)
        from org.jruby.ext.ffi.jffi.Function.newInstance(Function.java:135)
        from org.jruby.ext.ffi.jffi.Function$INVOKER$s$0$2$newInstance.call(Function$INVOKER$s$0$2$newInstance.gen)
        from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        from org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
        from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
        from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        from org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:127)
        from org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:113)
        from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
... 166 levels...
        from org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:183)
        from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        from D_3a_.JRuby.bin.jirb.invokeOther13:start(D:/JRuby/bin/jirb)
        from D_3a_.JRuby.bin.jirb.RUBY$script(D:/JRuby/bin/jirb:13)
        from java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:625)
        from org.jruby.ir.Compiler$1.load(Compiler.java:111)
        from org.jruby.Ruby.runScript(Ruby.java:821)
        from org.jruby.Ruby.runScript(Ruby.java:813)
        from org.jruby.Ruby.runNormally(Ruby.java:751)
        from org.jruby.Ruby.runFromMain(Ruby.java:573)
        from org.jruby.Main.doRunFromMain(Main.java:409)
        from org.jruby.Main.internalRun(Main.java:304)
        from org.jruby.Main.run(Main.java:233)
        from org.jruby.Main.main(Main.java:200)irb(main):004:0>
```

**Environment information**

Ruby:  `ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]`
JRuby:  `jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [Windows 7-amd64`

**Comment by npomf** [comment]
After checking the OpenAL wrapper (which uses very similar code but no function loading routine) and is also affected by the error, the only analogous line which is a probable cause between the two is:

```ruby
sym, ctype, argtype = parse_signature( signature, @type_alias )
```

This leads me to believe it is possibly the JFFI management of Fiddle's signature parsing that is resulting in the incorrect argument type being returned or processed.

**Comment by npomf** [comment]
Stumbled upon the source code of `JFFIInvoker` and found the for-loop which checks parameter types at [Line 52](https://github.com/headius/jruby/blob/master/core/src/main/java/org/jruby/ext/ffi/jffi/JFFIInvoker.java#L52).  It appears to contain where the error is raised:

```java
com.kenai.jffi.Type[] jffiParamTypes = new com.kenai.jffi.Type[parameterTypes.length];
for (int i = 0; i < jffiParamTypes.length; ++i) {
    if ((jffiParamTypes[i] = FFIUtil.getFFIType(parameterTypes[i])) == null) {
        throw runtime.newArgumentError("Invalid parameter type " + parameterTypes[i]);
    }
}
```

It would appear that `VOID` is listed as a valid parameter type (see: [FFIUtil.java:30](https://github.com/headius/jruby/blob/master/core/src/main/java/org/jruby/ext/ffi/jffi/FFIUtil.java#L30)).

**Comment by npomf** [comment]
I have found by replacing all signatures of `glXXXX( void )` with `glXXXX()` that this alleviates the problem.

This behavior differs from MRI's fiddle implementation.

I now encounter the following:

```
NameError: uninitialized constant Fiddle::CParser::TYPE_PTRDIFF_T
	from org/jruby/RubyModule.java:3181:in `const_missing'
	from /home/developer/jruby-9.0.4.0/lib/ruby/stdlib/fiddle/cparser.rb:160:in `parse_ctype'
	from /home/developer/jruby-9.0.4.0/lib/ruby/stdlib/fiddle/cparser.rb:169:in `parse_ctype'
	from /home/developer/jruby-9.0.4.0/lib/ruby/stdlib/fiddle/cparser.rb:88:in `block in parse_signature'
	from org/jruby/RubyArray.java:2295:in `collect'
	from /home/developer/jruby-9.0.4.0/lib/ruby/stdlib/fiddle/cparser.rb:88:in `parse_signature'
	from lib/opengl/gl.rb:47:in `extern'
	from lib/opengl/gl.rb:212:in `import_symbols'
	from lib/opengl/gl.rb:42:in `load_lib'
	from (irb):13:in `<eval>'
	from org/jruby/RubyKernel.java:978:in `eval'
	from org/jruby/RubyKernel.java:1291:in `loop'
	from org/jruby/RubyKernel.java:1098:in `catch'
	from org/jruby/RubyKernel.java:1098:in `catch'
	from /home/developer/jruby-9.0.4.0/bin/jirb:13:in `<top>'
```

This seems strange again, as `TYPE_PTRDIFF_T` is [standard to MRI's fiddle](http://ruby-doc.org/stdlib-2.2.3/libdoc/fiddle/rdoc/Fiddle.html#TYPE_PTRDIFF_T).
