### ISSUE TITLE
StackOverflowError while rendering Java 8's default method

### ISSUE THREAD

**Issue by jinahya** [jruby/jruby#3596]
Please forgive me if I'm standing on a wrong spot.
I'm using Asciidoctor for rendering an article.
So far so good until I include a code snippet containing `default method` of Java 8. 
I honesty couldn't pinpoint which stack is wrong. (jruby?, asciidoctor?)

Here comes the stacktrace.
```
Exception in thread "main" java.lang.StackOverflowError
	at org.jruby.RubyString.hashCode(RubyString.java:1273)
	at org.jruby.RubyHash.internalGetEntry(RubyHash.java:550)
	at org.jruby.RubyHash.internalGet(RubyHash.java:544)
	at org.jruby.RubyHash.op_aref(RubyHash.java:1093)
	at org.jruby.RubyHash$INVOKER$i$1$0$op_aref.call(RubyHash$INVOKER$i$1$0$op_aref.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
	at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.IfNode.interpret(IfNode.java:110)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.MultipleAsgn19Node.interpret(MultipleAsgn19Node.java:104)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
```

**Comment by jinahya** [comment]
Sorry, it seems it was my fault. I'll reopen this issue if if occur again.
