### ISSUE TITLE
NPE while loading compiled .class - method def with rescue statement

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3701]
another LoadError: sample.class is not compiled Ruby; use java_import to load normal classes

* sample.rb* 
```ruby
class Sample
  def _call
    # no-op
  #rescue LoadError => e
  #  e || 1 # doesn't matter
  rescue => e
    #e || 2 # doesn't matter
  end
end
```

`jruby -e "require 'jruby'; JRuby.runtime.debug = true; require './sample.class'"`

```
Caused by: java.lang.NullPointerException
	at org.jruby.ir.persistence.IRReaderStream.decodeInstr(IRReaderStream.java:188)
	at org.jruby.ir.persistence.IRReaderStream.decodeInstructionsAt(IRReaderStream.java:173)
	at org.jruby.ir.persistence.IRReader.load(IRReader.java:54)
	at org.jruby.ir.runtime.IRRuntimeHelpers.decodeScopeFromBytes(IRRuntimeHelpers.java:1448)
```
```

**Comment by kares** [comment]
obviously working when compiled under 9.1
