### ISSUE TITLE
encoding of utf8 symbols (eg. :λ) 

### ISSUE THREAD

**Issue by elia** [jruby/jruby#3719]
The failing Opal build: https://travis-ci.org/opal/opal/jobs/114673459#L372
[The failing specs][specs] have been added [recently][commit], also maybe it's just a matter of setting the correct locale env vars as in https://github.com/jruby/jruby/issues/2204

[specs]: https://github.com/opal/opal/blob/0ac003566b7fc53845d7395b47d84f54cfc6421c/spec/lib/parser/variables_spec.rb#L105-L109
[commit]: https://github.com/opal/opal/commit/5716c3456feabe2280091b8f623f147ff109d789

### Environment

```bash
$ java -Xmx32m -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
$ javac -J-Xmx32m -version
javac 1.7.0_76
$ ruby --version
jruby: warning: unknown property jruby.cext.enabled
jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-03-09 5b08612 Java HotSpot(TM) 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 +jit [linux-amd64]
$ rvm --version
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
jruby: warning: unknown property jruby.cext.enabled
Bundler version 1.6.9
$ gem --version
jruby: warning: unknown property jruby.cext.enabled
2.4.8
```

### Expected/Actual Behavior

```rb
  1) Opal::Parser parses unicode local variables
     Failure/Error: parsed("λ = 1").should == [:lasgn, :λ, [:int, 1]]
       expected: [:lasgn, :?, [:int, 1]]
            got: (:lasgn, :λ, (:int, 1)) (using ==)
     # ./spec/lib/parser/variables_spec.rb:106:in `block in (root)'
  2) Opal::Parser parses unicode constants
     Failure/Error: parsed("FOOλ = 1").should == [:cdecl, :FOOλ, [:int, 1]]
       expected: [:cdecl, :FOO?, [:int, 1]]
            got: (:cdecl, :FOOλ, (:int, 1)) (using ==)
     # ./spec/lib/parser/variables_spec.rb:102:in `block in (root)'
```

**Comment by phluid61** [comment]
Is this related to #4070 ?

**Comment by elia** [comment]
Probably yes, see also #3880.

**Comment by headius** [comment]
#4070 is fixed but #3880 is not. There's a chance this is already fixed for 9.1.9.0, or it may be fixed by work @enebo and I are doing to finally fix up symbol encodings (probably for 9.2, depending on impact).

I could not find the original branch for this reproduction, so I'm unsure how to test it. @elia?

**Comment by elia** [comment]
@headius the reason is that we switched to use the `parser` gem for parsing instead of our home brew solution and the specs are now gone from `master`. The relevant spec is still available on the [`0-10-stable` branch](https://github.com/opal/opal/blob/0-10-stable/spec/lib/parser/variables_spec.rb#L102-L104). 

Feel free to close this issue at your discretion.

---

In case you want to repro the issue just do the following:

```bash
git clone https://github.com/opal/opal --recursive --branch 0-10-stable
bundle install
# remove the RUBY_PLATFORM check
bundle exec rspec spec/lib/parser/variables_spec.rb
```

**Comment by elia** [comment]
@headius confirmed, thanks!
