### ISSUE TITLE
Compilation fails with openjdk8 u92

### ISSUE THREAD

**Issue by brauliobo** [jruby/jruby#3838]
Just switching to openjdk7 u99 make it succeed

**Comment by headius** [comment]
Looks like the problem was our `sun.misc.Unsafe` mock being out of date. They added this:

```java
    /**
     * Throws IllegalAccessError; for use by the VM.
     * @since 1.8
     */
    private static void throwIllegalAccessError() {
        throw new IllegalAccessError();
    }
```

The javac command line `mvn -X` shows doesn't include the additional flags we pass (like bootstrap-shifting our unsafe-mock into place) but removing our mock let the build complete. With just-released unsafe-mock-8.92 we should be good to go again.

**Comment by headius** [comment]
Here's the actual error, FWIW, along with the useless Maven error.

Maven:
```
[INFO] Compiling 1 source file to /Users/headius/projects/jruby/core/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JRuby .............................................. SUCCESS [  0.219 s]
[INFO] JRuby Core ......................................... FAILURE [  1.506 s]
[INFO] JRuby Truffle ...................................... SKIPPED
[INFO] JRuby Lib Setup .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.693 s
[INFO] Finished at: 2016-04-29T13:41:40-05:00
[INFO] Final Memory: 34M/385M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project jruby-core: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project jruby-core: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:915)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jruby-core
```

javac with command line:
```
$ javac -J-Xbootclasspath/p:/Users/headius/.m2/repository/com/headius/unsafe-mock/8.0/unsafe-mock-8.0.jar -d /Users/headius/projects/jruby/core/target/classes -classpath /Users/headius/projects/jruby/core/target/classes:/Users/headius/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/Users/headius/.m2/repository/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.jar:/Users/headius/.m2/repository/org/ow2/asm/asm-tree/5.0.4/asm-tree-5.0.4.jar:/Users/headius/.m2/repository/org/ow2/asm/asm-analysis/5.0.4/asm-analysis-5.0.4.jar:/Users/headius/.m2/repository/org/ow2/asm/asm-util/5.0.4/asm-util-5.0.4.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-netdb/1.1.5/jnr-netdb-1.1.5.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-enxio/0.12/jnr-enxio-0.12.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-unixsocket/0.12/jnr-unixsocket-0.12.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-posix/3.0.29/jnr-posix-3.0.29.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-constants/0.9.2-SNAPSHOT/jnr-constants-0.9.2-SNAPSHOT.jar:/Users/headius/.m2/repository/com/github/jnr/jnr-ffi/2.0.9/jnr-ffi-2.0.9.jar:/Users/headius/.m2/repository/com/github/jnr/jffi/1.2.12-SNAPSHOT/jffi-1.2.12-SNAPSHOT.jar:/Users/headius/.m2/repository/com/github/jnr/jffi/1.2.12-SNAPSHOT/jffi-1.2.12-SNAPSHOT-native.jar:/Users/headius/.m2/repository/org/jruby/joni/joni/2.1.10/joni-2.1.10.jar:/Users/headius/.m2/repository/org/jruby/extras/bytelist/1.0.13/bytelist-1.0.13.jar:/Users/headius/.m2/repository/org/jruby/jcodings/jcodings/1.0.17/jcodings-1.0.17.jar:/Users/headius/.m2/repository/org/jruby/dirgra/0.3/dirgra-0.3.jar:/Users/headius/.m2/repository/com/headius/invokebinder/1.7/invokebinder-1.7.jar:/Users/headius/.m2/repository/com/headius/options/1.4/options-1.4.jar:/Users/headius/.m2/repository/com/headius/coro-mock/1.0/coro-mock-1.0.jar:/Users/headius/.m2/repository/com/headius/unsafe-mock/8.0/unsafe-mock-8.0.jar:/Users/headius/.m2/repository/com/headius/jsr292-mock/1.1/jsr292-mock-1.1.jar:/Users/headius/.m2/repository/org/ow2/asm/asm-debug-all/5.0_BETA/asm-debug-all-5.0_BETA.jar:/Users/headius/.m2/repository/bsf/bsf/2.4.0/bsf-2.4.0.jar:/Users/headius/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/Users/headius/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/Users/headius/.m2/repository/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.jar:/Users/headius/.m2/repository/org/apache/ant/ant/1.9.2/ant-1.9.2.jar:/Users/headius/.m2/repository/org/apache/ant/ant-launcher/1.9.2/ant-launcher-1.9.2.jar:/Users/headius/.m2/repository/org/osgi/org.osgi.core/5.0.0/org.osgi.core-5.0.0.jar:/Users/headius/.m2/repository/org/jruby/joda-timezones/2013d/joda-timezones-2013d.jar:/Users/headius/.m2/repository/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar:/Users/headius/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar: -sourcepath /Users/headius/projects/jruby/core/src/main/java:/Users/headius/projects/jruby/core/target/generated-sources/annotations:/Users/headius/projects/jruby/core/target/generated-sources: /Users/headius/projects/jruby/core/src/main/java/org/jruby/runtime/Constants.java -s /Users/headius/projects/jruby/core/target/generated-sources -processor org.jruby.anno.AnnotationBinder -g -verbose -deprecation -target 1.7 -source 1.7 -encoding utf-8 -XDignore.symbol.file=true
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000106b773ca, pid=20080, tid=0x0000000000001303
#
# JRE version:  (8.0_92-b14) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x5773ca]  universe_post_init()+0x6a9
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/headius/projects/jruby/hs_err_pid20080.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Abort trap: 6
```

I guess it really didn't like us taking that method away.

**Comment by chrisseaton** [comment]
Nothing like a forrest of plexuses, classworlds and mojos to make problems easy to understand.
