### ISSUE TITLE
Jruby9000 caybara webkit throws exception

### ISSUE THREAD

**Issue by pcsgithubid** [jruby/jruby#3889]

**Comment by pcsgithubid** [comment]
after executing the feature spec, it throws the below exception.  but
still spec continues and pass

technical stack

jruby 9000
capybara webkit 1.3.0

Finished in 7.94 seconds (files took 12.13 seconds to load)
1 example, 0 failures

java.nio.channels.AsynchronousCloseException
  at
java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
  at sun.nio.ch.SourceChannelImpl.read(SourceChannelImpl.java:173)
  at org.jruby.RubyIO.transfer(RubyIO.java:4241)
  at org.jruby.RubyIO.copy_stream(RubyIO.java:4136)
  at
org.jruby.RubyIO$INVOKER$s$0$2$copy_stream.call(RubyIO$INVOKER$s$0$2$copy_stream.gen)
  at
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:693)
  at
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
  at
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
  at
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
  at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
  at
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:321)
  at
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
  at
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:136)
  at
org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:118)
  at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)
  at org.jruby.runtime.Block.call(Block.java:106)
  at org.jruby.RubyProc.call(RubyProc.java:324)
  at org.jruby.RubyProc.call(RubyProc.java:239)
  at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
  at java.lang.Thread.run(Thread.java:745)

**Comment by headius** [comment]
Can you provide a way for us to reproduce this and tell us exactly what JRuby version you're using?

**Comment by pcsgithubid** [comment]
i am using jruby-9.0.0.0 and trying to execute feature spec with enabled js: true  with capybara-webkit driver.when i run the feature spec, after completing spec, it throws the above exception

**Comment by BanzaiMan** [comment]
Two things:

1. `capybara-webkit` 1.3.0 is quite old (https://rubygems.org/gems/capybara-webkit/versions/1.3.0)
1. A recent version of `capybara-webkit`, while it claims to be compatible with JRuby (1.7.19), may or may not install smoothly (https://github.com/thoughtbot/capybara-webkit/issues/725#issuecomment-212672551). This is not to say that it doesn't work. I don't have expertise to make that judgement.

I'm only saying that this combination of things may not work at all.

**Comment by pcsgithubid** [comment]
does jruby9000 works fine with poltergriest ?

**Comment by pcsgithubid** [comment]
i get the same exception with jruby-9.1.3 and latest capybara webkit 1.11.1

**Comment by headius** [comment]
@pcsgithubid If you could, please create a simple github repo that we can use to reproduce on 9.1.4.0. I am not familiar with getting capybara set up and using it for testing. With a reproduction we may find this very quickly.
