### ISSUE TITLE
Different handling of default values and Hash splat values than MRI

### ISSUE THREAD

**Issue by boberetezeke** [jruby/jruby#3910]
### Environment

Using JRuby 9.1.0.0
Using MRI 2.3.0

### Expected Behavior

I am not sure what the expected behavior is. JRuby's seems more consistent, but both seem weird. The behavior has to do with having a default positional parameter and passing in a hash. If there is
no default parameter, then the hash goes to the first argument. If there is one, then it is captured by
the **hargs always with JRuby and sometimes with MRI (seems if the hash keys are symbols).

### Actual Behavior

Here is the code that demonstrates the difference:

```ruby
def no_hargs_test(x, **hargs)
  puts "no_hargs: x = #{x.inspect}"
  puts "hargs = #{hargs.inspect}"
end

def hargs_test(x=1, **hargs)
  puts "hargs: x = #{x.inspect}"
  puts "hargs = #{hargs.inspect}"
end
```

JRuby:
```text
---------- called with 5 ---------
no_hargs: x = 5
hargs = {}
hargs: x = 5
hargs = {}
---------- called with [5] ---------
no_hargs: x = [5]
hargs = {}
hargs: x = [5]
hargs = {}
---------- called with :x => 3 ---------
no_hargs: x = {:x=>3}
hargs = {}
hargs: x = 1
hargs = {:x=>3}
---------- called with 'x' => 3 ---------
no_hargs: x = {"x"=>3}
hargs = {}
hargs: x = 1
hargs = {"x"=>3}
---------- called with :a => 3 ---------
no_hargs: x = {:a=>3}
hargs = {}
hargs: x = 1
hargs = {:a=>3}
---------- called with 'a' => 3 ---------
no_hargs: x = {"a"=>3}
hargs = {}
hargs: x = 1
hargs = {"a"=>3}
```

MRI:
```text
---------- called with 5 ---------
no_hargs: x = 5
hargs = {}
hargs: x = 5
hargs = {}
---------- called with [5] ---------
no_hargs: x = [5]
hargs = {}
hargs: x = [5]
hargs = {}
---------- called with :x => 3 ---------
no_hargs: x = {:x=>3}
hargs = {}
hargs: x = 1
hargs = {:x=>3}
---------- called with 'x' => 3 ---------
no_hargs: x = {"x"=>3}
hargs = {}
hargs: x = {"x"=>3}
hargs = {}
---------- called with :a => 3 ---------
no_hargs: x = {:a=>3}
hargs = {}
hargs: x = 1
hargs = {:a=>3}
---------- called with 'a' => 3 ---------
no_hargs: x = {"a"=>3}
hargs = {}
hargs: x = {"a"=>3}
hargs = {}
```

**Comment by headius** [comment]
@boberetezeke Hey there! If these cases don't already exist in https://github.com/ruby/spec, you should definitely put together a pull request.

We know that there's several cases we don't quite have right yet, and have not managed to get them fixed yet. I know @enebo in particular wants to get these remaining issues tidied up. Having good specs for all these failing cases will help us get it done quicker :-)

Did you run into this in a library, or your own code, or just playing around?

**Comment by boberetezeke** [comment]
I am working on a project that will be using Datomic and so I tried the tests in JRuby and one of the 222 tests failed. This is the reason why. I will look into RubySpec for a test on this or make one. I am not sure however how it really should work.

**Comment by headius** [comment]
As of JRuby 9.4 we match Ruby 3.1 behavior, which has the following output and rejects the `:a` forms:

```
[] jruby $ jruby blah.rb
no_hargs: x = 5
hargs = {}
hargs: x = 5
hargs = {}
no_hargs: x = [5]
hargs = {}
hargs: x = [5]
hargs = {}
ArgumentError: wrong number of arguments (given 0, expected 1)
  no_hargs_test at blah.rb:1
         <main> at blah.rb:15
... 3 levels...
[] jruby $ (chruby 3.1 ; ruby blah.rb)
no_hargs: x = 5
hargs = {}
hargs: x = 5
hargs = {}
no_hargs: x = [5]
hargs = {}
hargs: x = [5]
hargs = {}
blah.rb:1:in `no_hargs_test': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from blah.rb:15:in `<main>'
```

There's no going back so I'm marking this as fixed in 9.4.0.0 (already released).
