### ISSUE TITLE
No existing session to resume

### ISSUE THREAD

**Issue by dgolombek** [jruby/jruby#3974]
### Environment

* jruby-openssl 0.9.17
* net-http-persistent 2.9.4

### Expected Behavior

Opening a new session should work.

### Actual Behavior

```
No existing session to resume: org/jruby/ext/openssl/SSLSocket.java:217:in `connect'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
org/jruby/ext/timeout/Timeout.java:115:in `timeout'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.25.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:756:in `do_start'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.25.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:751:in `start'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:965:in `reset'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:628:in `connection_for'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:25:in `perform_request'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `call'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:21:in `with_net_http_connection'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
```

Calls from up in Faraday and higher elided. This started after upgrading from 0.9.16 to 0.9.17 and went away as soon as we reverted. It happened on every session that was created. I believe this was caused by ed95b2c7bf85c3b4d3ff430cf7656cc4ac92535d

**Comment by dgolombek** [comment]
Sorry, wrong project, moving this to https://github.com/jruby/jruby-openssl/issues/97
