### ISSUE TITLE
stdlib update for 9.1 (from Ruby 2.3.1)

### ISSUE THREAD

**Issue by kares** [jruby/jruby#4087]
JRuby 9.1 did not update stdlib to accompany changes from Ruby 2.3.1and is currently at 2.3.0

there are however issues e.g. "old-style" yaml AR column serialization failing as : 
```
NoMethodError: undefined method `key?' for nil:NilClass
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/ostruct.rb:176:in `respond_to_missing?'
org/jruby/RubyKernel.java:1857:in `respond_to?'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:380:in `init_with'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:373:in `revive'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:207:in `visit_Psych_Nodes_Mapping'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/visitor.rb:15:in `visit'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/visitor.rb:5:in `accept'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:31:in `accept'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:310:in `visit_Psych_Nodes_Document'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/visitor.rb:15:in `visit'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/visitor.rb:5:in `accept'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:31:in `accept'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych/nodes/node.rb:37:in `to_ruby'
/opt/local/rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/psych.rb:252:in `load'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/coders/yaml_column.rb:26:in `load'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/type/serialized.rb:19:in `type_cast_from_database'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/attribute.rb:104:in `type_cast'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/attribute.rb:42:in `original_value'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/attribute.rb:37:in `value'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/attribute_set.rb:31:in `fetch_value'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
/opt/local/rvm/gems/jruby-9.1.2.0@jdbc/gems/activerecord-4.2.6/lib/active_record/attribute_methods.rb:50:in `content'
```
... while this seems to be a Psych issue its worked around in ostruc.rb 2.3.1 : https://github.com/ruby/ruby/commit/4c1ac0bc07eb7ae03684761351953418ad5deb1b

would have updated the ostruct.rb file but I am unsure of the policy - maybe its best if the whole stdlib is upgraded and the reported Ruby compatibility version is upgraded at a **2.3.1** patch level.

// cc @enebo @headius should this get into 9.1.3 or too risky to update the .rb stdlib ?

**Comment by headius** [comment]
We would like to update stdlib but need to review diffs and make sure any changes committed to jruby/jruby get back into jruby/ruby. I can work on that today.
