### ISSUE TITLE
jruby-gradle plugin fails with a 9.1.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by robertpanzer** [jruby/jruby#4114]
### Environment

JRuby 9.1.3.0-SNAPSHOT (999cea0a0012a14fee62370c3fbe9a8fa1ec0f9a)
MacOS and Windows
Java 1.8.0_91
Grade 2.14

### Expected Behavior

The JRuby Gradle plugin should be able to install Ruby gems in the AsciidoctorJ build.

### Actual Behavior

The build fails with this error:
```
:asciidoctorj:jrubyPrepare
[Fatal Error] erubis-2.7.0.pom:15:35: The content of elements must consist of well-formed character data or markup.
[Fatal Error] erubis-2.7.0.pom:15:35: The content of elements must consist of well-formed character data or markup.
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at org.jruby.RubyInstanceConfig.<init>(RubyInstanceConfig.java:84)
        at org.jruby.Main.<init>(Main.java:101)
        at org.jruby.Main.main(Main.java:200)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
:asciidoctorj:jrubyPrepare FAILED
```

It seems like the classes are missing in the 9.1.3.0-SNAPSHOT. 
They are present in a jruby-core-9.1.2.0.jar but missing in jruby-core-9.1.3.0-SNAPSHOT.jar.

**Comment by mkristian** [comment]
@robertpanzer I am not sure how you built the SNAPSHOT, with `mvn clean install -Pdist` ? `mvn clean install` does not produce a release artifact ! `mvn clean install -Pdist` or `mvn clean install -Pcomplete` or some other profile is needed.

**Comment by robertpanzer** [comment]
I called `./mvnw -Pall $skipTests`.
At least I got some artifacts installed in my local maven cache.
Did I miss some steps?

**Comment by mkristian** [comment]
@robertpanzer no you did not, all indeed does not build the release artifact for core :(

lemme fix this.

**Comment by mkristian** [comment]
@robertpanzer I did not run your gradle example but manually tested the content of the jar.

**Comment by robertpanzer** [comment]
Thanks! Also retested!
