### ISSUE TITLE
#__send__ wrong number of arguments N+1 for N (compile.fastest=true + JDK 7)

### ISSUE THREAD

**Issue by glebm** [jruby/jruby#416]
I am trying out my Rails app with jruby-1.7.0

After a few concurrent requests (under puma) I start getting the following error

```
wrong number of arguments (1 for 0) 
/Users/glebm/.rvm/rubies/jruby-1.7.0/lib/ruby/1.9/monitor.rb:139:in `signal'
activerecord (3.2.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:289:in `checkin'
```

Line 289 from connection_pool.rb:

```
@queue.signal
```

Line 139 from monitor.rb:

```
 @monitor.__send__(:mon_check_owner)
```

_Update_: A few more runs show that:
- At some point an arbitrary call to `__send__` starts failing
- So far I've seen the one in monitor (above), and `date.rb:1786` (5 for 4)
- Looks like this only happens with `compile.fastest=true` in .jrubyrc
- How do I investigate further?

---

```
$ java -version
java version "1.7.0_09"
Java(TM) SE Runtime Environment (build 1.7.0_09-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.5-b02, mixed mode)
```

**Comment by hydrogen18** [comment]
I can confirm this still happens with RoR 3.2. Does anyone have a workaround?

```
exception:	wrong number of arguments (1 for 0)
backtrace:	/home/ericu/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/monitor.rb:139:in `signal'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:289:in `checkin'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:406:in `_run__788318293__checkin__59997172__callbacks'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:390:in `_run_checkin_callbacks'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:287:in `checkin'
/home/ericu/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ericu/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:286:in `checkin'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:120:in `release_connection'
/home/ericu/community/config/initializers/000_rails_patches.rb:121:in `release_connection_with_synchronization'
/home/ericu/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/ericu/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'
/home/ericu/community/config/initializers/000_rails_patches.rb:120:in `release_connection_with_synchronization'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:131:in `with_connection'
/home/ericu/community/vendor/gems/background_jobs/lib/background_jobs/consumer.rb:225:in `handleDelivery'
/home/ericu/.rvm/gems/jruby-1.7.19@community/gems/statsd-ruby-1.2.1/lib/statsd.rb:232:in `time'
/home/ericu/community/vendor/gems/background_jobs/lib/background_jobs/consumer.rb:224:in `handleDelivery'
/home/ericu/community/vendor/gems/background_jobs/lib/background_jobs/consumer.rb:222:in `handleDelivery'
```

**Comment by enebo** [comment]
1.7.x is EOL and this will not get fixed.  Marking WONTFIX
