### ISSUE TITLE
sshkit error while deploying with jruby-9.1.5.0

### ISSUE THREAD

**Issue by zoras** [jruby/jruby#4191]
Capistrano deployment works on `jruby-9.1.2.0` but fails with `jruby-9.1.5.0`
### Environment
- JRuby version (`jruby -v`)
  `jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 [darwin-x86_64]`
- Operating system
  `Mac OSX Seirra`
- Installed or activated gems
  `Capistrano, sshkit`
- Application/framework version
  `Rails`
### Expected Behavior
- Capistrano deployment works on `jruby-9.1.2.0` but fails with `jruby-9.1.5.0`
### Actual Behavior
- This is the error log while doing the deployment

``` [bash]
❯ cap staging deploy
Exception in thread "Ruby-0-Thread-2: /Users/zoras/.rvm/gems/jruby-9.1.5.0/gems/sshkit-1.11.2/lib/sshkit/runners/parallel.rb:10" java.lang.NullPointerException
    at org.jruby.ext.openssl.PKeyEC$Point.initialize(PKeyEC.java:836)
    at org.jruby.ext.openssl.PKeyEC$Point$INVOKER$i$0$0$initialize_DBG.call(PKeyEC$Point$INVOKER$i$0$0$initialize_DBG.gen)
    at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:724)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:368)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:205)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:209)
    at org.jruby.RubyClass.newInstance(RubyClass.java:1008)
    at org.jruby.RubyClass$INVOKER$i$newInstance_DBG.call(RubyClass$INVOKER$i$newInstance_DBG.gen)
    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
    at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
    at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
    at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
    at org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:189)
...
00:02 git:check
      01 git ls-remote --heads git@bitbucket.org:projectrepo/project.git
(Backtrace restricted to imported tasks)
cap aborted!
Net::SSH::Disconnect: connection closed by remote host

EOFError: End of file reached

Tasks: TOP => git:check
(See full trace by running task with --trace)
The deploy has failed with an error: connection closed by remote host
```

**Comment by headius** [comment]
I trimmed down your exception...please use a paste service like https://gist.github.com for long output.

It would be helpful if you could provide a way for us to reproduce this problem. You can also help us by running JRuby with `-Xjit.threshold=0` and providing the new backtrace using https://gist.github.com.

**Comment by headius** [comment]
Note also this is a jruby-openssl issue and probably should be re-opened at https://github.com/jruby/jruby-openssl/issues.

**Comment by zoras** [comment]
Thanks for the heads up @headius 
However, it throws the same exception with `-Xjit.threshold=0` JRuby option.

I can't get the demo app running in order to reproduce this problem for you
https://github.com/jruby/jruby-rails-templates/issues/2

**Comment by anteyk** [comment]
Hi @zoras did you found solution for this issue or workaround? I just faced with exactly same issue:(

**Comment by vorberohus** [comment]
Hello, having the same problem with sshkit and jruby-9.1.6.0

**Comment by anteyk** [comment]
Just found the solution, that works for me https://github.com/jruby/jruby-openssl/issues/105 (inserted that lines in started)

**Comment by zoras** [comment]
@anteyk I had been holding on to jruby-9.1.2.0 and I can confirm that works for me as well. Thanks, closing this issue.

**Comment by cmthakur** [comment]
@zoras you can try appending this lines to `deploy.rb` file. It works for me with `jruby 9.1.7.0 (2.3.1)`. I think its a `net-ssh` error.
```
Net::SSH::Transport::Algorithms::ALGORITHMS.values.each { |algs| algs.reject! { |a| a =~ /^ecd(sa|h)-sha2/ } }
Net::SSH::KnownHosts::SUPPORTED_TYPE.reject! { |t| t =~ /^ecd(sa|h)-sha2/ }
```
