### ISSUE TITLE
Zlib produces different output to MRI

### ISSUE THREAD

**Issue by pointlessone** [jruby/jruby#4244]
### Environment

Provide at least:
* JRuby 9.1.5.0
* macOS 10.12.1 developer beta

### Expected Behavior

Zlib should produce the same output as MRI given the same input.

I need to consistently generate same binary data in both MRI and JRuby.

### Actual Behavior

 In most cases Zlib actually generates the same output but in one case it does not. I don't know what is different. The output seem to be valid but I need consistency between implementations, too. I tried both compact syntax and a more explicit one.

```ruby
 Zlib::Deflate.deflate(data)
```

```ruby
z = Zlib::Deflate.new(
  Zlib::DEFAULT_COMPRESSION,
  Zlib::MAX_WBITS,
  Zlib::DEF_MEM_LEVEL,
  Zlib::HUFFMAN_ONLY
)
compressed_data = z.deflate(data, Zlib::FINISH)
z.close
```

They both produce output different to MRI.

Here's example data: [data.bin.zip](https://github.com/jruby/jruby/files/546623/data.bin.zip). The file is zipped because GH doesn't allow random files to be uploaded.

**Comment by kares** [comment]
same on 9.2 ... output is different

**Comment by headius** [comment]
This would not seem to be a bug in JRuby as much as a bug in jzlib, but I have no clues beyond that. Maybe @ymnk has an idea?

**Comment by HoneyryderChuck** [comment]
this happens to me as well:

```ruby
zstream = Zlib::Inflate.new(Zlib::MAX_WBITS + 32)
buf = zstream.inflate(binstr)
zstream.finish #=> Zlib::BufError: buffer error in jruby 10
zstream.close
```

**Comment by headius** [comment]
@HoneyryderChuck That is using the binary file provided by @pointlessone yes? If it was producing incorrect zlib output back then, the file may be invalid now. There have been many other fixes to zlib since 2016, including some related to inconsistent output, so I'm going to close this as invalid and we can reopen if @pointlessone reports that it's still broken.

Note this is unlikely to be the same as your other issue #9022 because that does still produce the same binary output as CRuby, it just does it in slightly different chunks.

**Comment by headius** [comment]
Lack of follow-up from user and original file is now not loadable on JRuby's zlib, so this probably was a bug in zlib/jzlib that we fixed some time ago.

Note that both CRuby and JRuby fail with similar errors now:

```
[] tmp $ jruby -rzlib blah.rb
Zlib::DataError: invalid stored block lengths
       << at org/jruby/ext/zlib/JZlibInflate.java:141
  inflate at org/jruby/ext/zlib/JZlibInflate.java:196
  inflate at org/jruby/ext/zlib/JZlibInflate.java:190
   <main> at blah.rb:2
[] tmp $ cx 3.4 ruby -rzlib blah.rb
blah.rb:2:in 'Zlib::Inflate#inflate': incorrect header check (Zlib::DataError)
	from blah.rb:2:in '<main>'
```
