### ISSUE TITLE
How to build jruby for a new platform --mips64el

### ISSUE THREAD

**Issue by vans88** [jruby/jruby#4246]
### Environment
os.arch: mips64el
os.name: fedora21
os.kernel: 4.4.21 
Java version: 1.8.0_25
.... .... 

### Expected Behavior
Recording the BUILDING.md file, run the command "./mvnw" and build successfully. but I can't find libjffi-1.2.so for my platform --mips64el-Linux/libjffi-1.2.so . **Any suggestions?** 
[root@dscn2 jruby]# find . -name *.so
./spec/ruby/fixtures/code/a/load_fixture.so
./spec/ruby/fixtures/code/load_fixture.ext.so
./spec/ruby/fixtures/code/load_fixture.so
./lib/jni/x86_64-Linux/libjffi-1.2.so
./lib/jni/x86_64-SunOS/libjffi-1.2.so
./lib/jni/i386-Linux/libjffi-1.2.so
./lib/jni/ppc64-Linux/libjffi-1.2.so
./lib/jni/i386-SunOS/libjffi-1.2.so
./lib/jni/sparcv9-SunOS/libjffi-1.2.so
./lib/jni/arm-Linux/libjffi-1.2.so
./lib/jni/aarch64-Linux/libjffi-1.2.so
./lib/jni/ppc64le-Linux/libjffi-1.2.so
./lib/jni/x86_64-FreeBSD/libjffi-1.2.so
./test/bogus.so

**Comment by enebo** [comment]
@vans88 unintuitively we build those as part of the https://github.com/jnr/jffi project.  Once build on each platform we commit them since we are not cross-compiling all of these platforms.

**Comment by headius** [comment]
Yes, @enebo is correct. We'd love to get MIPS support into jffi! Please open an issue there and try to build binaries for your platform. We'll incorporate them (and any necessary patches) into the next release.

**Comment by headius** [comment]
Keep this open until we can update our jffi to one that has MIPS support.

**Comment by vans88** [comment]
Many thanks to your reply, and your spirit of open source deeply encouraged me.  I will clone the  project ---https://github.com/jnr/jffi --- and build locally. if my get success, I will paste the modification  at the later comment.Thank you again.

**Comment by vans88** [comment]
###@headius

**Comment by vans88** [comment]
Currently， I find a dir named "mips" which contains the following files:

```
[root@dscn2 jffi]# ls -l /usr/local/jffi/jni/libffi/src/mips/
total 64
-rw-r--r-- 1 root root 26648 Oct 26 13:57 ffi.c
-rw-r--r-- 1 root root  6556 Oct 26 13:57 ffitarget.h
-rw-r--r-- 1 root root 14304 Oct 26 13:57 n32.S
-rw-r--r-- 1 root root 10586 Oct 26 13:57 o32.S
```

How do I use these file to get my platform supported?

**Comment by headius** [comment]
I am confused...did it build your .so or not? It sounds like you did get it to build a jar, and that jar when put into archive/ unpacked properly into the jni dir.

As for the libffi mips code...I would have expected libffi's Makefile to have done the right thing here. If it's not, that's where you would want to investigate.

Do you know of any way to get access to a MIPS environment somewhere in the cloud?

**Comment by vans88** [comment]
Er..., I have **jffi-native** rpm package installed in Fedora21 (mips64el),  via the command "rpm -ql jffi-native", a file named "libjffi-1.2.so" shown as follows:
```
[root@dscn2 archive]# rpm -ql jffi-native
/usr/lib/java/jffi-native.jar
/usr/lib/java/jffi/jffi-native.jar
/usr/lib64/jffi
/usr/lib64/jffi/mips64-Linux
/usr/lib64/jffi/mips64-Linux/libjffi-1.2.so
/usr/lib64/jffi/mips64-Linux/libjffi.so
/usr/share/doc/jffi-native
/usr/share/doc/jffi-native/COPYING.GPL
/usr/share/doc/jffi-native/COPYING.LESSER
/usr/share/doc/jffi-native/LICENSE
/usr/share/maven-metadata/jffi-native.xml
```
Here I  unpacked one of jars in "archive" directory, the same file named  "libjffi-1.2.so" will be found in a  platform-related DIR.
```
[root@dscn2 archive]# uname -a
Linux dscn2 4.4.21+ #3 SMP PREEMPT Wed Oct 12 09:14:23 CST 2016 mips64 mips64 mips64 GNU/Linux
[root@dscn2 archive]# uname -p
mips64
[root@dscn2 archive]# file /usr/lib64/jffi/mips64-Linux/libjffi-1.2.so
/usr/lib64/jffi/mips64-Linux/libjffi-1.2.so: ELF 64-bit LSB shared object, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, BuildID[sha1]=f599ca5881af7949a6e4551aac043384778ac9af, not stripped
```

**Comment by vans88** [comment]
Could I use the jffi-native rpm package instead of building jffi source from github? if so, What should I use the rpm jffi-native  to build jruby next? My final purpose is to build logstash, but when I run  the command bin/logstash -e "",  an error shown as follows:
```
[root@dscn2 logstash]# bin/logstash -e ""
Sending Logstash logs to /usr/local/logstash/logs which is now configured via log4j2.properties.
LoadError: Unsupported platform: unknown-linux
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /usr/local/logstash/vendor/jruby/lib/ruby/shared/ffi/ffi.rb:69
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /usr/local/logstash/vendor/jruby/lib/ruby/shared/ffi.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /usr/local/logstash/vendor/jruby/lib/ruby/shared/ffi.rb:1
           (root) at /usr/local/logstash/logstash-core/lib/logstash/util/prctl.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
             LibC at /usr/local/logstash/logstash-core/lib/logstash/util/prctl.rb:3
           (root) at /usr/local/logstash/logstash-core/lib/logstash/util/prctl.rb:2
           (root) at /usr/local/logstash/logstash-core/lib/logstash/util.rb:1
  set_thread_name at /usr/local/logstash/logstash-core/lib/logstash/util.rb:20
          execute at /usr/local/logstash/logstash-core/lib/logstash/runner.rb:204
           (root) at /usr/local/logstash/lib/bootstrap/environment.rb:68

```
through searching the keyword **"LoadError: Unsupported platform: unknown-linux"**, I know the above error caused by jruby' jffi doesn't support my platform mips64el.

` If you have a local JRuby installed you can force logstash to use your local JRuby instead of the embedded JRuby with the `USE_RUBY=1` environment variable.`

**Comment by vans88** [comment]
I very sorry to tell the fact that there doesn't a way to get access to a MIPS environment in the cloud so far. I  am also working for the mips cloud platform.

**Comment by vans88** [comment]
When useing  the jruby built from jruby project and set environment variable "USE_RUBY=1", I am getting the following errror:
```
[root@dscn2 logstash]# bin/logstash --help
/usr/local/share/gems/gems/bundler-1.13.5/lib/bundler.rb:429:in `rescue in eval_gemspec':  (Bundler::GemspecError)
[!] There was an error while loading `logstash-core-plugin-api.gemspec`: The logstash-core-api need to be build on jruby. Bundler cannot continue.

 #  from /usr/local/logstash/logstash-core-plugin-api/logstash-core-plugin-api.gemspec:27
 #  -------------------------------------------
 #    else
 >      raise "The logstash-core-api need to be build on jruby"
 #    end
 #  -------------------------------------------
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler.rb:421:in `eval_gemspec'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler.rb:374:in `block in load_gemspec_uncached'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/shared_helpers.rb:54:in `chdir'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/shared_helpers.rb:54:in `block in chdir'
        from /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/shared_helpers.rb:53:in `chdir'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler.rb:369:in `load_gemspec_uncached'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler.rb:359:in `load_gemspec'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/source/path.rb:146:in `block in load_spec_files'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/source/path.rb:145:in `each'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/source/path.rb:145:in `load_spec_files'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/source/path.rb:95:in `local_specs'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/source/path.rb:103:in `specs'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:665:in `block in converge_locked_specs'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:654:in `each'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:654:in `converge_locked_specs'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:243:in `resolve'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:174:in `specs'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:233:in `specs_for'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/definition.rb:222:in `requested_specs'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/runtime.rb:118:in `block in definition_method'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler/runtime.rb:19:in `setup'
        from /usr/local/share/gems/gems/bundler-1.13.5/lib/bundler.rb:99:in `setup'
        from /usr/local/logstash/lib/bootstrap/bundler.rb:64:in `setup!'
        from /usr/local/logstash/lib/bootstrap/environment.rb:64:in `<main>'
```

**Comment by kszsa** [comment]
@vans88 ,I encountered the same problem. I want to know if your logstash transplant has been successful, How to solve it? thanks!

**Comment by kszsa** [comment]
@vans88 ,I encountered the same problem. I want to know if your logstash transplant has been successful, How to solve it? thanks!

**Comment by trumanliu** [comment]
@kszsa +1,have you solved this problem?I am also trying to run logstash on a server with loongson cpu.

**Comment by trumanliu** [comment]
@kszsa +1,have you solved this problem?I am also trying to run logstash on a server with loongson cpu.

**Comment by headius** [comment]
@trumanliu Would it be possible for you to try running JRuby (without logstash) on whatever MIPS system you're using? I'm not sure about the status of MIPS support in our native bits, but it would help if we could confirm that latest JRuby doesn't work on its own (logstash ships with older versions of JRuby usually).

**Comment by headius** [comment]
FWIW one of the things that blocks some JRuby MIPS functionality is support for our native FFI library, jffi. Unfortunately the only PR we've gotten for MIPS has been abandoned: https://github.com/jnr/jffi/pull/63

**Comment by maggiedot** [comment]
@headius I have the same problem on the loongson mips64 when run logstash 6.4.0. I installed latest JRuby 9.2.7.0, and output is below:
```shell
[root@localhost bin]# ./jruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 25.192-b12 on 1.8.0_192-b12 +jit [linux-mips64el]
[root@localhost bin]# 
[root@localhost bin]# uname -a
Linux localhost.localdomain 3.10.0 #1 SMP PREEMPT Tue Mar 21 11:43:21 CST 2017 00012-g243a566 mips64 mips64 mips64 GNU/Linux
```

Wish it can help you.

**Comment by jackwang713** [comment]
I also encountered the same problem, on the mips64el platform jruby ffi can not run, I can provide a test platform for debugging, hoping to help improve these compatibility issues. If you need a remote connection, please contact me: 
jackwang713@163.com

**Comment by headius** [comment]
@jackwang713 That would be an enormous help! I will contact you by email.

**Comment by jackwang713** [comment]
@headius I don't know if you have received my mail. I've been waiting for two days.

**Comment by headius** [comment]
@jackwang713 Apologies, your email got routed weirdly in my email, perhaps because of the attachment. I have received it and connected successfully!

**Comment by jackwang713** [comment]
@headius Has there been any progress on this issue? What else can I help do?

**Comment by headius** [comment]
Sorry about the delay here.

JRuby master is now running with the jffi that has the FFI binary in place for mips64el-Linux, so that's part of the way.

I think we need to patch Platform.java to have MIPS as a platform entry (it already has Linux).

And then under lib/ruby/ffi/platform we need to get the appropriate files generated (or manually tweaked, since the generator seems broken currently) so that they have appropriate typedefs/sizes for all the listed types.

I'll see what I can do to get those typedefs generating.

**Comment by headius** [comment]
@jackwang713 Ok, are you able to at least start up JRuby master (maybe from a nightly build at https://jruby.org/nightly)? If so, I need to know the output of this code:

```
puts ENV_JAVA['os.name']
puts ENV_JAVA['os.arch']
```

That should let us get Platform.java updated.

**Comment by jackwang713** [comment]
I don't know how to run the code you gave me. I made the following attempt.
```
[root@mips ~]# ruby -e "puts ENV_JAVA['os.name']"
Traceback (most recent call last):
-e:1:in `<main>': uninitialized constant ENV_JAVA (NameError)
```
Using java to obtain System.getProperty("os.name") and System.getProperty("os.arch"), I got the result.
**`OSName:Linux,OSArch:mips64el`**

**Comment by headius** [comment]
@jackwang713 The command you ran shold have worked; I suspect it was run with CRuby instead of JRuby.

```
$ ruby -rpp -e 'pp ENV_JAVA.to_h'
{"java.runtime.name"=>"OpenJDK Runtime Environment",
 "jruby.home"=>"/Users/headius/projects/jruby",
 "sun.boot.library.path"=>
  "/Library/Java/JavaVirtualMachines/jdk-08-u202-b08-hotspot/Contents/Home/jre/lib",
 "java.vm.version"=>"25.202-b08",
```

Would it be possible to get access to your system again? You can send me an email with details.

**Comment by headius** [comment]
@jackwang713 I have updated our set of `types.conf` files from https://github.com/ffi/ffi, which may get us a bit further in running properly on your system. Would you be able to test out the branch in #5886?

**Comment by jujiangtao** [comment]
Hello！I want to know whether jruby can be built on the platform --mips64el now.

**Comment by headius** [comment]
@jujiangtao Greetings!

Much work has happened since this issue was last updated, and I believe JRuby itself supports mips64el fairly well at this point. I do not know whether that means JRuby will successfully build, since our build still uses a slightly older version of JRuby (for stability).

Could you work with me to finish this issue? We can start by having you run `./mvnw` on a clean checkout of JRuby and go from there.

**Comment by headius** [comment]
FWIW I would also like to understand the importance of *building* on mips64el. The binaries we distribute should work on mips64el without further building (we ship native bits for all supported platforms at once).
