### ISSUE TITLE
[Truffle] Add -run parameter

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#4267]
### Example
```sh
../../../../../bin/jruby -X+T -run -e rm -- -f openssl.su
../../../../../bin/jruby -run -e rm -- -f openssl.su
```

### Expected Behavior

```
$ ../../../../../bin/jruby -run -e rm -- -f openssl.su
# Removes file if it exists
```

### Actual Behavior
```
../../../../../bin/jruby -X+T -run -e rm -- -f openssl.su
WARNING: This JVM does not have the Graal compiler. JRuby+Truffle's performance without it will be limited. See https://github.com/jruby/jruby/wiki/Truffle-FAQ#how-do-i-get-jrubytruffle
/Users/brandonfish/Documents/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': cannot load such file -- un (LoadError)
	from /Users/brandonfish/Documents/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Also should work using `bin/jruby-truffle`

Found using `mkmf` makefile

**Comment by eregon** [comment]
Might be only the matter of putting stdlib's `un.rb` in our stdlib.

**Comment by bjfish** [comment]
I've added un here: 63af7288e13f2b7ab8bb084fb55073edc042d66f and had to stub `Thread::Backtrace::Location#label` to get this to work
