### ISSUE TITLE
New syntax errors in 2.3.1/2.3.2 tests.

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4308]
Items patched up in 2.3.1 presumably.

```
[6602/8090] TestSyntax#test_alias_symbol = 0.01 s     
 12) Failure:
TestSyntax#test_alias_symbol [/Users/headius/projects/jruby/test/mri/lib/test/unit/assertions.rb:818]:
[ruby-dev:47681] [Bug #8851].

1. [ 4/16] Assertion for "alias a %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tIDENTIFIER
   | alias a %s(p)>>.

2. [ 8/16] Assertion for "alias :'a' %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tIDENTIFIER
   | alias :'a' %s(p)>>.

3. [12/16] Assertion for "alias :\"a\" %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tIDENTIFIER
   | alias :"a" %s(p)>>.

4. [13/16] Assertion for "alias %s(a) p"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tLPAREN2
   | alias %s(a) p>>.

5. [14/16] Assertion for "alias %s(a) :'p'"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tLPAREN2
   | alias %s(a) :'p'>>.

6. [15/16] Assertion for "alias %s(a) :\"p\""
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tLPAREN2
   | alias %s(a) :"p">>.

7. [16/16] Assertion for "alias %s(a) %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:790:in `block in test_alias_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:791: syntax error, unexpected tLPAREN2
   | alias %s(a) %s(p)>>..

[6613/8090] TestSyntax#test_cmdarg_kwarg_lvar_clashing_method = 0.00 s         
 13) Failure:
TestSyntax#test_cmdarg_kwarg_lvar_clashing_method [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:367]:
[ruby-core:73816] [Bug#12073].
Exception raised:
<#<SyntaxError: [ruby-core:73816] [Bug#12073]:1: syntax error, unexpected ':'
a = 1; a b: 1>>.

[6614/8090] TestSyntax#test_dedented_heredoc_with_blank_less_indented_linesh: a: command not found
sh: line 2: b: command not found
sh: a: command not found
sh: line 2: b: command not found
[6615/8090] TestSyntax#test_dedented_heredoc_with_blank_less_indented_line_escapedsh: a: command not found
sh: line 2: b: command not found
sh: a: command not found
sh: line 2: b: command not found
[6616/8090] TestSyntax#test_dedented_heredoc_with_blank_more_indented_linesh: a: command not found
sh: line 2: b: command not found
sh: a: command not found
sh: line 2: b: command not found
 = 0.01 s
 14) Failure:
TestSyntax#test_dedented_heredoc_with_blank_more_indented_line [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:563]:

1. [3/4] Assertion for "'eos'"
   | <"a\n  \nb\n"> expected but was
   | <"a\n\nb\n">..

[6617/8090] TestSyntax#test_dedented_heredoc_with_blank_more_indented_line_escapedsh: a: command not found
sh: line 2: b: command not found
sh: a: command not found
sh: line 2: b: command not found
[6618/8090] TestSyntax#test_dedented_heredoc_with_concatenationsh: y: command not found    
[6619/8090] TestSyntax#test_dedented_heredoc_with_empty_linesh: This: command not found
sh: line 2: That: command not found
sh: This: command not found
sh: line 2: That: command not found
[6620/8090] TestSyntax#test_dedented_heredoc_with_indentationsh: a: command not found
sh: line 1: b: command not found
sh: a: command not found
sh: line 1: b: command not found
 = 0.01 s
 15) Failure:
TestSyntax#test_dedented_heredoc_with_indentation [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:533]:

1. [3/4] Assertion for "'eos'"
   | <" a\nb\n"> expected but was
   | <"a\nb\n">..

[6621/8090] TestSyntax#test_dedented_heredoc_with_interpolated_expressionsh: 1a: command not found
sh: line 1: zy: command not found
sh: 1a: command not found
sh: line 1: zy: command not found
 = 0.01 s
 16) Failure:
TestSyntax#test_dedented_heredoc_with_interpolated_expression [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:589]:

1. [3/4] Assertion for "'eos'"
   | <" \#{1}a\nzy\n"> expected but was
   | <"\#{1}a\nzy\n">..

[6622/8090] TestSyntax#test_dedented_heredoc_with_interpolated_stringsh: a: command not found
sh: line 1: zy: command not found
sh: a: command not found
sh: line 1: zy: command not found
 = 0.01 s
 17) Failure:
TestSyntax#test_dedented_heredoc_with_interpolated_string [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:598]:

1. [3/4] Assertion for "'eos'"
   | <"\#{mesg} a\n zy\n"> expected but was
   | <"\#{mesg} a\nzy\n">..

[6623/8090] TestSyntax#test_dedented_heredoc_without_indentationsh: y: command not found
sh: line 1: z: command not found
sh: y: command not found
sh: line 1: z: command not found
[6670/8090] TestSyntax#test_syntax_ext = 2.76 s                             
 18) Failure:
TestSyntax#test_syntax_ext [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:27]:
assert_separately failed with error message
pid 52880 exit 0
| warning: unknown argument for --disable: `gem'


[6671/8090] TestSyntax#test_syntax_lib = 2.92 s
 19) Failure:
TestSyntax#test_syntax_lib [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:25]:
assert_separately failed with error message
pid 52892 exit 0
| warning: unknown argument for --disable: `gem'


[6672/8090] TestSyntax#test_syntax_sample = 2.79 s
 20) Failure:
TestSyntax#test_syntax_sample [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:26]:
assert_separately failed with error message
pid 52905 exit 0
| warning: unknown argument for --disable: `gem'


[6673/8090] TestSyntax#test_syntax_test = 2.80 s  
 21) Failure:
TestSyntax#test_syntax_test [/Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:28]:
assert_separately failed with error message
pid 52917 exit 0
| warning: unknown argument for --disable: `gem'


[6676/8090] TestSyntax#test_undef_symbol = 0.01 s   
 22) Failure:
TestSyntax#test_undef_symbol [/Users/headius/projects/jruby/test/mri/lib/test/unit/assertions.rb:818]:
[ruby-dev:47681] [Bug #8851].

1. [ 4/16] Assertion for "undef a, %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef a, %s(p)>>.

2. [ 8/16] Assertion for "undef :'a', %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef :'a', %s(p)>>.

3. [12/16] Assertion for "undef :\"a\", %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef :"a", %s(p)>>.

4. [13/16] Assertion for "undef %s(a), p"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef %s(a), p>>.

5. [14/16] Assertion for "undef %s(a), :'p'"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef %s(a), :'p'>>.

6. [15/16] Assertion for "undef %s(a), :\"p\""
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef %s(a), :"p">>.

7. [16/16] Assertion for "undef %s(a), %s(p)"
   | /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:802:in `block in test_undef_symbol'.
   | Exception raised:
   | <#<SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_syntax.rb:803: syntax error, unexpected tIDENTIFIER
   | undef %s(a), %s(p)>>..
```

**Comment by headius** [comment]
@enebo These are all fixed, yes?

**Comment by enebo** [comment]
@headius all but the dedent tests

**Comment by enebo** [comment]
I am closing. All new syntax changes have been fix.  We have errors with dedents still but that is excluded in MRI tests so we know what we need to fix from that.

**Comment by headius** [comment]
@enebo I have a couple more to tag I'll associate with this issue, but I won't reopen.
