### ISSUE TITLE
JRuby 9.1.6.0 tries to access O_TMPFILE under Windows

### ISSUE THREAD

**Issue by ips219** [jruby/jruby#4332]
Hi, i've this problem running JRuby 9.1.6.0 on Windows 10 with Java 8 

```
java.lang.NoSuchFieldError: O_TMPFILE
	at org.jruby.RubyFile.createFileClass(RubyFile.java:202)
	at org.jruby.Ruby.initCore(Ruby.java:1570)
	at org.jruby.Ruby.bootstrap(Ruby.java:1352)
	at org.jruby.Ruby.init(Ruby.java:1247)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.internal.EmbedRubyRuntimeAdapterImpl.runParser(EmbedRubyRuntimeAdapterImpl.java:167)
	at org.jruby.embed.internal.EmbedRubyRuntimeAdapterImpl.parse(EmbedRubyRuntimeAdapterImpl.java:94)
	at org.jruby.embed.ScriptingContainer.parse(ScriptingContainer.java:1239)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:89)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:133)
```

I think this is the same problem as related [#3332](https://github.com/jruby/jruby/issues/3332)

These are the flags included for **linux** platform on the jnr.constants.Constant package

```
package jnr.constants.platform.linux;
import jnr.constants.Constant;
public enum OpenFlags implements Constant {
    O_RDONLY, O_WRONLY, O_RDWR, O_ACCMODE, O_NONBLOCK, O_APPEND, O_SYNC, O_ASYNC, O_FSYNC, O_CREAT, O_TRUNC, O_EXCL, O_TMPFILE, O_CLOEXEC
```

And these are the flags included for **windows** platform on the jnr.constants.Constant package

```
package jnr.constants.platform.windows;
import jnr.constants.Constant;
public enum OpenFlags implements Constant {
    O_APPEND, O_ACCMODE, O_CREAT, O_WRONLY, O_EXCL, O_RDONLY, O_BINARY, O_RDWR, O_TRUNC

```

As you can see code is checking for this flags and they are not available under windows platform:
[https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyFile.java#L202](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyFile.java#L202)
[https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyFile.java#L148](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyFile.java#L148)

**Comment by enebo** [comment]
@nirvdrum @eregon you guys recently changed something in jnr-constants right?  Or maybe I should ask does any ideas jump out at you?  The code in RubyFile looks ok.

**Comment by nirvdrum** [comment]
The jnr-constants changes were made after the JRuby 9.1.6.0 release. I don't think they're to blame. But I'll investigate a bit.

**Comment by nirvdrum** [comment]
I can't reproduce. But it would be interesting to try with the `jnr.constants.fake` system property set to `false` (available in jnr-constants 0.9.7-SNAPSHOT).

**Comment by dcransac** [comment]
Hi I'm currently facing this same problem (using Windows 10, JRE 1.8.0_73 and  jruby 9.1.6.0)

```
Exception in thread "main" java.lang.NoSuchFieldError: O_TMPFILE
	at org.jruby.RubyFile.createFileClass(RubyFile.java:202)
	at org.jruby.Ruby.initCore(Ruby.java:1570)
	at org.jruby.Ruby.bootstrap(Ruby.java:1352)
	at org.jruby.Ruby.init(Ruby.java:1247)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.internal.EmbedRubyRuntimeAdapterImpl.runParser(EmbedRubyRuntimeAdapterImpl.java:167)
	at org.jruby.embed.internal.EmbedRubyRuntimeAdapterImpl.parse(EmbedRubyRuntimeAdapterImpl.java:94)
	at org.jruby.embed.ScriptingContainer.parse(ScriptingContainer.java:1239)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:89)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at TestEngine.speedTest(TestEngine.java:39)
	at TestEngine.main(TestEngine.java:14)
```

Is there any way I could help investigating this?

**Comment by ips219** [comment]
Maybe there are some dependency problems on jruby-core package related with the jnr-constants package?

I've tried to force jnr-constants with the required version (0.9.5) and it works:

```
        <dependency>
            <groupId>com.github.jnr</groupId>
            <artifactId>jnr-constants</artifactId>
            <version>0.9.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-core</artifactId>
            <version>9.1.6.0</version>
            <exclusions> 
                <exclusion>
                    <groupId>com.github.jnr</groupId>
                    <artifactId>jnr-constants</artifactId>
                </exclusion>
            </exclusions> 
        </dependency>
```

Note that on jruby-core 9.1.6.0, jnr-constants dependency [is declared on the POM with 0.9.5 version](https://github.com/jruby/jruby/blob/9.1.6.0/core/pom.xml#L149) but when I build my project version 0.9.4 is downloaded as some of the dependencies of jruby-core require that version (jnr-unixsocket & jnr-enxio)

**Comment by headius** [comment]
@ips219 Yes I think that's the only likely explanation. This error should not be possible if JRuby builds properly. However if it then proceeds to capture the wrong version of jnr-constants, this error could result.

I will do a pass over all jnr projects and ensure they are updated to latest versions of everything.
