### ISSUE TITLE
Addrinfo not working on alpine linux

### ISSUE THREAD

**Issue by Paxa** [jruby/jruby#4408]
Error caused by https://github.com/jruby/jruby/blob/a5bf7de68f81015f5149c806f68f944309e9c290/core/src/main/java/org/jruby/ext/socket/Addrinfo.java#L786
```java
private Protocol protocol = Protocol.getProtocolByNumber(0);
```

Because `getprotobyname_r` not exists in musl lib.

Stack trace:
```
Dec 23, 2016 5:56:19 AM jnr.netdb.NativeProtocolsDB load
WARNING: Failed to load native protocols db
java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40)
	at jnr.netdb.NativeProtocolsDB$LinuxLibProto$jnr$ffi$2.getprotobyname_r(Unknown Source)
	at jnr.netdb.NativeProtocolsDB$LinuxNativeProtocolsDB.getProtocolByName(NativeProtocolsDB.java:176)
	at jnr.netdb.NativeProtocolsDB.load(NativeProtocolsDB.java:80)
	at jnr.netdb.NativeProtocolsDB.access$000(NativeProtocolsDB.java:40)
	at jnr.netdb.NativeProtocolsDB$SingletonHolder.<clinit>(NativeProtocolsDB.java:47)
	at jnr.netdb.NativeProtocolsDB.getInstance(NativeProtocolsDB.java:43)
	at jnr.netdb.Protocol$ProtocolDBSingletonHolder.load(Protocol.java:107)
	at jnr.netdb.Protocol$ProtocolDBSingletonHolder.<clinit>(Protocol.java:103)
	at jnr.netdb.Protocol.getProtocolDB(Protocol.java:96)
	at jnr.netdb.Protocol.getProtocolByNumber(Protocol.java:59)
	at org.jruby.ext.socket.Addrinfo.<init>(Addrinfo.java:549)
	at org.jruby.ext.socket.SocketUtils$2.addrinfo(SocketUtils.java:273)
	at org.jruby.ext.socket.SocketUtils.buildAddrinfoList(SocketUtils.java:367)
	at org.jruby.ext.socket.SocketUtils.getaddrinfoList(SocketUtils.java:249)
	at org.jruby.ext.socket.Addrinfo.getaddrinfo(Addrinfo.java:217)
	at org.jruby.ext.socket.Addrinfo$INVOKER$s$0$0$getaddrinfo.call(Addrinfo$INVOKER$s$0$0$getaddrinfo.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:742)
```

**Comment by headius** [comment]
This is a jnr-netdb fix. We'll leave this open until we upgrade to a fixed version.

**Comment by Paxa** [comment]
It was message from library and that library continued to work.
I moved to alpine with glibc and that message is gone

**Comment by headius** [comment]
We'd still like to be able to support musl libc even though it has some rather different functions than glibc. Is this still a problem on musl with current JRuby?

**Comment by anicholson** [comment]
@headius I just encountered the same error on jruby 9.1.12.0 on a musl Alpine.

**Comment by Paxa** [comment]
Working fine with glibc on alpine, I'm using this image https://hub.docker.com/r/anapsix/alpine-java/
