### ISSUE TITLE
Java::JavaLang::ArrayIndexOutOfBoundsException but no array nor concurrency 

### ISSUE THREAD

**Issue by glebm** [jruby/jruby#4412]
### Environment

jruby-9.1.5.0

```console
$ java -Xmx32m -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_111
$ ruby --version
jruby: warning: unknown property jruby.cext.enabled
jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [linux-x86_64]
```

https://travis-ci.org/glebm/i18n-tasks/jobs/186875944

### Expected Behavior

* The test suite passes.

```bash
git clone https://github.com/glebm/i18n-tasks
cd i18n-tasks
git checkout 5bed89a62062c52442f99b590f877e0321627546
bundle
COVERAGE=1 bundle exec rspec
```

### Actual Behavior

```
Failures:
  1) Data commands #add_missing adds the missing keys to base locale first, then to other locales with -v argument
     Failure/Error: Unable to infer file and line number from backtrace
     Java::JavaLang::ArrayIndexOutOfBoundsException:
     # java.lang.System.arraycopy(Native Method)
     # org.jruby.ext.stringio.StringIO.write(StringIO.java:1026)
     # org.jruby.ext.stringio.StringIO$INVOKER$i$1$0$write.call(StringIO$INVOKER$i$1$0$write.gen)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
     # org.jruby.RubyIO.write(RubyIO.java:2565)
     # org.jruby.ext.stringio.StringIO$GenericWritable.puts(StringIO.java:1213)
     # org.jruby.ext.stringio.StringIO$GenericWritable$INVOKER$s$0$0$puts.call(StringIO$GenericWritable$INVOKER$s$0$0$puts.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:720)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:738)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
     # org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
    ...
```
Full backtrace: https://gist.githubusercontent.com/glebm/ce8366d0e013f7f6b399709e112b85cf/raw/63431d1b18f24a189a6778c5497459e0d8579743/jruby%2520backtrace

**Comment by kares** [comment]
narrowed down to the failing commit - so theres `Thread.start` [going on after-all](https://github.com/glebm/i18n-tasks/commit/a04d1e62e6b704f8a6e416ec41e122f2e9e17e27) ... which must have assumed thread-safety for a `String` instance or `StringIO`. failure could be improved to wrap the Java exception into a `ConcurrencyError` like Array does. but otherwise this is a thread-safety issue. 
-> Ruby's structures are not to be assumed safe in multi-threaded scenarios.

**Comment by glebm** [comment]
Hi @kares, thanks for looking into this!

> so theres Thread.start going on after-all 

Yes. The build I linked in the OP is *after* this commit though. When I posted this issue, I thought that `Thread.start` was unrelated, as it was now thread-safe. On a second thought, there could be other shared mutable state, though I can't tell what it is from the stack trace.

> heh I got a 🍏 with JRuby 9.1.5.0 / 9.1.6.0 ... https://travis-ci.org/kares/i18n-tasks/builds/187646200

The failure is reproducible most of the time, and you should see it if you re-run the build a couple of times.

**Comment by glebm** [comment]
It doesn't work with `compile.mode=FORCE`, unfortunately 😞 
Is there a better way to get a stack trace with ruby method names?

```
 NoMethodError:
   private method `available_locales' called for #<I18n::Backend::Simple:0x6cbb79c3>
   # /Users/glebm/.rvm/gems/jruby-9.1.6.0@i18n-tasks/gems/i18n-0.7.0/lib/i18n/config.rb:43:in `available_locales'
    ...
```

**Comment by glebm** [comment]
@kares From the stacktrace above, looks like this is the culprit:

```ruby
$stderr.puts(*args)
```

**Comment by glebm** [comment]
Fixed! Thanks for your help @kares!

**Comment by glebm** [comment]
opened a separate issue about the i18n gem not working in AOT mode: https://github.com/jruby/jruby/issues/4416

**Comment by glebm** [comment]
@kares OK, interesting. However, the error happens in `StringIO`: https://gist.github.com/glebm/7bfd80df13194444e41f33dc358ee3bb

What could this mean?

**Comment by glebm** [comment]
@kares Looks like the bug is that StringIO isn't thread-safe!

```console
$ cat test.rb                                                                                                                                                          
a = StringIO.new
100.times.map do
  Thread.start do
    100.times { a.puts *%w(hello) }
  end
end.each(&:join)
$ jruby test.rb
Exception in thread "Ruby-0-Thread-98: test.rb:1" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.jruby.util.ByteList.grow(ByteList.java:1102)
	at org.jruby.util.ByteList.length(ByteList.java:584)
	at org.jruby.RubyString.resize(RubyString.java:995)
	at org.jruby.ext.stringio.StringIO.strioExtend(StringIO.java:701)
	at org.jruby.ext.stringio.StringIO.write(StringIO.java:1024)
	at org.jruby.ext.stringio.StringIO$INVOKER$i$1$0$write.call(StringIO$INVOKER$i$1$0$write.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
	at org.jruby.RubyIO.write(RubyIO.java:2567)
	at org.jruby.ext.stringio.StringIO$GenericWritable.puts(StringIO.java:1213)
	at org.jruby.ext.stringio.StringIO$GenericWritable$INVOKER$s$0$0$puts.call(StringIO$GenericWritable$INVOKER$s$0$0$puts.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:67)
	at test.invokeOther1:puts(test.rb:4)
	at test.RUBY$block$\=test\,rb$2(test.rb:4)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:76)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:136)
	at org.jruby.RubyFixnum.times(RubyFixnum.java:299)
	at org.jruby.RubyFixnum$INVOKER$i$0$0$times.call(RubyFixnum$INVOKER$i$0$0$times.gen)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:139)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:145)
	at test.invokeOther4:times(test.rb:4)
	at test.RUBY$block$\=test\,rb$1(test.rb:4)
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:67)
	at org.jruby.runtime.Block.call(Block.java:126)
	at org.jruby.RubyProc.call(RubyProc.java:324)
	at org.jruby.RubyProc.call(RubyProc.java:249)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
	at java.lang.Thread.run(Thread.java:745)
```

Should I open a separate issue about this?

**Comment by glebm** [comment]
Opened a separate issue about StringIO not being thread-safe: https://github.com/jruby/jruby/issues/4417
