### ISSUE TITLE
War file error

### ISSUE THREAD

**Issue by abner01061998** [jruby/jruby#4768]
#Ok, look i have been trying to generate war file for an existing rails Project with jruby
What does I do ? 

Install jruby 
Install Rails in Jruby 
Copy my project to jruby/samples
Run  jruby – S bundle install
Run  jruby – S bundle –deployment
And finally 
Jruby -S warble

the file is deployed succesfully but when i run into mi url i get this

org.jruby.rack.RackInitializationException: java.lang.NullPointerException
	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:31)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5043)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:592)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5612)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:540)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:917)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:900)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2044)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1690)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:536)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:535)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:558)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)

**Comment by kares** [comment]
no need to double post issues across repositories  at https://github.com/jruby/warbler/issues/419
