### ISSUE TITLE
Getting error while giving fully qualified path to parse file with yard-cucumber

### ISSUE THREAD

**Issue by saxenadeepakkumar** [jruby/jruby#4836]
Hi Team,

I am using yard to parse files and generate document. I install gem in jar to work on this. When I am giving relative path of files/folder to yard then it is working fine but when I am giving fully qualified path to yard then it is giving following error and not parsing files. But when I am using standalone ruby instead of Jruby then I am able to parse file and generate document:
**[warn]: Cannot parse `/etrade/home/dkumar5/documentation/Cuke_Experiment-master/Cuke_Experiment-master/features/Facebook_home_page.feature': invalid empty object name
[warn]: ArgumentError: invalid empty object name
[warn]: Stack trace:
        uri:classloader:/gems/yard-0.9.9/lib/yard/code_objects/base.rb:190:in `new'
        uri:classloader:/gems/yard-cucumber-3.1.0/lib/cucumber/city_builder.rb:53:in `block in find_or_create_namespace'
        org/jruby/RubyArray.java:1734:in `each'
        uri:classloader:/gems/yard-cucumber-3.1.0/lib/cucumber/city_builder.rb:51:in `find_or_create_namespace'
        uri:classloader:/gems/yard-cucumber-3.1.0/lib/cucumber/city_builder.rb:20:in `initialize'
        uri:classloader:/gems/yard-cucumber-3.1.0/lib/yard/parser/cucumber/feature.rb:18:in `initialize'**

I am using: **jruby-complete-9.1.13.0.jar**.

Please help and provide solution.
Thanks in advance

**Comment by headius** [comment]
Can you provide an example script or repository that reproduces the issue? There's not a lot to go on here. The errors appear to be from yard and don't mean much to us.
