### ISSUE TITLE
Could not load Logmanager "org.apache.juli.ClassLoaderLogManager"

### ISSUE THREAD

**Issue by anilg** [jruby/jruby#500]
Getting following error : 

```
Could not load Logmanager "org.apache.juli.ClassLoaderLogManager"
java.lang.ClassNotFoundException: org.apache.juli.ClassLoaderLogManager
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.util.logging.LogManager$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.util.logging.LogManager.<clinit>(Unknown Source)
    at java.util.logging.Logger.getLogger(Unknown Source)
    at org.jruby.util.log.JavaUtilLoggingLogger.<init>(JavaUtilLoggingLogger.java:43)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.jruby.util.log.LoggerFactory.<clinit>(LoggerFactory.java:48)
    at org.jruby.Main.<clinit>(Main.java:76)
```

I am using jruby-1.7.1, Rails 3.2.8 and tomcat-6

**Comment by NateUniAccount** [comment]
FWIW I had this error and it was due to the CARBON_HOME env var not being set, adding a line in my start script eg.
`export CARBON_HOME='/path/to/wso2'`
made it work
