### ISSUE TITLE
"str".freeze optimization sporadically produces a different object

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5070]
There's a newly-modified spec that tests `"abc".freeze.equal?("abc".freeze)` and it appears to be intermittently failing. It appears to fail consistently on Travis.

[The spec] looks like this:

```ruby
  it "produces the same object whenever called on an instance of a literal in the source" do
    "abc".freeze.should equal "abc".freeze
  end
```

And fails like this:

```
     [exec] 1)
     [exec] String#freeze produces the same object whenever called on an instance of a literal in the source FAILED
     [exec] Expected "abc"
     [exec]  to be identical to "abc"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/freeze_spec.rb:6:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2595:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1704:in `all?'
     [exec] org/jruby/RubyArray.java:1777:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/freeze_spec.rb:3:in `<main>'
     [exec] org/jruby/RubyKernel.java:987:in `load'
     [exec] org/jruby/RubyBasicObject.java:2595:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1777:in `each'
```

See #4970 for a related issue we believed we fixed in 9.1.16.

**Comment by headius** [comment]
I think this was due to the entire rubyspec suite running with `--debug` which turns on `--debug=frozen-string-literal`, causing all frozen strings to be new instances for debugging. I'll remove the tag and ensure it's passing on travis.

**Comment by headius** [comment]
FYI `--debug` is now relegated to the `slow` rubyspec run, which does not include the `String#freeze` specs.
