### ISSUE TITLE
TypeError: bind argument must be an instance of ...

### ISSUE THREAD

**Issue by amarkowitz** [jruby/jruby#5131]
### Environment
```
$> ruby -v
jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [darwin-x86_64]
```
```
$> uname -a
Darwin <computer_name> 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
```
failure test case:
```ruby
# Gemfile
source 'https://rubygems.org'    

    gem 'mocha',            '1.4.0'
    gem 'minitest',         '5.11.3'
    gem 'minitest-stub_any_instance', '1.0.2'
```

```ruby
# test_foo.rb
require "minitest/autorun"
require 'minitest/stub_any_instance'
require 'mocha/minitest'

class Stubber; def foo; 'bar'; end; end

class FooTest < MiniTest::Spec
  i_suck_and_my_tests_are_order_dependent!

  it 'sets us up for failure' do
    Stubber.any_instance.stubs(:foo)
  end

  def bad_stuff
    original_define = Stubber.instance_method(:foo)

    Stubber.stub_any_instance(:foo, proc { |*args| original_define.bind(self).call(*args) }) { Stubber.new.foo }
  end

  it "does not fail with an error" do
    bad_stuff
  end

  it "fails with an error" do
    bad_stuff
  end
end
```

```
# run with the following command
$> gem install bundler && bundle install && ruby test_foo.rb
```

### Expected Behavior

No errors.

### Actual Behavior

```
TypeError: bind argument must be an instance of Stubber
    org/jruby/RubyUnboundMethod.java:105:in `bind'
    test_foo.rb:17:in `block in bad_stuff'
    org/jruby/RubyBasicObject.java:1728:in `instance_exec'
```

### Behavior from various versions of jruby and MRI ruby

```
# jruby-9.1.16.0
$> ruby test_foo.rb
Run options: --seed 51722

# Running:

..E

Finished in 0.021569s, 139.0873 runs/s, 0.0000 assertions/s.

  1) Error:
FooTest#test_0003_fails with an error:
TypeError: bind argument must be an instance of Stubber
    org/jruby/RubyUnboundMethod.java:105:in `bind'
    test_foo.rb:17:in `block in bad_stuff'
    org/jruby/RubyBasicObject.java:1728:in `instance_exec'

3 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

```
# jruby-9.1.13.0
$> ruby test_foo.rb
Run options: --seed 38186

# Running:

..E

Finished in 0.060058s, 49.9516 runs/s, 0.0000 assertions/s.

  1) Error:
FooTest#test_0003_fails with an error:
TypeError: bind argument must be an instance of Stubber
    org/jruby/RubyUnboundMethod.java:105:in `bind'
    test_foo.rb:17:in `block in bad_stuff'
    org/jruby/RubyBasicObject.java:1728:in `instance_exec'

3 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

```
# MRI Ruby 2.4.4
$> ruby test_foo.rb
Run options: --seed 46128

# Running:

...

Finished in 0.001754s, 1710.3763 runs/s, 0.0000 assertions/s.

3 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

```
# MRI Ruby 2.3.3
$> ruby test_foo.rb
Run options: --seed 31182

# Running:

...

Finished in 0.001718s, 1746.2165 runs/s, 0.0000 assertions/s.

3 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

possibly related to #2519

**Comment by headius** [comment]
Thanks for the test case! Looking into it for a few minutes this evening...

**Comment by headius** [comment]
Oddly enough, the following change appears to fix the problem. It seems to match similar logic in MRI that accesses `owner`, as well as logic in our own RubyModule that does the same.

I'll push the change and hopefully you can confirm it's working for you tonight.

If we can narrow this down to a piece of code that does not depend on minitest, it would be great to add a spec to https://github.com/ruby/spec!

**Comment by amarkowitz** [comment]
Heya, @headius!  I spent a little time this evening and I *think* I was able to boil down the test case a bit.  The initial test case for some reason doesn't fail until the second time the `instance_method` is attempted to be bound, however here's what I'm hoping is a simpler test case:

```ruby
PrependedModule = Class.new(Module)

class Stubber; def foo; 'bar'; end; end

definition_target = PrependedModule.new
Stubber.__send__(:prepend, definition_target)

definition_target.class_eval(<<-CODE, __FILE__, __LINE__ + 1)
      def foo(*args, &block)
        # no-op
      end
CODE

definition_target.send(:remove_method, :foo)

original_define = Stubber.instance_method(:foo)
new_name = "__new__foo"

Stubber.class_eval do
  alias_method new_name, :foo

  define_method(:foo) do
    original_define.bind(Stubber.new).call
  end
end

Stubber.new.foo

Stubber.class_eval do
  undef_method :foo
  alias_method :foo, new_name
  undef_method new_name
end
```

The code is a bit contrived, but I'm pretty sure this is what mocha and minitest are doing behind the scenes (I'm running jruby 9.1.13.0).
