### ISSUE TITLE
jruby 9.2.0.0 on s390x

### ISSUE THREAD

**Issue by p-mongo** [jruby/jruby#5248]
I am trying to install jruby 9.2.0.0 on IBM s390x. `uname -a` is as follows:

<pre>
Linux rhel72-z-dev.stuff 3.10.0-693.17.1.el7.s390x #1 SMP Sun Jan 14 10:38:29 EST 2018 s390x s390x s390x GNU/Linux
</pre>

The first hurdle I ran into was that `uname -m` returns `s390x` and jruby then attempts to load `./lib/jni/s390x-Linux/libjffi-1.2.so` which does not exist. Instead, as far as I can tell, the correct binary for this machine is `./lib/jni/ppc64le-Linux/libjffi-1.2.so`. I modified the tarball by hand basically copying ppc64le-Linux to s390x-Linux but I am wondering if there is a way to tell jruby to reference ppc64le-Linux without tarball modifications.

Then, I unpacked the tarball and ran `irb` which produced the following:

<pre>
$ irb
OpenJDK 64-Bit Zero VM warning: You have loaded library /home/u/jruby-9.2.0.0/lib/jni/s390x-Linux/libjffi-1.2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
NotImplementedError: fstat unimplemented unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
  initialize at org/jruby/RubyIO.java:1036
        open at org/jruby/RubyIO.java:1177
  initialize at /home/u/jruby-9.2.0.0/lib/ruby/stdlib/irb/input-method.rb:141
  initialize at /home/u/jruby-9.2.0.0/lib/ruby/stdlib/irb/context.rb:70
  initialize at /home/u/jruby-9.2.0.0/lib/ruby/stdlib/irb.rb:410
       start at /home/u/jruby-9.2.0.0/lib/ruby/stdlib/irb.rb:381
      <main> at /home/u/jruby-9.2.0.0/bin/irb:13
</pre>

The message says libjffi was loaded, therefore I am not clear whether the troubleshooting instructions in https://github.com/jruby/jruby/wiki/Native-Libraries apply.

Regardless, they recommend the following:

> The first line of attack is to pass -Xnative.verbose=true to JRuby itself so it will log errors that occur during startup of our FFI subsystem.

They don't say *how* to pass that option to jruby, thus I tried `irb -Xnative.verbose=true` and that didn't work either:

<pre>
$ irb -Xnative.verbose=true
OpenJDK 64-Bit Zero VM warning: You have loaded library /home/u/jruby-9.2.0.0/lib/jni/s390x-Linux/libjffi-1.2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
IRB::UnrecognizedSwitch: Unrecognized switch: -Xnative.verbose=true
</pre>

At this point I don't know how to troubleshoot further.

**Comment by headius** [comment]
Ahh ok this isn't too bad. I think the simplest way would be like we do for Solaris/SunOS or Darwin/MacOS and have a translation table that knows "s390x" is a "ppc64le" environment.

You can pass that option to JRuby via JRUBY_OPTS env, or if running a command you can do something like `jruby -Xnative.verbose -S irb`.

**Comment by headius** [comment]
This is probably a jffi or jnr-ffi bug.

**Comment by p-mongo** [comment]
I think this was my mistake as I was on a big endian system.

On the big endian system I received this message with the native.verbose set:

<pre>
java.lang.UnsatisfiedLinkError: /home/u/jruby-9.2.0.0/lib/jni/s390x-Linux/libjffi-1.2.so: /home/u/jruby-9.2.0.0/lib/jni/s390x-Linux/libjffi-1.2.so: ELF file data encoding not big-endian (Possible cause: endianness mismatch)
</pre>

... which is indeed quite helpful.

However switching to ppc64-Linux produced:

<pre>
java.lang.UnsatisfiedLinkError: /home/u/jruby-9.2.0.0/lib/jni/s390x-Linux/libjffi-1.2.so: /home/u/jruby-9.2.0.0/lib/jni/s390x-Linux/libjffi-1.2.so: cannot open shared object file: No such file or directory (Possible cause: can't load Power PC 64-bit .so on a IBM System/390-bit platform)
</pre>

As I don't know anything about either PPC64 or s390 I have no idea if this is meant to work at all.

On the little endian system `uname -m` returns `ppc64le` which is great, I am investigating that one further.

**Comment by headius** [comment]
Hmm...well we don't use the system OpenSSL...we have a look-alike library build atop Bouncy Castle. But this does indeed look like some crypto/network issue.

We're happy to help you keep investigating but for obvious reasons it's difficult for us to fix these things alone :-(

**Comment by p-mongo** [comment]
Okay, my boss doesn't want me to spend too much time on s390x thus if you want me to run some commands or follow instructions like the jffi stuff above I can do that but figuring out where in the ruby/jruby/java/os stack this protocol error is coming from is not something I'll be able to do on my own.

**Comment by p-mongo** [comment]
I downloaded the tarball referenced by rbenv, untarred it and was able to get an irb shell with 9.1.17.0.

**Comment by p-mongo** [comment]
And now I have this:

<pre>
$ irb
irb(main):001:0> require 'open-uri'
=> true
irb(main):002:0> open('https://rubygems.org').read.length
OpenSSL::SSL::SSLError: Received fatal alert: protocol_version
	from org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/net/http.rb:938:in `connect'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/net/http.rb:868:in `do_start'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/net/http.rb:857:in `start'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:319:in `open_http'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:737:in `buffer_open'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:212:in `block in open_loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:210:in `open_loop'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:151:in `open_uri'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:717:in `open'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:35:in `open'
	from (irb):2:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1316:in `loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /home/oleg.pudeyev/jruby-9.1.17.0/bin/irb:13:in `<main>'
irb(main):003:0> open('https://python.org').read.length
OpenSSL::SSL::SSLError: Received fatal alert: protocol_version
	from org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/net/http.rb:938:in `connect'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/net/http.rb:868:in `do_start'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/net/http.rb:857:in `start'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:319:in `open_http'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:737:in `buffer_open'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:212:in `block in open_loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:210:in `open_loop'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:151:in `open_uri'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:717:in `open'
	from /home/oleg.pudeyev/jruby-9.1.17.0/lib/ruby/stdlib/open-uri.rb:35:in `open'
	from (irb):3:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1316:in `loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /home/oleg.pudeyev/jruby-9.1.17.0/bin/irb:13:in `<main>'
irb(main):004:0> open('https://google.com').read.length
=> 10798
</pre>

**Comment by p-mongo** [comment]
Installed ibm-java-jre-8.0-5.17-ppc64-archive.bin from https://developer.ibm.com/javasdk/downloads/sdk8/, it seems to work:

<pre>
$ java -showversion 2>&1 |head -10
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.17 - pxl6480sr5fp17-20180627_01(SR5 FP17))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20180626_390413 (JIT enabled, AOT enabled)
OpenJ9   - 5cdc604
OMR      - a24bc01
IBM      - 21870d6)
JCL - 20180619_01 based on Oracle jdk8u171-b11

Usage: java [-options] class [args...]
           (to execute a class)
$ jruby -v                        
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 IBM J9 VM 2.9 on 8.0.5.17 - pxl6480sr5fp17-20180627_01(SR5 FP17) +jit [linux-ppc64le]
$ jruby -S irb 
irb(main):001:0> require 'open-uri'
=> true
irb(main):002:0> open('https://rubygems.org').read.length
=> 11427
</pre>

**Comment by p-mongo** [comment]
For the big endian machine I have no clue what to do though.

**Comment by p-mongo** [comment]
My current impression is that for s390x (big endian native) I will need to build jffi.
