### ISSUE TITLE
(NameError) uninitialized constant JRuby::Util::SEPARATOR

### ISSUE THREAD

**Issue by dyrby76** [jruby/jruby#5327]
### Environment
JRuby Version: jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [linux-x86_64]

JRUBY_OPTS not set.

* Operating system and platform (e.g. `uname -a`)

Linux mjensen-vpc2 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Java version

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

* Gem File:

```ruby
source 'https://rubygems.org'
gem 'logstash-codec-plain', '3.0.2'
```

* Command:

```
jruby -S bundle install --path ./gems --no-cache
```

### Expected Behavior
Installation should complete without errors.

### Actual Behavior

```
Installing gems...
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies................
Using bundler 1.16.0
Fetching numerizer 0.1.1
Installing numerizer 0.1.1
...
Fetching treetop 1.4.15
Installing treetop 1.4.15
Fetching logstash-core 5.6.4 (java)
Installing logstash-core 5.6.4 (java)
  jar dependencies for logstash-core-5.6.4-java.gemspec . . .
/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/monitor.rb:256: warning: toplevel constant Mutex referenced by Thread::Mutex
NameError: uninitialized constant JRuby::Util::SEPARATOR
   const_missing at org/jruby/RubyModule.java:3309
  path_separator at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:61
  split_gem_path at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/path_support.rb:50
      initialize at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/path_support.rb:32
           paths at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems.rb:393
            path at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems.rb:439
            dirs at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:70
       stubs_for at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/specification.rb:869
  matching_specs at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:279
        to_specs at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:302
         to_spec at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:322
             gem at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:65
         require at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:47
           <top> at uri:classloader:/maven/tools/dsl.rb:1
         require at org/jruby/RubyKernel.java:944
          (root) at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
           <top> at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
[ERROR] Internal error: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant JRuby::Util::SEPARATOR -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant JRuby::Util::SEPARATOR
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant JRuby::Util::SEPARATOR
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1352)
	at org.sonatype.maven.polyglot.ruby.RubyParser.<init>(RubyParser.java:42)
	at org.sonatype.maven.polyglot.ruby.RubyModelReader.read(RubyModelReader.java:56)
	at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:143)
	at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:95)
...
Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util::SEPARATOR
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3309)
	at RUBY.path_separator(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:61)
	at RUBY.split_gem_path(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/path_support.rb:50)
	at RUBY.initialize(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/path_support.rb:32)
	at RUBY.paths(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems.rb:393)
	at RUBY.path(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems.rb:439)
	at RUBY.dirs(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:70)
	at RUBY.stubs_for(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/specification.rb:869)
	at RUBY.matching_specs(/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:279)
...
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by headius** [comment]
I suspect that LogStash is pulling in an older JRuby version but still using stdlib from the current version you're running on. This constant does not exist prior to JRuby 9.2.

**Comment by dyrby76** [comment]
I tested with other versions. It fails with 9.2.0.0 and 9.1.10.0 but it works with 9.1.6.0.

**Comment by kares** [comment]
tried to reproduce without luck, but I think it might be jar_dependencies' maven dsl that loads the 9.2 .rb files
somehow ... not sure why it could happen but that could explain the issue. also : 
```
Installing logstash-core 5.6.4 (java)
  jar dependencies for logstash-core-5.6.4-java.gemspec . . .
/usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/monitor.rb:256: warning: toplevel constant Mutex referenced by Thread::Mutex
NameError: uninitialized constant JRuby::Util::SEPARATOR
   const_missing at org/jruby/RubyModule.java:3309
  path_separator at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:61
  split_gem_path at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/path_support.rb:50
      initialize at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/path_support.rb:32
           paths at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems.rb:393
            path at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems.rb:439
            dirs at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:70
       stubs_for at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/specification.rb:869
  matching_specs at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:279
        to_specs at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:302
         to_spec at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:322
             gem at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:65
         require at /usr/local/lib/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:47
           <top> at uri:classloader:/maven/tools/dsl.rb:1
```
... this `bundle install` part clearly indicates an issue in that direction.
maybe something to improve in **ruby-maven** ... @mkristian any guesses why it might happen?

@dyrby76 are you using any ruby manager, any chance you could share your `env` after you reproduced?

**Comment by mkristian** [comment]
maybe there is JRUBY_HOME set - someone else had this recently. ruby-maven/jar-dependencies does not clear ENV before forking. i.e. it can be improved there.
