### ISSUE TITLE
9.2.[01].0 fails to install csl-styles GEM on Windows (Errno::ESRCH)

### ISSUE THREAD

**Issue by ysb33r** [jruby/jruby#5427]
### Background

This issue has been discovered whilst working on v2.x of  the https://github.com/asciidoctor/asciidoctor-gradle-plugin. 

The issue occurs only on Windows and it is part of a group of GEMs that are installed during a test. However the problem has been isolated to the `csl-styles` GEM and can be reproduced from the command-line.

This is very similar to behaviour described in #2498. Although that issue mentioned 9.2.0.0 it is tagged for 1.7.  and dates back to 2015. I thought it would be better to create a new issue with an easy to reproduce case.

### Environment

Reproduced with JDK8. I don't know yet about JDK10, 11.

*JRuby version*:

```
java.exe -Dfile.encoding=utf-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp C:\path\to\jruby-complete-9.2.0.0.jar org.jruby.Main -v
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.172-b11 on 1.8.0_172-b11 +jit [mswin32-x86_64]
```

### Expected Behavior

I would expect the `csl-styles` gem to be installed with JRuby 9.2.0.0 & 9.2.1.0 on all supported operating systems.
 
### Actual Behavior

This is Windows-only behaviour. I have reproduced this on Windows 10 and builds running on Appveyor

Get a copy of the csl-styles GEM (I was using 1.0.1.9). Now run.
```
$ java.exe -Dfile.encoding=utf-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp C:\path\to\jruby-complete-9.2.0.0.jar org.jruby.Main -S gem install  C:\path\to\csl-styles-1.0.1.9.gem --ignore-dependencies --install-dir=C:\output\to\asciidoctorGems --no-user-install --wrappers --no-document --local --debug
```

and assuming that `C:\output\to\asciidoctorGems` exists the failure output is 
```
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `Errno::ENOENT' at org/jruby/RubyFile.java:1268 - No such file or directory - C:/output/to/asciidoctorGems/specifications/csl-styles-1.0.1.9.gemspec
<... Lots of similar errors ...>
Exception `Errno::ENOENT' at org/jruby/RubyFile.java:1268 - No such file or directory - Exception `Errno::ESRCH' at org/jruby/RubyFile.java:646 - No such process - No message available
Exception `Errno::ESRCH' at org/jruby/RubyFile.java:646 - No such process - No message available
ERROR:  While executing gem ... (Errno::ESRCH)
    No such process - No message available
        org/jruby/RubyFile.java:646:in `chmod'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1322:in `chmod'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1000:in `block in chmod'
        org/jruby/RubyArray.java:1801:in `each'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:999:in `chmod'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:385:in `block in extract_tar_gz'
        org/jruby/RubyIO.java:1179:in `open'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:383:in `block in extract_tar_gz'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65:in `each'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:365:in `block in extract_tar_gz'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:474:in `block in open_tar_gz'
        org/jruby/ext/zlib/RubyGzipFile.java:97:in `wrap'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:471:in `open_tar_gz'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:364:in `extract_tar_gz'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:345:in `block in extract_files'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65:in `each'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:342:in `block in extract_files'
        org/jruby/RubyIO.java:1179:in `open'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package/file_source.rb:30:in `with_read_io'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/package.rb:339:in `extract_files'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/installer.rb:794:in `extract_files'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/installer.rb:304:in `install'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:235:in `install_gem_without_dependencies'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:191:in `install_gem'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:255:in `block in install_gems'
        org/jruby/RubyArray.java:1801:in `each'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:251:in `install_gems'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:158:in `execute'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/command.rb:313:in `invoke_with_build_args'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/command_manager.rb:171:in `process_args'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/command_manager.rb:141:in `run'
        uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/gem_runner.rb:59:in `run'
        uri:classloader:/META-INF/jruby.home/bin/jgem:21:in `<main>'
        org/jruby/RubyKernel.java:994:in `load'
        uri:classloader:/META-INF/jruby.home/bin/gem:4:in `<main>'
Exception `Gem::SystemExitException' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/user_interaction.rb:394 - Exiting RubyGems with exit_code 1
```

**Comment by enebo** [comment]
@ysb33r I am trying this with 1.8.0_181 on win10 and I am not seeing the ESRCH happen.  I am running with all sources on the same drive (C:).  Trying to think what difference must exist to get ESRCH.

Actually reading #2498 refers to an MS bug.  Is your install dir location a pretty long path?  Can you try a shorter path (I use C:\opt\jruby\hoh).  If that works then we will know what we are up against I can try a longer path but without knowing how long I will just make something unusually long (although https://github.com/jruby/jruby/issues/2498#issuecomment-138669636 implies this long path issue may have been fixed on some windows releases).

**Comment by enebo** [comment]
Hmm I used a pretty long path but I am on win10 and should be fairly up to date on updates.  Not sure if windows version is in play here or not:

```text
 java -Dfile.encoding=utf-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp maven\jruby-complete\target\jruby-complete-9.2.1.0.jar org.jruby.Main -S gem install  C:\Users\enebo\Downloads\csl-styles-1.0.1.9.gem --ignore-dependencies --install-dir=C:\opt\jruby\heh\fourscore\andseven\yearsago\thispath\shouldbe\getting\pretty\long\perhaps\Ihopethisisenough --no-user-install --wrappers --no-document --local --debug
```

**Comment by ysb33r** [comment]
Maybe long path is the issue.

This is an example Appveyor build where the issue has been detected - https://ci.appveyor.com/project/ysb33r/asciidoctor-gradle-plugin-6gtcd/builds/20070590/tests

The last line in the test output is key to this:
```
Starting process 'command 'C:\Program Files\Java\jdk1.8.0\bin\java.exe''. Working directory: C:\projects\asciidoctor-gradle-plugin-6gtcd\asciidoctor-gradle-jvm-gems\build\gradleTest\external-gems\4.10.2 Command: C:\Program Files\Java\jdk1.8.0\bin\java.exe -Dfile.encoding=utf-8 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\projects\asciidoctor-gradle-plugin-6gtcd\testfixtures\offline-repo\build\repo\org.jruby\jruby-complete\9.2.0.0\jruby-complete-9.2.0.0.jar org.jruby.Main -S gem install C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\asciidoctor-bibtex\0.3.1\d1941976710c424cb56e2becb7968d46c4e0e683\asciidoctor-bibtex-0.3.1.gem C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\bibtex-ruby\4.4.7\f9eabfd4041feee0667cddb983e3f53e47e2cba0\bibtex-ruby-4.4.7.gem C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\citeproc-ruby\1.1.10\b506cd8802060a989c850696b23400cd400657b3\citeproc-ruby-1.1.10.gem C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\csl-styles\1.0.1.9\4dd8342ae6e920adc8d4c68ad74dee3e554b48a1\csl-styles-1.0.1.9.gem C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\latex-decode\0.3.1\769a8951984edb6363b4fd9391e5933774119ce0\latex-decode-0.3.1.gem C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\citeproc\1.0.9\68a56d854c1cf68cc7d3f3c59c5b83cb59786548\citeproc-1.0.9.gem C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\csl\1.5.0\5fbdd9e4eeeeff8abaa51b76baa57caee2fe49a7\csl-1.5.0.gem C:\Users\appveyor\AppData\Local\Temp\1
```

Here you would have the path to the `csl-styles` GEM to be `C:\Users\appveyor\AppData\Local\Temp\1\.gradle-test-kit-appveyor\caches\modules-2\files-2.1\rubygems\csl-styles\1.0.1.9\4dd8342ae6e920adc8d4c68ad74dee3e554b48a1\csl-styles-1.0.1.9.gem`. Would you consider that a long path in this context?

**Comment by ysb33r** [comment]
> Hmm I used a pretty long path but I am on win10 and should be fairly up to date on updates. Not sure if windows version is in play here or not:

Our Appveyor build uses the `Visual Studio 2017` image, which should be pretty much up to date. The local Windows machine I tested on is up to date with all the latest patches AFAIK.

**Comment by enebo** [comment]
@ysb33r if on your local machine you can set something shorter just to see.  I have only seen this error raised for 2 reasons to date: 1) long path which supposedly is fixed on windows 2) UNC path access.  I will continue to try and look online and try to brainstorm.

**Comment by ysb33r** [comment]
@enebo I have now diagnosed it down to the install-dir being to long.

**Comment by enebo** [comment]
@ysb33r Knowing this I will try and figure out if there are some versions of windows which never had this long path work done.  Or whether there is some setting which can exist which mitigates this issue.

**Comment by enebo** [comment]
@ysb33r this article maybe will help: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

Not sure though if you can apply any of this to an appveyor build though?

**Comment by headius** [comment]
9.2 has been EOL for some time (as has 9.3 and 9.4 was EOL as of June).

If this remains a problem with JRuby 10.0+ please open a new issue.
