### ISSUE TITLE
StackOverFlowError when requiring active_support and bundler

### ISSUE THREAD

**Issue by ckpeter** [jruby/jruby#5454]
### Environment
jruby 9.2.4.0 (2.5.0) 2018-11-13 8faff06 Java HotSpot(TM) Client VM 25.92-b14 on 1.8.0_92-b14 +jit [mswin32-i386]
Windows 10

### Expected Behavior

Put a gem file in a directory Gemfile:

```
source "https://rubygems.org"
gem "activesupport", "4.2.7"
```

Run this script stackoverflow.rb:

```
require "rubygems"
require 'active_support/all'
require "bundler/setup"
```

The script should terminate normally. Indeed, this script runs fine in JRuby 9.1.17.

### Actual Behavior

With JRuby 9.2.4.0:
```
C:\foo\bar>jruby -J-Xss8192 stackoverflow.rb
C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
LoadError: load error: bundler/feature_flag -- java.lang.StackOverflowError: null
                 feature_flag at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:478
                         path at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler/settings.rb:233
       configured_bundle_path at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:84
             use_system_gems? at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:351
           configure_gem_path at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:541
  configure_gem_home_and_path at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:534
                    configure at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:66
                   definition at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:134
                        setup at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler.rb:101
                       <main> at C:/bin/jruby/lib/ruby/gems/shared/gems/bundler-1.17.1/lib/bundler/setup.rb:10
                      require at org/jruby/RubyKernel.java:976
                      require at C:/bin/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:135
                       <main> at stackoverflow.rb:4
```

In another run (which I can't find the switch right now to reproduce), I am seeing the stack blown up:
```

C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.invokeOther7:to_default_s(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.RUBY$block$Numeric$0(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
        at org.jruby.runtime.MixedModeIRBlockBody.callDirect(MixedModeIRBlockBody.java:116)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:286)
        at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:80)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.invokeOther7:to_default_s(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.RUBY$block$Numeric$0(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
        at org.jruby.runtime.MixedModeIRBlockBody.callDirect(MixedModeIRBlockBody.java:116)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:286)
        at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:80)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.invokeOther7:to_default_s(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.RUBY$block$Numeric$0(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
        at org.jruby.runtime.MixedModeIRBlockBody.callDirect(MixedModeIRBlockBody.java:116)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:286)
        at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:80)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.invokeOther7:to_default_s(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.RUBY$block$Numeric$0(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
        at org.jruby.runtime.MixedModeIRBlockBody.callDirect(MixedModeIRBlockBody.java:116)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:286)
        at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:80)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.invokeOther7:to_default_s(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.RUBY$block$Numeric$0(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
        at org.jruby.runtime.MixedModeIRBlockBody.callDirect(MixedModeIRBlockBody.java:116)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:286)
        at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:80)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.invokeOther7:to_default_s(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
        at C_3a_.bin.jruby.lib.ruby.gems.shared.gems.activesupport_minus_4_dot_2_dot_7.lib.active_support.core_ext.numeric.conversions.RUBY$block$Numeric$0(C:/bin/jruby/lib/ruby/gems/shared/gems/activesupport-4.2.7/lib/active_support/core_ext/numeric/conversions.rb:131)
```

**Comment by headius** [comment]
Thank you for the blown-up version! That isn't a very long repeat cycle so I suspect this will be something obvious.

**Comment by ckpeter** [comment]
Thank you, Charles.

I didn't have the time to investigate at the time, but this issue was present in the original 9.2.0.0 release too.

**Comment by headius** [comment]
@ckpeter Ah-ha...this might be an incompatibility with Ruby 2.5's merging of Fixnum and Bignum into integer.

The code in question that's blowing up does the following:

activesupport/core_ext/numeric/conversions.rb
```ruby
  [Float, Fixnum, Bignum, BigDecimal].each do |klass|
    klass.send(:alias_method, :to_default_s, :to_s)

    klass.send(:define_method, :to_s) do |*args|
...
```

In Ruby 2.5, Fixnum and Bignum point at Integer, so the following happens:

1. Fixnum (really Integer) aliases `to_default_s` for `to_s`, which is the real `to_s`.
2. Fixnum (really Integer) defines a new `to_s` that does this `define_method` block.
3. Bignum (really Integer) aliases `to_default_s` for `to_s`, which is now the `define_method` version.
4. At this point, both `to_s` and `to_default_s` point at the `define_method` version, so it blows up the stack.

Unfortunately we have to punt this as a third-party issue. I don't believe Rails 4.2.x supports Ruby 2.5. It supports 2.4 as of 4.2.8 (I think?) so if you need to stay on Rails 4.2 I think you'll be limited to JRuby 9.1.x.

**Comment by ckpeter** [comment]
Understood. Thanks very much for the help and sorry for the trouble!

**Comment by ahorek** [comment]
FYI it was fixed by https://github.com/rails/rails/commit/253796732b9c39ad5eddf1c7539bef08881c0a35

rails 4.2.8 should work fine

**Comment by headius** [comment]
@ahorek Ah yes, the Integer unification was a 2.4 feature after all. Thanks!

**Comment by ckpeter** [comment]
@ahorek, that's very helpful for me to know.

Thanks to both of you for your help!
