### ISSUE TITLE
on windows if folder name is utf8 string,  File.directory? get wrong result

### ISSUE THREAD

**Issue by tka** [jruby/jruby#547]
JRuby 1.7.3  On windows 7 

```
require 'fileutils' ;
FileUtils.mkdir 'test';
Dir.chdir('test');
FileUtils.mkdir('✓');
Dir.glob("*") do |x|
  p "#{x} - #{File.exist?(x)}"; 
  p File.directory?(x);
end
```

result with Ruby 1.9.3 mode irb

```
"\xC3\xA2\xC2\x9C\xC2\x93 - false"
false
```

result with Ruby 1.8.7 mode irb

```
"\342\234\223 - true"
SystemCallError: Unknown error - Unknown Error (20047) - C:/jruby-1.7.3/test/?
    from org/jruby/RubyFileTest.java:101:in `directory?'
    from org/jruby/RubyFileTest.java:86:in `directory?'
    from (irb):7:in `evaluate'
    from org/jruby/RubyDir.java:339:in `glob'
    from (irb):5:in `evaluate'
    from org/jruby/RubyKernel.java:1061:in `eval'
    from C:/jruby-1.7.3/lib/ruby/1.8/irb.rb:158:in `eval_input'
    from C:/jruby-1.7.3/lib/ruby/1.8/irb.rb:271:in `signal_status'
    from C:/jruby-1.7.3/lib/ruby/1.8/irb.rb:155:in `eval_input'
    from org/jruby/RubyKernel.java:1409:in `loop'
    from org/jruby/RubyKernel.java:1160:in `catch'
    from C:/jruby-1.7.3/lib/ruby/1.8/irb.rb:154:in `eval_input'
    from C:/jruby-1.7.3/lib/ruby/1.8/irb.rb:71:in `start'
    from org/jruby/RubyKernel.java:1160:in `catch'
    from C:/jruby-1.7.3/lib/ruby/1.8/irb.rb:70:in `start'
    from C:\jruby-1.7.3\/bin/jirb_swing:54:in `(root)'
```

**Comment by enebo** [comment]
This is broken on 9k (using same UTF-8 encoding at top as previous commenter did):

```text
/c/opt/jruby master 508% jruby b.rb
"\xE2\x9C\x93 - false"
false
```

With C Ruby:
```text
/c/opt/jruby master 511% ruby.exe b.rb
"\u2713 - true"
true
```
