### ISSUE TITLE
LoadError: no such file to load -- socket  with jruby.jar

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#5606]
### Environment

$ jruby -v
jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b Java HotSpot(TM) 64-Bit Server VM 25.201-b09 on 1.8.0_201-b09 +jit [mswin32-x86_64]

### Expected Behavior
```java
public class JavaTest {
  public static void main(String[] args)  {
    (new org.jruby.embed.ScriptingContainer()).runScriptlet("require 'socket'");
  }
}
```

javac -cp jruby-9.2.5.0.jar JavaTest.java
java -cp "jruby-9.2.5.0.jar;." JavaTest

No exception occurs.

### Actual Behavior
javac -cp jruby-9.2.6.0.jar JavaTest.java
java -cp "jruby-9.2.6.0.jar;." JavaTest
```
LoadError: no such file to load -- socket
  require at org/jruby/RubyKernel.java:984
   <main> at <script>:1
Exception in thread "main" org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- socket
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1295)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1288)
        at JavaTest.main(JavaTest.java:3)
Caused by: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- socket
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:984)
        at RUBY.<main>(<script>:1)
```

**Comment by headius** [comment]
Socket and several other libraries that were "magic built-ins" prior to 9.2.6 are now normal standard libraries in lib/ruby/stdlib. In order to use those libraries you will want to either run the jruby-complete.jar file (an artifact of our release process) or specify `-Djruby.home=<path to jruby install>` so those files can be found.

I'm willing to discuss whether this is too cumbersome, but essentially we made a special exception for a few standard libraries before and make no exceptions now. It could be argued that all of stdlib should live in jruby.jar, but then we'd be duplicating files on the filesystem.

For now I will close this. Feel free to drop by our Matrix, Gitter, or IRC rooms if you want to discuss it further.
