### ISSUE TITLE
Jruby on Rails application changes initialization sequence when used with jdbc adapter

### ISSUE THREAD

**Issue by joshianand** [jruby/jruby#5644]
### Environment
jruby 9.1.17.0 (2.3.3)
* Operating system: Found issue on Windows as well as centos 

Other relevant info you may wish to add:
gem 'activerecord-jdbcmysql-adapter'
gem 'therubyrhino'
gem 'jruby-openssl'

### Expected Behavior

Initilization sequence should load enviornments/developemet.rb or production.rb before database.yaml is executed

### Actual Behavior

I had been working on my rails application with ruby 2.3.3 and everything was working fine . I had requirement to create war package from my existing rails code, so I switched to jruby and installed required gems . as soon as i start my sever in production mode or development mode Rails stats processing database.yaml and none of initializers files or the group files (production.rb or development.rb files under config/enviornments) are loaded before that (they are loaded after database.yaml is initialised). This does not happen when using ruby and associated mysql gem.

**Comment by joshianand** [comment]
@kares @bernerdschaefer @nicksieger @olleolleolle

**Comment by kares** [comment]
not sure how much jruby-rack affects the initialization order, but it sure does not patch any Rails internals.
if this is really that different from a non-embedded mode (please confirm with a minimal reproducible if possible) than we might try changing the booter: https://github.com/jruby/jruby-rack/blob/master/src/main/ruby/jruby/rack/rails_booter.rb#L25-L40 (believe you could also sub-class and set your own booter class - just poke around the Java initialization part)

**Comment by joshianand** [comment]
@kares, the boot method addresses rails 2 and rails 3 , I am working on rails 5 can that be an issue ? I have no experience of < rails 4

**Comment by kares** [comment]
if you read the code ... non Rails 2 applies to all Rails 3+ ... so do not worry about you having Rails 5

**Comment by joshianand** [comment]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
warble aborted!
NoMethodError: undefined method `config' for Rails:Module
Did you mean?  concerning
/opt/javarailsapp/cloudse-ror/RubyOnRails/config/application.rb:9:in `<main>'
uri:classloader:/jruby/kernel/kernel.rb:1:in `(root)'
uri:classloader:/jruby/kernel/kernel.rb:13:in `<main>'
Rakefile:4:in `block in <main>'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/application.rb:1:in `(root)'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/application.rb:61:in `load_project_rakefile'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/application.rb:58:in `load_project_rakefile'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler.rb:26:in `block in project_application'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/traits/rails.rb:28:in `before_configure'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `before_configure'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `before_configure'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/config.rb:215:in `initialize'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/task.rb:48:in `block in initialize'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/application.rb:27:in `load_rakefile'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/application.rb:79:in `<main>'
/home/centos/.rvm/gems/jruby-9.2.5.0/gems/warbler-2.0.5/lib/warbler/application.rb:74:in `run'
/home/centos/.rvm/gems/jruby-9.2.5.0/bin/jruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

This is the trace when I try to warble for jruby rails application, it is not able to find config  in application.rb which comes from Rails.configuration

**Comment by joshianand** [comment]
This is on centos

**Comment by headius** [comment]
I guess I could see the sequence in the Rails 3+ boot logic might cause things to load in a different order. Isn't there one file we can load to do this whole sequence properly for Rails?
