### ISSUE TITLE
Maven build throws uninitialized constant JRuby::Util Exception.

### ISSUE THREAD

**Issue by whitingjr** [jruby/jruby#5660]
### Environment

```
$ git branch
* (HEAD detached at 9.2.6.0)
  master
$ jruby --version
jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b OpenJDK 64-Bit Server VM 9.0.4+11 on 9.0.4+11 +jit [linux-x86_64]
$ java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
$  uname -a
Linux f28lite 4.20.14-100.fc28.x86_64 #1 SMP Tue Mar 5 19:45:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ jruby -S gem list
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

*** LOCAL GEMS ***

cmath (default: 1.0.0)
csv (default: 1.0.0)
did_you_mean (1.2.0)
fileutils (default: 1.1.0)
ipaddr (default: 1.2.0)
jar-dependencies (default: 0.4.0)
jruby-lint (0.4.1)
jruby-openssl (default: 0.10.1 java)
jruby-readline (default: 1.3.7 java)
json (default: 2.1.0 java)
minitest (5.10.3)
net-telnet (0.1.1)
nokogiri (1.10.1 java)
power_assert (1.1.3)
psych (default: 3.1.0 java)
rake (12.3.0)
rake-ant (default: 1.0.4)
rdoc (default: 6.0.1)
scanf (default: 1.0.0)
term-ansicolor (1.7.1)
test-unit (3.2.8)
tins (1.20.2)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
$
```

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
* Operating system and platform (e.g. `uname -a`)

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

### Expected Behavior

The Maven package goal is completed successfully.

### Actual Behavior

Maven goal fails because the script bundled in the jruby runtime has not been configured correctly before being executed.

```
$ mvn -e -X clean package
Apache Maven 3.5.2 (Red Hat 3.5.2-5)
Maven home: /usr/share/maven
Java version: 9.0.4, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-openjdk-9.0.4.11-6.fc28.x86_64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.20.14-100.fc28.x86_64", arch: "amd64", family: "unix"
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/whitingjr/.m2/settings.xml
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/whitingjr/.m2/repository
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1113975, ConflictMarker.markTime=529957, ConflictMarker.nodeCount=32, ConflictIdSorter.graphTime=610394, ConflictIdSorter.topsortTime=436652, ConflictIdSorter.conflictIdCount=24, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=6611787, ConflictResolver.conflictItemCount=31, DefaultDependencyCollector.collectTime=308932060, DefaultDependencyCollector.transformTime=12861817}
[DEBUG] io.takari.polyglot:polyglot-ruby:jar:0.3.1.1:
[DEBUG]    io.takari.polyglot:polyglot-common:jar:0.3.1:compile
[DEBUG]    org.jruby:jruby:pom:9.1.17.0:compile
[DEBUG]       org.jruby:jruby-core:jar:9.1.17.0:compile
[DEBUG]          com.github.jnr:jnr-netdb:jar:1.1.6:compile
[DEBUG]          com.github.jnr:jnr-enxio:jar:0.16:compile
[DEBUG]          com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[DEBUG]          com.github.jnr:jnr-unixsocket:jar:0.17:compile
[DEBUG]          com.github.jnr:jnr-posix:jar:3.0.44:compile
[DEBUG]          com.github.jnr:jnr-constants:jar:0.9.9:compile
[DEBUG]          com.github.jnr:jffi:jar:1.2.16:compile
[DEBUG]          com.github.jnr:jffi:jar:native:1.2.16:compile
[DEBUG]          org.jruby.joni:joni:jar:2.1.15:compile
[DEBUG]          org.jruby.extras:bytelist:jar:1.0.15:compile
[DEBUG]          org.jruby.jcodings:jcodings:jar:1.0.27:compile
[DEBUG]          org.jruby:dirgra:jar:0.3:compile
[DEBUG]          com.headius:invokebinder:jar:1.10:compile
[DEBUG]          com.headius:options:jar:1.4:compile
[DEBUG]          com.headius:unsafe-fences:jar:1.0:compile
[DEBUG]          com.jcraft:jzlib:jar:1.1.3:compile
[DEBUG]          com.martiansoftware:nailgun-server:jar:0.9.1:compile
[DEBUG]          joda-time:joda-time:jar:2.8.2:compile
[DEBUG]          com.headius:modulator:jar:1.0:compile
[DEBUG]       org.jruby:jruby-stdlib:jar:9.1.17.0:compile
[DEBUG] Populating class realm coreExtension>io.takari.polyglot:polyglot-ruby:0.3.1.1
[DEBUG]   Included /home/whitingjr/.m2/repository/io/takari/polyglot/polyglot-ruby/0.3.1.1/polyglot-ruby-0.3.1.1.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/io/takari/polyglot/polyglot-common/0.3.1/polyglot-common-0.3.1.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/jruby/9.1.17.0/jruby-9.1.17.0.pom
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/jruby-core/9.1.17.0/jruby-core-9.1.17.0.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jnr-netdb/1.1.6/jnr-netdb-1.1.6.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jnr-enxio/0.16/jnr-enxio-0.16.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jnr-unixsocket/0.17/jnr-unixsocket-0.17.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jnr-posix/3.0.44/jnr-posix-3.0.44.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jnr-constants/0.9.9/jnr-constants-0.9.9.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/joni/joni/2.1.15/joni-2.1.15.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/extras/bytelist/1.0.15/bytelist-1.0.15.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/jcodings/jcodings/1.0.27/jcodings-1.0.27.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/dirgra/0.3/dirgra-0.3.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/headius/invokebinder/1.10/invokebinder-1.10.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/headius/options/1.4/options-1.4.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/headius/unsafe-fences/1.0/unsafe-fences-1.0.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/com/headius/modulator/1.0/modulator-1.0.jar
[DEBUG]   Included /home/whitingjr/.m2/repository/org/jruby/jruby-stdlib/9.1.17.0/jruby-stdlib-9.1.17.0.jar
[DEBUG] Populating class realm maven.ext
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.annotation.* < maven.ext
[DEBUG]   Imported: javax.enterprise.inject.* < maven.ext
[DEBUG]   Imported: javax.enterprise.util.* < maven.ext
[DEBUG]   Imported: javax.inject.* < maven.ext
[DEBUG]   Imported: org.apache.maven.* < maven.ext
[DEBUG]   Imported: org.apache.maven.artifact < maven.ext
[DEBUG]   Imported: org.apache.maven.classrealm < maven.ext
[DEBUG]   Imported: org.apache.maven.cli < maven.ext
[DEBUG]   Imported: org.apache.maven.configuration < maven.ext
[DEBUG]   Imported: org.apache.maven.exception < maven.ext
[DEBUG]   Imported: org.apache.maven.execution < maven.ext
[DEBUG]   Imported: org.apache.maven.execution.scope < maven.ext
[DEBUG]   Imported: org.apache.maven.lifecycle < maven.ext
[DEBUG]   Imported: org.apache.maven.model < maven.ext
[DEBUG]   Imported: org.apache.maven.monitor < maven.ext
[DEBUG]   Imported: org.apache.maven.plugin < maven.ext
[DEBUG]   Imported: org.apache.maven.profiles < maven.ext
[DEBUG]   Imported: org.apache.maven.project < maven.ext
[DEBUG]   Imported: org.apache.maven.reporting < maven.ext
[DEBUG]   Imported: org.apache.maven.repository < maven.ext
[DEBUG]   Imported: org.apache.maven.rtinfo < maven.ext
[DEBUG]   Imported: org.apache.maven.settings < maven.ext
[DEBUG]   Imported: org.apache.maven.toolchain < maven.ext
[DEBUG]   Imported: org.apache.maven.usability < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.* < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.authentication < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.authorization < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.events < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.observers < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.proxy < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.repository < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.resource < maven.ext
[DEBUG]   Imported: org.codehaus.classworlds < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.* < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.classworlds < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.component < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.configuration < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.container < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.context < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.logging < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.personality < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < maven.ext
[DEBUG]   Imported: org.eclipse.aether.* < maven.ext
[DEBUG]   Imported: org.eclipse.aether.artifact < maven.ext
[DEBUG]   Imported: org.eclipse.aether.collection < maven.ext
[DEBUG]   Imported: org.eclipse.aether.deployment < maven.ext
[DEBUG]   Imported: org.eclipse.aether.graph < maven.ext
[DEBUG]   Imported: org.eclipse.aether.impl < maven.ext
[DEBUG]   Imported: org.eclipse.aether.installation < maven.ext
[DEBUG]   Imported: org.eclipse.aether.internal.impl < maven.ext
[DEBUG]   Imported: org.eclipse.aether.metadata < maven.ext
[DEBUG]   Imported: org.eclipse.aether.repository < maven.ext
[DEBUG]   Imported: org.eclipse.aether.resolution < maven.ext
[DEBUG]   Imported: org.eclipse.aether.spi < maven.ext
[DEBUG]   Imported: org.eclipse.aether.transfer < maven.ext
[DEBUG]   Imported: org.eclipse.aether.version < maven.ext
[DEBUG]   Imported: org.fusesource.jansi.* < maven.ext
[DEBUG]   Imported: org.slf4j.* < maven.ext
[DEBUG]   Imported: org.slf4j.helpers.* < maven.ext
[DEBUG]   Imported: org.slf4j.spi.* < maven.ext
[DEBUG]   Imported: org.sonatype.maven.polyglot < maven.ext
[DEBUG]   Imported: org.sonatype.maven.polyglot.execute < maven.ext
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Message scheme: color
[DEBUG] Message styles: debug info warning error success failure strong mojo project
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/whitingjr/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/whitingjr/.m2/toolchains.xml
[DEBUG] Using local repository at /home/whitingjr/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/whitingjr/.m2/repository
[INFO] Scanning for projects...
[DEBUG] /thebounty/work/redhat/java/jruby/jruby-git/.polyglot.pom.rb
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:122)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util
    at org.jruby.RubyModule.const_missing (org/jruby/RubyModule.java:3370)
    at RUBY.<main> (/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/stringio.rb:2)
    at org.jruby.RubyKernel.require (org/jruby/RubyKernel.java:956)
    at RUBY.<main> (/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/specification.rb:1)
    at org.jruby.RubyKernel.require (org/jruby/RubyKernel.java:956)
    at RUBY.<module:(root)> (/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/specification.rb:17)
    at RUBY.<main> (/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems.rb:1)
    at org.jruby.RubyKernel.require (org/jruby/RubyKernel.java:956)
    at RUBY.<main> (/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems.rb:1376)
    at org.jruby.RubyKernel.load (org/jruby/RubyKernel.java:974)
    at RUBY.<main> (/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems.rb:117)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
$
```

 It seems the build instructions are missing a step to prepare the environment for BUILDING. The JRuby installed runtime has a dependency on the stringio gem.

**Comment by whitingjr** [comment]
Plus when I try following the [build instructions](https://github.com/jruby/jruby/blob/master/BUILDING.md) the build fails as well. For the same reason.

```
$ ./mvnw
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip
..............................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/whitingjr/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9-bin.zip to /home/whitingjr/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2
Set executable permissions for: /home/whitingjr/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/bin/mvn
[INFO] Scanning for projects...
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant JRuby::Util
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3370)
	at RUBY.<main>(/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/stringio.rb:2)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at RUBY.<main>(/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/specification.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at RUBY.<module:(root)>(/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/specification.rb:17)
	at RUBY.<main>(/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at RUBY.<main>(/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems.rb:1376)
	at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:974)
	at RUBY.<main>(/home/whitingjr/java/jruby/jruby-9.2.6.0/lib/ruby/stdlib/rubygems.rb:117)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
$
```

**Comment by kares** [comment]
the isolation seems to be the problem - polyglot is using jruby (embed) 9.1.17.0 but it attempts to load 9.2.6.0 stdlib files from your home dir, its likely you have a `GEM_HOME/GEM_PATH` set ?

make sure this isn't on the path: `/home/whitingjr/java/jruby/jruby-9.2.6.0/lib`

**Comment by mkristian** [comment]
looks more like JRUBY_HOME to me. @whitingjr can it be you have this set in your env ?

**Comment by whitingjr** [comment]
@mkristian yes that's right. To me that's the obvious way to configure jruby in an environment. Was that a flawed assumption ?

**Comment by mkristian** [comment]
@whitingjr JRUBY_HOME does tell a running jruby where to find the ruby stdlib and other things. this is where things get mixed up. your installed jruby is not the same which is used by the maven built. 
I am not sure what the use case is where you want another JRUBY_HOME then the one of the running jruby. seeing this problem here and other problems in the past I doubt the setting JRUBY_HOME is a good idea - the default of not setting it is good enough. cc/ @kares @enebo 
but a similar problem exists for GEM_HOME and GEM_PATH but that is not the case with as far I can tell.

**Comment by whitingjr** [comment]
@mkristian sure, I set that environment property name. It can be anything. I'll change it.

**Comment by whitingjr** [comment]
@mkristian I am happy for this issue be closed.
