### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?): "http://api.example.co"

### ISSUE THREAD

**Issue by prcongithub** [jruby/jruby#5724]
We are facing a weird issue with JRuby inside a docker container. Same thing works when running the code outside docker on a regular Ubuntu / CentOS machine.

Docker image: jruby:9.2.6.0
Ruby: 2.5.3

Stacktrace:
```
! Unable to load application: URI::InvalidURIError: bad URI(is not URI?): "http://authapilocal.es-q.co"
sq_api_1  | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
sq_api_1  | URI::InvalidURIError: bad URI(is not URI?): "http://authapilocal.es-q.co"
sq_api_1  |   /project/config/initializers/vger.rb:97:in `split'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/uri/rfc3986_parser.rb:73:in `parse'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/uri/common.rb:237:in `parse'
sq_api_1  |   /project/config/initializers/vger.rb:107:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:1029:in `load'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:1:in `block in (root)'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:657:in `load_config_initializer'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:656:in `block in load_config_initializer'
sq_api_1  |   org/jruby/RubyArray.java:1792:in `each'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block in Engine'
sq_api_1  |   org/jruby/RubyBasicObject.java:2681:in `instance_exec'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:422:in `block in each_strongly_connected_component_from'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:421:in `block in each_strongly_connected_component_from'
sq_api_1  |   org/jruby/RubyArray.java:1792:in `each'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
sq_api_1  |   org/jruby/RubyMethod.java:120:in `call'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:415:in `each_strongly_connected_component_from'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component'
sq_api_1  |   org/jruby/RubyArray.java:1792:in `each'
sq_api_1  |   org/jruby/RubyMethod.java:132:in `call'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:613:in `Engine'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:226:in `tsort_each'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:205:in `tsort_each'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:361:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:987:in `require'
sq_api_1  |   org/jruby/RubyKernel.java:1015:in `require_relative'
sq_api_1  |   /project/config/environment.rb:5:in `block in <main>'
sq_api_1  |   org/jruby/RubyBasicObject.java:2609:in `instance_eval'
sq_api_1  |   config.ru:1:in `(root)'
sq_api_1  |   config.ru:3:in `new_from_string'
sq_api_1  |   org/jruby/RubyKernel.java:1061:in `eval'
sq_api_1  |   /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
sq_api_1  |   config.ru:1:in `new_from_string'
sq_api_1  |   /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
sq_api_1  |   /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/configuration.rb:318:in `load_rackup'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/configuration.rb:243:in `app'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/runner.rb:138:in `load_and_bind'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/single.rb:87:in `run'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/launcher.rb:183:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:1022:in `load'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/cli.rb:77:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:1022:in `load'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/bin/puma:10:in `<main>'
sq_api_1  |   /usr/local/bundle/bin/puma:1:in `(root)'
sq_api_1  |   /usr/local/bundle/bin/puma:29:in `<main>'
```

**Comment by headius** [comment]
Can you reproduce this with just a simple Ruby script within the Docker container? That would be a big help in diagnosing why this happens.

**Comment by prcongithub** [comment]
@headius Same thing happening with Ruby-2.5.3 as well.
```
sq_api_1  | ! Unable to load application: URI::InvalidURIError: bad URI(is not URI?): "http://authapilocal.es-q.co"
sq_api_1  | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
sq_api_1  | URI::InvalidURIError: bad URI(is not URI?): "http://authapilocal.es-q.co"
sq_api_1  |   /usr/local/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split'
sq_api_1  |   /usr/local/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
sq_api_1  |   /usr/local/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
```

**Comment by prcongithub** [comment]
I created another sample ruby app and docker compose and dockerfile for the same.

URI.parse works inside a container.

Ruby File
```
url = "http://authlocal.es-q.co"
puts "URL: #{parsed_url}"
parsed_url = URI.parse("http://authlocal.es-q.co")
puts "Parsed URL: #{parsed_url}"
```
Dockerfile
```
FROM ruby:2.5.3

RUN mkdir /project

WORKDIR /project

COPY . /project
```
docker-compose file
```
version: '2.2'

services:
  sample_ruby_app:
    build:
      context: .
    command: 'ruby test.rb'
    volumes:
      - .:/project
```
Could this be because of some other gem I have in my Gemfile which is overriding Regexp.match somewhere?

**Comment by prcongithub** [comment]
Above same script is also working with JRuby Latest image inside docker.

**Comment by prcongithub** [comment]
@headius 
I am extremely sorry to bother you for this. 
Its a silly docker issue where in env files with KEY=VALUE pairs with VALUE included in double quotes are read with the double quotes and not as simple strings
Changing the below
```
URL="apilocal.es-q.co"
```
to
```
URL=apilocal.es-q.co
```
fixes the issues.

Closing this!
