### ISSUE TITLE
Unable to execute Ruby script in JDK11 via JRuby 9.2.7.0

### ISSUE THREAD

**Issue by Syed-SnapLogic** [jruby/jruby#5798]
My source code is listed at https://github.com/Syed-SnapLogic/SyedsPublicRepo/tree/master/JrubyTest.

I unable to execute the code at https://github.com/Syed-SnapLogic/SyedsPublicRepo/blob/master/JrubyTest/src/main/java/com/syed/jrubytest/Test2.java.

I am getting the below error:
```
--- exec-maven-plugin:1.5.0:exec (default-cli) @ JrubyTest ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/home/gaian/.m2/repository/com/headius/backport9/1.2/backport9-1.2.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
NilClass
NilClass
Exception in thread "main" org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `hasNext' for nil:NilClass
	at RUBY.execute(<script>:14)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
Any help to resolve the above error would be a great favour.  Thanks.

**Comment by enebo** [comment]
@Syed-SnapLogic  try changing all global variables to constants (e.g. $input -> INPUT) and see if your example works.

**Comment by Syed-SnapLogic** [comment]
@enebo, sorry, I didn't get what exactly you meant.  Can you pls provide your suggestion in more details with an illustration?

**Comment by enebo** [comment]
@Syed-SnapLogic on this line https://github.com/Syed-SnapLogic/SyedsPublicRepo/blob/master/JrubyTest/src/main/java/com/syed/jrubytest/Test2.java#L60 you use $input etc... which are global variables.  Below you bind to constants (e.g. INPUT).  I do not think $input can be anything other than nil.

**Comment by Syed-SnapLogic** [comment]
@enebo, sorry, your point is invalid.  If I simply use an older JRuby, 9.1.17.0, the program works fine and delivers output.  I want to use latest version, 9.2.7.0, but its giving that problem.  According to me, its a bug in JRuby or I am missing some correct configuration.  Thats what I need help here for.

**Comment by enebo** [comment]
@Syed-SnapLogic I did misread your code with the constant comment above.   You are doing a setBinding("input", something).    I do not see where yet but we changed binding to require the globals to be written as them:

```text
    private static final String INPUT = "$input";
```

It you try changing those String to add a '$' in front I believe this script will work in 9.2.  I will see if I can find which commit changed this.  I am giving 50% odds this was intentional (and 9.2 is a major release in JRuby so this may be a required change to move to 9.2).  I will comment again once I figure out when this changed.

**Comment by enebo** [comment]
This appears to be the change:  https://github.com/jruby/jruby/issues/5012#issuecomment-368632823

**Comment by AlexWayfer** [comment]
I'm also affected by this just in tests for `filewatcher`, example of job: https://cirrus-ci.com/task/5294985679470592

**Comment by enebo** [comment]
@AlexWayfer Are you sure?  This reported issue was from a change in our Java embedding (as in a java program wants to call Ruby) and filewatcher appears to be a normal Ruby gem/app.  I think you should file a new issue on this.  From that CI job I cannot tell immediately why you are getting ENOENT so perhaps a little more localizing what is being in those cases would make that new issue a little easier to fix that problem.

**Comment by AlexWayfer** [comment]
> @AlexWayfer Are you sure?

No, but the tests for Filewacher is like spawning ruby-executable from Ruby (JRuby in this case). 

And I found this issue by warnings lilke `com.headius.backport9.modules.Modules`.

> I think you should file a new issue on this.

OK, thank you.

**Comment by headius** [comment]
The "Illegal reflective access" warning here is benign and not related to the error. See #6049 and others for that issue.
