### ISSUE TITLE
Non-deterministic "TypeError: allocator undefined for Thread" errors

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#5842]
I'm using JRuby to run Rails in a Puma webserver, and using it to accept payments from Braintree using the braintree gem (latest versions of all of those, details in the Environment section below). I'm doing a few hundred transactions a day without issue, and have been running this set up for about a year, but in the last month or so every now and then I've been getting errors like the one below, a `TypeError`, with the message `allocator undefined for Thread`, it looks like its when psych is trying to serialize something into YAML and save it. This isn't deterministic, even replaying the same exact input and code works 99% of the time.

```
class: TypeError
allocator undefined for Thread
        org/jruby/RubyClass.java:234:in `allocate'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:373:in `revive'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        org/jruby/RubyArray.java:1842:in `each_slice'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:336:in `revive_hash'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:374:in `revive'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        org/jruby/RubyArray.java:1842:in `each_slice'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:336:in `revive_hash'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:374:in `revive'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        org/jruby/RubyArray.java:1842:in `each_slice'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:336:in `revive_hash'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:374:in `revive'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        org/jruby/RubyArray.java:1842:in `each_slice'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:336:in `revive_hash'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:374:in `revive'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        org/jruby/RubyArray.java:1842:in `each_slice'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:336:in `revive_hash'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:374:in `revive'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:16:in `visit'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/visitor.rb:6:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:32:in `accept'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych/nodes/node.rb:50:in `to_ruby'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych.rb:279:in `load'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/coders/yaml_column.rb:26:in `load'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/type/serialized.rb:22:in `deserialize'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/type/helpers/mutable.rb:8:in `cast'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute.rb:175:in `type_cast'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute.rb:42:in `value'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute.rb:156:in `changed_from_assignment?'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute.rb:59:in `changed?'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_mutation_tracker.rb:49:in `changed?'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_mutation_tracker.rb:15:in `block in changed_attribute_names'
        org/jruby/RubyArray.java:2663:in `select'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/attribute_mutation_tracker.rb:15:in `changed_attribute_names'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/attribute_methods/dirty.rb:114:in `changed_attribute_names_to_save'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/attribute_methods/dirty.rb:146:in `keys_for_partial_write'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/attribute_methods/dirty.rb:140:in `_create_record'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:346:in `block in _create_record'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:346:in `_create_record'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/timestamp.rb:102:in `_create_record'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/persistence.rb:705:in `create_or_update'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:342:in `block in create_or_update'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/callbacks.rb:342:in `create_or_update'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/persistence.rb:308:in `save!'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/persistence.rb:53:in `create!'
        /var/www/vhosts/mysite/releases/20190820090405/app/controllers/checkout_controller.rb:216:in `handle_successful_subscription_result'
        /var/www/vhosts/mysite/releases/20190820090405/app/controllers/checkout_controller.rb:100:in `block in complete_checkout'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
        /var/www/vhosts/mysite/releases/20190820090405/app/controllers/checkout_controller.rb:46:in `complete_checkout'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:38:in `block in process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
        org/jruby/RubyArray.java:1800:in `each'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/puma-4.1.0-java/lib/puma/configuration.rb:228:in `call'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/puma-4.1.0-java/lib/puma/server.rb:664:in `handle_request'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/puma-4.1.0-java/lib/puma/server.rb:467:in `process_client'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/puma-4.1.0-java/lib/puma/server.rb:328:in `block in run'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/puma-4.1.0-java/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
``` 

### Environment

**jruby -v**: jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10 +jit [linux-x86_64]

(This was happening in JRuby 9.2.7.0 as well, so its not a regression form 9.2.7.0->9.2.8.0)

**JRUBY_OPTS**: --server -J-Xloggc:/log/gc/puma.gclog -J-XX:+UseGCLogFileRotation -J-XX:NumberOfGCLogFiles=2 -J-XX:GCLogFileSize=500M -J-XX:+UseG1GC -J-XX:MaxGCPauseMillis=200 -J-XX:+ParallelRefProcEnabled -J-Djruby.jit.max=5000 -J-XX:OnOutOfMemoryError=/script/force_kill_puma -J-Xmx8g -J-Xms8g -J-XX:ReservedCodeCacheSize=1g -J-Dcom.sun.management.jmxremote.authenticate=false -J-Dcom.sun.management.jmxremote.ssl=false -J-Dcom.sun.management.jmxremote.port=9523

**Gems**: Rails 5.2.3, Puma 4.1.0, braintree 2.98.0

**Comment by kares** [comment]
seems very much like an application issue from the given trace, 
somehow you end up trying to serialize a state with a thread constant (instance?) : 
```
        /home/web/.rvm/rubies/jruby-9.2.8.0/lib/ruby/stdlib/psych.rb:279:in `load'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/coders/yaml_column.rb:26:in `load'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/type/serialized.rb:22:in `deserialize'
        /var/www/vhosts/mysite/shared/bundle/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/type/helpers/mutable.rb:8:in `cast'
```
... would focus here - trying to log the yaml (column) content before it's loaded and than investigate

**Comment by mohamedhafez** [comment]
I think you are right, I've been serializing `Braintree::Subscription` objects to YAML, but I think it has something in it that shouldn't be serialized, I'm seeing some issues on MRI as well. Sorry for the false alarm, and thanks for the advice!
