### ISSUE TITLE
How to generate `rb` file by `rake` for `s390x-linux`?

### ISSUE THREAD

**Issue by samding01** [jruby/jruby#5846]
### Environment

Provide at least:
* JRuby version (`jruby -v`) 
     jruby 9.2.7.0 (2.5.3) 2019-08-01 8a269e3 OpenJDK 64-Bit Server VM 11.0.4+11-post-Ubuntu-1ubuntu218.04.3 on 11.0.4+11-post-Ubuntu-1ubuntu218.04.3 +jit [linux-s390x]
* Operating system and platform (e.g. `uname -a`)
     Linux csz25083.canlab.ibm.com 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:14:23 UTC 2018 s390x s390x s390x GNU/Linux

### Inquiry

After building, on the generated jar :`lib/target/jruby-stdlib-9.2.7.0.jar`, there are 10 files under platform x86_64-linux (directory: `META-INF/jruby.home/lib/ruby/stdlib/ffi/platform/x86_64-linux`):

         errno.rb  etc.rb  fcntl.rb  platform.conf  socket.rb
          stat.rb  sysconf.rb  syslog.rb  types.conf  zlib.rb

But under `s390x-linux` (directory: `META-INF/jruby.home/lib/ruby/stdlib/ffi/platform/s390x-linux`), there are only 1 file

           types.conf

The fist line of each files has `# This file is generated by rake. Do not edit.` ( for example `sysconf.rb`

The questions here are:
1) how  these file are generated by `rake` for x86_64-linux?
2) Is there any way to generate the similar files for `s390x-linux`?

Thanks,

**Comment by headius** [comment]
The rakefile for this lives in a sibling directory, under lib/ruby/stdlib/ffi/tools:

https://github.com/jruby/jruby/tree/2c3147e674967e87cd227ed6afd379cb192008a7/lib/ruby/stdlib/ffi/tools

Can you give that a try?

**Comment by samding01** [comment]
@headius  Thank you.
Can you let me know HOW TO run `rake` to generate those rb files?
```
# rake -f Rakefile
rake aborted!
LoadError: cannot load such file -- ffi
/home/jruby/lib/ruby/stdlib/ffi/tools/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
Note that those of rb files under `x86_64-linux` are managed by `git` ;
When I build jruby by `./mvnw` at rjuby home, no new files generated under `lib/ruby/stdlib/ffi/platform/s390x-linux` folder.

**Comment by headius** [comment]
Did you run that `rake` command with JRuby? It looks like you ran it with CRuby without FFI installed.

It may work fine with CRuby + FFI, but I have not tried that.

I am testing it now on Mac and making some tweaks to get it to build, but I believe it should work ok on Linux.

**Comment by headius** [comment]
@samding01 Oops, that reply was for you ^

**Comment by samding01** [comment]
@headius 
I do not have  `CRuby` installed. 
I can `git clone` jruby and build on s390x-linux. All is fine.

Can you please let me know the steps how to run `rake` to generate those rb files?

Thanks,

**Comment by headius** [comment]
I believe just running `rake` from within that ffi/tools directory should work. Can you try that?

You might also stop by our Matrix channel, IRC channel, or Gitter channel if you want to collaborate for a bit;

**Comment by samding01** [comment]
Under directory `/home/jruby/lib/ruby/stdlib/ffi/tools`, invoke `rake` and  get:
```
$ rake
rake aborted!
LoadError: cannot load such file -- ffi
/home/jruby/lib/ruby/stdlib/ffi/tools/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

$ rake -V
rake, version 12.3.1
```

**Comment by headius** [comment]
Can you run this and post the output? FFI is shipped with JRuby, so something's wrong about your environment.

```
$ ruby -v -e "require 'ffi'; p FFI"
jruby 9.2.6.0-SNAPSHOT (2.5.3) 2019-08-28 a55e357 OpenJDK 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]
FFI
```

**Comment by headius** [comment]
We also never print out `<top (required)>` so I'm pretty sure you're running CRuby.

**Comment by samding01** [comment]
Here is output:
```
#  ruby -v -e "require 'ffi'; p FFI"
ruby 2.5.1p57 (2018-03-29 revision 63029) [s390x-linux-gnu]
Traceback (most recent call last):
        2: from -e:1:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ffi (LoadError)
```

**Comment by samding01** [comment]
on a x86_64 ubuntu 16.04, it got the same output:
```
 $ ruby -v -e "require 'ffi'; p FFI"
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ffi (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by headius** [comment]
Yes, that's not JRuby.

**Comment by headius** [comment]
You may be able to get that to work if you `gem install ffi` but I have not tried running this code on CRuby.

**Comment by samding01** [comment]
1)  `gem install ffi`;
2) build jruby by `./mvnw`; then `export PATH=/home/jruby/bin:$PATH`;
Then get follows:
```
# ruby -v -e "require 'ffi'; p FFI"
jruby 9.2.7.0 (2.5.3) 2019-08-01 8a269e3 OpenJDK 64-Bit Server VM 11.0.4+11-post-Ubuntu-1ubuntu218.04.3 on 11.0.4+11-post-Ubuntu-1ubuntu218.04.3 +jit [linux-s390x]
```
and `rake` gets:
```
# rake

rake aborted!
Compilation error generating struct fcntl-flock (struct flock):
        In file included from /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4:3:0:
        /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4: In function ‘main’:
        /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4:17:69: error: ‘struct flock’ has no member named ‘l_sysid’; did you mean ‘l_pid’?
             printf("l_sysid %u %u\n", (unsigned int) offsetof(struct flock, l_sysid),
                                                                             ^
        /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4:18:36: error: ‘struct flock’ has no member named ‘l_sysid’; did you mean ‘l_pid’?
                    (unsigned int) sizeof(s.l_sysid));
                                            ^~~~~~~
                                            l_pid
        In file included from /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4:3:0:
        /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4:21:67: error: ‘struct flock’ has no member named ‘l_pad’; did you mean ‘l_pid’?
             printf("l_pad %u %u\n", (unsigned int) offsetof(struct flock, l_pad),
                                                                           ^
        /home/jruby/lib/ruby/stdlib/ffi/tools/fcntl-flock.struct_generator20190830-27767-cfkp4:22:36: error: ‘struct flock’ has no member named ‘l_pad’; did you mean ‘l_pid’?
                    (unsigned int) sizeof(s.l_pad));
                                            ^~~~~
                                            l_pid
org/jruby/ext/tempfile/Tempfile.java:260:in `open'
(eval):2:in `(eval)'
Tasks: TOP => default => build => s390x => gen_ffi_files_s390x
```
on x86_64 get the similar errors

**Comment by samding01** [comment]
Is there any update ? the question is  how the  these "rb" files was generated by "rake" on x86_64.

**Comment by samding01** [comment]
Is there any update ? the question is how the these "rb" files was generated by "rake" on x86_64.

**Comment by huimxu** [comment]
Is there any update ? the question is how the these "rb" files was generated by "rake" on x86_64.

**Comment by headius** [comment]
Hello, somehow this issue was ignored for a while.

The files generated here may be out of date. This is the source file used to generate the fcntl flock structure:

https://github.com/jruby/jruby/blob/01030ab2f5f3b2ce79f24d201a5555f046a8ec24/lib/ruby/stdlib/ffi/platform/fcntl-flock.rb.ffi

The problematic `l_sysid`and `l_pad` do appear here but do not seem to be present on either Linux or MacOS. I am not sure why they are included.

These files do not exist on JRuby master in part because they were unmaintained. We do not ship any of these default struct mappings anymore and would recommend that you just define the struct layout yourself.

The files were removed as part of this PR: https://github.com/jruby/jruby/pull/6503

There are examples of how to define these structs that you can use as a model there.

We would not be opposed to spinning these files off into a third-party library, like an "ffi-posix" gem that contains common bindings, but currently we do not need these files and have not maintained them for many years.

**Comment by headius** [comment]
More information:

It appears that this unusual flock structure is from Solaris, and this file was mistakenly created based on that struct definition while fixing a bug:

https://github.com/jruby/jruby/commit/01030ab2f5f3b2ce79f24d201a5555f046a8ec24

The only reason these files existed was to add support for the Ruby `flock` function when running on Solaris, which has no `flock` but uses `fcntl` with the flock struct to accomplish the same behavior.

If you need to use this struct via FFI in your own application, I recommend you just create your own binding.

However, if this struct needs to be available when JRuby is running on s390x-linux (e.g. if s390x-linux does not support the `flock` function) please open a new issue demonstrating the problem. This issue was about generating the platform files, which are no longer provided or supported.
