### ISSUE TITLE
Stackoverflow Exception during canonicalize path

### ISSUE THREAD

**Issue by MotherCake** [jruby/jruby#5899]
Hi,

I'm using Java with this Premailer https://github.com/mdedetrich/java-premailer-wrapper to send nearly pretty mails to Outlook user. 
This Premailer uses Jruby 9.1.2.0 and Rubygems 1.8.7
When i start sending mails i get a Stackoverflow Exception 

> threw an unhandled Exception: : java.lang.StackOverflowError
        at java.base/java.lang.StringLatin1.newString(StringLatin1.java:782)
        at java.base/java.lang.String.substring(String.java:1855)
        at deployment.project.war//org.jruby.RubyFile.canonicalize(RubyFile.java:1911)
        at deployment.project.war//org.jruby.RubyFile.canonicalize(RubyFile.java:1940)
        at deployment.project.war//org.jruby.RubyFile.canonicalize(RubyFile.java:1940)
        at deployment.project.war//org.jruby.RubyFile.canonicalize(RubyFile.java:1940)
        .....
I'm a Jruby noob and i do not know what happens here and which path is canonicalized. I hope you guys can give me a hint.

Thx in advance.

**Comment by enebo** [comment]
@MotherCake any chance you can try using a newer version of JRuby?  9.1.2.0 was released may 2016.  I recommend 9.2.8.0 but the latest of the 9.1.x series was 9.1.17.0.  This problem does not ring any bells but we have fixed so many things since that release.
