### ISSUE TITLE
Occasional Errors when using Theine - ERROR -- : run() in thread failed: closed stream

### ISSUE THREAD

**Issue by rwilliams** [jruby/jruby#5983]
### Environment

jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]

**Host OS - WSL2**
Linux 975c34fa2e2c 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Docker Container**
GNU/LinuxDistributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

**Gem/Framework info:**
Rails 6.1 nothing too exciting

**Environment variables**
JRUBY_OPTS=--dev

### Expected Behavior
I expect `theine routes` to show routes and run fast after warm up.

### Actual Behavior
`theine routes` completes but then throws the following error

> E, [2019-11-26T05:47:27.744527 #676] ERROR -- : run() in thread failed: closed stream:\n org/jruby/RubyIO.java:3556:in `select'
> org/jruby/RubyKernel.java:669:in `select'
> /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:306:in `readpartial'
> /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:279:in `read_events'
> /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
> /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
> org/jruby/ext/thread/Mutex.java:164:in `synchronize'
> /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /opt/jruby/lib/ruby/stdlib/
> forwardable.rb:229:in `start'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in Listener'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
> /usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
> /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/evented_file_update_checker.rb:113:in `boot!'
> /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/evented_file_update_checker.rb:68:in `initialize'
> /usr/local/bundle/gems/railties-6.0.1/lib/rails/application/finisher.rb:220:in `block in Finisher'
> /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `instance_exec'
> /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `run'
> /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:347:in `call'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:226:in `tsort_each'
> /opt/jruby/lib/ruby/stdlib/tsort.rb:205:in `tsort_each'
> /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:60:in `run_initializers'
> /usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:363:in `initialize!'
> /home/user/cds/config/environment.rb:5:in `<main>'
> /usr/local/bundle/bundler/gems/theine-754b7ff494ec/lib/theine/worker.rb:144:in `require'
> /usr/local/bundle/bundler/gems/theine-754b7ff494ec/lib/theine/worker.rb:144:in `boot'
> /usr/local/bundle/bundler/gems/theine-754b7ff494ec/lib/theine/worker.rb:53:in `run'
> /usr/local/bundle/bundler/gems/theine-754b7ff494ec/lib/theine/worker.rb:155:in `<main>'
> warning: thread "Ruby-0-Thread-4: /usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6" terminated with exception (r
> eport_on_exception is true):
> RuntimeError: No current exception
>    at :1
>    at :1

It doesn't seem the crash the theine server it's just a little annoying getting all that mess after the command.

**Comment by rwilliams** [comment]
[Stack trace](https://gist.githubusercontent.com/rwilliams/8141fdefd5b8b26b32ead12826020ebf/raw/92830894bdbd09b27ed042439b900cde9c164b3a/error_trace) when not using theine.

**Comment by headius** [comment]
Usually this error means that the process was shut down while there were still active threads. Part of shutdown is closing open streams, which would trigger an error in threads still using them.
