### ISSUE TITLE
Updating from 1.6.8 to 9.2.9.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [jruby/jruby#6001]
**Environment**
Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

**Expected Behavior**
When I try to upgrade JRuby-Complete from 1.6.8 to the version after 1.7.0. The following code breaks.

```
public class Testruby {
	
	
	@Test
	public void demo() {
		
		ScriptingContainer scriptingContainer = new ScriptingContainer();
		
		Object ret = null;
			
		File script = new File("src/test/ruby/NestedTypesAction.rb");
			
			scriptingContainer.getLoadPaths().add(Testruby.getPath(script));
			scriptingContainer.runScriptlet("load '" + "NestedTypesAction.rb"  + "'");
			ret = scriptingContainer.runScriptlet(Testruby.getFileNameSansExtension(script) + ".new");
		
	}
	
	
	public static String getFileNameSansExtension(File file)
	{
		String filename = file.getName();
		if(filename.lastIndexOf('.') > 0)
		{
			return filename.substring(0,filename.lastIndexOf('.'));
		}
		else return filename;
	}
	
	public static String getPath(File file)
	{
		int sep = file.getPath().lastIndexOf(File.separator);
		return file.getPath().substring(0, sep);
	}

}
```

NestedTypesAction.rb
```
require 'java'
require 'TrifaceJRubyAction.rb'

# dummy action to set some basic values for testing.
# sets basic ruby types
class NestedTypesAction < TrifaceJRubyAction
  
  def execute()
    @objectmap["list"] = [["a","b"],["c","d"]]
    @objectmap["map"] = {"key1" => {"foo","bar"}, "key2" => {"bar","baz"}}
    return getMap()
  end
  
end
```

TrifaceJRubyAction.rb
```
require 'java'
require 'ClojureMap.rb'
import com.instrument.triface.action.ATrifaceAction

#
# An abstract action class defining common getters and setters.
# Extending classes must implement execute().
#
# Currently designed to handle clojure maps (IPersistantMap)
#
class TrifaceJRubyAction < ATrifaceAction
  
  	def initialize
  		@objectmap = Hash.new
  	end
  
	def execute()
		raise NotImplementedError.new
	end
	
	def setMapInternal(m)
    	# TODO: figure out how to do better type checking. this sucks.
    	if m.getClass().toString() == "class clojure.lang.PersistentArrayMap"
    		@objectmap = ClojureMap.new(m)
    	else
    		@objectmap = m
    	end
	end
	
	def getMapInternal()
		if @objectmap.is_a?(ClojureMap)
			return @objectmap.getMap()			 
		else
			return @objectmap
		end
  	end
	
end
```

ClojureMap.rb
```
require 'java'

class ClojureMap < Hash
  
  def initialize(cljMap)
  	@persistentMap = cljMap
  end
  
  def [](key)
    @persistentMap.get(key)
  end

  def []=(key, value)
    @persistentMap = @persistentMap.assoc(key, value)
  end
  
  def getMap()
  	return @persistentMap
  end
end
```

The code should pass.

**Actual Behavior**

After upgrading, the code throws an error:
```
Running Testruby
SyntaxError: /Users/chenlingchao/PycharmProjects/bug-check/new/jruby-complete/caribou-action-adapter/src/test/ruby/NestedTypesAction.rb:10: syntax error, unexpected ','
    @objectmap["map"] = {"key1" => {"foo","bar"}, "key2" => {"bar","baz"}}
                                         ^
    load at org/jruby/RubyKernel.java:1013
  <main> at <script>:1
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.829 sec <<< FAILURE!
demo(Testruby)  Time elapsed: 2.814 sec  <<< ERROR!
org.jruby.embed.EvalFailedException: (SyntaxError) /Users/chenlingchao/PycharmProjects/bug-check/new/jruby-complete/caribou-action-adapter/src/test/ruby/NestedTypesAction.rb:10: syntax error, unexpected ','
    @objectmap["map"] = {"key1" => {"foo","bar"}, "key2" => {"bar","baz"}}
                                         ^
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1295)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1288)
	at Testruby.demo(Testruby.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.java:99)
	at org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java:81)
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
	at org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)
	at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)
	at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:71)
	at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:35)
	at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.jruby.exceptions.SyntaxError: (SyntaxError) /Users/chenlingchao/PycharmProjects/bug-check/new/jruby-complete/caribou-action-adapter/src/test/ruby/NestedTypesAction.rb:10: syntax error, unexpected ','
    @objectmap["map"] = {"key1" => {"foo","bar"}, "key2" => {"bar","baz"}}
                                         ^
	at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1013)
	at RUBY.<main>(<script>:1)
```

**Comment by headius** [comment]
I believe the problem is this syntax, which was supported in Ruby 1.8 but removed in 1.9:

```
[] ~/projects/jruby $ rvm ruby-1.8.7 do ruby -e 'p({"foo", "bar"})'
{"foo"=>"bar"}

[] ~/projects/jruby $ rvm ruby-1.9.3 do ruby -e 'p({"foo", "bar"})'
-e:1: syntax error, unexpected ',', expecting tASSOC
p({"foo", "bar"})
         ^
-e:1: syntax error, unexpected '}', expecting $end
p({"foo", "bar"})
```

JRuby started defaulting to Ruby 1.9 behavior in JRuby 1.7, and subsequent releases have kept up with the Ruby 2.x line. I believe if you fix this syntax you will no longer get the error.
