### ISSUE TITLE
caller_locations called from `#initialize` doesn't contain `new`

### ISSUE THREAD

**Issue by palkan** [jruby/jruby#6055]
**Environment Information**
  
Provide at least:
* JRuby version: jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]

**Expected Behavior**

Given the following script:

```ruby
class A
  def self.build
    new
  end

  def initialize
    puts caller_locations(1, 5)
  end
end
```

I want the following command to match the MRI (2.5+) output:

```sh
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

$ ruby -r ./caller_locations.rb -e "A.build"

/app/tmp/caller_locations.rb:3:in `new'
/app/tmp/caller_locations.rb:3:in `build'
-e:1:in `<main>'
```

**Actual Behavior**

The actual output doesn't contains the `new` line:

```sh
$ ruby -v
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]

$ ruby -r ./caller_locations.rb -e "A.build"
/app/tmp/caller_locations.rb:3:in `build'
-e:1:in `<main>'
```

**Comment by headius** [comment]
Can I ask why you want the `new` line in there?

This is likely due to an optimization in `new` that performs the allocation and `initialize` call together. It allows that logic to inline better than it would otherwise, which then leads to further optimizations.

It's possible to get `new` to show up here, but it would require either dropping the optimization or generating a separate `new` body for every single class (since otherwise the `initialize` can't inline through it).

**Comment by headius** [comment]
Actually I may be partially wrong; the optimization I talked about is only enabled in invokedynamic mode; normally calls to new will proceed just line any other call.

So this will likely remain a problem in indy mode, but there's something else going on in non-indy mode to lose that frame.

**Comment by headius** [comment]
Ok so it looks like this change was made intentionally around eight years ago: https://github.com/jruby/jruby/commit/aa4e8bb8ddcd97e94f73dab1957137de1a053af8

The problem then was that having a .java line in the stack trace (since our `new` is written in Java` messed up expectations that it have a .rb line. CRuby actually loses information here, since it fakes out the `new` entry to show the line where it was called, not a line inside the actual `new` implementation.

However when emitting "caller" information, we do actually fix up these methods to match CRuby. Here's the output of `caller(0)` with the above patch reverted:

```
[] ~/projects/jruby $ cat blah.rb
class A
  def self.build
    new
  end

  def initialize
    puts caller(0)
  end
end
A.build

[] ~/projects/jruby $ jruby blah.rb
blah.rb:7:in `initialize'
blah.rb:3:in `new'
blah.rb:3:in `build'
blah.rb:10:in `<main>'

[] ~/projects/jruby $ rvm ruby-2.6.5 do ruby blah.rb
blah.rb:7:in `initialize'
blah.rb:3:in `new'
blah.rb:3:in `build'
blah.rb:10:in `<main>'
```

And the problematic stack trace for an error:

```
RuntimeError: No current exception
  initialize at blah.rb:7
         new at org/jruby/RubyClass.java:911
       build at blah.rb:3
      <main> at blah.rb:10
```

Note that under invokedynamic, the `new` line will still eventually disappear once it is inlined with `initialize` into the caller.

**Comment by palkan** [comment]
> Can I ask why you want the new line in there?

I don't really need it but MRI has it :)

> Note that under invokedynamic, the new line will still eventually disappear once it is inlined with initialize into the caller.

I think, mentioning this minor incompatibility in the [corresponding WiKi page](https://github.com/jruby/jruby/wiki/Differences-Between-MRI-and-JRuby) would be enough.

**Comment by headius** [comment]
I added a snippit to that wiki page.

For the moment I have no plans to remove the optimization, given the cost/benefits there. If there's a valid practical reason not to drop the `new` frame, I'm willing to discuss that.

I will however try out a PR that restores the `new` frames otherwise, since it's a simple change and it may not break as many things as it did in 2011.

**Comment by headius** [comment]
Ah leave open for a bit of discussion and to watch the upcoming PR.
