### ISSUE TITLE
shopify-api gem reporting NoMethodError: undefined method `threadsafe_attribute'

### ISSUE THREAD

**Issue by IBee21** [jruby/jruby#6119]
shopify-api gem does not work.  Early versions used to work (a few years back).

**Environment Information**
  JRuby  9.2.11.0
  Windows 10

Easy way to reproduce:
```
gem install shopify_api
gem install shopify_api_console
shopify-api console
```

```
NoMethodError: undefined method `threadsafe_attribute' for #<Class:ShopifyAPI::Base>
       method_missing at org/jruby/RubyBasicObject.java:1708
      singleton class at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:34
         <class:Base> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:33
  <module:ShopifyAPI> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:4
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:3
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources.rb:1
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api.rb:21
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api_console-2.0.0/lib/shopify_api_console/console.rb:4
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api_console-2.0.0/bin/shopify-api:3
                 load at org/jruby/RubyKernel.java:1009
               <main> at C:\jruby-9.2.11.0\bin\shopify-api:23
```

Works fine with normal ruby-2.5.7-1-x64 from https://www.ruby-lang.org

**Comment by olleolleolle** [comment]
The reproduce: a tiny erratum:

`gem install shopify_api_console` installs, (note the underscore)

With ruby-2.6.3, it fails on missing a file `~/.shopify/shops/default`. (One would need Shopify-related setup to make the `console` command run.)

But! To be clear, that expected failure looks like this. This is when everything works correctly with the Ruby implementation.

```
➜  ~ shopify-api console
Traceback (most recent call last):
	10: from /Users/olle/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /Users/olle/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	 8: from /Users/olle/.rvm/gems/ruby-2.6.3/bin/shopify-api:23:in `<main>'
	 7: from /Users/olle/.rvm/gems/ruby-2.6.3/bin/shopify-api:23:in `load'
	 6: from /Users/olle/.rvm/gems/ruby-2.6.3/gems/shopify_api_console-2.0.0/bin/shopify-api:4:in `<top (required)>'
	 5: from /Users/olle/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	 4: from /Users/olle/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	 3: from /Users/olle/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	 2: from /Users/olle/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	 1: from /Users/olle/.rvm/gems/ruby-2.6.3/gems/shopify_api_console-2.0.0/lib/shopify_api_console/console.rb:105:in `console'
/Users/olle/.rvm/gems/ruby-2.6.3/gems/shopify_api_console-2.0.0/lib/shopify_api_console/console.rb:105:in `read': No such file or directory @ rb_sysopen - /Users/olle/.shopify/shops/default (Errno::ENOENT)
```

**Comment by olleolleolle** [comment]
By introducing `extend ::ThreadsafeAttributes::ClassMethods` just above the line with the failure, it was possible to get the same error that MRI got (i.e. get the thing working).

I understand this does not help _you_ very much, but perhaps it circles the issue better.

**Comment by olleolleolle** [comment]
This seems to be the removal which made it no longer work: https://github.com/Shopify/shopify_api/commit/6a50c3c807c70fcf0df343f054fb86b5e260fd5c

**Comment by headius** [comment]
Where does `threadsafe_attribute` come from? It's not even present in head rails and I've not been able to find it in rails history either.

**Comment by headius** [comment]
Aha, I did not realize activeresource has its own repo.

This appears to be the same issue and it's from last year: https://github.com/Shopify/shopify_api/issues/586

From what I can gather, `ShopifyAPI::Base` extends `ActiveResource::Base` which includes `ThreadsafeAttributes`, and that should be making the method available.

The include happens inside `class << self` (so acting on the metaclass), which triggers an `extend` inside threadsafe_attributes.rb.

Given this sequence I think this is a reasonable script to try to reproduce the problem (and it does error):

```ruby
module M1
  def self.included(klass)
    klass.extend M2
  end
  module M2
    def foo; end
  end
end

class A
  include M1
end

class B < A
  class << self
    foo
  end
end
```

**Comment by headius** [comment]
Ok scratch that... CRuby also fails:

```
[] ~/projects/jruby $ jruby test.rb
NameError: undefined local variable or method `foo' for #<Class:B>
   method_missing at org/jruby/RubyBasicObject.java:1708
  singleton class at test.rb:16
       <module:B> at test.rb:15
           <main> at test.rb:14

[] ~/projects/jruby $ rvm ruby-2.6.5 do ruby test.rb
Traceback (most recent call last):
	2: from test.rb:14:in `<main>'
	1: from test.rb:15:in `<class:B>'
test.rb:16:in `singleton class': undefined local variable or method `foo' for #<Class:B> (NameError)
```

**Comment by headius** [comment]
More data...

Here's where that method is defined: https://github.com/rails/activeresource/blob/4accda8bc03ceae0ad626f8cec0b4751e89a58ad/lib/active_resource/threadsafe_attributes.rb#L11

Here's where it is included into `ActiveResource::Base`: https://github.com/rails/activeresource/blob/4accda8bc03ceae0ad626f8cec0b4751e89a58ad/lib/active_resource/base.rb#L321

And here's where it's called in shopify_api: https://github.com/Shopify/shopify_api/blob/6a50c3c807c70fcf0df343f054fb86b5e260fd5c/lib/shopify_api/resources/base.rb#L32

I'm stumped at the moment because my test case fails in CRuby as well.

**Comment by chrisface** [comment]
Had a look at the example reproduction code and the error that you get in CRuby `undefined local variable or method `foo' for #<Class:B>`.  From what I've looked into, this shouldn't work based on the code example.

The core of the issue seems to be that when you're trying to call `foo`, the current context of the body is the MetaClass as you described it. The parent of this MetaClass A is then the B MetaClass. The method `foo` here is currently unbound which is why it throws the error.

I did some experimentation in a Gist that will highlight this a bit more clearly.

Using the same setup as it currently is we can call `foo` like this.
```
class << self
  instance_method(:foo).bind(self).call
end
```

Or we can instead use `instance_eval` where the body context is then the Class and not the MetaClass.

```
class F < A
  instance_eval do
    puts "Self in instance eval #{self}" # F
    foo # This works :)
  end
end
```
Hope that this is of some use in fixing your issue.

https://gist.github.com/chrisface/e49c79a964ca1d2039e7e602ee42b49a#file-eigenwat-rb

**Comment by headius** [comment]
@chrisface Right, I agree with you... `foo` should not be callable there. My reproduction was an attempt to mimic what seems to happen inside ActiveResource when it starts up.

> From what I can gather, ShopifyAPI::Base extends ActiveResource::Base which includes ThreadsafeAttributes, and that should be making the method available.
> 
> The include happens inside class << self (so acting on the metaclass), which triggers an extend inside threadsafe_attributes.rb.

But as you observed, my example case fails in both JRuby and CRuby, so I seem to be missing something about how the actual code works. 🤔

**Comment by headius** [comment]
Revisiting this because it crossed my path.

Newer versions of shopify_api don't install due to a dependency on the `oj` gem. The version used in the original description are:

* shopify_api: 9.0.2
* shopify_api_console: 2.0.0

They need to be resolved together in something like a `Gemfile`:

```ruby
source "https://rubygems.org"

gem "shopify_api", "9.0.2"
gem "shopify_api_console", "2.0.0"
```

With that installed, the original command fails as before on versions 9.4 through 10.1, but appears to produce the expected error with the branch from #9446 (note `-rlogger` due to older Rails depending on `logger` being loaded by some core libs that no longer do so):

```
$ ruby -rlogger -S shopify-api console 
Errno::ENOENT: No such file or directory - /Users/headius/.shopify/shops/default
                     sysopen at org/jruby/RubyIO.java:1352
                        read at org/jruby/RubyIO.java:4439
                     console at /Users/headius/.gem/jruby/4.0.0/gems/shopify_api_console-2.0.0/lib/shopify_api_console/console.rb:105
                         run at /Users/headius/.gem/jruby/4.0.0/gems/thor-0.18.1/lib/thor/command.rb:27
              invoke_command at /Users/headius/.gem/jruby/4.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120
                    dispatch at /Users/headius/.gem/jruby/4.0.0/gems/thor-0.18.1/lib/thor.rb:363
                       start at /Users/headius/.gem/jruby/4.0.0/gems/thor-0.18.1/lib/thor/base.rb:439
                      <main> at /Users/headius/.gem/jruby/4.0.0/gems/shopify_api_console-2.0.0/bin/shopify-api:4
                        load at org/jruby/RubyKernel.java:1402
  activate_and_load_bin_path at /Users/headius/work/jruby/lib/ruby/stdlib/rubygems.rb:303
                      <main> at /Users/headius/work/jruby/bin/shopify-api:25
```

It seems that #9446 may also resolve this issue.
