### ISSUE TITLE
Tracing updates for Ruby 2.6

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6149]
There are a number of tracing updates in Ruby 2.6. We consider them a low-priority item, but I want to track the spec/test excludes.

**Comment by headius** [comment]
<details>
<summary>RubySpec TracePoint specs</summary>

```
1)
TracePoint#enable target: option enables trace point for specific location ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:114:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
2)
TracePoint#enable target: option traces all the events triggered in specified location ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:134:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
3)
TracePoint#enable target: option does not trace events in nested locations ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:156:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
4)
TracePoint#enable target: option traces some events in nested blocks ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:186:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
5)
TracePoint#enable target: option raises ArgumentError if target object cannot trigger specified event ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:251:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:250:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
6)
TracePoint#enable target: option raises ArgumentError if passed not Method/UnboundMethod/Proc ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:262:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:261:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
7)
TracePoint#enable target: option option value accepts Method ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:202:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
8)
TracePoint#enable target: option option value accepts UnboundMethod ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:219:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
9)
TracePoint#enable target: option option value accepts Proc ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:234:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
10)
TracePoint#enable target: option nested enabling and disabling raises ArgumentError if trace point already enabled with target is re-enabled with target ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:273:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:272:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
11)
TracePoint#enable target: option nested enabling and disabling raises ArgumentError if trace point already enabled without target is re-enabled with target ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:286:in `block in <main>'
org/jruby/ext/tracepoint/TracePoint.java:161:in `enable'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:285:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:284:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
12)
TracePoint#enable target: option nested enabling and disabling raises ArgumentError if trace point already enabled with target is re-enabled without target ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:297:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:296:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
13)
TracePoint#enable target: option nested enabling and disabling raises ArgumentError if trace point already enabled with target is disabled with block ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:309:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:308:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
14)
TracePoint#enable target: option nested enabling and disabling traces events when trace point with target is enabled in another trace point enabled without target ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:328:in `block in <main>'
org/jruby/ext/tracepoint/TracePoint.java:161:in `enable'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:327:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
15)
TracePoint#enable target: option nested enabling and disabling traces events when trace point with target is enabled in another trace point enabled with target ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:347:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
16)
TracePoint#enable target: option nested enabling and disabling traces events when trace point without target is enabled in another trace point enabled with target ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:367:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
17)
TracePoint#enable target_line: option traces :line events only on specified line of code ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:396:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
18)
TracePoint#enable target_line: option raises ArgumentError if :target option isn't specified ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:408:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:407:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
19)
TracePoint#enable target_line: option raises ArgumentError if :line event isn't registered ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:426:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:425:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
20)
TracePoint#enable target_line: option raises ArgumentError if :target_line value is out of target code lines range ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:436:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:435:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
21)
TracePoint#enable target_line: option raises TypeError if :target_line value couldn't be coerced to Integer ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:446:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:445:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
22)
TracePoint#enable target_line: option raises ArgumentError if :target_line value is negative ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:456:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:455:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
23)
TracePoint#enable target_line: option accepts value that could be coerced to Integer ERROR
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:472:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/enable_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
24)
TracePoint#eval_script is the evald source code ERROR
ArgumentError: unknown event: script_compiled
org/jruby/ext/tracepoint/TracePoint.java:63:in `initialize'
org/jruby/RubyClass.java:918:in `new'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/eval_script_spec.rb:15:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/eval_script_spec.rb:5:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/eval_script_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
25)
TracePoint#parameters returns the parameters of block ERROR
NoMethodError: undefined method `parameters' for #<TracePoint:disabled>
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:8:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:8:in `block in <main>'
org/jruby/ext/tracepoint/TracePoint.java:161:in `enable'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:8:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:4:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
26)
TracePoint#parameters returns the parameters of lambda block ERROR
NoMethodError: undefined method `parameters' for #<TracePoint:disabled>
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:17:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:17:in `block in <main>'
org/jruby/ext/tracepoint/TracePoint.java:161:in `enable'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:17:in `block in <main>'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:4:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/tracepoint/parameters_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2615:in `instance_eval'
org/jruby/RubyArray.java:1817:in `each'
```
</details>

<details>
<summary>MRI suite</summary>
```
 1) Failure:
TestTracer#test_tracer_with_option_r [/home/travis/build/jruby/jruby/test/mri/test_tracer.rb:9]:
Expected /rubygems\/core_ext\/kernel_require\.rb:\d+:Kernel:<:/ to match nil.
  2) Failure:
TestTracer#test_tracer_with_option_r_without_gems [/home/travis/build/jruby/jruby/test/mri/test_tracer.rb:21]:
unexpected output from `ruby --disable-gems -rtracer -e 1`.
<1> expected but was
<0>.
  3) Failure:
TestSetTraceFunc#test_lineno_in_optimized_insn [/home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:1919]:
[Bug #14809].
<"7\n"> expected but was
<"">.
  4) Failure:
TestSetTraceFunc#test_tracepoint_nested_enabled_with_target [/home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:1998]:
<"can't nest-enable a targetting TracePoint"> expected but was
<"wrong number of arguments calling `enable` (given 1, expected 0)">.
  5) Error:
TestSetTraceFunc#test_script_compiled:
ArgumentError: unknown event: script_compiled
    org/jruby/ext/tracepoint/TracePoint.java:63:in `initialize'
    org/jruby/RubyClass.java:918:in `new'
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:2094:in `test_script_compiled'
  6) Error:
TestSetTraceFunc#test_tracepoint_enable_target:
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:1962:in `check_with_events'
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:1974:in `test_tracepoint_enable_target'
  7) Error:
TestSetTraceFunc#test_tracepoint_enable_with_target_line:
ArgumentError: wrong number of arguments calling `enable` (given 1, expected 0)
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:2075:in `test_tracepoint_enable_with_target_line'
  8) Error:
TestSetTraceFunc#test_tracepoint_parameters:
NoMethodError: undefined method `parameters' for #<TracePoint:disabled>
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:722:in `block in test_tracepoint_parameters'
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:735:in `block in test_tracepoint_parameters'
    org/jruby/ext/tracepoint/TracePoint.java:161:in `enable'
    /home/travis/build/jruby/jruby/test/mri/ruby/test_settracefunc.rb:735:in `test_tracepoint_parameters'
```
</details>

**Comment by headius** [comment]
Note the tracer library needs an update, which may fix those two failures. See ruby/tracer#1

**Comment by headius** [comment]
Link to #5147, coverage options added in 2.5.
