### ISSUE TITLE
CSV parsing and encoding errors in 2.6

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6157]
Not sure why these tests are failing on JRuby's 2.6 branch, since we use the exact same code for the `csv` library. However, here they are.

```
[ 36/897] TestCSV::Parsing#test_malformed_csv = 0.02 s                                          
  1) Failure:
TestCSV::Parsing#test_malformed_csv [/Users/headius/projects/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[ 89/897] TestCSVEncodings#test_encoding_is_upgraded_during_writing_as_needed = 0.01 s                             
  2) Failure:
TestCSVEncodings#test_encoding_is_upgraded_during_writing_as_needed [/Users/headius/projects/jruby/test/mri/csv/test_encodings.rb:233]:
<"UTF-8"> expected but was
<"US-ASCII">.

[ 90/897] TestCSVEncodings#test_encoding_is_upgraded_for_ascii_content_during_writing_as_needed = 0.01 s
  3) Failure:
TestCSVEncodings#test_encoding_is_upgraded_for_ascii_content_during_writing_as_needed [/Users/headius/projects/jruby/test/mri/csv/test_encodings.rb:241]:
<"UTF-8"> expected but was
<"ISO-8859-1">.

[108/897] TestCSVEncodings::DifferentOFS#test_encoding_is_upgraded_during_writing_as_needed = 0.01 s             
  4) Failure:
TestCSVEncodings::DifferentOFS#test_encoding_is_upgraded_during_writing_as_needed [/Users/headius/projects/jruby/test/mri/csv/test_encodings.rb:233]:
<"UTF-8"> expected but was
<"US-ASCII">.

[109/897] TestCSVEncodings::DifferentOFS#test_encoding_is_upgraded_for_ascii_content_during_writing_as_needed = 0.00 s
  5) Failure:
TestCSVEncodings::DifferentOFS#test_encoding_is_upgraded_for_ascii_content_during_writing_as_needed [/Users/headius/projects/jruby/test/mri/csv/test_encodings.rb:241]:
<"UTF-8"> expected but was
<"ISO-8859-1">.

[467/897] TestCSVParseInvalid#test_ignore_invalid_line = 0.00 s                                                          
  6) Error:
TestCSVParseInvalid#test_ignore_invalid_line:
FiberError: dead fiber called
    org/jruby/ext/fiber/ThreadFiber.java:68:in `resume'
    uri:classloader:/jruby/kernel/enumerator.rb:95:in `next'
    uri:classloader:/jruby/kernel/enumerator.rb:17:in `next'
    /Users/headius/projects/jruby/lib/ruby/stdlib/csv.rb:1316:in `shift'
    /Users/headius/projects/jruby/test/mri/csv/parse/test_invalid.rb:34:in `test_ignore_invalid_line'

[716/897] TestCSVWriteGeneralGenerate#test_encoding_euc_jp = 0.01 s                                                            
  7) Failure:
TestCSVWriteGeneralGenerate#test_encoding_euc_jp [/Users/headius/projects/jruby/test/mri/csv/write/test_general.rb:205]:
<"\x{A4A2},\x{A4A4},\x{A4A6}\n"> expected but was
<"\xA4\xA2,\xA4\xA4,\xA4\xA6\n">.

[717/897] TestCSVWriteGeneralGenerate#test_encoding_utf8 = 0.01 s  
  8) Failure:
TestCSVWriteGeneralGenerate#test_encoding_utf8 [/Users/headius/projects/jruby/test/mri/csv/write/test_general.rb:199]:
<"あ,い,う\n"> expected but was
<"\xE3\x81\x82,\xE3\x81\x84,\xE3\x81\x86\n">.

[755/897] TestCSVWriteGeneralGenerate::DifferentOFS#test_encoding_euc_jp = 0.00 s
  9) Failure:
TestCSVWriteGeneralGenerate::DifferentOFS#test_encoding_euc_jp [/Users/headius/projects/jruby/test/mri/csv/write/test_general.rb:205]:
<"\x{A4A2},\x{A4A4},\x{A4A6}\n"> expected but was
<"\xA4\xA2,\xA4\xA4,\xA4\xA6\n">.

[756/897] TestCSVWriteGeneralGenerate::DifferentOFS#test_encoding_utf8 = 0.00 s  
 10) Failure:
TestCSVWriteGeneralGenerate::DifferentOFS#test_encoding_utf8 [/Users/headius/projects/jruby/test/mri/csv/write/test_general.rb:199]:
<"あ,い,う\n"> expected but was
<"\xE3\x81\x82,\xE3\x81\x84,\xE3\x81\x86\n">.
```

**Comment by headius** [comment]
Link to #5576.

**Comment by k77ch7** [comment]
Except for one test result,  I think jruby csv library test results is same to MRI 2.6.6.
TestCSVParseInvalid#test_ignore_invalid_line error message seems similar to #4864.



JRuby;
```
[ 36/897] TestCSV::Parsing#test_malformed_csv = 0.07 s
  1) Failure:
TestCSV::Parsing#test_malformed_csv [/Users/kiichi/git/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[ 48/897] TestCSV::Parsing::DifferentOFS#test_malformed_csv = 0.02 s
  2) Failure:
TestCSV::Parsing::DifferentOFS#test_malformed_csv [/Users/kiichi/git/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[133/897] TestCSVFeatures#test_gzip_reader = 0.12 s
  3) Error:
TestCSVFeatures#test_gzip_reader:
NoMethodError: undefined method `close' for nil:NilClass
    /Users/kiichi/git/jruby/test/mri/csv/test_features.rb:234:in `test_gzip_reader'

[164/897] TestCSVFeatures::DifferentOFS#test_gzip_reader = 0.04 s
  4) Error:
TestCSVFeatures::DifferentOFS#test_gzip_reader:
NoMethodError: undefined method `close' for nil:NilClass
    /Users/kiichi/git/jruby/test/mri/csv/test_features.rb:234:in `test_gzip_reader'

[472/897] TestCSVParseInvalid#test_ignore_invalid_line = 0.02 s
  5) Error:
TestCSVParseInvalid#test_ignore_invalid_line:
FiberError: dead fiber called
    org/jruby/ext/fiber/ThreadFiber.java:68:in `resume'
    uri:classloader:/jruby/kernel/enumerator.rb:95:in `next'
    uri:classloader:/jruby/kernel/enumerator.rb:17:in `next'
    /Users/kiichi/git/jruby/lib/ruby/stdlib/csv.rb:1316:in `shift'
    /Users/kiichi/git/jruby/test/mri/csv/parse/test_invalid.rb:34:in `test_ignore_invalid_line'

Finished tests in 18.539814s, 48.3824 tests/s, 549.7898 assertions/s.
897 tests, 10193 assertions, 2 failures, 3 errors, 0 skips

ruby -v: jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-04-24 d6fa59fde4 Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [darwin-x86_64]
```

MRI 2.6.6
```
[ 36/897] TestCSV::Parsing#test_malformed_csv = 0.00 s
  1) Failure:
TestCSV::Parsing#test_malformed_csv [/Users/kiichi/git/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[ 48/897] TestCSV::Parsing::DifferentOFS#test_malformed_csv = 0.00 s
  2) Failure:
TestCSV::Parsing::DifferentOFS#test_malformed_csv [/Users/kiichi/git/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[133/897] TestCSVFeatures#test_gzip_reader = 0.00 s
  3) Error:
TestCSVFeatures#test_gzip_reader:
NoMethodError: undefined method `close' for nil:NilClass
    /Users/kiichi/git/jruby/test/mri/csv/test_features.rb:234:in `ensure in test_gzip_reader'
    /Users/kiichi/git/jruby/test/mri/csv/test_features.rb:234:in `test_gzip_reader'

[164/897] TestCSVFeatures::DifferentOFS#test_gzip_reader = 0.00 s
  4) Error:
TestCSVFeatures::DifferentOFS#test_gzip_reader:
NoMethodError: undefined method `close' for nil:NilClass
    /Users/kiichi/git/jruby/test/mri/csv/test_features.rb:234:in `ensure in test_gzip_reader'
    /Users/kiichi/git/jruby/test/mri/csv/test_features.rb:234:in `test_gzip_reader'

Finished tests in 13.108263s, 68.4301 tests/s, 846.1075 assertions/s.
897 tests, 11091 assertions, 2 failures, 2 errors, 0 skips

ruby -v: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
```

**Comment by headius** [comment]
@k77ch7 Huh well that's interesting. I'll look into the extra failure today and also try to figure out why these tests are in MRI's suite if they fail.

**Comment by headius** [comment]
In my case there's even fewer, but we do match MRI except for the dead fiber error.

```
[] ~/projects/jruby $ jruby test/mri/runner.rb test/mri/csv/
Run options: 

# Running tests:

[ 36/897] TestCSV::Parsing#test_malformed_csv = 0.02 s                                          
  1) Failure:
TestCSV::Parsing#test_malformed_csv [/Users/headius/projects/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[ 48/897] TestCSV::Parsing::DifferentOFS#test_malformed_csv = 0.01 s                                    
  2) Failure:
TestCSV::Parsing::DifferentOFS#test_malformed_csv [/Users/headius/projects/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[472/897] TestCSVParseInvalid#test_ignore_invalid_line = 0.01 s                                                          
  3) Error:
TestCSVParseInvalid#test_ignore_invalid_line:
FiberError: dead fiber called
    org/jruby/ext/fiber/ThreadFiber.java:68:in `resume'
    uri:classloader:/jruby/kernel/enumerator.rb:95:in `next'
    uri:classloader:/jruby/kernel/enumerator.rb:17:in `next'
    /Users/headius/projects/jruby/lib/ruby/stdlib/csv.rb:1316:in `shift'
    /Users/headius/projects/jruby/test/mri/csv/parse/test_invalid.rb:34:in `test_ignore_invalid_line'

Finished tests in 7.036608s, 127.4762 tests/s, 1448.8515 assertions/s.                                                         
897 tests, 10195 assertions, 2 failures, 1 errors, 0 skips

ruby -v: jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-04-24 d6fa59fde4 OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-b10 +jit [darwin-x86_64]

[] ~/projects/jruby $ rvm ruby-2.6.5 do ruby test/mri/runner.rb test/mri/csv
Run options: 

# Running tests:

[ 36/897] TestCSV::Parsing#test_malformed_csv = 0.00 s                                          
  1) Failure:
TestCSV::Parsing#test_malformed_csv [/Users/headius/projects/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

[ 48/897] TestCSV::Parsing::DifferentOFS#test_malformed_csv = 0.00 s                                    
  2) Failure:
TestCSV::Parsing::DifferentOFS#test_malformed_csv [/Users/headius/projects/jruby/test/mri/csv/test_csv_parsing.rb:171]:
<"Unquoted fields do not allow \\r or \\n (line 4)."> expected but was
<"Unquoted fields do not allow new line <\"\\r\"> in line 4.">.

Finished tests in 1.410111s, 636.1201 tests/s, 7866.7566 assertions/s.                                                         
897 tests, 11093 assertions, 2 failures, 0 errors, 0 skips

ruby -v: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
```

**Comment by headius** [comment]
Trivial repro of the remaining failure:

```ruby
x = CSV.new("aaa\nbb\"b\nggg")
p x.shift
x.shift rescue puts $!
p x.shift
```

CSV eagerly parses the first line, so it must be valid. The second line gets parsed once we shift again, but fails (as expected) with `MalformedCSVError`. This bubbles out of the fiber and terminates it, leading to a `dead fiber` error for the final shift.

In CRuby, the final "ggg" line is returned for the last shift.

It seems like we're supposed to bubble the error out without killing the fiber, somehow. Could be a bug in how we handle exceptions raised in a fiber.

**Comment by headius** [comment]
I believe the final failure is due to a bug in our Enumerator logic.

Based on this example running in CRuby, it appears that if the enumerator fiber terminates and you go back in, it should be re-started:

```
$ rvm ruby-2.6.5 do ruby -e 'Enumerator.new { 2.times {|i| raise i.to_s } }.tap {|f| 2.times { f.next rescue puts $!.message }}'
0
0
```

By contrast, on JRuby the second call to `next` produces the `dead fiber` error.

**Comment by headius** [comment]
I am skeptical that this behavior is expected and I have filed https://bugs.ruby-lang.org/issues/16816

Meanwhile, since this is the existing behavior, I have created #6190 which I will merge shortly. This fixes the last failure.

**Comment by headius** [comment]
With #6190 merged, we now match CRuby's errors. @k77ch7 Thank you for the help!
