### ISSUE TITLE
Lambda fails to arity check incoming single-arg array in JIT

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6165]
The arity-checking logic for lambdas differs between the unoptimized startup interpreter and the optimized full interpreter or JIT modes. As a result, the following code does not error when it should:

```ruby
[[1, 2, 3]].collect(&->(a, b, c) {[a, b, c]})
```

Along the optimized paths for this lambda block, the logic is splatting the incoming array into the arguments before checking arity. The simple interpreter just checks arity and properly errors.

I tried a simple fix for this by deleting the `toAry` logic in IRRuntimeHelpers.prepareBlockArgs, but it led to the following error:

```
Error: test_zip(TestEnumerator): ArgumentError: wrong number of arguments (given 1, expected 2)
/home/travis/build/jruby/jruby/test/jruby/test_enumerator.rb:-1:in `block in test_zip'
/home/travis/build/jruby/jruby/test/jruby/test_enumerator.rb:253:in `each'
org/jruby/RubyEnumerable.java:1275:in `each_with_index'
org/jruby/RubyEnumerator.java:396:in `each'
org/jruby/RubyEnumerable.java:1936:in `zip'
/home/travis/build/jruby/jruby/test/jruby/test_enumerator.rb:272:in `test_zip'
     269: 
     270:     a = []
     271:     cond = ->((x, i), y) { a << [x, y, i] }
  => 272:     @obj.each_with_index.zip([:a, :b, :c], &cond)
     273:     assert_equal([[1,:a,0],[2,:b,1],[3,:c,2],[1,nil,3],[2,nil,4]], a)
     274: 
     275:     a = []
```

This is not a new issue but it came up due to a new test in CRuby 2.6's test suite. I will tag it for now to get the 2.6 branch merged, but we need to unify how all these dispatch paths work.

**Comment by headius** [comment]
Note that the simple interpreter uses RubyProc.prepareArgs to set up the argument list, which does no splatting before lambda arity check. However slightly different logic is used along different yield paths, and the second example above (which fails after my patch) does things differently.

**Comment by headius** [comment]
The bad fix also led to dozens of failures in enumerator logic, of the following forms:

```
13) Error:
TestEnumerable#test_max_by:
ArgumentError: wrong number of arguments (given 1, expected 2)
    /home/travis/build/jruby/jruby/test/mri/ruby/test_enum.rb:13:in `block in test_max_by'
    /home/travis/build/jruby/jruby/test/mri/ruby/test_enum.rb:13:in `each'
    org/jruby/RubyEnumerable.java:1275:in `each_with_index'
    org/jruby/RubyEnumerator.java:396:in `each'
    org/jruby/RubyEnumerable.java:1475:in `max_by'
    /home/travis/build/jruby/jruby/test/mri/ruby/test_enum.rb:511:in `test_max_by'
```

**Comment by skunkworker** [comment]
@headius I may be out on a limb here but this may be related to a doublesplat bug that I found https://github.com/jruby/jruby/issues/6255
