### ISSUE TITLE
Sporadic failure in tcp_server_loop on JDK11+

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6381]
The tcp_server_loop spec fails sporadically on Travis under JDK 11 or higher, with errors similar to this:

```
1)
Socket.tcp_server_loop when a connection is available yields a Socket and an Addrinfo ERROR
NoMethodError: undefined method `each' for nil:NilClass
/home/travis/build/jruby/jruby/lib/ruby/stdlib/socket.rb:813:in `block in accept_loop'
org/jruby/RubyKernel.java:1524:in `loop'
/home/travis/build/jruby/jruby/lib/ruby/stdlib/socket.rb:811:in `accept_loop'
/home/travis/build/jruby/jruby/lib/ruby/stdlib/socket.rb:864:in `block in tcp_server_loop'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/fixtures/classes.rb:144:in `block in tcp_server_sockets'
/home/travis/build/jruby/jruby/lib/ruby/stdlib/socket.rb:788:in `tcp_server_sockets'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/fixtures/classes.rb:142:in `tcp_server_sockets'
/home/travis/build/jruby/jruby/lib/ruby/stdlib/socket.rb:863:in `tcp_server_loop'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/socket/tcp_server_loop_spec.rb:26:in `block in <main>'
```

We need to either fix this or mark tag the spec as unreliable on those JDK versions.

**Comment by headius** [comment]
Example failing build:

https://travis-ci.org/github/jruby/jruby/jobs/722742575#L1090

**Comment by headius** [comment]
Other failures likely from the same root cause:

```
1)
Socket.tcp_server_loop when a connection is available yields a Socket and an Addrinfo ERROR
RuntimeError: Did not succeed within 20.0 seconds
/home/travis/build/jruby/jruby/spec/ruby/library/socket/fixtures/classes.rb:79:in `loop_with_timeout'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/socket/tcp_server_loop_spec.rb:36:in `block in <main>'
org/jruby/RubyBasicObject.java:2695:in `instance_exec'
org/jruby/RubyArray.java:4556:in `all?'
org/jruby/RubyArray.java:1815:in `each'
org/jruby/RubyArray.java:1815:in `each'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/socket/tcp_server_loop_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1078:in `load'
org/jruby/RubyBasicObject.java:2695:in `instance_exec'
org/jruby/RubyArray.java:1815:in `each'
2)
An exception occurred during: after :each
Socket.tcp_server_loop when a connection is available yields a Socket and an Addrinfo ERROR
Errno::EBADF: Bad file descriptor - No message available
org/jruby/ext/socket/RubySocket.java:694:in `close'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/socket/tcp_server_loop_spec.rb:19:in `block in <main>'
org/jruby/RubyBasicObject.java:2695:in `instance_exec'
org/jruby/RubyArray.java:4556:in `all?'
org/jruby/RubyArray.java:1815:in `each'
org/jruby/RubyArray.java:1815:in `each'
/home/travis/build/jruby/jruby/spec/ruby/library/socket/socket/tcp_server_loop_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1078:in `load'
org/jruby/RubyBasicObject.java:2695:in `instance_exec'
org/jruby/RubyArray.java:1815:in `each'
```
