### ISSUE TITLE
Error --> can't modify frozen OpenSSL::SSL::SSLContext

### ISSUE THREAD

**Issue by mistergibson** [jruby/jruby#6453]
I get this error connecting to a matrix server over https. Mind you, I have spoken with the developers of matrix-sdk and they indicate that at no time do they modify the open SSL Context. I can only conclude this is a JRuby bug at this point.

**Environment Information**
  
Provide at least:
* JRuby version "9.2.13.0"
* Linux Mint 19.3

Other relevant info you may wish to add:
matrix-sdk gem
rufus-scheduler gem

**Expected Behavior**

Use the defined SSL Context without error.

**Actual Behavior**

E, [2020-10-29T03:52:17.013797 #22800] ERROR -- : can't modify frozen OpenSSL::SSL::SSLContext
Backtrace: /opt/jruby/lib/ruby/stdlib/jopenssl23/openssl/ssl.rb:145:in `block in set_params'
org/jruby/RubyHash.java:1415:in `each'
/opt/jruby/lib/ruby/stdlib/jopenssl23/openssl/ssl.rb:145:in `set_params'
/opt/jruby/lib/ruby/stdlib/net/http.rb:975:in `connect'
/opt/jruby/lib/ruby/stdlib/net/http.rb:1548:in `begin_transport'
/opt/jruby/lib/ruby/stdlib/net/http.rb:1500:in `transport_request'
/opt/jruby/lib/ruby/stdlib/net/http.rb:1474:in `request'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:298:in `block in request'
org/jruby/RubyKernel.java:1442:in `loop'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:290:in `request'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/protocols/cs.rb:67:in `sync'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:499:in `block in sync'
org/jruby/RubyKernel.java:1442:in `loop'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:497:in `sync'
/home/mistergibson/Documents/Development/gxg-framework/lib/gxg/net_clients.rb:4547:in `listen_for_events'
(irb):19:in `block in evaluate'
/home/mistergibson/Documents/Development/gxg-framework/lib/gxg/gxg_events.rb:514:in `block in every'
/opt/jruby/lib/ruby/gems/shared/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:223:in `do_call'
/opt/jruby/lib/ruby/gems/shared/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:267:in `trigger_now'
/opt/jruby/lib/ruby/gems/shared/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:312:in `block in start_work_thread'
/opt/jruby/lib/ruby/gems/shared/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:311:in `block in start_work_thread'
org/jruby/RubyKernel.java:1442:in `loop'
/opt/jruby/lib/ruby/gems/shared/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:301:in `block in start_work_thread'

**Comment by mistergibson** [comment]
Further --> this error seems related. Might help you narrow it down:

E, [2020-10-29T15:18:19.868179 #19971] ERROR -- : Unhandled Java::JavaLang::NullPointerException raised in background listener
E, [2020-10-29T15:18:19.868768 #19971] ERROR -- : 
org.jruby.ext.openssl.SSLContext.createSSLEngine(SSLContext.java:635)
org.jruby.ext.openssl.SSLSocket.ossl_ssl_setup(SSLSocket.java:221)
org.jruby.ext.openssl.SSLSocket.connectImpl(SSLSocket.java:287)
org.jruby.ext.openssl.SSLSocket.connect_nonblock(SSLSocket.java:276)
org.jruby.ext.openssl.SSLSocket$INVOKER$i$connect_nonblock.call(SSLSocket$INVOKER$i$connect_nonblock.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:191)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:178)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:396)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:205)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:121)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:108)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:354)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:143)
opt.jruby.lib.ruby.stdlib.net.http.invokeOther2:connect(/opt/jruby/lib/ruby/stdlib/net/http.rb:1543)
opt.jruby.lib.ruby.stdlib.net.http.RUBY$method$begin_transport$0(/opt/jruby/lib/ruby/stdlib/net/http.rb:1543)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:106)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
opt.jruby.lib.ruby.stdlib.net.http.invokeOther13:begin_transport(/opt/jruby/lib/ruby/stdlib/net/http.rb:1500)
opt.jruby.lib.ruby.stdlib.net.http.RUBY$method$transport_request$0(/opt/jruby/lib/ruby/stdlib/net/http.rb:1500)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:106)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:386)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:184)
opt.jruby.lib.ruby.stdlib.net.http.invokeOther11:transport_request(/opt/jruby/lib/ruby/stdlib/net/http.rb:1474)
opt.jruby.lib.ruby.stdlib.net.http.RUBY$method$request$0(/opt/jruby/lib/ruby/stdlib/net/http.rb:1474)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:375)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:174)
opt.jruby.lib.ruby.gems.shared.gems.matrix_sdk_minus_2_dot_1_dot_3.lib.matrix_sdk.api.invokeOther28:request(/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:298)
opt.jruby.lib.ruby.gems.shared.gems.matrix_sdk_minus_2_dot_1_dot_3.lib.matrix_sdk.api.RUBY$block$request$4(/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:298)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:148)
org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:66)
org.jruby.runtime.Block.yieldSpecific(Block.java:153)
org.jruby.RubyKernel.loop(RubyKernel.java:1442)
org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:151)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:160)
opt.jruby.lib.ruby.gems.shared.gems.matrix_sdk_minus_2_dot_1_dot_3.lib.matrix_sdk.api.invokeOther105:loop(/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:290)
opt.jruby.lib.ruby.gems.shared.gems.matrix_sdk_minus_2_dot_1_dot_3.lib.matrix_sdk.api.RUBY$method$request$0(/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:290)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)
org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:137)
org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:70)
org.jruby.runtime.Block.yieldSpecific(Block.java:153)
org.jruby.RubyKernel.loop(RubyKernel.java:1442)
org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:93)
org.jruby.ir.instructions.CallBase.interpret(CallBase.java:546)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:375)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:174)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:137)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:60)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)
org.jruby.runtime.Block.call(Block.java:139)
org.jruby.RubyProc.call(RubyProc.java:318)
org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
java.lang.Thread.run(Thread.java:748)

**Comment by mistergibson** [comment]
From the matrix-sdk developer:

"And the line it's erroring on is response = http.request request, which doesn't make any sense either
The only thought I have about it is if the JRuby implementation doesn't support re-using request objects, as in sending the same request more than once
Because the API will retry a request if it hits a rate limit response"

**Comment by headius** [comment]
@mistergibson I think the note about "re-using request objects" is likely the biggest clue; because of the way we use Bouncy Castle to implement the OpenSSL functionality, it's not possible for us to reuse things like SSL contexts... they're tied to the original connection.

Testing is a bit weak here, but if you can provide a reproducible script or repository that we can run to see these errors, it would help us move forward.

FYI several of us are in the US and will be mostly dark until after the election on Tuesday, but I wanted to jump in and say that we're interested in getting this fixed!

**Comment by mistergibson** [comment]
I don't have a repo for replication, but this should work: (Under JRuby 9.2.13.0):

require 'matrix-sdk'
client = MatrixSdk::Client.new(URI.parse("https://the-server.org"), user_id: "the-user")
client.login("the-user", "password")
room = client.public_rooms[0]
room.send_text("No matter how you slice it, it still comes out baloney.")
--> The error occurs 100% of the time.

**Comment by headius** [comment]
@mistergibson Thanks, that is helpful!

**Comment by kares** [comment]
based on the trace, this is the same as https://github.com/jruby/jruby/issues/6453 which has been resolved in jruby-openssl **0.15.6**
