### ISSUE TITLE
Unhandled IOError --> SSLSocket.java:893:in `sysread_nonblock'

### ISSUE THREAD

**Issue by mistergibson** [jruby/jruby#6455]
**Environment Information**

    JRuby version "9.2.13.0"
    Linux Mint 19.3

matrix-sdk 2.1.3 gem

**Expected Behavior**
send text to chatroom

**Actual Behavior**

To Reproduce:

require 'matrix-sdk'
client = MatrixSdk::Client.new(URI.parse("https://the-server.org"), user_id: "the-user")
client.login("the-user", "password")
room = client.public_rooms[0]
room.send_text("Test")
=> {:event_id=>"$TVtcoEr2cXc7yeHbTaMXFGRYp08I1bxp-l9m-_gsIlY"}
E, [2020-10-31T09:43:35.722300 #9012] ERROR -- : Unhandled IOError raised in background listener
E, [2020-10-31T09:43:36.020989 #9012] ERROR -- : Unsupported record version Unknown-121.112
org/jruby/ext/openssl/SSLSocket.java:893:in `sysread_nonblock'
/opt/jruby/lib/ruby/stdlib/jopenssl23/openssl/buffering.rb:182:in `read_nonblock'
/opt/jruby/lib/ruby/stdlib/net/protocol.rb:175:in `rbuf_fill'
/opt/jruby/lib/ruby/stdlib/net/protocol.rb:157:in `readuntil'
/opt/jruby/lib/ruby/stdlib/net/protocol.rb:167:in `readline'
/opt/jruby/lib/ruby/stdlib/net/http/response.rb:40:in `read_status_line'
/opt/jruby/lib/ruby/stdlib/net/http/response.rb:29:in `read_new'
/opt/jruby/lib/ruby/stdlib/net/http.rb:1504:in `block in transport_request'
org/jruby/RubyKernel.java:1189:in `catch'
/opt/jruby/lib/ruby/stdlib/net/http.rb:1501:in `transport_request'
/opt/jruby/lib/ruby/stdlib/net/http.rb:1474:in `request'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:282:in `block in request'
org/jruby/RubyKernel.java:1442:in `loop'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/api.rb:273:in `request'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/protocols/cs.rb:67:in `sync'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:499:in `block in sync'
org/jruby/RubyKernel.java:1442:in `loop'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:497:in `sync'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:533:in `listen_forever'
/opt/jruby/lib/ruby/gems/shared/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:450:in `block in start_listener_thread'

**Comment by headius** [comment]
Seems like a missing feature we can implement with `read_nonblock` possibly. Need to look into the semantics of how a `sysread` operates in the presence of an SSL wrapper.

**Comment by kares** [comment]
The `sysread_nonblock` exception handling has been improved in https://github.com/jruby/jruby-openssl/pull/351 — the `exception` flag is now properly propagated through the read path so that `read_nonblock(..., exception: false)` returns `:wait_readable` instead of throwing.

The specific 'Unsupported record version' error in this report is an `SSLException` from the JSSE engine (likely a TLS version mismatch or corrupted data), which is a different path — but the overall exception handling in the nonblock read path is much more robust now.

**Comment by headius** [comment]
We should finally be able to fix this with jruby/jruby-openssl#351 so we're going to go for it.

**Comment by headius** [comment]
I believe this is fixed by the jruby-openssl upgrade to 0.16.0.
