### ISSUE TITLE
bundle install on Windows fails with NotImplementedError: stat.st_gid unsupported or native support failed to load

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6458]
Happens on jruby-head with Bundler 2.
Maybe a recent change caused this? I never saw it before.

https://github.com/ruby/setup-ruby/runs/1378857770?check_suite_focus=true
https://github.com/ruby/setup-ruby/runs/1378857565?check_suite_focus=true
```
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-head\bin\bundle.bat config --local path vendor/bundle"
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-head\bin\bundle.bat lock"
  Fetching gem metadata from https://rubygems.org/.
  Resolving dependencies...
  Writing lockfile to D:/a/setup-ruby/setup-ruby/Gemfile.lock
  Cache key: setup-ruby-bundler-cache-v2-windows-latest-jruby-head-Gemfile.lock-095290c5236b11deb5dd04d5add69dccaac6031c6c7519ebe74c6a916382b678
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-head\bin\bundle.bat install --jobs 4"
```  
  ## Backtrace
  
  ```
  NotImplementedError: stat.st_gid unsupported or native support failed to load; see https://github.com/jruby/jruby/wiki/Native-Libraries
    org/jruby/RubyFileStat.java:301:in `gid'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1433:in `copy_metadata'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:500:in `block in copy_entry'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1518:in `wrap_traverse'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:494:in `copy_entry'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:551:in `block in mv'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1588:in `block in fu_each_src_dest'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1604:in `fu_each_src_dest0'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1586:in `fu_each_src_dest'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:539:in `mv'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/compact_index_client/updater.rb:72:in `block in update'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/shared_helpers.rb:103:in `filesystem_access'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/compact_index_client/updater.rb:71:in `block in update'
    D:/jruby-head/lib/ruby/stdlib/tmpdir.rb:93:in `mktmpdir'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/compact_index_client/updater.rb:31:in `update'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/compact_index_client.rb:98:in `update'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:75:in `available?'
    org/jruby/RubyMethod.java:131:in `call'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:16:in `block in available?'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/fetcher.rb:162:in `use_api'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `block in api_fetchers'
    org/jruby/RubyArray.java:2676:in `select'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `api_fetchers'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:393:in `block in remote_specs'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/index.rb:11:in `build'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:392:in `remote_specs'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:88:in `specs'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/lazy_specification.rb:75:in `__materialize__'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/spec_set.rb:83:in `block in materialize'
    org/jruby/RubyArray.java:2629:in `map!'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/definition.rb:158:in `resolve_remotely!'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/installer.rb:303:in `resolve_if_needed'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/installer.rb:84:in `block in run'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/process_lock.rb:12:in `block in lock'
    org/jruby/RubyIO.java:1160:in `open'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/process_lock.rb:9:in `lock'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/installer.rb:73:in `run'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/installer.rb:25:in `install'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/cli/install.rb:66:in `run'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/cli.rb:256:in `block in install'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/settings.rb:124:in `temporary'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/cli.rb:255:in `install'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/exe/bundle:46:in `block in <main>'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
    D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.1.4/exe/bundle:34:in `<main>'
    org/jruby/RubyKernel.java:1083:in `load'
    D:\jruby-head\bin\bundle:23:in `<main>'
  ```
  
  ## Environment
  
  ```
  Bundler       2.1.4
    Platforms   ruby, universal-java-1.8
  Ruby          2.6.5p0 (2020-10-27 revision 67812) [java]
    Full Path   D:/jruby-head/bin/jruby.exe
    Config Dir  D:/jruby-head/etc
  RubyGems      3.0.6
    Gem Home    D:/a/setup-ruby/setup-ruby/vendor/bundle/jruby/2.6.0
    Gem Path    D:/a/setup-ruby/setup-ruby/vendor/bundle/jruby/2.6.0
    User Home   C:\Users\runneradmin
    User Path   C:\Users\runneradmin/.gem/jruby/2.6.0
    Bin Dir     D:/a/setup-ruby/setup-ruby/vendor/bundle/jruby/2.6.0/bin
  OpenSSL       
    Compiled    JRuby-OpenSSL 0.10.5
    Loaded      JRuby-OpenSSL 0.10.5
    Cert File   C:\Program Files\Java\jdk8u265-b01\jre/lib/security/cacerts
    Cert Dir    C:\Program Files\Java\jdk8u265-b01\jre/lib/security
  Tools         
    Git         2.29.0.windows.1
    RVM         not installed
    rbenv       not installed
    chruby      not installed
  ```
  
  ## Bundler Build Metadata
  
  ```
  Built At          2020-01-05
  Git SHA           32a4159325
  Released Version  true
  ```
  
  ## Bundler settings
  
  ```
  path
    Set for your local app (D:/a/setup-ruby/setup-ruby/.bundle/config): "vendor/bundle"
  jobs
    Set for your local app (D:/a/setup-ruby/setup-ruby/.bundle/config): 4
  ```
  
  ## Gemfile
  
  ### Gemfile
  
  ```ruby
  # Used for testing
  source 'https://rubygems.org'
  
  gem "rake"
  gem "path"
  gem "json", "2.2.0"
  ```
  
  ### Gemfile.lock
  
  ```
  GEM
    remote: https://rubygems.org/
    specs:
      json (2.2.0-java)
      path (2.0.1)
      rake (13.0.1)
  
  PLATFORMS
    java
  
  DEPENDENCIES
    json (= 2.2.0)
    path
    rake
  
  BUNDLED WITH
     2.1.4
  ```

**Comment by eregon** [comment]
Executing `bundle lock` before `bundle install` seems to be what triggers this.
So before my change in setup-ruby to use `bundle lock` first, it worked fine:
https://github.com/eregon/setup-ruby/runs/1379034164?check_suite_focus=true

After the change to `bundle lock` before `bundle install`, it fails, but only on `jruby-head` on Windows, JRuby 9.1.17.0 and 9.2.13.0 work fine on Windows:
https://github.com/eregon/setup-ruby/runs/1379079376?check_suite_focus=true

**Comment by eregon** [comment]
`bundle lock` is needed to properly cache on GitHub Actions (https://github.com/ruby/setup-ruby/issues/105), so it would be great if this could be fixed quickly.

**Comment by eregon** [comment]
Using `JRUBY_OPTS=-Xnative.verbose=true` shows `Successfully loaded native POSIX impl.` (on Windows):
https://github.com/eregon/setup-ruby/runs/1379104913?check_suite_focus=true#step:3:34
