### ISSUE TITLE
SocketError when sending Unix socket datagrams

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#6504]
when I run the simple script below, it works in MRI, but raises `SocketError (No message available)` in JRuby 9.2.14.0 on Ubuntu 18.04. It would be awesome to get this working so I could have my JRuby daemons communicate with systemd

```ruby
Addrinfo.unix("/run/systemd/notify", :DGRAM).connect do |s|
  s.close_on_exec = true
  s.write("READY=1")
end
```

here's the stack trace:
```
Traceback (most recent call last):
        9: from /home/web/.rvm/rubies/jruby-9.2.14.0/bin/irb:13:in `<main>'
        8: from org/jruby/RubyKernel.java:1189:in `catch'
        7: from org/jruby/RubyKernel.java:1189:in `catch'
        6: from org/jruby/RubyKernel.java:1442:in `loop'
        5: from org/jruby/RubyKernel.java:1048:in `eval'
        4: from (irb):2:in `evaluate'
        3: from /home/web/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/socket.rb:139:in `connect'
        2: from /home/web/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/socket.rb:66:in `connect_internal'
        1: from org/jruby/ext/socket/RubySocket.java:215:in `connect'
SocketError (No message available)
```

**Comment by headius** [comment]
Could you come up with a reproduction that does not depend on systemd?

This may work better on master (9.3) which has better support for Addrinfo.

**Comment by mohamedhafez** [comment]
I tried using master, but got the same error, gives this stack trace:

```
Traceback (most recent call last):
       11: from /home/web/.rvm/rubies/jruby-head/bin/irb:23:in `<main>'
       10: from org/jruby/RubyKernel.java:1049:in `load'
        9: from /home/web/.rvm/rubies/jruby-head/lib/ruby/gems/shared/gems/irb-1.0.0/exe/irb:11:in `<main>'
        8: from org/jruby/RubyKernel.java:1234:in `catch'
        7: from org/jruby/RubyKernel.java:1234:in `catch'
        6: from org/jruby/RubyKernel.java:1504:in `loop'
        5: from org/jruby/RubyKernel.java:1088:in `eval'
        4: from (irb):3:in `evaluate'
        3: from /home/web/.rvm/rubies/jruby-head/lib/ruby/stdlib/socket.rb:139:in `connect'
        2: from /home/web/.rvm/rubies/jruby-head/lib/ruby/stdlib/socket.rb:66:in `connect_internal'
        1: from org/jruby/ext/socket/RubySocket.java:207:in `connect'
SocketError (No message available)
```

Been banging my head against the wall trying to get `netcat` to listen on a unix *datagram* socket for half an hour now, for some reason `nc -lvUu /tmp/mysock` and `nc -lvUus /tmp/mysock`  aren't doing what I expect. 

The systemd socket /run/systemd/notify is always just there listening as a unix datagram socket on Ubuntu and anyone can send to it, sorry I can't seem to come up with a way to reproduce this more generally

**Comment by mohamedhafez** [comment]
It looks like on Ubuntu, `/dev/log` is also a listening unix datagram socket that has nothing to do with systemd, and the same issue occurs there. The following code works on MRI, but not JRuby master (it fails with the same stack trace as above):

```ruby
require 'socket'
Addrinfo.unix("/dev/log", :DGRAM).connect do |s|
  s.close_on_exec = true
  s.write("READY=1")
end
```

**Comment by headius** [comment]
The problem is that we assume dgram sockets are not UNIX sockets and always create an IP DatagramSocket for them here:

https://github.com/jruby/jruby/blob/332dd7a6c9eb32a205765527f60ece06d2892cb2/core/src/main/java/org/jruby/ext/socket/RubySocket.java#L440-L470

We need to have similar family-checking logic in the dgram path here.

**Comment by headius** [comment]
I have added the right pieces to do datagram things with a UnixDatagramChannel but I am not sure the actual channel is doing the right thing. I can connect now but when writing it complains about having no destination. It seems the datagram version of the Unix socket channel is not passing address, maybe?

**Comment by ccutrer** [comment]
I'm working around this for presumably the same use case for now like this:

```ruby
def jnr
  Java::Jnr
end

module SdNotify
  def self.notify(state, unset_env = false)
    sock = ENV["NOTIFY_SOCKET"]

    return nil unless sock

    ENV.delete("NOTIFY_SOCKET") if unset_env

    begin
      addr = jnr.unixsocket.UnixSocketAddress.new(sock)
      channel = jnr.unixsocket.UnixDatagramChannel.open

      channel.send(java.nio.ByteBuffer.wrap(state.to_java_bytes), addr)
    rescue StandardError => e
      raise NotifyError, "#{e.class}: #{e.message}", e.backtrace
    ensure
      channel&.close
    end
  end
end
```

**Comment by mohamedhafez** [comment]
@ccutrer thanks this approach worked for me on 9.4.12.0!
