### ISSUE TITLE
[Ripper] wrong number of arguments (given 1, expected 2) on DOT2/3

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#6524]
**Environment Information**
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2021-01-10 f2d67a75c3 Java HotSpot(TM) 64-Bit Server VM 15.0.1+9-18 on 15.0.1+9-18 +jit [mswin32-x86_64]

**Expected Behavior**
it looks like a missing feature from ruby 2.6 work

https://github.com/jruby/jruby/blob/25e5f422d1c1adea6669f47b50cdf82ee48de952/core/src/main/java/org/jruby/ext/ripper/RipperParser.y#L868

according to ruby sources, ```DOT2``` and ```DOT3``` should take an argument ```new_nil_at``` but it is not implemented

https://github.com/ruby/ruby/blob/7ff0e93f96cc55467d791ebc841f12f9130bf181/parse.y#L11721
https://github.com/ruby/ruby/blob/7ff0e93f96cc55467d791ebc841f12f9130bf181/parse.y#L4391

I'm not familiar with the code, but I hope @enebo will know what to do.

**Actual Behavior**

full backtrace
```
(ArgumentError) wrong number of arguments (given 1, expected 2)
java/lang/Thread.java:1598:in `getStackTrace'
org/jruby/runtime/backtrace/TraceType.java:242:in `getBacktraceData'
org/jruby/runtime/backtrace/TraceType.java:53:in `getBacktrace'
org/jruby/RubyException.java:402:in `captureBacktrace'
org/jruby/exceptions/RaiseException.java:190:in `preRaise'
org/jruby/exceptions/RaiseException.java:65:in `<init>'
org/jruby/exceptions/Exception.java:39:in `<init>'
org/jruby/exceptions/StandardError.java:38:in `<init>'
org/jruby/exceptions/ArgumentError.java:38:in `<init>'
org/jruby/RubyArgumentError.java:56:in `constructThrowable'
org/jruby/RubyException.java:364:in `toThrowable'
org/jruby/exceptions/RaiseException.java:84:in `from'
org/jruby/Ruby.java:4263:in `newRaiseException'
org/jruby/Ruby.java:3600:in `newArgumentError'
org/jruby/runtime/Arity.java:255:in `raiseArgumentError'
org/jruby/ir/runtime/IRRuntimeHelpers.java:581:in `checkArity'
org/jruby/ir/instructions/CheckArityInstr.java:70:in `checkArity'
org/jruby/ir/interpreter/InterpreterEngine.java:410:in `processBookKeepingOp'
org/jruby/ir/interpreter/InterpreterEngine.java:197:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:155:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/ripper/core.rb:79:in `_dispatch_2'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/internal/runtime/methods/AliasMethod.java:84:in `call'
org/jruby/RubyClass.java:822:in `finvoke'
org/jruby/runtime/Helpers.java:530:in `invoke'
org/jruby/ext/ripper/RipperParserBase.java:131:in `dispatch'
org/jruby/ext/ripper/RipperParser.java:2577:in `execute'
org/jruby/ext/ripper/RipperParser.java:1598:in `yyparse'
org/jruby/ext/ripper/RipperParser.java:1489:in `yyparse'
org/jruby/ext/ripper/RipperParserBase.java:80:in `parse'
org/jruby/ext/ripper/RubyRipper.java:347:in `parse'
org/jruby/ext/ripper/RubyRipper$INVOKER$i$0$0$parse.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:831:in `call'
org/jruby/ir/runtime/IRRuntimeHelpers.java:1181:in `instanceSuper'
org/jruby/ir/instructions/InstanceSuperInstr.java:94:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:80:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:123:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/ripper/lexer.rb:79:in `parse'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:110:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:141:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:345:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:80:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:123:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/ripper/lexer.rb:73:in `lex'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:110:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:141:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:345:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/ripper/filter.rb:61:in `parse'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:172:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:571:in `initialize'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:138:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:182:in `call'
org/jruby/RubyClass.java:918:in `newInstance'
org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:349:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:172:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:575:in `parse'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:172:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:87:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/parser/ruby.rb:180:in `initialize'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:66:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:84:in `call'
org/jruby/RubyClass.java:939:in `newInstance'
org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:84:in `call'
org/jruby/ir/instructions/CallBase.java:549:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:87:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/parser.rb:191:in `for'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:66:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:84:in `call'
org/jruby/ir/instructions/CallBase.java:549:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/rdoc.rb:360:in `parse_file'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:172:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:116:in `INTERPRET_BLOCK'
C:/jruby/lib/ruby/stdlib/rdoc/rdoc.rb:416:in `block in parse_files'
org/jruby/runtime/InterpretedIRBlockBody.java:135:in `commonYieldPath'
org/jruby/runtime/IRBlockBody.java:179:in `doYield'
org/jruby/runtime/BlockBody.java:117:in `yield'
org/jruby/runtime/Block.java:188:in `yieldNonArray'
org/jruby/RubyArray.java:2608:in `collectCommon'
org/jruby/RubyArray.java:2622:in `map'
org/jruby/RubyArray$INVOKER$i$0$0$map.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:555:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:328:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:86:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:93:in `callIter'
org/jruby/ir/instructions/CallBase.java:546:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/rdoc.rb:414:in `parse_files'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:371:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:174:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:116:in `INTERPRET_BLOCK'
C:/jruby/lib/ruby/stdlib/rdoc/rubygems_hook.rb:190:in `block in generate'
org/jruby/runtime/InterpretedIRBlockBody.java:135:in `commonYieldPath'
org/jruby/runtime/IRBlockBody.java:172:in `doYield'
org/jruby/runtime/BlockBody.java:108:in `yield'
org/jruby/runtime/Block.java:184:in `yield'
org/jruby/RubyDir.java:445:in `chdir'
org/jruby/RubyDir$INVOKER$s$0$1$chdir.gen:-1:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:207:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:382:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:184:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:191:in `callIter'
org/jruby/ir/interpreter/InterpreterEngine.java:337:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:80:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:123:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/rubygems_hook.rb:189:in `generate'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:110:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:350:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:143:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:345:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:116:in `INTERPRET_BLOCK'
C:/jruby/lib/ruby/stdlib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
org/jruby/runtime/InterpretedIRBlockBody.java:135:in `commonYieldPath'
org/jruby/runtime/IRBlockBody.java:172:in `doYield'
org/jruby/runtime/BlockBody.java:108:in `yield'
org/jruby/runtime/Block.java:184:in `yield'
org/jruby/RubyArray.java:1845:in `each'
org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:555:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:328:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:86:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:93:in `callIter'
org/jruby/ir/instructions/CallBase.java:546:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:87:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rdoc/rubygems_hook.rb:55:in `generation_hook'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:66:in `call'
org/jruby/runtime/MethodBlockBody.java:62:in `call'
org/jruby/runtime/Block.java:143:in `call'
org/jruby/RubyProc.java:299:in `call'
org/jruby/RubyProc$INVOKER$i$call.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:371:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:392:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:205:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:325:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:116:in `INTERPRET_BLOCK'
C:/jruby/lib/ruby/stdlib/rubygems/request_set.rb:323:in `block in install_hooks'
org/jruby/runtime/InterpretedIRBlockBody.java:135:in `commonYieldPath'
org/jruby/runtime/IRBlockBody.java:172:in `doYield'
org/jruby/runtime/BlockBody.java:108:in `yield'
org/jruby/runtime/Block.java:184:in `yield'
org/jruby/RubyArray.java:1845:in `each'
org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:555:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:328:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:86:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:93:in `callIter'
org/jruby/ir/instructions/CallBase.java:546:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:92:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:195:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/request_set.rb:322:in `install_hooks'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:182:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:392:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:205:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:325:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/request_set.rb:221:in `install'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:371:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:174:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:92:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:195:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:212:in `install_gem'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:182:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:392:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:205:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:325:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:116:in `INTERPRET_BLOCK'
C:/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:264:in `block in install_gems'
org/jruby/runtime/InterpretedIRBlockBody.java:135:in `commonYieldPath'
org/jruby/runtime/IRBlockBody.java:172:in `doYield'
org/jruby/runtime/BlockBody.java:108:in `yield'
org/jruby/runtime/Block.java:184:in `yield'
org/jruby/RubyArray.java:1845:in `each'
org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:555:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:328:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:86:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:93:in `callIter'
org/jruby/ir/instructions/CallBase.java:546:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:361:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:80:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:123:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:258:in `install_gems'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:110:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:350:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:143:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:345:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:80:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:123:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:165:in `execute'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:110:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:350:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:143:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:345:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:92:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:195:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/command.rb:321:in `invoke_with_build_args'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:182:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:392:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:205:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:325:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:92:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:195:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/command_manager.rb:184:in `process_args'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:182:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:392:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:205:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:325:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:92:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:195:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/command_manager.rb:148:in `run'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:182:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:392:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:205:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:325:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159:in `INTERPRET_METHOD'
C:/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:59:in `run'
org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:371:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:174:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:96:in `INTERPRET_ROOT'
C:/jruby/bin/jgem:21:in `<main>'
org/jruby/ir/interpreter/Interpreter.java:81:in `execute'
org/jruby/ir/interpreter/Interpreter.java:30:in `execute'
org/jruby/ir/IRTranslator.java:42:in `execute'
org/jruby/Ruby.java:1266:in `runInterpreter'
org/jruby/Ruby.java:2841:in `loadFile'
org/jruby/runtime/load/LibrarySearcher.java:936:in `load'
org/jruby/runtime/load/LibrarySearcher.java:894:in `load'
org/jruby/runtime/load/LoadService.java:322:in `load'
org/jruby/RubyKernel.java:1079:in `loadCommon'
org/jruby/RubyKernel.java:1049:in `load'
org/jruby/RubyKernel$INVOKER$s$load.gen:-1:in `call'
org/jruby/internal/runtime/methods/JavaMethod.java:417:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:371:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:174:in `call'
org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
org/jruby/ir/interpreter/StartupInterpreterEngine.java:72:in `interpret'
org/jruby/ir/interpreter/Interpreter.java:96:in `INTERPRET_ROOT'
gem:4:in `<main>'
org/jruby/ir/interpreter/Interpreter.java:81:in `execute'
org/jruby/ir/interpreter/Interpreter.java:30:in `execute'
org/jruby/ir/IRTranslator.java:42:in `execute'
org/jruby/Ruby.java:1288:in `runInterpreter'
org/jruby/Ruby.java:1292:in `runInterpreter'
org/jruby/Ruby.java:1177:in `runNormally'
org/jruby/Ruby.java:1154:in `runNormally'
org/jruby/Ruby.java:1190:in `runNormally'
org/jruby/Ruby.java:973:in `runFromMain'
org/jruby/Main.java:393:in `doRunFromMain'
org/jruby/Main.java:287:in `internalRun'
org/jruby/Main.java:234:in `run'
org/jruby/Main.java:206:in `main'
```

**Comment by enebo** [comment]
Fixed before:

```text
jruby -rripper -e 'p Ripper.sexp("(2..)")'
[:program, [[:paren, [[:dot2, [:@int, "2", [1, 1]]]]]]]
```

after:

```text
system ~/work/jruby master * 1042% jruby -rripper -e 'p Ripper.sexp("(2..)")'
[:program, [[:paren, [[:dot2, [:@int, "2", [1, 1]], nil]]]]]
```

I think I will need to audit ripper.y against parser.y and finish #6158.

**Comment by ahorek** [comment]
I can confirm your change fixes the error. Thank you
