### ISSUE TITLE
Flaky test failure in rubygems test suite

### ISSUE THREAD

**Issue by deivid-rodriguez** [jruby/jruby#6622]
We sometimes get this error during rubygems test run on jruby: https://github.com/rubygems/rubygems/pull/4464/checks?check_run_id=2129751594. We get this very very rarely (once a month maybe, or even less). 

I mentioned this in https://github.com/jruby/jruby/pull/6533#issuecomment-772794593, where I believe it's suggested that this might be already fixed, just not released. Opening an issue just in case to confirm.

Note that this is a realworld test case where we verify that `gem install rails` works. 

```
$ gem install rails --verbose --backtrace
(...)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `ignored=' for nil:NilClass
	/home/runner/.rubies/jruby-9.2.16.0/lib/ruby/stdlib/rubygems/stub_specification.rb:193:in `to_spec'
	org/jruby/RubyArray.java:2577:in `map'
	/home/runner/.rubies/jruby-9.2.16.0/lib/ruby/stdlib/rubygems/specification.rb:748:in `_all'
	/home/runner/.rubies/jruby-9.2.16.0/lib/ruby/stdlib/rubygems/specification.rb:953:in `each'
	org/jruby/RubyEnumerable.java:1872:in `any?'
	/home/runner/.rubies/jruby-9.2.16.0/lib/ruby/stdlib/rubygems/resolver/activation_request.rb:111:in `installed?'
	/home/runner/.rubies/jruby-9.2.16.0/lib/ruby/stdlib/rubygems/request_set.rb:173:in `block in install'
```

**Expected Behavior**

No errors, just like on other rubies.

**Actual Behavior**

A crash.

Thanks!

**Comment by deivid-rodriguez** [comment]
Never saw this again, so closing!
