### ISSUE TITLE
Intermittent NPE in interrupted read spec

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6669]
The following failure was seen in one build for #6666 but appears to be intermittent:

```
IO#read raises IOError when stream is closed by another thread FAILED
Expected #<Java::JavaLang::NullPointerException: > (Java::JavaLang::NullPointerException)
to be kind of IOError
/home/travis/build/jruby/jruby/spec/ruby/core/io/read_spec.rb:322:in `block in <main>'
org/jruby/RubyBasicObject.java:2668:in `instance_exec'
org/jruby/RubyArray.java:4648:in `all?'
org/jruby/RubyArray.java:1852:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/io/read_spec.rb:178:in `<main>'
org/jruby/RubyKernel.java:1049:in `load'
org/jruby/RubyBasicObject.java:2668:in `instance_exec'
org/jruby/RubyArray.java:1852:in `each'
```

This spec tests whether a blocking read interrupted by the stream closing raises IOError. There are a number of possible explanations since this involves concurrent threads mucking about with the same IO object. I do not have a full stack trace and have not been able to reproduce this.

**Comment by ntkme** [comment]
@headius I got similar intermittent `NullPointerException` when reading from a stream that is closed in another thread. In my case, I'm running a child process and polling stdout of child process. When the child process exits and closes the stdout stream, the polling thread may occasionally crash with `NullPointerException` instead of raising an `IOError`.

```
warning: thread "Ruby-0-Thread-3: /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/dispatcher.rb:17" terminated with exception (report_on_exception is true):
java.lang.NullPointerException
	at org.jruby.util.io.PosixShim.read(PosixShim.java:158)
	at org.jruby.util.io.OpenFile$2.run(OpenFile.java:1325)
	at org.jruby.util.io.OpenFile$2.run(OpenFile.java:1316)
	at org.jruby.RubyThread.executeReadWrite(RubyThread.java:1748)
	at org.jruby.util.io.OpenFile.readInternal(OpenFile.java:1384)
	at org.jruby.util.io.OpenFile.fillbuf(OpenFile.java:1295)
	at org.jruby.RubyIO.getByte(RubyIO.java:2882)
	at org.jruby.RubyIO.getbyte(RubyIO.java:2859)
	at org.jruby.RubyIO.readbyte(RubyIO.java:2896)
	at org.jruby.RubyIO$INVOKER$i$0$0$readbyte.call(RubyIO$INVOKER$i$0$0$readbyte.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.varint.invokeOther0:readbyte(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/varint.rb:14)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.varint.RUBY$block$read$1(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/varint.rb:14)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:72)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:157)
	at org.jruby.RubyKernel.loop(RubyKernel.java:1507)
	at org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:152)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:161)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.varint.invokeOther6:loop(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/varint.rb:13)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.varint.RUBY$method$read$0(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/varint.rb:13)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:165)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:185)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:173)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.compiler.invokeOther1:read(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/compiler.rb:56)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.compiler.RUBY$block$read$1(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/compiler.rb:56)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:72)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:157)
	at org.jruby.ext.thread.Mutex.synchronize(Mutex.java:171)
	at org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize.call(Mutex$INVOKER$i$0$0$synchronize.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:152)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:161)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.compiler.invokeOther5:synchronize(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/compiler.rb:55)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.compiler.RUBY$method$read$0(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/compiler.rb:55)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:152)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.dispatcher.invokeOther2:read(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/dispatcher.rb:19)
	at Users.runner.work.sass_minus_embedded_minus_host_minus_ruby.sass_minus_embedded_minus_host_minus_ruby.lib.sass.embedded.dispatcher.RUBY$block$initialize$0(/Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/dispatcher.rb:19)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
	at org.jruby.runtime.MixedModeIRBlockBody.yieldDirect(MixedModeIRBlockBody.java:111)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:72)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:157)
	at org.jruby.RubyKernel.loop(RubyKernel.java:1507)
	at org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:560)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:94)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:546)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)
	at org.jruby.runtime.Block.call(Block.java:143)
	at org.jruby.RubyProc.call(RubyProc.java:309)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by headius** [comment]
@ntkme Thank you for that stack trace! Yes, this does indeed seem to be a similar problem. The failing line appears to be this one:

```java
int read = fd.chRead.read(buffer);
```

There are two things that could be null there, `fd`, and `chRead`, but the latter should have been detected earlier in the read logic (if it were null, we would not attempt to read, and it never gets cleared to null again). So I think the problem is as follows:

* `OpenFile.READ_TASK` acquires a reference to the `fd` here: https://github.com/jruby/jruby/blob/00d9bcbc7dbef6da08f101ea339bd4a00f252f32/core/src/main/java/org/jruby/util/io/OpenFile.java#L1319
* While the stream should be locked by the current thread at this point, it may have been closed and nulled out prior to this code.
* No logic exists in this path to ensure that the `fd` is non-null, so it blows up when we proceed to try to access the `Channel` objects it would reference.

I believe we can produce a better error here by checking again whether `fd` is null and raising an appropriate `IOError` for that case.
