### ISSUE TITLE
Remaining Zeitwerk fixes

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6781]
In #5638 we were tracking our pass rate on the Zeitwerk test suite, which required the load service work from #5764. Most of that suite is now passing, with the following three tests the only failures:

```
Failure:
TestRubyCompatibility#test_absolute_paths_passed_to_require_end_up_in__LOADED_FEATURES_as_is [/Users/headius/projects/zeitwerk/test/lib/zeitwerk/test_ruby_compatibility.rb:50]
Minitest::Assertion: Expected false to be truthy.

Error:
TestExplicitNamespace#test_explicit_namespaces_enable_the_tracer_until_loaded:
NameError: uninitialized constant TestExplicitNamespace::Hotel
    org/jruby/RubyModule.java:3942:in `const_missing'
    /Users/headius/projects/zeitwerk/test/lib/zeitwerk/test_explicit_namespace.rb:155:in `block in test_explicit_namespaces_enable_the_tracer_until_loaded'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:82:in `block in with_setup'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:61:in `block in with_files'
    org/jruby/RubyDir.java:419:in `chdir'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:54:in `with_files'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:76:in `with_setup'
    /Users/headius/projects/zeitwerk/test/lib/zeitwerk/test_explicit_namespace.rb:153:in `block in test_explicit_namespaces_enable_the_tracer_until_loaded'

Error:
TestExplicitNamespace#test_the_tracer_handles_singleton_classes:
NameError: uninitialized constant TestExplicitNamespace::Hotel
    org/jruby/RubyModule.java:3942:in `const_missing'
    /Users/headius/projects/zeitwerk/test/lib/zeitwerk/test_explicit_namespace.rb:200:in `block in test_the_tracer_handles_singleton_classes'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:82:in `block in with_setup'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:61:in `block in with_files'
    org/jruby/RubyDir.java:419:in `chdir'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:54:in `with_files'
    /Users/headius/projects/zeitwerk/test/support/loader_test.rb:76:in `with_setup'
    /Users/headius/projects/zeitwerk/test/lib/zeitwerk/test_explicit_namespace.rb:198:in `block in test_the_tracer_handles_singleton_classes'
```

I'm moving these last three to a separate issue for 9.3.1.

**Comment by headius** [comment]
Bump. I have not checked this in a long time because nobody is reported issues, but we are still not in the zeitwerk CI and if there are any remaining issues we should fix them. 

cc @fxn

**Comment by fxn** [comment]
Hey @headius!

First, the current version of Zeitwerk requires Ruby 3.2, because it uses `Module#const_added`.

Now, I tried

```
% ruby -v
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 Java HotSpot(TM) 64-Bit Server VM 23+37-2369 on 23+37-2369 +jit [arm64-darwin
```

with the previous version and there are several failures in these files:

```
test/lib/zeitwerk/test_conflicting_directory.rb
test/lib/zeitwerk/test_private_constants.rb
test/lib/zeitwerk/test_ruby_compatibility.rb
test/lib/zeitwerk/test_utf8.rb
```

Those are unrelated to the refactor using `const_added`, so if you'd like to dig into them, reproduction is easy. You checkout the repo and `git checkout v2.6`. Then

```
% bin/test test/lib/zeitwerk/test_private_constants.rb
```

for example.

If you want to concentrate on one test throw `focus` just before its definition and run `bin/test` without arguments.

I believe you'll quickly see what is not working (e.g., you may realize `Module#autoload` may not be checking if the constant is private and the reference was qualified, in which case it should not resolve at that point in the lookup). However, happy to help understanding them.

**Comment by bolshakov** [comment]
I'm looking at the history of milestones changes and wondering whether we can ever expect compatibility

**Comment by headius** [comment]
@bolshakov Me too! Of course I'm one of only a few folks working on JRuby right now, so it's tough to find time to get these tests green.

Do you have a specific issue affecting you, or just curious about the status of Zeitwerk on JRuby? I just ran Zeitwerk master against JRuby 10 and it seems to have degraded a bit:

```
461 tests, 1061 assertions, 9 failures, 19 errors, 0 skips
```

If you'd like to help, I can give you some guidance!

**Comment by headius** [comment]
@fxn I'm looking into this test, which is perhaps at the root of problems:

```
Error:
TestEagerLoad#test_eager_loads_gems:
NameError: uninitialized constant MyGem::Foo
    org/jruby/RubyModule.java:4864:in 'const_missing'
    test/tmp/my_gem.rb:7:in '<class:MyGem>'
    test/tmp/my_gem.rb:5:in '<main>'
    org/jruby/RubyKernel.java:1183:in 'require'
    /Users/headius/work/jruby/lib/ruby/stdlib/bundled_gems.rb:81:in 'block in replace_require'
    lib/zeitwerk/core_ext/kernel.rb:34:in 'require'
    test/lib/zeitwerk/test_eager_load.rb:131:in 'block in TestEagerLoad'
    test/support/loader_test.rb:80:in 'with_load_path'
    test/lib/zeitwerk/test_eager_load.rb:130:in 'block in TestEagerLoad'
    test/support/loader_test.rb:71:in 'block in with_files'
    org/jruby/RubyDir.java:442:in 'chdir'
    test/support/loader_test.rb:62:in 'with_files'
    test/lib/zeitwerk/test_eager_load.rb:129:in 'block in TestEagerLoad'
```

Near as I can tell, the logic here sets up an autoload for the constant associated with the current file (MyGem and `my_gem.rb` in this case) and I believe it should be setting up autoloads for modules under that constant's subdir (files in `my_gem/` like `foo.rb`). It seems like that's not happening but I'm not sure where to look.

I added `log!` to the `my_gem.rb` contents and only get this output before it fails:

```
Zeitwerk@my_gem: autoload set for MyGem, to be autovivified from /Users/headius/work/zeitwerk/test/tmp/my_gem
Zeitwerk@my_gem: earlier autoload for MyGem discarded, it is actually an explicit namespace defined in /Users/headius/work/zeitwerk/test/tmp/my_gem.rb
Zeitwerk@my_gem: autoload set for MyGem, to be loaded from /Users/headius/work/zeitwerk/test/tmp/my_gem.rb
```

Compare to output from CRUby 3.4:

```
Zeitwerk@my_gem: autoload set for MyGem, to be autovivified from /Users/headius/work/zeitwerk/test/tmp/my_gem
Zeitwerk@my_gem: earlier autoload for MyGem discarded, it is actually an explicit namespace defined in /Users/headius/work/zeitwerk/test/tmp/my_gem.rb
Zeitwerk@my_gem: autoload set for MyGem, to be loaded from /Users/headius/work/zeitwerk/test/tmp/my_gem.rb
Zeitwerk@my_gem: autoload set for MyGem::Foo, to be autovivified from /Users/headius/work/zeitwerk/test/tmp/my_gem/foo
Zeitwerk@my_gem: earlier autoload for MyGem::Foo discarded, it is actually an explicit namespace defined in /Users/headius/work/zeitwerk/test/tmp/my_gem/foo.rb
Zeitwerk@my_gem: autoload set for MyGem::Foo, to be loaded from /Users/headius/work/zeitwerk/test/tmp/my_gem/foo.rb
...
```

Why are the additional autoloads getting lost?

**Comment by headius** [comment]
@fxn Seems like the loader for the MyGem module is getting lost... I'm seeing it reach this point in the code, but it does not get a `loader_for` MyGem:

https://github.com/fxn/zeitwerk/blob/2120324b37f8832e4476f20b5a4247197f6a64c3/lib/zeitwerk/core_ext/module.rb#L6

**Comment by fxn** [comment]
@headius just a heads up, I'll come back to this!

**Comment by headius** [comment]
@fxn I will go ahead and merge in what I have in #8852, since it greatly reduces the number of failures. The order-dependent failures are probably not cleaning up properly when running on JRuby... not removing a constant or rolling back some other changes from the tests. I will file a separate issue for that and ping you there.

**Comment by headius** [comment]
The bulk of these failures will be resolved by #8852, and #8863 documents the small set of order-dependent failures that appear to pass in isolation. We'll deal with those separately and get the current set of fixes merged in for 10.0.1.0.

**Comment by fxn** [comment]
@headius awesome.

Unfortunately, as you have seen, if something is broken it can cause unwanted side-effects that pollute other tests. This is natural since the gem works with global state all the time, you know.

In practice, if that happens, I try to pinpoint the culprit (the others pass in isolation), and that solves them all.

I would like to explore running each individual test in a subprocess, but since the suite is quite stable, I have not given priority to that. Indeed, precisely I would need to see how would that work in JRuby.

**Comment by headius** [comment]
@rolandoam Sorry I missed your comment! I have merged in several fixes from #8852 and filed a new issue for the remaining failures: #8863. I'm looking into them now but if you have a chance maybe you can find what's wrong!

I'd also recommend re-testing ruby-llm with a JRuby master snapshot to see if my fixes have resolved your issues!
