### ISSUE TITLE
Internal error: org.jruby.exceptions.RaiseException: (LoadError) Unsupported platform: x86_64-windows

### ISSUE THREAD

**Issue by AnmolNarang** [jruby/jruby#6786]
Sorry if this/similar issue is already opened. 

**Environment Information**
  
Provide at least:
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11.0.12+7-LTS on 11.0.12+7-LTS +jit [mswin32-x86_64]
Windows 10
JAVA 11 (Corretto)

*** LOCAL GEMS ***
bundler (1.17.3)
jbundler (0.9.3)

Jarfile ( there are some internal jars, one of them is complied with Java 11)

Other relevant info you may wish to add:
I had been using jruby 9.2.9.0 with JAVA 8 with no issues for my test automation. 
But now since the devs have move to JAVA 11 and they provided me a JAR which is complied with JAVA 11 ( and won't work with JAVA 8), so I am forced to update my JAVA Version

NOTE: I upgraded my Jruby to latest 9.2.19.0 or Head (https://github.com/ruby/jruby-dev-builder/releases/tag/builds-20210809-190921) but didn't resolved my problem. Below details are with Jruby 9.2.11.1

**Expected Behavior**

I can ignore the warnings but Jbundle is failing and I cannot download the jars and do my testing.
**Actual Behavior**

Observation 1: 

C:\rubyz3950>gem list bundle
2021-08-25T17:41:19.534-04:00 [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.

Observation 2:
C:\rubyz3950>bundle install
2021-08-25T17:44:55.573-04:00 [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.ext.openssl.SecurityHelper (file:/C:/jruby-9.2.11.1/lib/ruby/stdlib/jopenssl.jar) to field java.security.MessageDigest.provider
WARNING: Please consider reporting this to the maintainers of org.jruby.ext.openssl.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Observation(Error) 3: 
C:\rubyz3950>jbundle install
2021-08-25T17:45:58.231-04:00 [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
...
unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil (file:/C:/Users/naranga/.m2/repository/org/jruby/jruby-core/9.1.2.0/jruby-core-9.1.2.0.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (LoadError) Unsupported platform: x86_64-windows -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (LoadError) Unsupported platform: x86_64-windows
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) Unsupported platform: x86_64-windows
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.<top>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ffi/ffi.rb:69)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.<top>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ffi.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.<top>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ffi.rb:1)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:962)
        at RUBY.<top>(uri:classloader:/jruby/kernel/file.rb:1)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
Errno::ENOENT: No such file or directory - C:/OCLCAutomation/rubyz3950/pkg/dependencies.txt
               sysopen at org/jruby/RubyIO.java:1237
                  read at org/jruby/RubyIO.java:3774
  install_dependencies at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/lock_down.rb:113
             lock_down at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/lock_down.rb:54
               install at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/cli.rb:80
                   run at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27
        invoke_command at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
              dispatch at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387
                 start at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466
                <main> at C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/jbundler-0.9.3/bin/jbundle:47
                  load at org/jruby/RubyKernel.java:1009
                <main> at c:\jruby-9.2.11.1\bin\jbundle:23

Update 
8/26 - I did a hack, installed jars with 1.8 and then upgraded java to 11.   Only thing would be, every time jar is updated I have to revert java version(1.8) to download and then revert(11) to access jars

**Comment by headius** [comment]
@AnmolNarang Hello!

It is not clear to me how you are installing JRuby. If you are running a current version of JRuby from one of our standard release files, you should not be getting the `illegal reflective access operation` at all. Those errors indicate that you are not running from our standard distributions, or your JDK installation is peculiar in some way.

Can you explain to me how you are getting JRuby? Who are these "devs" that are giving you a different jar file for Java 11?

**Comment by headius** [comment]
@mkritian This could be due to jbundler or the Maven plugins still being on very old versions of JRuby. We really need to get those updated to 9.2.19 and new releases pushed.

**Comment by headius** [comment]
@AnmolNarang My above comment to @mkristian could do with some explanation. I can see from your logs that you are using some JRuby-based Maven plugins, which in most cases are running very old versions of JRuby. Updating your local JRuby may be insufficient in such cases, which is why I pinged @mkristian about us getting those plugins updated to a newer version of JRuby that works better with Java module restrictions.

**Comment by AnmolNarang** [comment]
> @AnmolNarang Hello!
> 
> It is not clear to me how you are installing JRuby. If you are running a current version of JRuby from one of our standard release files, you should not be getting the `illegal reflective access operation` at all. Those errors indicate that you are not running from our standard distributions, or your JDK installation is peculiar in some way.
> 
> Can you explain to me how you are getting JRuby? Who are these "devs" that are giving you a different jar file for Java 11?


I am running the standard jruby ( downloaded from https://www.jruby.org/)
Devs from my organization. My Automation code depends on some jars which are developed by my organization.

**Comment by AnmolNarang** [comment]
> @AnmolNarang My above comment to @mkristian could do with some explanation. I can see from your logs that you are using some JRuby-based Maven plugins, which in most cases are running very old versions of JRuby. Updating your local JRuby may be insufficient in such cases, which is why I pinged @mkristian about us getting those plugins updated to a newer version of JRuby that works better with Java module restrictions.

Thank you @headius for the response. 
Yes, I am using Jbundler to manage the jar dependencies and that's where the problem is. Others are warning. 

BTW, I checked with other resources in my org and all of them are getting these warnings, and everyone is using standard Jruby ( downloaded from https://www.jruby.org/)

**Comment by AnmolNarang** [comment]
I guess, https://github.com/mkristian/jbundler/issues/96 is same as mine.

**Comment by headius** [comment]
Yes I think we will need @mkristian help on this, or potentially we will have to take over the repository.

Are you out there @mkristian?

**Comment by mkristian** [comment]
Yes, I will see to it this weekend.

10 Sep 2021 17:12:24 Charles Oliver Nutter ***@***.***>:

**Comment by AnmolNarang** [comment]
Hello  @mkristian
is there any update on this?
