### ISSUE TITLE
Backtrace with NoMethodError does not display number of lines when more than 32768 lines

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#6847]
**Environment Information**
  
```
jruby 9.3.0.0-SNAPSHOT (2.6.8) 2021-09-16 4727fcb3b0 OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04 on 11.0.11+9-Ubuntu-0ubuntu2.20.04 +jit [linux-x86_64]
```

**Expected Behavior**

In Jruby 9.2.19.0, backtrace with NoMethodError displays the number of lines even if there are more than 32768 lines.

```
$ cat Test.java
```
```java
public class Test {
    public static void main(String[] args) {
        StringBuilder str = new StringBuilder();
        for(int i = 0; i < 32768; i++) {
            str.append("\n");
        }
        str.append("nil.xxx\n");
        new org.jruby.embed.ScriptingContainer().runScriptlet(str.toString());
    }
}
```
```
$javac Test.java -cp jruby-complete.jar
$ java -cp jruby-complete.jar:. Test
NoMethodError: undefined method `xxx' for nil:NilClass
  <main> at <script>:32769
Exception in thread "main" org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `xxx' for nil:NilClass
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1295)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1288)
        at Test.main(Test.java:8)
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `xxx' for nil:NilClass
        at RUBY.<main>(<script>:32769)
```

**Actual Behavior**

```
$ java -cp jruby-complete-9.3.0.0-20210916.221728-287.jar:. Test
Exception in thread "main" org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `xxx' for nil:NilClass
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1296)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1289)
        at Test.main(Test.java:8)
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `xxx' for nil:NilClass
        at RUBY.<main>(<script>)
```

**Comment by enebo** [comment]
@yamam Can I ask how many lines you have in files which are longer than this?  We combine line numbers and column offsets into a single int to save memory.  We could consider giving another bit for line at the cost of column but that would noly get us to ~65k lines.

**Comment by yamam** [comment]
The longest file has about 50,000 lines.

**Comment by enebo** [comment]
@yamam Thanks for the info.  Perhaps we will use 9 bits for line number and 7 bits for the column.  The column value is less important but we have gotten a bug report of someone generating all their source as a single line.

**Comment by yamam** [comment]
I noticed that the backtrace in the rescue section shows a negative number of lines.

```java
public class Test {
    public static void main(String[] args) {
        StringBuilder str = new StringBuilder();
        for(int i = 0; i < 32768; i++) {
            str.append("\n");
        }
        str.append("begin;nil.xxx;rescue;puts $!.backtrace;end\n");
        new org.jruby.embed.ScriptingContainer().runScriptlet(str.toString());
    }
}
```

```
$ java -cp jruby-complete.jar:. Test                                                                                                                                                
<script>:-32767:in `<main>'
```

**Comment by enebo** [comment]
@yamam yeah this is because the 16 bits shared for line number are the high bits of an integer and the integer will overflow once the value is more than 16 bits.  In my previous comment I should have said 17 bits and 15 bits for changing the value.

I am thinking of adding a warning when we see the line number exceed 17 bits so at least you will get something saying line numbers may start looking weird.

**Comment by yamam** [comment]
@enebo If the number of lines is negative, we can add 65536 to get the correct number of lines up to 65535.
