### ISSUE TITLE
[Q] How to fix `NoMethodError (undefined method `runtime' for JRuby:Module)` on JRuby 9.3.0.0?

### ISSUE THREAD

**Issue by hiroyuki-sato** [jruby/jruby#6868]
Hello, Could you tell me How to fix `NoMethodError (undefined method `runtime' for JRuby:Module)` on JRuby 9.3.0.0?

Should I change like this?

```ruby
if JRUBY_VERSION < 9.3 # Dummy code.
  require 'java'
else
  require 'jruby'
end
```

**Environment Information**
  
* JRuby version: 9.3.0.0
* Operating system and platform: macOS 11.6

**Expected Behavior**

I expected msgpack loading properly on JRuby 9.3.0.0 like the below.

```
irb(main):001:0> require 'msgpack'
=> true
```

**Actual Behavior**

```
gem list | grep msgpack
msgpack (1.4.2 java)
```

```
irb(main):001:0> JRUBY_VERSION
=> "9.3.0.0"
irb(main):002:0> require 'msgpack'
Traceback (most recent call last):
       11: from /Users/user/.rbenv/versions/jruby-9.3.0.0/bin/irb:23:in `<main>'
       10: from org/jruby/RubyKernel.java:1052:in `load'
        9: from /Users/user/.rbenv/versions/jruby-9.3.0.0/lib/ruby/gems/shared/gems/irb-1.0.0/exe/irb:11:in `<main>'
        8: from org/jruby/RubyKernel.java:1237:in `catch'
        7: from org/jruby/RubyKernel.java:1237:in `catch'
        6: from org/jruby/RubyKernel.java:1507:in `loop'
        5: from org/jruby/RubyKernel.java:1091:in `eval'
        4: from (irb):2:in `evaluate'
        3: from /Users/user/.rbenv/versions/jruby-9.3.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:160:in `require'
        2: from org/jruby/RubyKernel.java:1017:in `require'
        1: from /Users/user/.rbenv/versions/jruby-9.3.0.0/lib/ruby/gems/shared/gems/msgpack-1.4.2-java/lib/msgpack.rb:6:in `<main>'
NoMethodError (undefined method `runtime' for JRuby:Module)
```

And I found this article.

https://github.com/jruby/jruby-examples/pull/16/
https://github.com/jruby/jruby/issues/6724

So I tried to fix it like this.

```diff
diff --git a/lib/msgpack.rb b/lib/msgpack.rb
index 25aacd0..8884d33 100644
--- a/lib/msgpack.rb
+++ b/lib/msgpack.rb
@@ -1,7 +1,7 @@
 require "msgpack/version"

 if defined?(RUBY_ENGINE) && RUBY_ENGINE == "jruby" # This is same with `/java/ =~ RUBY_VERSION`
-  require "java"
+  require "jruby"
   require "msgpack/msgpack.jar"
   org.msgpack.jruby.MessagePackLibrary.new.load(JRuby.runtime, false)
 else
```

```
% \irb -I /tmp/msgpack-ruby/lib/
irb(main):001:0> require 'msgpack'
=> true
```

This change seems fine on JRuby 9.3.0.0. But this change break msgpack loading on 9.2.19.0

```
\irb -I /tmp/msgpack-ruby/lib/
irb(main):001:0> JRUBY_VERSION
=> "9.2.19.0"
irb(main):002:0> require 'msgpack'
Traceback (most recent call last):
       11: from /Users/user/.rbenv/versions/jruby-9.2.19.0/bin/irb:13:in `<main>'
       10: from org/jruby/RubyKernel.java:1189:in `catch'
        9: from org/jruby/RubyKernel.java:1189:in `catch'
        8: from org/jruby/RubyKernel.java:1442:in `loop'
        7: from org/jruby/RubyKernel.java:1048:in `eval'
        6: from (irb):2:in `evaluate'
        5: from /Users/user/.rbenv/versions/jruby-9.2.19.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83:in `require'
        4: from org/jruby/RubyKernel.java:974:in `require'
        3: from /private/tmp/msgpack-ruby/lib/msgpack.rb:5:in `<main>'
        2: from /Users/user/.rbenv/versions/jruby-9.2.19.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83:in `require'
        1: from org/jruby/RubyKernel.java:974:in `require'
LoadError (no such file to load -- msgpack/msgpack)
```

Best regards.

**Comment by hiroyuki-sato** [comment]
I resolved this by myself. 
The reason is that it requires `msgpack/msgpack.jar` but it doesn't exist in `/private/tmp/msgpack-ruby/lib/msgpack/msgpack.jar`.
