### ISSUE TITLE
ruby-maven does not recognize Java 9+

### ISSUE THREAD

**Issue by ghost** [jruby/jruby#6904]
**Overview**

The "ruby-maven"gem has not been maintained since June 2016 (last version [3.3.12](https://rubygems.org/gems/ruby-maven/versions/3.3.12)), and does not appear to recognize Java SE 9 and later.  The issue can be replicated by running the `jgem update` command from terminal, which, when the ruby-maven gem attempts to update, will report an unrecognized Java version and attempt to default to Java 1.7 or similar, based upon an incorrect interpretation of the reported version numbers (i.e.: Java SE 14 may attempt to default to Java 1.4).

**Environment Information**

* `jruby 9.3.1.0 (2.6.8) 2021-10-13 2e01e7199d OpenJDK 64-Bit Server VM 17+35-2724 on 17+35-2724 +indy +jit [mswin32-x86_64]`
* Bug appears to affect all versions of JRuby where one or more packaged gems rely on "jar-dependencies" gem.
* Confirmed on Windows 10 (x86_64), but likely affects any OS.
* Newly unpacked TAR/ZIP archives of JRuby builds are affected (output below was from the latest 9.3.1.0 tarball).

**Expected Behavior**

JRuby should be able to update its gems without error.

**Actual Behavior**

Example output from a clean install of latest JRuby (9.3.1.0 at time of writing):

```
> jgem update
. . .
Updating psych
Fetching psych-4.0.2-java.gem
  jar dependencies for psych-4.0.2-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Fetching ruby-maven-libs-3.3.9.gem
Fetching ruby-maven-3.3.12.gem
Successfully installed ruby-maven-libs-3.3.9
Successfully installed ruby-maven-3.3.12
Parsing documentation for ruby-maven-libs-3.3.9
Installing ri documentation for ruby-maven-libs-3.3.9
Installing darkfish documentation for ruby-maven-libs-3.3.9
Parsing documentation for ruby-maven-3.3.12
Installing ri documentation for ruby-maven-3.3.12
Installing darkfish documentation for ruby-maven-3.3.12
Done installing documentation for ruby-maven-libs, ruby-maven after 0 seconds
Parsing documentation for ruby-maven-3.3.12
Parsing documentation for ruby-maven-libs-3.3.9
Done installing documentation for ruby-maven, ruby-maven-libs after 0 seconds

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

unsupported Java version "17", defaulting to 1.7
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @351f2244 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @351f2244
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @351f2244
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - D:/Programs/JRuby/lib/ruby/gems/shared/gems/psych-4.0.2-java/deps.lst
```

*Notice:  some output was removed for the sake of clarity and brevity.  Output begins with offending gems.*

**Comment by flavorjones** [comment]
I'm seeing what appears to be the same error, and I have a docker/OCI image in which it's easily reproducible (based on the upcoming release of rake-compiler-dock).

Steps to reproduce:

1. `docker pull flavorjones/rake-compiler-dock-jruby:1.1.1.flavorjones20211224`
2. `docker run -it flavorjones/rake-compiler-dock-jruby:1.1.1.flavorjones20211224 /bin/bash`
3. (in the container) `gem install psych`

Output:

```text
root@44bfebde86c0:/# gem install psych
Fetching psych-4.0.3-java.gem
  jar dependencies for psych-4.0.3-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Fetching ruby-maven-libs-3.3.9.gem
Fetching ruby-maven-3.3.12.gem
Successfully installed ruby-maven-libs-3.3.9
Successfully installed ruby-maven-3.3.12
Parsing documentation for ruby-maven-libs-3.3.9
Installing ri documentation for ruby-maven-libs-3.3.9
Parsing documentation for ruby-maven-3.3.12
Installing ri documentation for ruby-maven-3.3.12
Done installing documentation for ruby-maven-libs, ruby-maven after 1 seconds
Parsing documentation for ruby-maven-3.3.12
Parsing documentation for ruby-maven-libs-3.3.9
Done installing documentation for ruby-maven, ruby-maven-libs after 0 seconds

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

unsupported Java version "17", defaulting to 1.7
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7930ffa9 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7930ffa9
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7930ffa9
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /usr/local/rvm/gems/jruby-9.3.1.0/gems/psych-4.0.3-java/deps.lst
```

This docker image was created this morning from this dockerfile: https://github.com/flavorjones/rake-compiler-dock/blob/bc85e80d2a7b1ed53d33af013cc19a03191d408c/Dockerfile.jruby

cc @larskanis for awareness

**Comment by deivid-rodriguez** [comment]
https://github.com/jruby/ruby-maven has been updated and should be only pending a new release. Last time I looked, my conclusion was that releasing the latest updates there would fix this issue.

**Comment by flavorjones** [comment]
@deivid-rodriguez Thanks for the response, but unfortunately this problem is still reproducible using the git default branch of jruby/ruby-maven

Here's how to reproduce:

```ruby
# Gemfile
source "https://rubygems.org"
gem "psych"
gem "ruby-maven", git: "https://github.com/jruby/ruby-maven"
```

Use the latest rake-compiler-dock image:

```sh
docker pull larskanis/rake-compiler-dock-jruby:1.2.0

docker run -it larskanis/rake-compiler-dock-jruby:1.2.0 /bin/bash

# in the container ...
cat > Gemfile <<EOF
source "https://rubygems.org"
gem "psych"
gem "ruby-maven", git: "https://github.com/jruby/ruby-maven"
EOF

bundle install
```

The full output is:

```text
root@9c3e2d8f70e9:/# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
/usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::AF_INET6
/usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::IPPROTO_ICMPV6
/usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::IPPROTO_IPV6
/usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::PF_INET6
/usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::SOL_IPV6
Fetching https://github.com/jruby/ruby-maven
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies....
Using bundler 2.3.4
Using jar-dependencies 0.4.1
Fetching ruby-maven-libs 3.3.9
Fetching psych 4.0.3 (java)
Installing psych 4.0.3 (java)
  jar dependencies for psych-4.0.3-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Installing ruby-maven-libs 3.3.9
Using ruby-maven 3.3.12 from https://github.com/jruby/ruby-maven (at master@ef96c08)

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /usr/local/rvm/gems/jruby-9.3.2.0/gems/ruby-maven-3.3.12/lib/ruby_maven.rb:38)
unsupported Java version "17", defaulting to 1.7
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7e9f2c32 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7e9f2c32
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7e9f2c32
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

Error report info:

```
Errno::ENOENT: No such file or directory - /usr/local/rvm/gems/jruby-9.3.2.0/gems/psych-4.0.3-java/deps.lst
  org/jruby/RubyIO.java:1227:in `sysopen'
  org/jruby/RubyIO.java:3986:in `read'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/jars/installer.rb:69:in `load_from_maven'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/jars/installer.rb:235:in `install_dependencies'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/jars/installer.rb:224:in `do_install'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/jars/installer.rb:170:in `vendor_jars'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in <main>'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/rubygems/installer.rb:367:in `block in run_post_install_hooks'
  org/jruby/RubyArray.java:1865:in `each'
  /usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/stdlib/rubygems/installer.rb:366:in `run_post_install_hooks'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/rubygems_gem_installer.rb:43:in `install'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/source/rubygems.rb:204:in `install'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/worker.rb:57:in `block in process_queue'
  org/jruby/RubyKernel.java:1507:in `loop'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/rvm/gems/jruby-9.3.2.0/gems/bundler-2.3.4/lib/bundler/worker.rb:91:in `block in create_threads'
```

## Environment

```
Bundler             2.3.4
  Platforms         ruby, universal-java-17
Ruby                2.6.8p0 (2021-12-01 revision 67951) [java]
  Full Path         /usr/local/rvm/rubies/jruby-9.3.2.0/bin/jruby
  Config Dir        /usr/local/rvm/rubies/jruby-9.3.2.0/etc
RubyGems            3.2.29
  Gem Home          /usr/local/rvm/gems/jruby-9.3.2.0
  Gem Path          /usr/local/rvm/gems/jruby-9.3.2.0:/usr/local/rvm/rubies/jruby-9.3.2.0/lib/ruby/gems/shared
  User Home         /root
  User Path         /root/.local/share/gem/jruby/2.6.0
  Bin Dir           /usr/local/rvm/gems/jruby-9.3.2.0/bin
OpenSSL             
  Compiled          JRuby-OpenSSL 0.11.0
  Loaded            JRuby-OpenSSL 0.11.0
  Cert File         /usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts
  Cert Dir          /etc/ssl/certs
Tools               
  Git               2.25.1
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2021-12-29
Git SHA           2296a0d6cc
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
gem "psych"
gem "ruby-maven", git: "https://github.com/jruby/ruby-maven"
```

### Gemfile.lock

```
<No /Gemfile.lock found>
```

**Comment by flavorjones** [comment]
If it helps determine priority/urgency, this is a blocker to shipping Nokogiri, so I would appreciate any help you can provide on how to work around this.

**Comment by flavorjones** [comment]
This also happens using the latest official jruby docker hub image `jruby:9.3.2.0-jdk17`.

**Comment by deivid-rodriguez** [comment]
Can you try something? Instead of pointing to the git repository in the Gemfile, clone the gem, build it and install it. That way I think it should work (and it would proof that a release would fix the problem).

**Comment by flavorjones** [comment]
@deivid-rodriguez Yes, that works: packaging a gem from git master and installing it, then gem installing psych succeeds. (Using `jruby:9.3.2.0-jdk17`)

**Comment by deivid-rodriguez** [comment]
The explanation of why that works is that JRuby uses this gem through a rubygems plugin, which is required very early, so the fixed version of `ruby-maven` needs to be installed _before_ `bundle install` is run.

**Comment by flavorjones** [comment]
OK ... Can you help me understand whether I should work around this problem in Nokogiri's build scripts and CI, or wait for a ruby-maven release? How likely is a ruby-maven release in the next few days?

**Comment by deivid-rodriguez** [comment]
I would work around it. There's been no ruby-maven release in almost 6 years, so I think it's best to not rely on it. As far as I understand, the JRuby team is transitioning to maintaining this gem themselves, but they haven't been able to get to it yet.

**Comment by flavorjones** [comment]
OK, thanks so much for you help, @deivid-rodriguez! I will work around it.

**Comment by deivid-rodriguez** [comment]
No problem!
