### ISSUE TITLE
Unable to install a gem with jar dependencies on jruby built from source

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#6926]
Trying to run git bisect for an issue, but cannot install the needed gem. PATH and JRUBY_HOME are set. Works on jruby installed via rvm.

```
(base) ~/m/jruby ❯❯❯ gem install neo4j-java-driver                                                                                                                         tags/9.2.19.0 ✱
  jar dependencies for neo4j-java-driver-4.3.1-java.gemspec . . .
unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil (file:/Users/heinrich/.m2/repository/org/jruby/jruby-core/9.1.2.0/jruby-core-9.1.2.0.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant Errno::ENOTSUP -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant Errno::ENOTSUP
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant Errno::ENOTSUP
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3309)
	at RUBY.<module:Gem>(/Users/heinrich/mck/jruby/lib/ruby/stdlib/rubygems.rb:165)
	at RUBY.<top>(/Users/heinrich/mck/jruby/lib/ruby/stdlib/rubygems.rb:115)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
	at RUBY.<top>(uri:classloader:/jruby/kernel/gem_prelude.rb:1)
	at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:962)
	at RUBY.<top>(uri:classloader:/jruby/kernel/gem_prelude.rb:3)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /Users/heinrich/mck/jruby/lib/ruby/gems/shared/gems/neo4j-java-driver-4.3.1-java/deps.lst
```

**Comment by mohits** [comment]
Just to confirm that things are set up as the should be, could you try the following:
1. check the JRuby version to be sure that it is the one built from source that is on your path
2. could you also try to do `jruby -S gem install` rather than gem install

I'm not sure that these will definitely help but might throw up some additional information.

**Comment by klobuczek** [comment]
@mohits 
1. confirmed
2. same error

**Comment by headius** [comment]
I believe this indicates that the JRuby used by the jar-dependencies gem does not have ENOTSUP defined, but it is using the RubyGems on your system path that expects ENOTSUP to be available.

JRuby 9.2 and 9.3 both define the value, so the gem is likely running JRuby 9.1.x or earlier. It needs an update in any case.

You could work around this by defining ENOTSUP in a file loaded early in RubyGems, like rubygems.rb, so that the embedded JRuby will see the change.

```ruby
module Errno
  class ENOTSUP < SystemCallError
    Errno = 45
  end
end
```

We will not raise it but the rescue that uses it will not blow up.

**Comment by klobuczek** [comment]
@headius sorry not sure what you mean by adding the code to rubygems.rb. Where is the file located? Do you mean the one in jruby/lib/ruby/stdlib/rubygems.rb?
