### ISSUE TITLE
Unexpected build failure (GHA, ruby-head) on mime-types/ruby-mime-types

### ISSUE THREAD

**Issue by halostatue** [jruby/jruby#6938]
**Environment Information**

- GitHub Actions  
- `jruby-head`
- `macos-latest` and `ubuntu-latest`

**Expected Behavior**

The build should succeed as every other version in the matrix succeeds.

**Actual Behavior**

The build fails.

I have `jruby-head` as a build target in mime-types/ruby-mime-types. A PR for an upcoming release has GitHub Actions failures on macOS and Ubuntu on `jruby-head` (and _only_ `jruby-head`) in the same spot. I have as yet been unable to install a `jruby-head` version locally to investigate in more detail.

The log can be found here: https://github.com/mime-types/ruby-mime-types/runs/4215324179?check_suite_focus=true

```
▶ Run bundle exec ruby -S rake test --trace
/home/runner/.rubies/jruby-head/lib/ruby/stdlib/time.rb:3: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
rake aborted!
NoMethodError: undefined method `last' for "=":String
org/jruby/RubyYielder.java:115:in `yield'
org/jruby/RubyYielder.java:120:in `<<'
org/jruby/RubyArray.java:1858:in `each'
org/jruby/RubyGenerator.java:99:in `each'
org/jruby/RubyEnumerator.java:383:in `each'
org/jruby/RubyEnumerable.java:816:in `map'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/hoe-3.23.0/lib/hoe.rb:663:in `intuit_values'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/hoe-3.23.0/lib/hoe.rb:813:in `post_initialize'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/hoe-3.23.0/lib/hoe.rb:394:in `spec'
/home/runner/work/ruby-mime-types/ruby-mime-types/Rakefile:13:in `<main>'
org/jruby/RubyKernel.java:1052:in `load'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
org/jruby/RubyKernel.java:1052:in `load'
/home/runner/.rubies/jruby-head/bin/rake:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by halostatue** [comment]
This is the link to the logs on the main branch: https://github.com/mime-types/ruby-mime-types/runs/4215588492?check_suite_focus=true

**Comment by ahorek** [comment]
a simple repro
```
['string'].chunk { |l| l }.map(&:last)
```
btw this works
```
['string'].chunk { |l| l }.map { |x| x.last }
```

**Comment by halostatue** [comment]
This is still happening on JRuby 9.4.0.0:

<details>
<summary>macOS: <a href="https://github.com/mime-types/ruby-mime-types/actions/runs/3941238593/jobs/6746459169">https://github.com/mime-types/ruby-mime-types/actions/runs/3941238593/jobs/6746459169</a>

</summary>

```
Set Up Ruby
[1] Run ruby/setup-ruby@v1
[5] Modifying PATH
[11] Downloading Ruby
[14] Extracting  Ruby
[17] Print Ruby version
[18] /Users/runner/.rubies/jruby-9.4.0.0/bin/ruby --version
[19] jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 25.352-b08 on 1.8.0_352-b08 +jit [x86_64-darwin]
[20] Took   0.70 seconds
[21] Installing Bundler
[24] bundle install

Run Tests
[1] Run bundle exec ruby -S rake test --trace
[6] rake aborted!
[7] NoMethodError: undefined method `last' for "=":String
[8] org/jruby/RubyYielder.java:115:in `yield'
[9] org/jruby/RubyYielder.java:120:in `<<'
[10] org/jruby/RubyArray.java:1988:in `each'
[11] org/jruby/RubyGenerator.java:98:in `each'
[12] org/jruby/RubyEnumerator.java:397:in `each'
[13] org/jruby/RubyEnumerable.java:835:in `map'
[14] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/hoe-3.26.0/lib/hoe.rb:676:in `intuit_values'
[15] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/hoe-3.26.0/lib/hoe.rb:827:in `post_initialize'
[16] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/hoe-3.26.0/lib/hoe.rb:406:in `spec'
[17] /Users/runner/work/ruby-mime-types/ruby-mime-types/Rakefile:48:in `<main>'
[18] org/jruby/RubyKernel.java:1091:in `load'
[19] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
[20] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
[21] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
[22] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
[23] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
[24] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
[25] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
[26] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
[27] /Users/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
[28] org/jruby/RubyKernel.java:1091:in `load'
[29] /Users/runner/.rubies/jruby-9.4.0.0/bin/rake:23:in `<main>'
[30] Error: Process completed with exit code 1.
```

</details>

Ubuntu: https://github.com/mime-types/ruby-mime-types/actions/runs/3941238593/jobs/6746457223

**Comment by halostatue** [comment]
I can download and attach the log archives if you want, but it’s the same error.
