### ISSUE TITLE
Circular exception causes break JRuby

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#7035]
Howdy! This one comes from Datadog's [ddtrace](https://github.com/DataDog/dd-trace-rb) gem tests, and it doesn't block us, but I thought I'd report anyway since the behavior does not match MRI Ruby.

---

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): `jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 11.0.14+9-LTS on 11.0.14+9-LTS [darwin-x86_64]`
* Operating system and platform (e.g. `uname -a`): `Darwin ivoanjo 19.6.0 Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,2 Darwin`

**Expected Behavior**

Example code taken from upstream [`test/mri/ruby/test_exception.rb`](https://github.com/jruby/jruby/blob/779455dfae3b1bbc1ce3cd69d2c2a66c46aafabe/test/mri/ruby/test_exception.rb#L1276) (see also the changesets in https://bugs.ruby-lang.org/issues/15447?tab=changesets):

```ruby
puts RUBY_DESCRIPTION

begin
 raise "error 1"
rescue => e1
  raise "error 2" rescue raise e1, cause: $!
end
```

Behavior in Ruby 2.5:

```
$ ruby circular-causes-argumenterror.rb
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-darwin19]
Traceback (most recent call last):
circular-causes-argumenterror.rb:4:in `<main>': error 1 (RuntimeError)
```

Behavior in Ruby 2.6-3.1:

```
$ ruby circular-causes-argumenterror.rb
ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-darwin19]
circular-causes-argumenterror.rb:6:in `rescue in rescue in <main>': circular causes (ArgumentError)
	from circular-causes-argumenterror.rb:6:in `rescue in <main>'
	from circular-causes-argumenterror.rb:3:in `<main>'
circular-causes-argumenterror.rb:6:in `rescue in <main>': error 2 (RuntimeError)
	from circular-causes-argumenterror.rb:3:in `<main>'
circular-causes-argumenterror.rb:4:in `<main>': error 1 (RuntimeError)
```
**Actual Behavior**

JRuby gets stuck on an infinite loop:

```
ivo.anjo@macieira:~/datadog/second-dd-trace-rb$ ruby circular-causes-argumenterror.rb
jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 11.0.14+9-LTS on 11.0.14+9-LTS +jit [darwin-x86_64]
RuntimeError: error 1
  <main> at circular-causes-argumenterror.rb:4
RuntimeError: error 2
  <main> at circular-causes-argumenterror.rb:6
RuntimeError: error 1
  <main> at circular-causes-argumenterror.rb:4
RuntimeError: error 2
  <main> at circular-causes-argumenterror.rb:6
RuntimeError: error 1
# Repeat forever
```

**Comment by headius** [comment]
Well that's a fun one!
