### ISSUE TITLE
Ripper fails to process net-protocol sources

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7085]
With the changes in #7084 we can install the net-protocol gem and its upstream dependencies, but documentation generation for net-protocol fails with the following error. Seems like something missing or broken in our ripper logic:

```
Parsing documentation for net-protocol-0.1.2
Parsing sources...
Exception `NoMethodError' at /Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:496 - undefined method `[]' for nil:NilClass
Exception `NoMethodError' at /Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:496 - undefined method `[]' for nil:NilClass
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/headius/projects/jruby/bin/jruby -c lib/net/protocol.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

Exception `NoMethodError' at /Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:496 - undefined method `[]' for nil:NilClass
Exception `NoMethodError' at /Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:496 - undefined method `[]' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
	/Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:496:in `heredoc_end?'
	/Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:479:in `get_heredoc_tk'
	/Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:346:in `get_squashed_tk'
	/Users/headius/projects/jruby/lib/ruby/stdlib/rdoc/parser/ripper_state_lex.rb:580:in `parse'
...
```

Build from the branch in #7084 and run `gem install --debug net-protocol` to get this output.

**Comment by headius** [comment]
This appears to have been fixed by recent Ripper improvements (@enebo).
