### ISSUE TITLE
load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/jruby/util/io/FileExistsException

### ISSUE THREAD

**Issue by DilipMaharjan21** [jruby/jruby#7099]
An error occurred while loading ./spec/filters/lane_spec.rb.←[31m - Did you mean?
                    rspec ./spec/spec_helper.rb
←[0m
←[31mFailure/Error: require "logstash/devutils/rspec/spec_helper"←[0m
←[31m←[0m
←[31mLoadError:←[0m
←[31m  load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/jruby/util/io/FileExistsException←[0m
←[36m# ./spec/spec_helper.rb:2:in `<main>'←[0m
←[36m# ./spec/filters/lane_spec.rb:1:in `<main>'←[0m
←[36m# ------------------←[0m
←[36m# --- Caused by: ---←[0m
←[36m# Java::JavaLang::ClassNotFoundException:←[0m
←[36m#   org.jruby.util.io.FileExistsException←[0m
←[36m#   java.net.URLClassLoader.findClass(URLClassLoader.java:387)←[0m
No examples found.

Finished in 0 seconds (files took 3.35 seconds to load)
←[31m0 examples, 0 failures, 1 error occurred outside of examples←[0m

I am using jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 Java HotSpot(TM) 64-Bit Server VM 25.311-b11 on 1.8.0_311-b11 +jit [mswin32-x86_64]

Can someone please help me to fix this issue?

**Comment by seanstory** [comment]
I recently hit this too. Turns out this isn't a JRuby bug, but a logstash bug. See: https://github.com/elastic/logstash/issues/14203
