### ISSUE TITLE
jruby 9.3.6.0 warble

### ISSUE THREAD

**Issue by viglu** [jruby/jruby#7266]
Hi,

I have problems with warble. When I run `jruby -S warble -T --trace` outside my project everything is OK.
But when I run the same command in my project directory I get an error.
I always run `grep -R "jruby"` in my project directory to be sure that every file is set to version 9.3.6.0

Seems similar to [](https://github.com/jruby/jruby/issues/7160)

```
warble aborted!
TypeError: nil is not a string
org/jruby/RubyKernel.java:2071:in `respond_to?'
/usr/share/rvm/rubies/jruby-9.3.6.0/lib/ruby/stdlib/ostruct.rb:240:in `is_method_protected!'
/usr/share/rvm/rubies/jruby-9.3.6.0/lib/ruby/stdlib/ostruct.rb:223:in `new_ostruct_member!'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:190:in `[]='
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:251:in `method_missing'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/traits/rails.rb:52:in `after_configure'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/traits.rb:33:in `block in after_configure'
org/jruby/RubyArray.java:1865:in `each'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/traits.rb:33:in `after_configure'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/config.rb:217:in `initialize'
org/jruby/RubyClass.java:909:in `new'
config/warble.rb:23:in `initialize'
org/jruby/RubyKernel.java:1091:in `eval'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/task.rb:46:in `initialize'
org/jruby/RubyClass.java:881:in `new'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/application.rb:27:in `load_rakefile'
/usr/share/rvm/rubies/jruby-9.3.6.0/lib/ruby/gems/shared/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/usr/share/rvm/rubies/jruby-9.3.6.0/lib/ruby/gems/shared/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/rvm/rubies/jruby-9.3.6.0/lib/ruby/gems/shared/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/application.rb:79:in `run'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/lib/warbler/application.rb:74:in `run'
/usr/share/rvm/gems/jruby-9.3.6.0/gems/warbler-2.0.5/bin/warble:11:in `<main>'
org/jruby/RubyKernel.java:1052:in `load'
/usr/share/rvm/gems/jruby-9.3.6.0/bin/warble:25:in `<main>'

```

**Environment Information**
* jruby 9.3.6.0 (2.6.8) 2022-06-27 7a2cbcd376 OpenJDK 64-Bit Server VM 17.0.3+7-Ubuntu-0ubuntu0.20.04.1 on 17.0.3+7-Ubuntu-0ubuntu0.20.04.1 +jit [x86_64-linux]
* Linux poste-lvi-vm-linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chadlwilson** [comment]
This was eventually fixed with proper release of warbler 2.1.0 in https://github.com/jruby/warbler/releases/tag/v2.1.0 Not a jruby issue.
