### ISSUE TITLE
Methods mixed into a Ruby concrete subclass do not override Java methods from the superclass in JRuby 9.3.6.0

### ISSUE THREAD

**Issue by swprosser** [jruby/jruby#7270]
While trying to upgrade our application from JRuby 9.2.13.0 to JRuby 9.3.6.0, I have run into a problem. To make it easier to see what I am talking about, I have created the following program to demonstrate the behavior: https://github.com/swprosser/jruby-concrete-extension.

This problem occurs with JRuby 9.3.6.0 (and 9.3.4.0 and possibly earlier versions of JRuby 9.3). JRuby 9.2.21.0 does not have this problem.

I have a Ruby concrete subclass called RubyConcreteExtension which extends a Java class called JavaSuperclass. I mix in methods from a module (called RubyMixin) that defines methods with the same name and signature as methods in the Java superclass. I would expect for the methods from the included module to override the Java methods from the superclass. However, when the methods are called from Java, the methods are not overridden, and the version of the method defined in the Java superclass is called.

Here is the output of my [sample program](https://github.com/swprosser/jruby-concrete-extension) using JRuby 9.2.21.0:

```
Call Java version of getSnakeCase()
Call Ruby version of getCamelCase()
Call Ruby version of getSnakeCaseAlias()
Call Ruby version of getCamelCaseAlias()
Call Ruby version of getSnakeCaseAliasMethod()
Call Ruby version of getCamelCaseAliasMethod()
Call Java version of getSnakeCaseMixin()
Call Ruby version of getCamelCaseMixin()
Call Ruby version of getSnakeCaseAliasMixin()
Call Ruby version of getCamelCaseAliasMixin()
Call Ruby version of getSnakeCaseAliasMethodMixin()
Call Ruby version of getCamelCaseAliasMethodMixin()
```

As you can see, it only calls the Java version of the getSnakeCase method when the method is named in snake case in the Ruby subclass and no camel case alias (e.g. "getSnakeCase") exists. In all other scenarios, it calls the Ruby version of the method, even if the Ruby method is defined in a module and then included in the Ruby subclass.

In contrast, here is the output with JRuby 9.3.6.0:

```
Call Java version of getSnakeCase()
Call Ruby version of getCamelCase()
Call Ruby version of getSnakeCaseAlias()
Call Ruby version of getCamelCaseAlias()
Call Ruby version of getSnakeCaseAliasMethod()
Call Ruby version of getCamelCaseAliasMethod()
Call Java version of getSnakeCaseMixin()
Call Java version of getCamelCaseMixin()
Call Java version of getSnakeCaseAliasMixin()
Call Java version of getCamelCaseAliasMixin()
Call Java version of getSnakeCaseAliasMethodMixin()
Call Java version of getCamelCaseAliasMethodMixin()
```

Notice that the methods defined in the RubyMixin module did not override the Java methods (when called from Java). Instead, the Java versions of the methods were called.

This is not the only problem I found. If I add a `super()` call in the methods RubyConcreteExtension#snake_case_alias or RubyConcreteExtension#snake_case_alias_method, I get the following error with JRuby 9.3.6.0:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.jruby.exceptions.RaiseException
	at org.jruby.runtime.Helpers.rewriteStackTraceAndThrow(Helpers.java:2826)
	at org.jruby.javasupport.JavaCallable.handleThrowable(JavaCallable.java:155)
	at org.jruby.javasupport.JavaCallable.handleInvocationTargetEx(JavaCallable.java:163)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:434)
	at org.jruby.ir.runtime.IRRuntimeHelpers.javaProxySuper(IRRuntimeHelpers.java:1265)
	at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1216)
	at org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:131)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:100)
	at org.jruby.RubyClass.finvoke(RubyClass.java:782)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:661)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:370)
	at rubyobj.RubyConcreteExtension.getSnakeCaseAliasMethod(/Users/stephen.prosser/ws/jruby-concrete-extension/ruby_concrete_extension.rb)
	at foo.JavaSuperclass.main(JavaSuperclass.java:28)
```

I am not sure why it would be having trouble initializing the RaiseException class. The jruby-complete-9.3.6.0.jar file is on the classpath: `java -cp jruby-complete-9.3.6.0.jar:. foo.JavaSuperclass`.

`java -version` output:
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

`uname -a` output (I am running macOS Big Sur version 11.6.7):
```
Darwin C02FL27AMD6R-MB 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64
```

I searched to see if this was an intentional change from JRuby 9.2 to 9.3 or if it is a known bug, but I did not find anything that described this behavior specifically. Please let me know are there is any additional details I should provide.

**Comment by benissimo** [comment]
Possibly related: https://github.com/jruby/jruby/issues/6966#issuecomment-1172983776

**Comment by headius** [comment]
This is also likely due to the need for us to be less aggressive in accessing non-public methods, post Java 9 with modularity and strict visibility controls. Like #7220 this is not going to be fixed in 9.3. It might be fixable in 9.4 or 9.5 as we improve support for Java modules.
