### ISSUE TITLE
OpenJ9 failing -Ptest

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7470]
The OpenJ9 CI job has been failing for some months with the following failure:

```
Error:  Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.149 s <<< FAILURE! - in org.jruby.test.TestLoadService
Error:  org.jruby.test.TestLoadService.testRequireSocket  Time elapsed: 0.[271](https://github.com/jruby/jruby/actions/runs/3527450787/jobs/5916533897#step:5:272) s  <<< ERROR!
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- io/wait
```

But attempting to run locally with an OpenJ9 Java 8 from today, I get an unexpected classfile version mismatch:

```
[INFO] --- exec-maven-plugin:3.0.0:exec (invoker-generator) @ jruby-base ---
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 53.0 of class=com/jcraft/jzlib/GZIPInputStream, the maximum supported major version is 52.0; offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:783)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885)
	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:313)
	at java.lang.Class.getDeclaredMethods(Class.java:1017)
	at org.jruby.javasupport.binding.MethodGatherer$1.computeValue(MethodGatherer.java:288)
	at org.jruby.javasupport.binding.MethodGatherer$1.computeValue(MethodGatherer.java:284)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:229)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:211)
	at java.lang.ClassValue.get(ClassValue.java:117)
	at org.jruby.RubyModule$MethodClumper.clump(RubyModule.java:1278)
	at org.jruby.anno.InvokerGenerator.main(InvokerGenerator.java:78)
```

I will be ignoring failures in the build for now.

**Comment by headius** [comment]
OpenJ9 in the form of IBM Semeru 17.0.8.1 appears to run and pass `-Ptest` just fine now on my M1 Mac.
