### ISSUE TITLE
When invokedynamic is enabled: NoMethodError (super: no superclass method `previous_render_to_body'

### ISSUE THREAD

**Issue by katpadi** [jruby/jruby#7519]
**Environment Information**
 
```
JRuby version
jruby 9.3.8.0 (2.6.8) 2022-09-13 98d69c9461 OpenJDK 64-Bit Server VM 25.292-b10 on 1.8.0_292-b10 +jit [x86_64-darwin]`

JRUBY_OPTS
JRUBY_OPTS="--server -Xcompile.invokedynamic=true"

Operating system and platform
Darwin HMHX-2GG0JKMD6R 20.6.0 Darwin Kernel Version 20.6.0: Thu Sep 29 20:15:11 PDT 2022; root:xnu-7195.141.42~1/RELEASE_X86_64 x86_64

Application/framework version
Rails 6.1.7
```
**Issue**
The code is just a simple fibonacci in a Rails controller. I am trying to benchmark it using Apache Bench:
```
ab -r -c 5 -t 180 -H http://127.0.0.1:3000/api/benchmarks/fibo
```

Controller Code:
```ruby
  def fibo
    answer = fib(34)
    render plain: answer
  end

  private

  def fib(n)
    return n if n <= 1
    fib(n - 1) + fib(n - 2)
  end

```

It works when I boot up puma without `JRUBY_OPTS="-Xcompile.invokedynamic=true"`

However, when I boot up using the said JRUBY_OPTS, it returns and error:

```
Completed 500 Internal Server Error in 628ms (ActiveRecord: 0.0ms | Allocations: 0)
NoMethodError (super: no superclass method `previous_render_to_body' for #<Api::V1::BenchmarksController:0x00000000002a98>):
app/controllers/api/v1/benchmarks_controller.rb:18:in `fibo'
```

It's pointing to the line where `render plain: answer` is.

**Expected Behavior**
5702887

**Actual Behavior**
NoMethodError (super: no superclass method `previous_render_to_body' for #

NOTE: The error doesn't happen immediately. The ab command produces 200 OKs at first and then after some time returns the said error. 

Stacktrace:
```
NoMethodError (super: no superclass method `previous_render_to_body' for #<Api::V1::BenchmarksController:0x00000000003828>):

actionpack (6.1.7) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.1.7) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.1.7) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
/Users/katpadi/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/benchmark.rb:308:in `realtime'
activesupport (6.1.7) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
activerecord (6.1.7) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:45:in `render'
actionpack (6.1.7) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.1.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
org/jruby/RubyKernel.java:1940:in `tap'
actionpack (6.1.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.7) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.7) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.7) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.7) lib/active_support/callbacks.rb:106:in `run_callbacks'
actionpack (6.1.7) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.7) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.7) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.7) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.7) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.7) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.7) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.7) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.7) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.7) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
org/jruby/RubyArray.java:1865:in `each'
actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:842:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
activerecord (6.1.7) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.7) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/actionable_exceptions.rb:22:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.7) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.7) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
railties (6.1.7) lib/rails/engine.rb:539:in `call'
puma-5.6.5 (java) lib/puma/configuration.rb:252:in `call'
puma-5.6.5 (java) lib/puma/request.rb:77:in `block in handle_request'
puma-5.6.5 (java) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma-5.6.5 (java) lib/puma/request.rb:76:in `handle_request'
puma-5.6.5 (java) lib/puma/server.rb:443:in `process_client'
puma-5.6.5 (java) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by headius** [comment]
Good find. The delay is likely just due to JIT taking a while to kick in. I assume this is also broken in 9.3.9 and 9.4.

**Comment by headius** [comment]
Likely something differing in the logic for super calls between non-indy and indy dispatch.

**Comment by headius** [comment]
Could you reproduce this with the following JRuby flag, so I can see the internal backtrace? Use `-Xbacktrace.style=full` passed to JRuby.

**Comment by enebo** [comment]
Another request would be a small rails app which errors.  I can try making one but I am not sure if I will reproduce it or not.

**Comment by enebo** [comment]
I just realized this was not against 9.4 but 9.3.  Retargetting.

**Comment by headius** [comment]
This appears to work on JRuby 9.4.

**Comment by enebo** [comment]
@headius so you can reproduce this on 9.3?

**Comment by headius** [comment]
@enebo @katpadi So far, no, I cannot reproduce on 9.3. I have a test application with a simple controller that calls `render :plain` but after running for a long time it still functions properly.

@katpadi Could you push an example application that reproduces this on 9.3? Perhaps I did something differently than you.

**Comment by headius** [comment]
No follow-up since the initial report in December, and none of us can reproduce this, so I'm calling it invalid. @katpadi if you are able to provide us a reproduction against JRuby 9.3.10 we'll be happy to look into it, but it's possible other invokedynamic fixes have resolved this for you.
