### ISSUE TITLE
RSpec 3.11.0 fails to match KeyError exceptions under JRuby 9.4.0.0 (3.1.0)

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby#7540]
Ran into this as well on jruby-9.4.0.0 and rspec 3.11.0:

### `Gemfile`

```ruby
source 'https://rubygems.org'

gem 'rake'
gem 'rspec', '~> 3.0'
```

### Ruby code

```ruby
class Test

  def test
    raise(KeyError,"test")
  end

end
```

### RSpec test

```ruby
require 'spec_helper'

describe Test do
  describe "#test" do
    it "should test" do
      expect {
        subject.test
      }.to raise_error(KeyError,"test")
    end
  end
end
```

```
$ bundle exec rspec
```

### Ruby 3.1.3 (Expected Behavior)

```

Test
  #test
    should test

Finished in 0.00258 seconds (files took 0.09602 seconds to load)
1 example, 0 failures
```

### JRuby 9.4.0.0 (3.1.0) (Actual Behavior)

````
Failures:

  1) Test#test should test
     Failure/Error:
       expect {
         subject.test
       }.to raise_error(KeyError,"test")
     
       expected KeyError with "test", got #<KeyError: test> with backtrace:
         # ./lib/test.rb:4:in `test'
         # ./spec/test_spec.rb:10:in `block in <main>'
         # ./spec/test_spec.rb:11:in `block in <main>'
     # ./spec/test_spec.rb:11:in `block in <main>'
```

### Additional Information

* `jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +jit [x86_64-linux]`
* `rspec-3.11.0`
* `rspec-expectations-3.11.0`

**Comment by postmodern** [comment]
This seems kind of related to #7112 ?

**Comment by headius** [comment]
@postmodern Yes, this is the same issue. I will resolve it as duplicate and we'll fix it there.
