### ISSUE TITLE
cannot use T::Struct from sorbet-runtime due to exception

### ISSUE THREAD

**Issue by ashkulz** [jruby/jruby#7548]
**Environment Information**

```
$ jruby -v
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.5+0 on 17.0.5+0 +jit [x86_64-darwin]
$ uname -a
Darwin macbook-air.local 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64
$ gem install sorbet-runtime
Successfully installed sorbet-runtime-0.5.10598
Parsing documentation for sorbet-runtime-0.5.10598
Installing ri documentation for sorbet-runtime-0.5.10598
Done installing documentation for sorbet-runtime after 11 seconds
```

**Expected Behavior**

This was reported as sorbet/sorbet#1188 and closed as a bug in JRuby. This snippet works on CRuby:
```ruby
require 'sorbet-runtime'

class Foo < T::Struct
  prop :name, T.nilable(String)
end
```

**Actual Behavior**

On JRuby, this fails with an exception:
```
$ irb
jruby-9.4.0.0 :001 > require 'sorbet-runtime'
 => true 
jruby-9.4.0.0 :002 > 
jruby-9.4.0.0 :003?> class Foo < T::Struct
jruby-9.4.0.0 :004?>   prop :name, T.nilable(String)
jruby-9.4.0.0 :005 > end
/Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/pretty_printable.rb:54:in `valid_rule_key?': super: no superclass method `valid_rule_key?' for #<T::Props::Decorator:0xa0e33db @props={}, @class=Foo> (NoMethodError)
	from org/jruby/RubyUnboundMethod.java:143:in `bind_call'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/serializable.rb:194:in `valid_rule_key?'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/decorator.rb:229:in `block in prop_validate_definition!'
	from org/jruby/RubyArray.java:4961:in `any?'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/decorator.rb:229:in `prop_validate_definition!'
	from org/jruby/RubyUnboundMethod.java:143:in `bind_call'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/optional.rb:73:in `prop_validate_definition!'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/serializable.rb:304:in `prop_validate_definition!'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/decorator.rb:336:in `prop_defined'
	from org/jruby/RubyUnboundMethod.java:143:in `bind_call'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/props/_props.rb:115:in `prop'
	from org/jruby/RubyUnboundMethod.java:143:in `bind_call'
	from /Users/kulkarni/.rvm/gems/jruby-9.4.0.0/gems/sorbet-runtime-0.5.10598/lib/types/private/methods/call_validation.rb:256:in `validate_call'
	... 12 levels...
```

See [this comment](https://github.com/sorbet/sorbet/issues/1188#issuecomment-698975733) for an analysis on the original bug report.

**Comment by ashkulz** [comment]
@headius I'm willing to make a PR if you can point me in the right direction 🙂

**Comment by ashkulz** [comment]
The following monkey-patch seems to get our app to boot, not sure if it works properly:
```ruby
if RUBY_PLATFORM == 'java'
  # monkey-patch to workaround https://github.com/jruby/jruby/issues/7548
  module T::Props::PrettyPrintable
    module DecoratorMethods
      def valid_rule_key?(key)
        !!self.class.const_get(:VALID_RULE_KEYS)[key] || key == :inspect
      end
    end
  end
  module T::Props::Serializable::DecoratorMethods
    def valid_rule_key?(key)
      super || T::Props::Optional::DecoratorMethods.const_get(:VALID_RULE_KEYS)[key] || VALID_RULE_KEYS[key]
    end
  end
end

**Comment by headius** [comment]
This looks like a bug in how we implement `bind_call` in JRuby:

```
[] ~/work/jruby $ rvm ruby-3.1 do ruby -e 'module X; def foo; super; p :X; end; end; class A; def foo; p :A; end; end; a = A.new; X.instance_method(:foo).bind_call(a)'
:A
:X

[] ~/work/jruby $ ruby -v -e 'module X; def foo; super; p :X; end; end; class A; def foo; p :A; end; end; a = A.new; X.instance_method(:foo).bind_call(a)'
jruby 9.4.1.0-SNAPSHOT (3.1.0) 2022-11-28 d832f9fc79 OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +jit [x86_64-linux]
NoMethodError: super: no superclass method `foo' for #<A:0x77896335>
Did you mean?  for
        foo at -e:1
  bind_call at org/jruby/RubyUnboundMethod.java:143
     <main> at -e:1
... 4 levels...
```

It seems like `bind_call` should bind to the singleton instance of the object, allowing it to super from there.

**Comment by headius** [comment]
Yes, it appears that when `bind_call` was added, the logic for Method `bind` was also update to bind foreign methods (i.e. methods from another hierarchy or module) to a temporary include wrapper on the singleton class. We assumed that `bind_call` would be equivalent to the old logic for `bind().call()` but they changed that logic without documenting it.

**Comment by ashkulz** [comment]
Thanks for the very quick reply and triage, @headius!

I'm a bit surprised as the original bug report checked with Ruby 2.6 and I can reproduce it on JRuby 9.3 with the same snippet I posted above. I checked out your PR locally (_BTW, it's really very easy to build JRuby :tada:_) and it doesn't seem to help -- potentially there's a different root cause? :man_shrugging:

```
$ git rev-parse HEAD
48e5113e0c7e723650f2095c4f9522f497122167
$ ./mvnw
[lots of build output snipped]
$ bin/jruby bin/gem install sorbet-runtime
Fetching sorbet-runtime-0.5.10601.gem
Successfully installed sorbet-runtime-0.5.10601
Parsing documentation for sorbet-runtime-0.5.10601
Installing ri documentation for sorbet-runtime-0.5.10601
Done installing documentation for sorbet-runtime after 4 seconds
1 gem installed
$ bin/jruby bin/irb
irb(main):001:0> require 'sorbet-runtime'
=> true
irb(main):002:0> 
irb(main):003:1> class Foo < T::Struct
irb(main):004:1>   prop :name, T.nilable(String)
irb(main):005:0> end
/home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/pretty_printable.rb:54:in `valid_rule_key?': super: no superclass method `valid_rule_key?' for #<T::Props::Decorator:0x774c5e5c @props={}, @class=Foo> (NoMethodError)
	from org/jruby/RubyUnboundMethod.java:162:in `bind_call'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/serializable.rb:194:in `valid_rule_key?'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/decorator.rb:229:in `block in prop_validate_definition!'
	from org/jruby/RubyArray.java:4961:in `any?'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/decorator.rb:229:in `prop_validate_definition!'
	from org/jruby/RubyUnboundMethod.java:162:in `bind_call'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/optional.rb:73:in `prop_validate_definition!'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/serializable.rb:304:in `prop_validate_definition!'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/decorator.rb:336:in `prop_defined'
	from org/jruby/RubyUnboundMethod.java:162:in `bind_call'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/props/_props.rb:115:in `prop'
	from org/jruby/RubyUnboundMethod.java:162:in `bind_call'
	from /home/ashish/projects/jruby/lib/ruby/gems/shared/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/call_validation.rb:256:in `validate_call'
	... 10 levels...
```

We're currently seeing if we can get things working with JRuby 9.3, as jruby/activerecord-jdbc-adapter#1125 makes it impossible for us to proceed (and there _might_ be issues even after release :sweat_smile:). I can understand if it's not possible to backport any fix, though :+1:

**Comment by headius** [comment]
@ashkulz I find this a little bit confusing because bind_call is a Ruby 2.7 feature that was never implemented in JRuby 9.3. are you sure that is running against 9.3 and not 9.4 or master?

**Comment by headius** [comment]
@ashkulz Also, why do you have to use 9.3 if Rails 7 PostgreSQL JRuby support is not complete? Are you using Rails 7?

**Comment by ashkulz** [comment]
@headius this is on JRuby installed via rvm on Linux (_uses an older `sorbet-runtime`, last supporting Ruby 2.6_):
```
$ jruby -v
jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc OpenJDK 64-Bit Server VM 17.0.5+8-Ubuntu-2ubuntu120.04 on 17.0.5+8-Ubuntu-2ubuntu120.04 +jit [x86_64-linux]
$ gem install sorbet-runtime
Successfully installed sorbet-runtime-0.5.10461
Parsing documentation for sorbet-runtime-0.5.10461
Installing ri documentation for sorbet-runtime-0.5.10461
Done installing documentation for sorbet-runtime after 7 seconds
1 gem installed
$ irb
jruby-9.3.9.0 :001 > require 'sorbet-runtime'
 => true 
jruby-9.3.9.0 :002 > 
jruby-9.3.9.0 :003 > class Foo < T::Struct
jruby-9.3.9.0 :004?>     prop :name, T.nilable(String)
jruby-9.3.9.0 :005?>   end
Traceback (most recent call last):
       16: from org/jruby/RubyMethod.java:132:in `call'
       15: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/_props.rb:115:in `prop'
       14: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
       13: from org/jruby/RubyMethod.java:132:in `call'
       12: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/decorator.rb:336:in `prop_defined'
       11: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/serializable.rb:304:in `prop_validate_definition!'
       10: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/optional.rb:73:in `prop_validate_definition!'
        9: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
        8: from org/jruby/RubyMethod.java:132:in `call'
        7: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/decorator.rb:229:in `prop_validate_definition!'
        6: from org/jruby/RubyArray.java:4728:in `any?'
        5: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/decorator.rb:229:in `block in prop_validate_definition!'
        4: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/serializable.rb:194:in `valid_rule_key?'
        3: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
        2: from org/jruby/RubyMethod.java:132:in `call'
        1: from /usr/share/rvm/gems/jruby-9.3.9.0/gems/sorbet-runtime-0.5.10461/lib/types/props/pretty_printable.rb:23:in `valid_rule_key?'
NoMethodError (super: no superclass method `valid_rule_key?' for #<T::Props::Decorator:0x213ceb4e @props={}, @class=Foo>)
```
Sorry about linking that issue, I'm not sure what I was thinking -- we're still on Rails 6.x, but planning to dual boot Rails 7.0 in the near future :see_no_evil:

**Comment by headius** [comment]
Ok you are correct, it does appear that 2.6 has this same super behavior. I'll try to track down when it actually changed, but we should also apply fixes to 9.3 for this.

**Comment by headius** [comment]
OK I found it!

https://github.com/ruby/ruby/commit/46f578d806df70c4cae43b614e56558977a4cc44

This is where the original behavior was introduced, and a test was indeed added (which we currently exclude).

I will push another PR to introduce the same fix into 9.3.

**Comment by headius** [comment]
I merged a fix into 9.3 and rebased the 9.4 fix on top of that. This is fixed in both 9.3.10.0 and 9.4.1.0 but Github does not provide a way to set multiple release milestones.

**Comment by ashkulz** [comment]
Thanks for fixing this so quickly, @headius! :tada:

I assume it'll be included in the [next nightly snapshot](https://github.com/jruby/jruby/blob/master/.github/workflows/nightly-snapshot-publish.yml) for JRuby 9.4, but I'm not sure how `9.3.10.0-SNAPSHOT` would get created so that it [shows up in jruby-dist](https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/) -- will you have to do that manually?

**Comment by headius** [comment]
The 9.3 builds are still tied to a successful CI run, and I think we regressed due to some environment change on GHA. I'll look into that today so a snapshot can get built.

**Comment by headius** [comment]
@ashkulz We fixed our CI regression but the nightly build did not trigger. I just manually triggered it based on 9.3 HEAD and it should be available under nightly builds soon.

**Comment by ashkulz** [comment]
Thanks, @headius -- I can [see a snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/9.3.10.0-SNAPSHOT/) published :+1:
