### ISSUE TITLE
"Port already in use" errors when configuring remote JMX in 9.4

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#7641]
In JRuby 9.3 and prior, for years I've used the following Java command line arguments to set up JMX (in the env file for one of my systemd daemons):

```bash
JRUBY_OPTS="--server \
-J-Dcom.sun.management.jmxremote=true \
-J-Dcom.sun.management.jmxremote.ssl=false \
-J-Dcom.sun.management.jmxremote.port=18312 \
-J-Dcom.sun.management.jmxremote.rmi.port=18312 \
-J-Djava.rmi.server.hostname=localhost \
-J-Dcom.sun.management.jmxremote.password.file=/tmp/dummypass"
```

However, after updating to 9.4, it's failing with "Port already in use" errors. I've tried several different ports after verifying they aren't in use, and i've tried making `-J-Dcom.sun.management.jmxremote.port` different from `-J-Dcom.sun.management.jmxremote.rmi.port`, but I always get the same error below. Any idea what could be going on?
 
 ```
Error: JMX connector server communication error: service:jmx:rmi://ip-172-30-0-20:18312
jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 18312; nested exception is: 
        java.net.BindException: Address already in use
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:843)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:480)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
Caused by: java.rmi.server.ExportException: Port already in use: 18312; nested exception is: 
        java.net.BindException: Address already in use
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:415)
        at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
        at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:235)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap$PermanentExporter.exportObject(ConnectorBootstrap.java:205)
        at java.management.rmi/javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:153)
        at java.management.rmi/javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:138)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:453)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:839)
        ... 3 more
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.Net.bind(Net.java:544)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
        at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createServerSocket(TCPDirectSocketFactory.java:45)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:673)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
        ... 12 more
```

**Environment Information**
  
* JRuby version: `jruby 9.4.1.0 (3.1.0) 2023-02-07 237d5fa5f4 OpenJDK 64-Bit Server VM 17.0.6+10-LTS on 17.0.6+10-LTS +jit [x86_64-linux]`

* Operating system and platform (e.g. `uname -a`) 
Ubuntu 20.04
`Linux ns554971 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

(And just for context, I'm using JMX so I can connect processes running on the server to VisualVM on my laptop, through an ssh tunnel, so I can get insight into memory usage, garbage collection, etc)

**Comment by mohamedhafez** [comment]
Narrowed it down further, it seems to only happen when running commands with `bundle exec`, for example this works just fine:

`JRUBY_OPTS="--server -J-Dcom.sun.management.jmxremote=true -J-Dcom.sun.management.jmxremote.ssl=false -J-Dcom.sun.management.jmxremote.port=18312 -J-Dcom.sun.management.jmxremote.rmi.port=18312 -J-Djava.rmi.server.hostname=localhost -J-Dcom.sun.management.jmxremote.password.file=tmp/ipc_passwords/puma.jmx_password" irb`

but this produces the the error in the initially reported:

`JRUBY_OPTS="--server -J-Dcom.sun.management.jmxremote=true -J-Dcom.sun.management.jmxremote.ssl=false -J-Dcom.sun.management.jmxremote.port=18312 -J-Dcom.sun.management.jmxremote.rmi.port=18312 -J-Djava.rmi.server.hostname=localhost -J-Dcom.sun.management.jmxremote.password.file=tmp/ipc_passwords/puma.jmx_password" bundle exec irb`

**Comment by headius** [comment]
This is most likely because bundle exec is launching a sub process that picks up the same flags and tries to bind to the same port. Depending on the command you try to run, it may detect it is a ruby script and run it directly, or failing that, launch a sub process. I'm not sure the exact algorithm made used to determine how to launch.

I believe it's possible to specify environment variables to the bundle exec command for it to pass through to the child process. Maybe look into that?

**Comment by headius** [comment]
It's also possible something we're doing is preventing it from launching in-process, but that's just theorizing on my part. It would be a nice find if that were the case, since it would improve startup of other commands.

**Comment by mohamedhafez** [comment]
The script I'm executing ends up getting the same PID as the overall `bundle ...` command, even in cases where it fails with this error on both 9.3 and 9.4, so I don't think its that. I also couldn't reproduce with a bare bones rails install, so it might just be something with my code who knows. I'll try out some of the other options you suggested headius, thanks
