### ISSUE TITLE
Psych.load crashes with serialized string "\n\u2028* C" (used in Active Record serialize function)

### ISSUE THREAD

**Issue by Tim-Blokdijk** [jruby/jruby#7698]
```
require 'psych'
serialized_string = Psych.dump("\n\u2028* C")
deserialized_string = Psych.load(serialized_string)
```
Crashes the serializer:
```
org/jruby/ext/psych/PsychParser.java:305:in `_native_parse': (<unknown>): unexpected character found  (32) while scanning an alias at line 3 column 5 (Psych::SyntaxError)
```
**Environment Information**
JRuby version: `jruby 9.4.1.0 (3.1.0) 2023-02-07 237d5fa5f4 OpenJDK 64-Bit Server VM 11.0.17+8-post-Ubuntu-1ubuntu222.04 on 11.0.17+8-post-Ubuntu-1ubuntu222.04 +jit [x86_64-linux]`
Operating system: `Linux desktop 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Expected Behavior**
* Serialize to `"--- |2-\n\n\u2028  * C\n"`
* Deserialize back to `"\n\u2028* C"`
* To not crash

**Actual Behavior**

* Serializes to `"\x04\bI\"\f\n\xE2\x80\xA8* C\x06:\x06ET"`
* Does crash

**Comment by headius** [comment]
JRuby 9.4.1 upgrade the YAML backend SnakeYAML to a version that only accepts YAML 1.2. Perhaps this is not actually valid YAML in that spec?

@asomov Could this be a SnakeYAML Engine bug?

**Comment by headius** [comment]
The YAML dumped is below, and loading this YAML is sufficient to trigger the error. It appears to be coming from SnakeYAML.

```yaml
--- |2-

   * C
```

**Comment by Tim-Blokdijk** [comment]
The actual behavior is not serializing to: `"\x04\bI\"\f\n\xE2\x80\xA8* C\x06:\x06ET"`
It's `Marshal.dump("\n\u2028* C")` that outputs that sting, my bad.

`Psych.dump("\n\u2028* C")` outputs `"--- |2-\n\n  \u2028* C\n"`
And crashes when loaded with: `Psych.load("--- |2-\n\n  \u2028* C\n")`

**Comment by Tim-Blokdijk** [comment]
`serialized_string = Psych.dump("\n\u2028 C")` without the * after the U+2028 character does not crash but de-serializes to an empty string.

MRI Ruby does correctly process these exceptions.

**Comment by Tim-Blokdijk** [comment]
jruby-9.4.0.0 works as expected, de-serializes correctly and does not crash.

**Comment by Tim-Blokdijk** [comment]
> Perhaps this is not actually valid YAML in that spec?

[YAML 1.2.2 Spec](https://yaml.org/spec/1.2.2/) 5.4. Line Break Characters

> All other characters, including the form feed (x0C), are considered to be non-break characters. Note that these include the non-ASCII line breaks: next line (x85), line separator (x2028) and paragraph separator (x2029).
> 
> YAML version 1.1 did support the above non-ASCII line break characters; however, JSON does not. Hence, to ensure JSON compatibility, YAML treats them as non-break characters as of version 1.2. YAML 1.2 processors parsing a version 1.1 document should therefore treat these line breaks as non-break characters, with an appropriate warning.

**Comment by Tim-Blokdijk** [comment]
And yes, U+2029 triggers the same faulty behavior.

**Comment by headius** [comment]
Ok I'm still a bit confused about what is supposed to work.

This particular code also fails in CRuby 3.1:

```
$ (chruby 3.1 ; ruby -rpsych -e 'Psych.load("--- |2-\n\n  \u2028* C\n")')
/Users/headius/.rubies/ruby-3.1.3/lib/ruby/3.1.0/psych.rb:455:in `parse': (<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 4 column 1 (Psych::SyntaxError)
	from /Users/headius/.rubies/ruby-3.1.3/lib/ruby/3.1.0/psych.rb:455:in `parse_stream'
	from /Users/headius/.rubies/ruby-3.1.3/lib/ruby/3.1.0/psych.rb:399:in `parse'
	from /Users/headius/.rubies/ruby-3.1.3/lib/ruby/3.1.0/psych.rb:323:in `safe_load'
	from /Users/headius/.rubies/ruby-3.1.3/lib/ruby/3.1.0/psych.rb:369:in `load'
	from -e:1:in `<main>'
```

I'm not sure what you mean about Marshal vs Psych dumping and loading... could you update the example script to show what is wrong exactly?

**Comment by asomov** [comment]
Yes, SnakeYAML Engine explicitly **removed** the support for \u2028 to follow YAML 1.2
@headius it is not a bug, it is a feature

**Comment by asomov** [comment]
@headius I created an issue in SnakeYAML Engine. I do not see any bug now. I  added a few tests to explain.
https://bitbucket.org/snakeyaml/snakeyaml-engine/issues/46/open-psychload-crashes-with-serialized

Test:
https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/src/test/java/org/snakeyaml/engine/issues/issue46/JRuby2028Test.java

**Comment by Tim-Blokdijk** [comment]
> I'm not sure what you mean about Marshal vs Psych dumping and loading... could you update the example script to show what is wrong exactly?

Ignore anything about Marshal, it was just me trying different things on my local machine. When creating this issue I selected the Marshal output and mistakenly got it mixed up as Psych's output.

The core of the issue is that Active Record serialize uses Psych to save data.
```
serialized_string = Psych.dump("\n\u2028* C")
deserialized_string = Psych.load(serialized_string)
```
This string crashes the de-serializer with JRuby-9.4.1.0
```
serialized_string = Psych.dump("\n\u2028 C") # without the *
deserialized_string = Psych.load(serialized_string)
```
This string de-serializes to an empty string with JRuby-9.4.1.0

Same behavior with \u2029

JRuby-9.4.0.0 and MRI can correctly de-serialize these strings.

**Comment by Tim-Blokdijk** [comment]
> Yes, SnakeYAML Engine explicitly **removed** the support for \u2028 to follow YAML 1.2 @headius it is not a bug, it is a feature

`Psych.load(Psych.dump("\n \u2029"))` works, it correctly de-serializes.
`Psych.load(Psych.dump("\n\u2029* "))` also works.
`Psych.load(Psych.dump("\n\u2029*"))` but this crashes.
`Psych.load(Psych.dump("\n\u2029* 1"))` crashes.
`Psych.load(Psych.dump("\n\u2029"))` also crashes.

`Psych.load(Psych.dump("\n\u2029 1"))` empty string!

So SnakeYAML Engine does support 2028 and 2029 but fails "sometimes".

**Comment by asomov** [comment]
@Tim-Blokdijk your definitions of crash and failure are VERY confusing. There is no crash or failure. 
SnakeYAML may decide that the YAML is invalid and raise an exception. 

I will check the use cases.

**Comment by asomov** [comment]
@headius all the above use cases are parsed in SnakeYAML Engine:
https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/src/test/java/org/snakeyaml/engine/issues/issue46/JRubyPsychTest.java

I wonder why it fails to parse in JRuby.

**Comment by headius** [comment]
@asomov Ok thank you for confirming that. It could be a bug in the Psych Ruby code, since I can reproduce some of these against CRuby too.

**Comment by headius** [comment]
@Tim-Blokdijk I made your examples into a script:

```ruby
require 'psych'
["\n \u2029","\n\u2029* ","\n\u2029*","\n\u2029* 1","\n\u2029","\n\u2029 1"].each do |str|
  puts "trying #{str.inspect}"
  p Psych.load(Psych.dump(str))
rescue
  puts $!.message
end
```

CRuby does indeed handle all these cases. JRuby errors on some as shown below:

```
trying "\n \u2029"
"\n \u2029"
trying "\n\u2029* "
"\n\u2029* "
trying "\n\u2029*"
(<unknown>): unexpected character found 
(10) while scanning an alias at line 3 column 5
trying "\n\u2029* 1"
(<unknown>): unexpected character found  (32) while scanning an alias at line 3 column 5
trying "\n\u2029"
(<unknown>):  the leading empty lines contain more spaces (2) than the first non-empty line. while scanning a block scalar at line 4 column 1
trying "\n\u2029 1"
""
```

**Comment by headius** [comment]
This is most likely going to be a bug in Psych, so we're not going to be fixing it for the next JRuby release (9.4.2). We'll get it fixed in the gem and then update the shipped version in JRuby 9.4.3.

**Comment by asomov** [comment]
@headius just for your information: when I use only one slash (instead of 2 in Java), I face exactly the same errors in SnakeYAML.

**Comment by asomov** [comment]
@Tim-Blokdijk sorry, for the late message.[ I added many more tests](https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/src/test/java/org/snakeyaml/engine/issues/issue46/JRubyPsychTest.java)
May I kindly ask to review (I hope it clarifies better how SnakeYAML works)

**Comment by Tim-Blokdijk** [comment]
I'm not a Java programmer, so I can only read the test superficially. But I do see you're using the right strings here:
```
  @Test
  @DisplayName("Issue 46: parse different values")
  void parseDifferentValues() {
    parse(null, "\n \u2029");
    crash("while scanning an alias", "\n\u2029* "); // empty alias is not accepted
    crash("", "\n\u2029*"); // empty alias is not accepted
    crash("while scanning an alias", "\n\u2029* 1"); // empty alias is not accepted
    parse(null, "\n\u2029");
    parse(Integer.valueOf(1), "\n\u2029 1");
  }
```
Are these tests run somewhere? Or do you have to run them locally?

**Comment by asomov** [comment]
@Tim-Blokdijk yes, the tests are run as part of CI. You can run them locally (`./mvnw test`)
The `parse()` means it was parsed and the result is the first argument. 
`crash()` means it failed to parse
My point is that I could not detect any deviation [from the spec.](https://yaml.org/spec/1.2.2/)

**Comment by Tim-Blokdijk** [comment]
Well, "5.7. Escaped Characters" in the spec does allow for escaping x2028 and x2029. So my uninformed suspicion is that the encoder is not serializing according to spec in some situations.. and the decoder then chokes.

But irrespective of the spec, CRuby and JRuby have to use the exact same yaml serializer otherwise comparison operators will fail in Active Record attributes that are serialize'd.
And the current state is even worse as objects that have been saved to the DB years ago with MRI CRuby can now fail to initialize as parsing of a serialize'd attribute can give an error.

**Comment by headius** [comment]
Catching up here... have we determined that there's a bug to fix in JRuby (or really in the JRuby version of Psych) or is this expected behavior given our use of SnakeYAML Engine?

@Tim-Blokdijk I believe you should be able to install an older Psych that does not use SnakeYAML Engine and activate it in your app to get the old behavior. We moved to Engine because it is the path forward for SnakeYAML and because it dodges some questionable CVEs against the old SnakeYAML that people kept reporting.

The first version of Psych to use SnakeYAML Engine was 5.1.0.

**Comment by asomov** [comment]
@headius can you please try the latest snapshot ?
https://oss.sonatype.org/content/repositories/snapshots/org/snakeyaml/snakeyaml-engine/2.7-SNAPSHOT/

there are some changes for this issue
