### ISSUE TITLE
error: invalid multibyte character occurs in JRuby 9.4.2.0

### ISSUE THREAD

**Issue by ydah** [jruby/jruby#7769]
**Environment Information**

https://github.com/rubocop/rubocop/actions/runs/4781852585/jobs/8500672332
  
Provide at least:
* jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 11.0.18+10 on 11.0.18+10 +jit [x86_64-linux]
* Operating system and platform: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230417.1

**Expected Behavior**

No errors should occur.

**Actual Behavior**

Perhaps it seems experiencing problems like encoding errors that do not occur in CRuby.

```
RuntimeError:
       Error parsing example code: (string):1:5: error: invalid multibyte character: /[\Â§]/
       (string):1: r = /[\§]/
       (string):1:     ^~~~~~
     # ./lib/rubocop/rspec/expect_offense.rb:203:in `parse_processed_source'
     # ./lib/rubocop/rspec/expect_offense.rb:119:in `expect_offense'
     # ./spec/rubocop/cop/style/redundant_regexp_escape_spec.rb:623:in `block in <main>'
     # ./vendor/bundle/jruby/3.1.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block in <main>'
     # tasks/spec_runner.rake:40:in `block in run_specs'
     # tasks/spec_runner.rake:52:in `with_encoding'
     # tasks/spec_runner.rake:36:in `run_specs'
     # tasks/spec_runner.rake:164:in `block in <main>'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:1[60](https://github.com/rubocop/rubocop/actions/runs/4781852585/jobs/8500672332#step:4:61):in `invoke_task'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:[80](https://github.com/rubocop/rubocop/actions/runs/4781852585/jobs/8500672332#step:4:81):in `run'
     # ./vendor/bundle/jruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
```

**Comment by enebo** [comment]
Notes: something in the parse gem (I can see it bouncing through racc)  is calling Regexp#initialize and this is checking the syntax for errors and raising.  The actual error comes from RegexpSupport.unescapeNonAscii().  There is a mode parameter here which can be specified so that this will not raise.  I am betting however we make the regexp should be calling this with the mode set to not error.

**Comment by enebo** [comment]
Reduced to 
```text
Regexp.new(%q{[\§]})
```

We should not raise.

**Comment by enebo** [comment]
This is a simple issue to backport to 9.3.  So once landed I will also cherry-pick this back there.
