### ISSUE TITLE
Java class failed loading hides original exception

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7796]
While attempting to get Apache Arrow to load and be callable from JRuby, I ran into issues with classes that failed to initialize. The dependency chain had several required jars, and as I tried to add all the necessary libraries I got errors as classes tried to boot up that could not find other classes they were looking for.

This may be a symptom of not properly showing the full "cause" chain when printing out exceptions, or perhaps only when the "cause" chain involves non-Ruby exceptions.

Examples:

```
NameError: cannot initialize Java class org.apache.arrow.memory.RootAllocator (java.lang.ExceptionInInitializerError)
  method_missing at org/jruby/javasupport/JavaPackage.java:253
          <main> at arrow-vector.rb:7

NameError: cannot initialize Java class org.apache.arrow.memory.RootAllocator (java.lang.ExceptionInInitializerError)
                  getStackTrace at java/lang/Thread.java:2514
               getBacktraceData at org/jruby/runtime/backtrace/TraceType.java:246
                   getBacktrace at org/jruby/runtime/backtrace/TraceType.java:52
               captureBacktrace at org/jruby/RubyException.java:423
                       preRaise at org/jruby/exceptions/RaiseException.java:207
                         <init> at org/jruby/exceptions/RaiseException.java:65
                         <init> at org/jruby/exceptions/Exception.java:39
                         <init> at org/jruby/exceptions/StandardError.java:38
                         <init> at org/jruby/exceptions/NameError.java:38
             constructThrowable at org/jruby/RubyNameError.java:189
                    toThrowable at org/jruby/RubyException.java:385
                   newNameError at org/jruby/Ruby.java:4031
                   newNameError at org/jruby/Ruby.java:4077
                  loadJavaClass at org/jruby/javasupport/Java.java:1037
                  loadJavaClass at org/jruby/javasupport/Java.java:1023
```

This case is clearly hiding the original ExceptionInInitializerError which in turn hides whatever caused that error. The second trace is a full trace to show where we are improperly swallowing the exception details. Adding some exception handling at Java.java:1037 reveals the lost information:

```
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.jruby.dist/org.jruby.javasupport.JavaSupport.loadJavaClass(JavaSupport.java:328)
...
Caused by: java.lang.RuntimeException: No DefaultAllocationManager found on classpath. Can't allocate Arrow buffers. Please consider adding arrow-memory-netty or arrow-memory-unsafe as a dependency.
	at org.apache.arrow.memory.CheckAllocator.assertOnlyOne(CheckAllocator.java:81)
	at org.apache.arrow.memory.CheckAllocator.check(CheckAllocator.java:42)
	at org.apache.arrow.memory.DefaultAllocationManagerOption.getDefaultAllocationManagerFactory(DefaultAllocationManagerOption.java:98)
	at org.apache.arrow.memory.BaseAllocator$Config.getAllocationManagerFactory(BaseAllocator.java:772)
	at org.apache.arrow.memory.ImmutableConfig.access$801(ImmutableConfig.java:24)
	at org.apache.arrow.memory.ImmutableConfig$InitShim.getAllocationManagerFactory(ImmutableConfig.java:83)
	at org.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:47)
	at org.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:24)
	at org.apache.arrow.memory.ImmutableConfig$Builder.build(ImmutableConfig.java:485)
	at org.apache.arrow.memory.BaseAllocator.<clinit>(BaseAllocator.java:61)
	... 27 more
```

The chain of causes appears to log better when the exception gets raised through a Ruby to Java call (in this case, MemoryUtil needs a core Java package opened up to work properly):

```
Unhandled Java exception: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError: null
                            setZero at org/apache/arrow/memory/ArrowBuf.java:1175
                 initValidityBuffer at org/apache/arrow/vector/BaseFixedWidthVector.java:215
                         zeroVector at org/apache/arrow/vector/BaseFixedWidthVector.java:209
                      allocateBytes at org/apache/arrow/vector/BaseFixedWidthVector.java:341
                        allocateNew at org/apache/arrow/vector/BaseFixedWidthVector.java:308
                             invoke at jdk/internal/reflect/DirectMethodHandleAccessor.java:104
                             invoke at java/lang/reflect/Method.java:578
  invokeDirectWithExceptionHandling at org/jruby/javasupport/JavaMethod.java:315
                       invokeDirect at org/jruby/javasupport/JavaMethod.java:176
                               call at org/jruby/java/invokers/InstanceMethodInvoker.java:42
                       cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:466
                               call at org/jruby/runtime/callsite/CachingCallSite.java:244
         invokeOther24:allocate_new at arrow-vector.rb:19
                             <main> at arrow-vector.rb:19
...

Caused by:
java.lang.RuntimeException: Failed to initialize MemoryUtil. Was Java started with `--add-opens=java.base/java.nio=ALL-UNNAMED`? (See https://arrow.apache.org/docs/java/install.html)
                           <clinit> at org/apache/arrow/memory/util/MemoryUtil.java:138
                            setZero at org/apache/arrow/memory/ArrowBuf.java:1175
                 initValidityBuffer at org/apache/arrow/vector/BaseFixedWidthVector.java:215
                         zeroVector at org/apache/arrow/vector/BaseFixedWidthVector.java:209
                      allocateBytes at org/apache/arrow/vector/BaseFixedWidthVector.java:341
                        allocateNew at org/apache/arrow/vector/BaseFixedWidthVector.java:308
                             invoke at jdk/internal/reflect/DirectMethodHandleAccessor.java:104
                             invoke at java/lang/reflect/Method.java:578
  invokeDirectWithExceptionHandling at org/jruby/javasupport/JavaMethod.java:315
                       invokeDirect at org/jruby/javasupport/JavaMethod.java:176
                               call at org/jruby/java/invokers/InstanceMethodInvoker.java:42
                       cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:466
                               call at org/jruby/runtime/callsite/CachingCallSite.java:244
         invokeOther24:allocate_new at arrow-vector.rb:19
                        RUBY$script at arrow-vector.rb:19
...

Caused by:
java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @1a536164
   throwInaccessibleObjectException at java/lang/reflect/AccessibleObject.java:387
              checkCanSetAccessible at java/lang/reflect/AccessibleObject.java:363
              checkCanSetAccessible at java/lang/reflect/AccessibleObject.java:311
              checkCanSetAccessible at java/lang/reflect/Field.java:181
                      setAccessible at java/lang/reflect/Field.java:175
                           <clinit> at org/apache/arrow/memory/util/MemoryUtil.java:84
                            setZero at org/apache/arrow/memory/ArrowBuf.java:1175
                 initValidityBuffer at org/apache/arrow/vector/BaseFixedWidthVector.java:215
                         zeroVector at org/apache/arrow/vector/BaseFixedWidthVector.java:209
                      allocateBytes at org/apache/arrow/vector/BaseFixedWidthVector.java:341
                        allocateNew at org/apache/arrow/vector/BaseFixedWidthVector.java:308
                             invoke at jdk/internal/reflect/DirectMethodHandleAccessor.java:104
                             invoke at java/lang/reflect/Method.java:578
  invokeDirectWithExceptionHandling at org/jruby/javasupport/JavaMethod.java:315
                       invokeDirect at org/jruby/javasupport/JavaMethod.java:176
                               call at org/jruby/java/invokers/InstanceMethodInvoker.java:42
                       cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:466
                               call at org/jruby/runtime/callsite/CachingCallSite.java:244
         invokeOther24:allocate_new at arrow-vector.rb:19
                        RUBY$script at arrow-vector.rb:19
...
```

**Comment by kares** [comment]
:+1: since the cause is there maybe the `-Xlog.exceptions` logic could be adjusted to print cause like Java
