### ISSUE TITLE
Access Encoding from java code is broken on new thread

### ISSUE THREAD

**Issue by ntkme** [jruby/jruby#7820]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
  * jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 17.0.4+8-LTS on 17.0.4+8-LTS +jit [arm64-darwin]
* Operating system and platform (e.g. `uname -a`)
  * Darwin MacBook.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64

**Expected Behavior**

``` ruby
require 'java'

# This works in main thread
runtime = org.jruby.Ruby.getGlobalRuntime
puts runtime.evalScriptlet('Encoding::UTF_8')

Thread.new do
  # However, the same code is broken in new thread
  runtime = org.jruby.Ruby.getGlobalRuntime
  puts runtime.evalScriptlet('Encoding::UTF_8')
end.join
```

**Actual Behavior**

```
UTF-8
warning: thread "Ruby-0-Thread-1: repro.rb:6" terminated with exception (report_on_exception is true):
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at org.jruby.Ruby.evalScriptlet(org/jruby/Ruby.java:884)
	at org.jruby.Ruby.evalScriptlet(org/jruby/Ruby.java:860)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:344)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:205)
	at repro.invokeOther4:evalScriptlet(repro.rb:8)
	at repro.<main>(repro.rb:8)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:352)
	at java.lang.Thread.run(java/lang/Thread.java:833)
Unhandled Java exception: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
                      evalScriptlet at org/jruby/Ruby.java:884
                      evalScriptlet at org/jruby/Ruby.java:860
                            invoke0 at jdk/internal/reflect/NativeMethodAccessorImpl.java:-2
                             invoke at jdk/internal/reflect/NativeMethodAccessorImpl.java:77
                             invoke at jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43
                             invoke at java/lang/reflect/Method.java:568
  invokeDirectWithExceptionHandling at org/jruby/javasupport/JavaMethod.java:344
                       invokeDirect at org/jruby/javasupport/JavaMethod.java:205
         invokeOther4:evalScriptlet at repro.rb:8
                             <main> at repro.rb:8
                               call at org/jruby/RubyProc.java:352
                                run at java/lang/Thread.java:833
```

**Comment by ntkme** [comment]
Here is a workaround to the issue.

``` ruby
require 'java'

runtime = org.jruby.Ruby.getGlobalRuntime
puts runtime.getEncodingService.getEncoding(org.jcodings.specific.UTF8Encoding::INSTANCE)

Thread.new do
  runtime = org.jruby.Ruby.getGlobalRuntime
  puts runtime.getEncodingService.getEncoding(org.jcodings.specific.UTF8Encoding::INSTANCE)
end.join
```

**Comment by ntkme** [comment]
In real world, this breaks google-protobuf. PR for fixing protobuf using the workaround above: https://github.com/protocolbuffers/protobuf/pull/12919

**Comment by headius** [comment]
Wow that's weird.

**Comment by headius** [comment]
I opened #7824 with a possible fix. The problem here was not specific to encoding; indeed, almost any `evalScriptlet` run in another thread would trigger this because it tries to acquire the current frame's thread before we have pushed a frame.

```
[] jruby $ cat blah.rb
require 'java'

# This works in main thread
runtime = org.jruby.Ruby.getGlobalRuntime
puts runtime.evalScriptlet('1')

Thread.new do
  # However, the same code is broken in new thread
  runtime = org.jruby.Ruby.getGlobalRuntime
  puts runtime.evalScriptlet('1')
end.join%                                                                                                                                                                                                 [] jruby $ (chruby jruby-9.4.2.0 ; ruby -Xbacktrace.style=full blah.rb)
1
warning: thread "Ruby-0-Thread-1: blah.rb:7" terminated with exception (report_on_exception is true):
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at org.jruby.runtime.ThreadContext.getCurrentFrame(org/jruby/runtime/ThreadContext.java:571)
	at org.jruby.runtime.ThreadContext.getFrameSelf(org/jruby/runtime/ThreadContext.java:765)
	at org.jruby.Ruby.evalScriptlet(org/jruby/Ruby.java:884)
	at org.jruby.Ruby.evalScriptlet(org/jruby/Ruby.java:860)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:344)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:205)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(org/jruby/java/invokers/InstanceMethodInvoker.java:42)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(org/jruby/runtime/callsite/CachingCallSite.java:495)
	at org.jruby.runtime.callsite.CachingCallSite.call(org/jruby/runtime/callsite/CachingCallSite.java:244)
	at blah.invokeOther4:evalScriptlet(blah.rb:10)
	at blah.<main>(blah.rb:10)
```

This is likely leftover code from the old interpreter, which pushed more state in `preEvalScriptlet` including a frame. The new interpreter handles pushing its own frames (and the scope push may also be unnecessary here).
