### ISSUE TITLE
class com.sun.nio.file.ExtendedOpenOption cannot access class jdk.internal.misc.FileSystemOption

### ISSUE THREAD

**Issue by kares** [jruby/jruby#7835]
```
java.lang.IllegalAccessError: class com.sun.nio.file.ExtendedOpenOption (in unnamed module @0x69d33462) cannot access class jdk.internal.misc.FileSystemOption (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @0x69d33462
	at com.sun.nio.file.ExtendedOpenOption.<clinit>(ExtendedOpenOption.java:42)
	at org.jruby.util.io.ModeFlags.<clinit>(ModeFlags.java:93)
	at org.jruby.RubyFile.createFileClass(RubyFile.java:173)
	at org.jruby.Ruby.<init>(Ruby.java:451)
	at org.jruby.Ruby.newInstance(Ruby.java:716)
	at org.jruby.Ruby.newInstance(Ruby.java:705)
	at org.jruby.Ruby.getGlobalRuntime(Ruby.java:787)
```

**Environment Information**
  
Provide at least:
* JRuby version 9.3.10.0
* Operating system and platform (e.g. `uname -a`): Linux

There's `com.sun.nio.file.ExtendedOpenOption` use within JRuby, in 9.3.7.0 at attempt was made to make it work when the class is not available: https://github.com/jruby/jruby/commit/25e717f52d82b0d782bca60c68fd285ff3ee08bd

Seems the above fix `catch (NoClassDefFoundError)` is not sufficient, 
JRuby should catch `IllegalAccessError` as well and probably add `--add-opens=java.base/jdk.internal.misc=org.jruby.dist` to *bin//.jruby.module_opts* for command line use...

**Comment by sha0urya** [comment]
I want to work on this issue can you please assign it to me.

**Comment by sha0urya** [comment]
> ```
> java.lang.IllegalAccessError: class com.sun.nio.file.ExtendedOpenOption (in unnamed module @0x69d33462) cannot access class jdk.internal.misc.FileSystemOption (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @0x69d33462
> 	at com.sun.nio.file.ExtendedOpenOption.<clinit>(ExtendedOpenOption.java:42)
> 	at org.jruby.util.io.ModeFlags.<clinit>(ModeFlags.java:93)
> 	at org.jruby.RubyFile.createFileClass(RubyFile.java:173)
> 	at org.jruby.Ruby.<init>(Ruby.java:451)
> 	at org.jruby.Ruby.newInstance(Ruby.java:716)
> 	at org.jruby.Ruby.newInstance(Ruby.java:705)
> 	at org.jruby.Ruby.getGlobalRuntime(Ruby.java:787)
> ```
> 
> **Environment Information**
> 
> Provide at least:
> 
> * JRuby version 9.3.10.0
> * Operating system and platform (e.g. `uname -a`): Linux
> 
> There's `com.sun.nio.file.ExtendedOpenOption` use within JRuby, in 9.3.7.0 at attempt was made to make it work when the class is not available: [25e717f](https://github.com/jruby/jruby/commit/25e717f52d82b0d782bca60c68fd285ff3ee08bd)
> 
> Seems the above fix `catch (NoClassDefFoundError)` is not sufficient, JRuby should catch `IllegalAccessError` as well and probably add `--add-opens=java.base/jdk.internal.misc=org.jruby.dist` to _bin//.jruby.module_opts_ for command line use...



Based on the information provided, it seems that you are encountering an IllegalAccessError in JRuby due to a module access restriction. The error message suggests that the class com.sun.nio.file.ExtendedOpenOption is trying to access the class jdk.internal.misc.FileSystemOption, but the module java.base does not export jdk.internal.misc to the unnamed module.

So,it's really great if you assign this issue to me.
Thanks.!

**Comment by kares** [comment]
> So,it's really great if you assign this issue to me.

Feel free to go ahead and fire up a (draft) PR I do not think anyone else is looking into this atm.

**Comment by headius** [comment]
This is a very confusing error, because it shows `com.sun.nio.file.ExtendedOpenOption in an unnamed module. We don't error accessing that class, but that class errors accessing another internal class. I have no idea how you triggered this because a simple execution of JRuby at the command line doesn't do it:

from within `lib/`
```
$ java -jar jruby.jar -e 'puts 1'
2023-09-11T00:14:14.122+02:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
1
```

You can see that our `--add-opens` are not being applied here, and yet JRuby is able to boot and execute.

@kares How did you trigger this? I can't think of any reason that `ExtendedOpenOptions` should be showing up in an unnamed module.

**Comment by kares** [comment]
Yeah, it's like you have access to the nio (via `--add-opens`) but not to the stuff it requires.

This was triggered (unfortunately not by me) using embedded mode (starting a global runtime from Java).
Let me see if I can find the `--add-opens` in place and JDK version (not sure why I did not include those in the report).

**Comment by headius** [comment]
If you can provide a way for me to reproduce I can look into it, but I'm not sure how to trigger it right now.

**Comment by headius** [comment]
Moving this to 9.5 where we will be doing more modularity work.
