### ISSUE TITLE
Marshal.load error for Time with ivar

### ISSUE THREAD

**Issue by segiddins** [jruby/jruby#7902]
**Environment Information**
  
Provide at least:
`jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 19.0.1+10-21 on 19.0.1+10-21 +jit [arm64-darwin]`

**Expected Behavior**

The following test passes on MRI 3.2.2:

```ruby
require 'rubygems'
require 'minitest/autorun'

class T < Minitest::Test
  def test_a
    a = Marshal.load("\x04\bIu:\tTime\r\x01\xDF\x1E\x80eDI}\b:\n@type:\fruntime:\voffseti\xFE\x90\x9D:\tzoneI\"\bPDT\x06:\x06EF")
    assert_instance_of Time, a
    assert_equal :runtime, a.instance_variable_get(:@type)
    
  end
  
  def test_b
    b = Marshal.load("\x04\bIu:\tTime\r\x01\xDF\x1E\x80\x16o\x17}\t:\rsubmicro\"\x06\x00:\voffseti\xFE\x90\x9D:\tzoneI\"\bPDT\x06:\x06ET:\n@type:\fruntime")
    assert_instance_of Time, b
    assert_equal :runtime, b.instance_variable_get(:@type)
  end
  
  def test_c
    c = Marshal.load("\x04\bIu:\tTime\r\x01\xDF\x1E\x80qX\x8B/\t:\voffseti\xFE\x90\x9D:\tzoneI\"\bPDT\x06:\x06ET:\n@type:\fruntime:\rsubmicro\"\x06\x00")
    assert_instance_of Time, c
    assert_equal :runtime, c.instance_variable_get(:@type)
  end
end
```

**Actual Behavior**

On jruby:

```
jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 19.0.1+10-21 on 19.0.1+10-21 +jit [arm64-darwin]
Run options: --seed 65435

# Running:

EEE

Finished in 0.031763s, 94.4484 runs/s, 0.0000 assertions/s.

  1) Error:
T#test_a:
ArgumentError: dump format error for symbol(0xb)
    org/jruby/RubyMarshal.java:151:in `load'
    Untitled 17.rb:10:in `test_a'

  2) Error:
T#test_b:
ArgumentError: marshal data too short
    org/jruby/RubyMarshal.java:153:in `load'
    Untitled 17.rb:17:in `test_b'

  3) Error:
T#test_c:
ArgumentError: dump format error for symbol(0xd)
    org/jruby/RubyMarshal.java:151:in `load'
    Untitled 17.rb:23:in `test_c'

3 runs, 0 assertions, 0 failures, 3 errors, 0 skips
```

**Comment by headius** [comment]
📎 I see you're filing a lot of marshal bugs. Is the expectation that dumped marshal data from CRuby needs to load on JRuby, or are these bugs found using JRuby alone? We should be able to round-trip with CRuby anyway, but I'm curious how you found these.

**Comment by headius** [comment]
Oh, and do you have some code that produces these marshal dumps? It would be helpful if you could add some specs for these cases that roundtrip to and from expected data.

**Comment by segiddins** [comment]
Found them while doing https://github.com/rubygems/rubygems/pull/6896, and just seeing what was breaking both going between the different ruby impls, as well as what was working in ways I didn't expect

**Comment by headius** [comment]
@segiddins Ok thanks!

**Comment by headius** [comment]
@segiddins I am working through various Time marshaling fixes, but it would really help if I know how these particular binary strings were generated. As it is I have to squint at the marshal output or try to reverse engineer what CRuby creates from them, and I'm not sure I'm getting it quite right.

**Comment by segiddins** [comment]
I'll try to pull that together next week

**Comment by headius** [comment]
@segiddins Sorry to bug you again but I'm still unclear on how these marshal outputs were produced. I can get us passing more tests but none of them seem to hit this particular combination.
