### ISSUE TITLE
Unexpected ArgumentError calling Forwardable delegated single splat method with keyword arguments

### ISSUE THREAD

**Issue by lenny** [jruby/jruby#7918]
Inconsistency between MRI and Jruby

**Environment Information**
  

```
$ jruby -v
jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 11.0.18+10-post-Debian-1deb11u1 on 11.0.18+10-post-Debian-1deb11u1 +jit [aarch64-linux]
```

```
$ uname -a
Linux cfbc62a69df5 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 GNU/Linux
```

No `$JRUBY_OPTS`

**Other relevant information**

The bug was identified while investigating the root cause of [bug: intermittent ArgumentError from ignore_before_process on JRuby](https://github.com/rollbar/rollbar-gem/issues/1129) in the `rollbar` gem. We were using `rollbar-3.4.1` and Rails 7 (7.0.6), but the script below can be used to reproduce it independently.

*Note* - Also strange, but the script below can only reproduce the bug when loaded/required from a running app and/or IRB session. Running with `jruby splat_forwardable_bug.rb` does not reproduce it.

```
# splat_forwardable_bug.rb

require 'forwardable'

# Unexpected ArgumentError calling forwardable delegated single splat method with keyword arguments
#
# jruby-9.4.3.0
# keyword args passed for splat parameter
# on delegated method.
# If the value of the hash parameter receiving the keywork arguments
# is cleared, it can no longer be used as an argument
# to other methods.
class BugDemo
  extend Forwardable

  def_delegators :forwardee, :show_bug

  def forwardee
    @forwardee ||= Forwardee.new
  end
end

class Forwardee
  def foo(opts)
  end

  def show_bug(*args)
    _, opts = args
    opts.delete(:foo)
    raise 'opts should be empty Hash' unless opts == {}

    foo(opts)
  end
end

# This is fine
Forwardee.new.show_bug('_', foo: 'FOO')

# This is fine
BugDemo.new.show_bug('_', { foo: 'FOO' })

# This is fine
BugDemo.new.show_bug('_', {})

# This raises an error in jruby-9.4.3.0 but not mri 3.1.4
# ArgumentError: wrong number of arguments (given 0, expected 1)
# from splat_forwardable_bug.rb:22:in `foo'
begin
  BugDemo.new.show_bug('_', foo: 'FOO')
rescue ArgumentError => e
  puts 'Bug reproduced. Unexpected ArgumentError'
  raise
end

puts 'Bug not reproduced'

```

**Expected Behavior**

```
$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
> irb
irb(main):001:0> load 'splat_forwardable_bug.rb'
Bug not reproduced
```

**Actual Behavior**

```
$ irb
io/console on JRuby shells out to stty for most operations
irb(main):001:0> load 'splat_forwardable_bug.rb'
Bug reproduced. Unexpected ArgumentError
splat_forwardable_bug.rb:22:in `foo': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from splat_forwardable_bug.rb:30:in `show_bug'
        from /usr/local/rvm/rubies/jruby-9.4.3.0/lib/ruby/stdlib/forwardable.rb:238:in `show_bug'
        from splat_forwardable_bug.rb:47:in `<main>'
        from org/jruby/RubyKernel.java:1105:in `load'
        from (irb):1:in `evaluate'
        from org/jruby/RubyKernel.java:1159:in `eval'
        from org/jruby/RubyKernel.java:1601:in `loop'
        from org/jruby/RubyKernel.java:1308:in `catch'
        from org/jruby/RubyKernel.java:1308:in `catch'
        from /usr/local/rvm/rubies/jruby-9.4.3.0/lib/ruby/gems/shared/gems/irb-1.4.2/exe/irb:11:in `<main>'
        from org/jruby/RubyKernel.java:1105:in `load'
        from /usr/local/rvm/rubies/default/bin/irb:23:in `<main>'
        from org/jruby/RubyKernel.java:1159:in `eval'
        from /usr/local/rvm/rubies/default/bin/jruby_executable_hooks:22:in `<main>'
```

**Comment by lenny** [comment]
I had originally stumbled on [#6564 Unexpected ArgumentError when calling method and splatting empty hash](https://github.com/jruby/jruby/issues/6564) which looks like a similar type of issue.

**Comment by headius** [comment]
Appears to be a bug in the interpreter:

```
[] jruby $ jruby splat_forwardable.rb 
Bug not reproduced
[] jruby $ jruby -X-C splat_forwardable.rb
Bug reproduced. Unexpected ArgumentError
ArgumentError: wrong number of arguments (given 0, expected 1)
       foo at splat_forwardable.rb:24
  show_bug at splat_forwardable.rb:32
  show_bug at /Users/headius/work/jruby/lib/ruby/stdlib/forwardable.rb:238
    <main> at splat_forwardable.rb:49
```

**Comment by enebo** [comment]
I also just verified it is not specific to full interp but also startup interp.  This was extremely likely to be true but it never hurts to make sure.

**Comment by enebo** [comment]
Minimized Repro:

```ruby

class BugDemo
  def initialize
    @forwardee = Forwardee.new
  end
  
  def show_bug(*args, &block)
    @forwardee.show_bug(*args, &block)
  end
  ruby2_keywords :show_bug
end

class Forwardee
  def foo(opts)
  end

  def show_bug(*args)
    p args
    args[1].delete(:foo)
    foo(args[1])
  end
end

BugDemo.new.show_bug('_', foo: 'FOO')
```

There are several pieces which make this bug interesting.  If I swap BugDemo#show_bug to use `(...)` all is fine but this is using `ruby2_keywords` which is magicking last args value as a kwarg (which ironically is how it is being passed to it).

If I correct Forwarderr#show_bug to accept kwargs `**kwargs` then this also works as expected.

This is clearly hitting the `foo` callsite with an empty hash and deciding not to pass it as a normal hash.

So I wonder if this only works in JIT because it is hitting fixed arity path and is omitting some logic that the interpreter is not.  That would imply this accidentally works in JIT and that the basic kwarg logic is wrong in interpreter.

**Comment by enebo** [comment]
Reduced more:

```ruby
def foo(arg)
  p Hash.ruby2_keywords_hash?(arg)
end

arg = {}
arg = Hash.ruby2_keywords_hash(arg)
foo(arg)
```

So right now it looks like an empty kwarg should not get passed UNLESS it is only a kwarg by virtue of being marked one through `ruby2_keyword_hash`.

**Comment by enebo** [comment]
Fun additional observation which expands this beyond the interpreter:

```ruby
Hash.ruby2_keywords_hash({}).dup
```

internally our dup calls `initialize_dup(original)` and because it notices this is empty and kwarg it removes it somewhere.
