### ISSUE TITLE
Psych issue when running bundle cmd on a rails generator project

### ISSUE THREAD

**Issue by megatux** [jruby/jruby#7962]
> cannot load (ext) (org.jruby.ext.psych.PsychLibrary)

```
> bundle install
/home/runner/.rubies/jruby-9.4.3.0/bin/bundle config --local path /home/runner/work/htmx-rails/htmx-rails/vendor/bundle
/home/runner/.rubies/jruby-9.4.3.0/bin/bundle lock
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies............
Writing lockfile to /home/runner/work/htmx-rails/htmx-rails/Gemfile.lock
Cache key: setup-ruby-bundler-cache-v6-ubuntu-[22](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642863493?pr=9#step:4:28).04-x64-jruby-9.4.3.0-wd-/home/runner/work/htmx-rails/htmx-rails-with--without--only--Gemfile.lock-b42bbe47b7e55c13566d412e183[23](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642863493?pr=9#step:4:29)b055fb[24](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642863493?pr=9#step:4:30)ca27fb28399d3f473b954a01441
Cache Size: ~47 MB (49484407 B)
/usr/bin/tar -xf /home/runner/work/_temp/658a4ca5-6b56-41f5-a969-de012071923a/cache.tzst -P -C /home/runner/work/htmx-rails/htmx-rails --use-compress-program unzstd
Received 49484407 of 49484407 (100.0%), 47.1 MBs/sec
Cache restored successfully
Found cache for key: setup-ruby-bundler-cache-v6-ubuntu-22.04-x64-jruby-9.4.3.0-wd-/home/runner/work/htmx-rails/htmx-rails-with--without--only--Gemfile.lock-1b2ccf2fa902d23bef1[26](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642863493?pr=9#step:4:32)4e182cf7ca98171c76e8da5bada0fc5e08abe6bbaec
/home/runner/.rubies/jruby-9.4.3.0/bin/bundle install --jobs 4
--- ERROR REPORT TEMPLATE -------------------------------------------------------

``
NameError: cannot load (ext) (org.jruby.ext.psych.PsychLibrary)
  org/jruby/ext/jruby/JRubyUtilLibrary.java:219:in `load_ext'
  /home/runner/work/htmx-rails/htmx-rails/vendor/bundle/jruby/3.1.0/gems/psych-5.1.1-java/lib/psych.rb:7:in `<main>'
  org/jruby/RubyKernel.java:1071:in `require'
  /home/runner/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
  /home/runner/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/rubygems.rb:610:in `load_yaml'
  /home/runner/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/rubygems/config_file.rb:346:in `load_file'
  /home/runner/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/rubygems/config_file.rb:189:in `initialize'
  spec.add_development_dependency 'rspec'
  spec.add_development_dependency 'rubocop'
  spec.add_development_dependency 'simplecov', '~> 0.17.1'
end
``

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=cannot+load+%[28](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642863493?pr=9#step:4:34)ext%[29](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642863493?pr=9#step:4:35)+%28org.jruby.ext.psych.PsychLibrary%29&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
Error: The process '/home/runner/.rubies/jruby-9.4.3.0/bin/bundle' failed with exit code 1
```

**Environment Information**

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

jruby 9.4.3 on GH CI Ubuntu and Mac latest
[CI output](https://github.com/rootstrap/htmx-rails/actions/runs/6496272361/job/17642866996?pr=9)

* Operating system and platform (e.g. `uname -a`)

Other relevant info you may wish to add:

Locally, I installed jruby jruby-9.4.2.0 (previous version vs CI) and it is able to finish the `bundle` command but the RSpec run fails with

```
bundle update 
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.0.6
Using base64 0.1.1
Using concurrent-ruby 1.2.2
Using ruby2_keywords 0.0.5
Fetching connection_pool 2.4.1
Fetching mutex_m 0.1.2
Using builder 3.2.4
Fetching bigdecimal 3.1.4 (java)
Using erubi 1.12.0
Using ast 2.4.2
Using crass 1.0.6
Using bundler 2.4.13
Fetching minitest 5.20.0 (was 5.18.0)
Using diff-lcs 1.5.0
Using jar-dependencies 0.4.1
Using docile 1.4.0
Fetching webrick 1.8.1
Fetching racc 1.7.1 (java) (was 1.6.2)
Fetching rack 3.0.8 (was 2.2.7)
Fetching io-console 0.6.0 (java)
Installing bigdecimal 3.1.4 (java)
Installing connection_pool 2.4.1
Installing mutex_m 0.1.2
Installing webrick 1.8.1
Using thor 1.2.2
Fetching zeitwerk 2.6.12 (was 2.6.8)
Using htmx-rails 0.2.0 from source at `.`
Using json 2.6.3 (java)
Using kwalify 0.7.2
Fetching language_server-protocol 3.17.0.3
Using parallel 1.23.0
Using rainbow 3.1.1
Fetching regexp_parser 2.8.2 (was 2.8.0)
Installing minitest 5.20.0 (was 5.18.0)
Installing io-console 0.6.0 (java)
Installing racc 1.7.1 (java) (was 1.6.2)
Fetching rexml 3.2.6 (was 3.2.5)
Installing rack 3.0.8 (was 2.2.7)
Using rspec-support 3.12.1 (was 3.12.0)
Using ruby-progressbar 1.13.0
Fetching unicode-display_width 2.5.0 (was 2.4.2)
Using simplecov-html 0.10.2
Fetching drb 2.1.1
Fetching i18n 1.14.1 (was 1.13.0)
Using tzinfo 2.0.6
Fetching psych 5.1.1 (java)
Installing zeitwerk 2.6.12 (was 2.6.8)
Fetching reline 0.3.9
Installing language_server-protocol 3.17.0.3
Installing unicode-display_width 2.5.0 (was 2.4.2)
Using rspec-core 3.12.2
Using rspec-expectations 3.12.3
Using rspec-mocks 3.12.6 (was 3.12.5)
Using simplecov 0.17.1
Fetching nokogiri 1.15.4 (java) (was 1.15.2)
Installing regexp_parser 2.8.2 (was 2.8.0)
Installing drb 2.1.1
Fetching parser 3.2.2.4 (was 3.2.2.1)
Installing rexml 3.2.6 (was 3.2.5)
Fetching rack-session 2.0.0
Using rack-test 2.1.0
Fetching rackup 2.1.0
Using rspec 3.12.0
Installing i18n 1.14.1 (was 1.13.0)
Fetching activesupport 7.1.1 (was 7.0.5)
Installing reline 0.3.9
Installing psych 5.1.1 (java)
Installing rackup 2.1.0
Installing rack-session 2.0.0
  jar dependencies for psych-5.1.1-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Installing activesupport 7.1.1 (was 7.0.5)
Installing parser 3.2.2.4 (was 3.2.2.1)
Using reek 6.1.4
Fetching rubocop-ast 1.29.0 (was 1.28.1)
Installing rubocop-ast 1.29.0 (was 1.28.1)
Fetching rubocop 1.57.0 (was 1.51.0)
Installing rubocop 1.57.0 (was 1.51.0)
Installing nokogiri 1.15.4 (java) (was 1.15.2)
Fetching rails-dom-testing 2.2.0 (was 2.0.3)
Fetching loofah 2.21.4 (was 2.21.3)
Installing rails-dom-testing 2.2.0 (was 2.0.3)
Installing loofah 2.21.4 (was 2.21.3)
Using rails-html-sanitizer 1.6.0
Fetching actionview 7.1.1 (was 7.0.5)
Installing actionview 7.1.1 (was 7.0.5)
Fetching actionpack 7.1.1 (was 7.0.5)
Installing actionpack 7.1.1 (was 7.0.5)

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

2023-10-12T12:01:29.011-03:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
      org.snakeyaml:snakeyaml-engine:2.7:compile
Fetching rdoc 6.5.0
Installing rdoc 6.5.0
Fetching irb 1.8.1
Installing irb 1.8.1
Fetching railties 7.1.1 (was 7.0.5)
Installing railties 7.1.1 (was 7.0.5)
Using generator_spec 0.9.4
Bundle updated!

```

```
An error occurred while loading spec_helper.
Failure/Error: require 'generator_spec'

NameError:
  cannot load (ext) (org.jruby.ext.psych.PsychLibrary)
# ./spec/spec_helper.rb:4:in `<main>'
# ------------------
# --- Caused by: ---
# Java::JavaLang::NullPointerException:
#   inStream parameter is null
#   java.base/java.util.Objects.requireNonNull(Objects.java:259)
No examples found.
No examples found.

```

spech_helper.rb has this header:

```ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'generator_spec'
require 'simplecov'
```

**Comment by flavorjones** [comment]
I have the same issue in Nokogiri's CI pipeline: https://github.com/sparklemotion/nokogiri/actions/runs/6479652094/job/17593692848#step:4:14

**Comment by andrehjr** [comment]
I had the same issue, downgrading psych to 5.1.0 fixed it for me.

**Comment by bensheldon** [comment]
Looks like it's been reported on the `psych` library: https://github.com/ruby/psych/issues/655

**Comment by headius** [comment]
Yeah sorry for the inconvenience folks. If you pin psych to 5.1.0 it will work fine; there aren't any critical updates in 5.1.1. That version of the gem was unfortunately released with stale Java bits, resulting in it being unable to load. We'll get this sorted out with @hsbt as soon as possible.

**Comment by headius** [comment]
This is a Psych issue so we'll continue to track it at ruby/psych#655.
