### ISSUE TITLE
Attempting to use built-in bundle in jruby-complete jar throws errors

### ISSUE THREAD

**Issue by OpenSauce04** [jruby/jruby#7964]
**Environment Information**
  
jruby -v: `jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 21+35-Debian-1 on 21+35-Debian-1 +jit [x86_64-linux]`
uname -a: `Linux debianlaptop 6.5.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1 (2023-09-13) x86_64 GNU/Linux`

**Expected Behavior**

Bundle should not throw an error

**Actual Behavior**

Bundle throws an error

```
java -jar jruby-complete-9.4.3.0.jar -S bundle install
2023-10-13T10:26:41.378+01:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
Errno::EBADF: Bad file descriptor - git
                      spawn at org/jruby/RubyProcess.java:1779
                      spawn at org/jruby/RubyKernel.java:1815
                  popen_run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:222
                     popen3 at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:103
                   capture3 at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:290
  capture_and_filter_stderr at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:236
                        git at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:167
         with_clean_git_env at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/shared_helpers.rb:70
                        git at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:166
               full_version at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:83
                git_version at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/env.rb:78
                environment at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/env.rb:116
                     report at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/env.rb:17
   request_issue_report_for at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/friendly_errors.rb:67
                  log_error at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/friendly_errors.rb:53
       with_friendly_errors at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/friendly_errors.rb:126
                     <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/bundler-2.3.26/exe/bundle:36
                       load at org/jruby/RubyKernel.java:1105
                     <main> at uri:classloader:/META-INF/jruby.home/bin/bundle:23
Errno::ENOENT: No such file or directory - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/bundler.lock
               sysopen at org/jruby/RubyIO.java:1259
            initialize at org/jruby/RubyFile.java:364
                   new at org/jruby/RubyClass.java:931
                  open at org/jruby/RubyIO.java:1176
                  lock at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/process_lock.rb:9
                   run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/installer.rb:71
               install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/installer.rb:23
                   run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/cli/install.rb:62
               install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/cli.rb:257
             temporary at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/settings.rb:131
               install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/cli.rb:256
                   run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/command.rb:27
        invoke_command at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/invocation.rb:127
              dispatch at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/vendor/thor/lib/thor.rb:392
              dispatch at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/cli.rb:31
                 start at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/base.rb:485
                 start at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/cli.rb:25
                <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/bundler-2.3.26/exe/bundle:48
  with_friendly_errors at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/friendly_errors.rb:120
                <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/bundler-2.3.26/exe/bundle:36
                  load at org/jruby/RubyKernel.java:1105
                <main> at uri:classloader:/META-INF/jruby.home/bin/bundle:23
```

**Comment by headius** [comment]
I would guess this is failing because `bundle install` needs to launch subprocesses, and JRuby's subprocess often depends on some JDK internals. Could you try using the .jruby.module_opts file from the JRuby bin directory and passing it to the @java command like so?

```java @.jruby.module_opts -jar jruby-complete.jar bundle install```

Or you can copy the flags into your command line directly.

I think we should find a way for this to work without the module flags, or continue modularizing so we can specify the opens we need in some other way, but this could be a workaround for now.

**Comment by enebo** [comment]
@headius I think this line in the stack sticks out as strange:

"Errno::ENOENT: No such file or directory - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/bundler.lock"

**Comment by headius** [comment]
@enebo Hmm yeah it could also be trying to resolve the lockfile within the classloader namespace and not using the filesystem. So that would be from us putting the classloader URI as pwd when running inside a complete jar, I think.

**Comment by enebo** [comment]
heh yeah an external process will think that is a relative path in subdir `uri:classpath:` and it obviously won't be there.  What happens after that probably does not matter since it cannot read whatever that .lock contains.

**Comment by enebo** [comment]
AH...I think it is trying to make a temporary lock...we do not seem to have that file anywhere (I am not really working on this so I have not looked at bundler source to see).   If this is a significant reason it does not work it does not seem like a huge problem to fix it.

**Comment by OpenSauce04** [comment]
@headius Attempting to use the flags from .jruby.module_opts has the same error as above with the addition of these warnings:
```
java @.jruby.module_opts -jar jruby-complete-9.4.3.0.jar -S bundle install
WARNING: Unknown module: org.jruby.dist specified to --add-opens
WARNING: Unknown module: org.jruby.dist specified to --add-opens
WARNING: Unknown module: org.jruby.dist specified to --add-opens
WARNING: Unknown module: org.jruby.dist specified to --add-opens
```

**Comment by kares** [comment]
FYI: Bundler 2.x unlike 1.x will also attempt writing to .lock even if simply starting up the Bundle (unless it's explicitly told that the bundle is frozen).

I am also not sure how well `java -jar jruby-complete-9.4.3.0.jar -S bundle install` worked before, first of all Bundler is only part of stdlib since 9.3, so it wasn't even possible to attempt. I believe the only way it could ever work these days is setting `GEM_HOME` and friends.

@OpenSauce04 what are your expectations, where should it bundle install, should it consider a `Gemfile` in current WD, did you set `GEM_HOME` and `GEM_PATH` ?

**Comment by OpenSauce04** [comment]
@kares My intention is to use a `Gemfile` in the current working directory to install gems to a folder specified in `.bundle/config`

**Comment by kares** [comment]
could you maybe share your `.bundle/config` so it's clear what kind of Bundler configuration you have in place?

**Comment by OpenSauce04** [comment]
@kares Sorry for the late reply!
It's a very simple config, all it does is set the gem install path
```
---
BUNDLE_CACHE_ALL: "false"
BUNDLE_PATH: "gems"
```
I've verified that this config works as expected with a system install of JRuby

**Comment by headius** [comment]
With BUNDLE_PATH configured I was able to avoid the bundle.lock error, but it fails when trying to relaunch anything because it gets the "long" form of JRuby's command line:

```
Errno::ENOENT: No such file or directory - /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/java -cp :/Users/headius/.m2/repository/org/jruby/jruby-complete/9.4.3.0/jruby-complete-9.4.3.0.jar org.jruby.Main
  org/jruby/RubyKernel.java:1910:in `_exec_internal'
  uri:classloader:/jruby/kernel/kernel.rb:4:in `exec'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/self_manager.rb:71:in `block in restart_with'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler.rb:392:in `block in with_original_env'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler.rb:708:in `with_env'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler.rb:392:in `with_original_env'
```

It's trying to launch the full JRuby command line but that string does not resolve to an executable file and it breaks here. We have seen this problem before running from within the complete jar; many Ruby commands need to re-launch Ruby, but they expect the command to run Ruby to be a single executable file on the filesystem rather than a multi-argument command line.

This comes from `JRuby::Util.classpath_launcher`:

```
$ java -jar ~/.m2/repository/org/jruby/jruby-complete/9.4.3.0/jruby-complete-9.4.3.0.jar -e 'puts JRuby::Util.classpath_launcher'
2023-10-19T15:43:34.188-05:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/java -cp :/Users/headius/.m2/repository/org/jruby/jruby-complete/9.4.3.0/jruby-complete-9.4.3.0.jar org.jruby.Main
```

I'm not sure what the best path forward is here.

**Comment by headius** [comment]
I found a workaround: make an executable that can be used for relaunching. By setting its path into the RUBY env, we will use that path instead of the `java` command line:

```
[] jruby $ cat my_jruby.sh 
#!/bin/sh
export RUBY=$0
java -jar ~/.m2/repository/org/jruby/jruby-complete/9.4.3.0/jruby-complete-9.4.3.0.jar $@
[] jruby $ cat .bundle/config 
---
BUNDLE_PATH: "/tmp"
[] jruby $ ./my_jruby.sh -S bundle install
2023-10-19T15:52:36.950-05:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
2023-10-19T15:52:39.234-05:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.25
Fetching rspec-support 3.12.0
Fetching diff-lcs 1.5.0
Installing rspec-support 3.12.0
Installing diff-lcs 1.5.0
Fetching rspec-core 3.12.1
Fetching rspec-expectations 3.12.2
Fetching rspec-mocks 3.12.4
Installing rspec-core 3.12.1
Installing rspec-mocks 3.12.4
Installing rspec-expectations 3.12.2
Fetching rspec 3.12.0
Installing rspec 3.12.0
Bundle complete! 1 Gemfile dependency, 7 gems now installed.
Bundled gems are installed into `/tmp`
[] jruby $
```

**Comment by headius** [comment]
FYI I pushed a small PR to remove that FilenoUtil warning. Doesn't change any functionality and would not fix anything here, but it's an annoying warning eliminated: https://github.com/jruby/jruby/pull/7970

**Comment by OpenSauce04** [comment]
> I found a workaround: make an executable that can be used for relaunching. By setting its path into the RUBY env, we will use that path instead of the `java` command line:

Is there a way to make this workaround cross-platform (specifically with Windows and *nix)? I sense that this issue is pretty low priority and doesn't have a clear path forward, so using a workaround until the issue is fixed would be preferable

**Comment by headius** [comment]
Running a full JRuby environment from the complete jar is something we definitely want to support. For cases like yours, perhaps it would be useful to have a command you can run to generate a "fake" JRuby distribution directory with minimal pieces like a bin dir, a launch script, and native libraries (which tend to leak on Windows)?

**Comment by headius** [comment]
I'm not sure there's anything directly actionable here. Running bundler from the complete jar works about like we expect, but it requires the `ruby` command to be a simple executable and it needs a `BUNDLE_PATH` config set.

The executable glitch probably can and should be fixed, but that may be tricky; many places expect the current Ruby to have been launched from a single on-filesystem executable. The BUNDLE_PATH issue should probably be improved in Bundler, perhaps with a fallback to a temp location on the filesystem, or using the natural current directory.

There's potentially a JRuby feature request here to provide a "mini installer" in the complete jar that generates some of the basic command-line utilities and pre-unpacks things that need to run from the filesystem, like dynamic libraries.

@OpenSauce04 It would help us to understand what the rest of your environment is like. Why run with jruby-complete instead of a normal JRuby distribution on the filesystem? What does your ideal workflow look like?

**Comment by OpenSauce04** [comment]
I plan to bundle the jruby-complete jar with an application I'm developing.

I tried for a while to figure out a way of creating a jar for the application like you typically would with a jruby app, but I couldn't get a gem I depend on to cooperate, so I instead went the route of having jruby-complete.jar included with the app, and having a shell/bash script start the application by running the main Ruby file via jruby-complete.

**Comment by headius** [comment]
@OpenSauce04 thank you for the description of your app! It sounds like these workarounds let you move forward so that's great. I'm starting to form a picture in my head of how we might pack a partial distribution into JRuby complete that users could then unpack to get a minimal command line environment. It would still run from the complete jar, but there would be options as to how much should be unpacked.

The obvious item to include would be a bin directory with a JRuby command (possibly using the native executable launcher) that can run from the complete jar but still work like a normal distribution. Options might include unpacking native libraries like our FFI back end, unpacking bundler so it can create its lock, and unpacking the standard library or the gem hierarchy effectively making a fully installed JRuby backed by the complete jar.

@enebo I am wondering if install4j might be useful here. We could include a minimal installer as part of the complete jar.
