### ISSUE TITLE
I may have found a bug in the yaml parse of jruby - 

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jruby#7965]
Hey there jruby devs,

I may have found a bug; or perhaps a difference in behaviour between jruby and MRI ruby.

At any rate, before I describe the bug, let me copy/paste the .yml file that I used to discover
the bug (accidentally, when trying to run a commandline ruby application in jruby, as I am
testing whether I could use jruby on my windows machine eventually; I'd like to use as much
java as possible in the long run, but remain flexible too, so I am testing both graalvm + 
native-image, but also jruby; wish we could unify these two one day, without losing the
advantage of either, but I digress, so now the .yml file).

    # =========================================================================== #
    # This list is a reference. It keeps a listing of all special magical items 
    # in the world of Sarlem. Optionally it includes the location, the current 
    # carrier of it (may be nil if no carrier is known), the description, 
    # the history of the item, an image and a description of its powers. 
    # Additionally "folklore" may keep what the rumours say about this item.
    #
    # It can be german or english and a mix of both as well.
    #
    # Note that since as of September 2020, there may be dual descriptions:
    #
    #   one in german, and one in english.
    #
    # =========================================================================== #
    # Entries in [] denote
    #
    # Standard Entry should look like this:
    #
    # name:
    #  location: Johnny
    #  location_type: town
    #  current_carrier:
    #  background: |
    #   "blabla somewhere "
    #  description: |
    #   "blabla looks like so blabla"
    #  weight: 10 # in kg
    #  height: 20 # in cm
    #  history: |
    #   " history blablabla"
    #  powers:
    # =========================================================================== #
    # MAGICAL_ITEMS = YAML.load_file('/Users/x/DATA/RPG/SARLEM/YAML/magical_items.yml')
    # =========================================================================== #
    
    "Durai's Katana":
     location: Seamon (belongs to the Ko Chen clan)
     location_type: Inside a guarded clan house
     image: #
     background: |
      Durai war ein berühmter Krieger. Er lebte in Seamon und kämpfte zu 
      Lebzeiten gegen unzählige Ronins. Durch seinen Mut, Einsatz und seinem 
      taktischen Geschick, sowie seinen unglaublichen Kampfkräften konnten 
      zahlreiche schon verloren gewähnte Schlachten für den Emperor gewonnen 
      werden. Er perfektionierte den Dimak mit seinem Katana. Als er etwa 33 
      Jahre alt war, wurde seine Familie von dem verruchten Korobukuru 
      Pon-Tia niedergemetzelt. Daraufhin legte Durai sein Katana und seine 
      Insignien ab, und wurde zu einem wandernden Berserker. Er tötete einen 
      mordenden Korobukuru mit blossen Händen, nahm ihm seine schwere Axt ab 
      und jagte Pon-Tia viele Jahre lang hinterher. Dutzende Anhänger 
      Pon-Tia's starben durch Durai's Hand in den folgenden Jahren doch dem 
      gerissenen Pon-Tia gelang jedesmal die Flucht. Vergeblich versuchte 
      Durai Pon-Tia zur Strecke zu bringen. Schliesslich fiel Durai selbst 
      bei einem Attentat eines Ninja. Doch kurz nachdem seine Leiche 
      beigesetzt wurde, erwachte sein ruheloser Geist erneut, sich seiner 
      Aufgabe besindend - Pon-Tia zu töten. Über die Jahre wurde der Geist 
      verwirrt, und er jagte auch jene die Pon-Tia ähnelten. Sogar 
      ein dickliches Kind wurde von dem rastlosen Geist getötet. 
      Durai's Geist hörte schliesslich Mogi Tenshu rufen, und zog auch in 
      seine Richtung, konnte sich jedoch von dem Einfluss des untoten 
      Kamimeisters befreien und floh Richtung Süden, wo er seitdem Jagd auf 
      andere Kamis macht. Auf ewig rastlos ...
     powers:
      - Dimak (Cut Foe in Two, only against 
        ogre-down-to-goblin-sized, else "just" extra big damage)
      - Improved Parry II
      - HardToBreak III
      - Improved Speed if wielder is a true Samurai (&#20365;), by +20%
      - KForce + 8
    
    # =========================================================================== #
    # === Der Meisterstein.
    # =========================================================================== #
    "Meisterstein":
     location: somewhere on an island
     location_type: buried
     weight: 0.12  # in kg
     height: 10 # in cm
     image: #
     background: |
      The master's stone is a stone that is able to control all other Woyshat
      stones, thus truly making it the master stone. However had, it has been
      hidden since more than thousand years on an unknown island.
     background_in_german: |
      Der Meisterstein ist der Stein der alle anderen Woyshat-Steine 
      kontrollieren kann. Er ist aber schon seit tausenden Jahren 
      verschollen auf irgendeiner Insel.
     description: |
      This strange, inconspicuous stone looks as if it consists of several
      other stones. A diamond, a ruby, and a few other jewellry can be
      found in it. Interestingly enough, the stone seems to change its
      form ever so slightly. It is brilliant, attracts colour
      and glows slightly even when no sunlight appears. Touching
      it gives the person to touch it a slight feel of POWER.
     powers:
      - Control all Woyshats easily
      - Communicate with all Woyshats and know where they exist
      - Able to see what all woyshats see, hear etc...
      - Almost impossible to break
      - Can fly next to the one that controls it.
      - Gives light like a torch
    
    # =========================================================================== #
    # === Tumailamur's Dragonlance
    # =========================================================================== #
    "Tumailamur's Dragonlance":
     location: southeast of Limaal
     location_type: buried in a dragon cave, need some digging
     weight: 25  # in kg
     height: 350 # in cm
     image: ssss
     background: |
      Der grosse Drache Pardregh war eine Plage für das alte Westreich. 
      Als er schliesslich die Stadt Landeral angriff, setzte der König eine 
      hohe Belohnung auf den Kopf des Drachen.
      Ritter Tumailamur nahm sich der Sache an. Er ging zu den Zwergen und 
      bestellte eine Lanze. Nach zwei Jahren Schmiedezeit war die Lanze fertig.
      Er konnte dem Drachen sogar eine schwere Bauchwunde zufügen, aber der 
      Drache war zu gross für einen Menschen alleine und tötete Tumailamur 
      mit einem Biss. Die Lanze zog sich der Drache raus.
      
      Danach schlief er für 3 Wochen um sich von seiner Wunde zu 
      erholen. Die Lanze ist noch immer in der Drachenhöhle zu finden.
     powers:
      - Deadly Blow (Deals immense damage if wielder is able to do a 
        superior direct blow with it. Will impale i.e. humans with 
        ease, even if they have protection.)
      - HardToBreak IV
      - HardToParry II (Very hard to parry it)
    
    # =========================================================================== #
    # === Bronzern Mask of Facial Features
    # =========================================================================== #
    "Bronzern Mask of Facial Features":
     location: In possession of the carrying trader Salasar.
      Salasar normally travels near the Westreich. He is not 
      aware of the powers of this mask. 
     location_type: Inside a chest on the wagon of Salasar
     description: |
      This bronzern mask allows an attuned wearer to change 
      his face to whatever facial characteristics he desires 
      within the same general shape & size (as long as it is 
      the same gender and a humanoid race. The 'conversion' process 
      takes about 10 minutes. The concealment is not perfect 
      because the skin will look somewhat artificial, however 
      it is good enough for most purposes.
    
    # =========================================================================== #
    # === Loincloth of elemental Resistance
    # =========================================================================== #
    "Sarindels Loincloth of Elemental Resistance":
     location: Elfen tree in Middel Islands 
     location_type: On top of Sarindel
     description: |
      This grey and brown bison-skin loincloth grants a 
      strong resistance towards fire, cold, heat, ice and
      electricity IF the wearer wears no other clothes.
      (Shoes up to the ankle but not boots, helmets would be fine 
      though but the current wearer Sarindel does not use 
      helmets anyway. If other clothes are worn, the loincloth 
      can only protect at a very reduced rate.
    
    # =========================================================================== #
    # === Oku's Dagger of Slaying
    # =========================================================================== #
    "Oku's Dagger of Slaying":
     location: In Property of the Gray Puma Clan (Shinji)
     location_type: Shinji Shibata carries it
     description: |
      Dieser Dolch ist im Besitz des Grauen Puma Shinji Shibata.
    
      Man sagt, der Dolch täuscht den Betrachter, denn er ist in 
      Wirklichkeit ein längeres Ninjato, erscheint aber als Dolch. 
      Viele Menschen durchschauen diese Tarnung nicht, und wenn 
      sie dann ihren Fehler bemerken, sind sie bereits tot oder 
      schwer verwundet - so schwer das sie den Kampf verlieren werden.
      Einige Clans wissen aber das es manche Waffen gibt, die 
      unbedeutender erscheinen als sie es in Wahrheit sind ...
     powers:
      - HardToBreak II
      - KForce +4
      - Damages like Ninjato, hard to parry if wielder does not 
        know about it. Can be kept in a special, magical sheath 
        for daggers, otherwise it is as large as a Ninjato. The 
        wielder will always see the correct size. At times with 
        very low the good Yang powers, the weapon will fail to 
        conceal its size.
    
    
    # =========================================================================== #
    # Die legendären Unterarmschienen.
    # =========================================================================== #
    "StarBracers":
     location: vergraben in der Nähe Landerals
     location_type: earth
     description: |
      Diese Unterarmschienen für Menschen sind aus einem unbekannten, sehr 
      dünnen, jedoch extrem stabilen Material. Es sieht aus wie Silber, scheint 
      aber stärker zu glitzern - sogar im Dunkeln gibt es noch ein recht 
      schwaches Glühen, das man sogar als kleine "Fackel" verwenden könnte.
      Interessant ist ebenso, das sich diese Unterarmschienen beim Anlegen 
      aktiv an den Trägern anzupassen - zumindest sofern man nicht zu fette
      Unterarme hat. Stahlklingen scheinen komplett abzuprasseln von diesem 
      Unterarmschutz und die Innenseite scheint mit einer Art Lederstruktur
      beschaffen zu sein, die langsam nachwächst bei Beschädigung, und beinahe
      lebendig zu sein scheint. Einige Runen sind auf den Unterarmschienen 
      vorhanden, Runen mit vielen kleinen, geschwungenen Rechtecken und Kreisen
      die ineinander gelegt sind und mit Gold ausgelegt. Auch ein paar Symbole
      sind zu finden, wie ein Mann der mit einem gebogenem und einem geraden 
      Schwert gegen Wesen mit Flügeln und Hörnern kämpft.
     weight: 2 # beide Bracers
     length: 25 cm # Minimum.
     powers:
      - Nachwachsende Innenseite.
      - Aura die leichten Rüstungsschutz additiv hinzufügt (DSA Regel, RS +2)
      - So gut wie unzerstörbar.
      - Kann im Nahkampf als Schutz verwendet werden.
      - Provides a bit of light
     history: |
      Die Unterarmschienen stammen von Weltenreiser, der bereits gestorben
      ist. Sein Sternenschwert ist zerbrochen, aber die Unterarmschienen
      existieren weiterhin ebenso das Krummschwert.
    
    # =========================================================================== #
    # Weltenreiser's StarSabre
    # =========================================================================== #
    "StarSabre":
     location: in Weltenreisers Versteck in Ravenloft
     location_type: earth
     description: |
      Dieser Krummsäbel hat eine gezackte Klinge und eine metallisch
      rote Farbe, wie helles Blut oder dunkelrotes Kupfer. Er glänzt 
      schwach, und scheint aus schwarzrotem Stahl zu bestehen. Ein
      Rubin ist in seinem weissen Griff aus Elfenbein eingearbeitet,
      und es scheint als ob dieser Rubin ab und an leuchtet.
     weight: 3 # 
     length: 145 cm # Minimum.
     powers:
      - Fiery strike (3x / Tag). Macht Flammenschaden und geht leichter
        durch Rüstungen hindurch. Hierzu muss man den Rubin drücken mit
        dem Handballen.
      - So gut wie unzerstörbar.
      - Fireball (1x / Tag). Schickt einen Feuerball mit maximaler 
        Reichweite 30 Meter fort, der mittelschweren Schaden anrichtet.
        Hierzu muss man den Rubin längere Zeit drücken, danach kann man
        keinen Fiery strike machen für einen Tag, bis sich das Schwert
        "regeneriert".
     history: |
    
    # =========================================================================== #
    # Berserk No-Dachi
    # =========================================================================== # 
    "Berserk No-Dachi":
     location: Kenzai
     location_type: A Kenzai town
    
    # =========================================================================== #
    # Shaman Rod of remote causing Serious Wounds
    # =========================================================================== #
    "Shaman Rod of Remote causing Serious Wounds":
     location: Kenzai
     location_type: A Kenzai town
    
    
    # =========================================================================== #
    # === The Boline
    # =========================================================================== #
    "The Boline":
     location: Yibuto clan
     location_type: A Yibuto town
    
    # =========================================================================== #
    # === The Giant Club of Karthunga
    # =========================================================================== #
    "The Giant Club of Karthunga":
     location: |
      Somewhere on the jungle area of the giant turtle Mismarak, near
      the southern area.
     location_type: Giant turtle Mismarak
     powers: |
      "This huge club (around 4 Meters long) has special powers - but
      only for those that have giant strength. It can crush walls and
      stone repeatedly, without the wielder ever tiring - not to forget
      that it can easily crush through flesh and bones." 
    
    # =========================================================================== #
    # === The chest of the Fallen Dragon
    # =========================================================================== # 
    "The chest of the Fallen Dragon":
     location: somewhere buried on the eastcoast (west of Tai)
     location_type: under earth
     powers: |
      Can summon a powerful snake-Kami which will help whoever opened 
      it first. The Kami needs energy to survive (and carry out tasks) 
      and thus needs to feed on yin-yang energy. It is a powerful 
      ethereal creature. Over time the Kami and whoever opened 
      the chest will become a new magical creature.
    
The above is from a roleplaying game; some of its content is outdated, back to 25 years ago or
more and I have not updated it in ages. Anyway, the important part is this one here:

 history: |

So specifically:

" history: |

"

Psych parser in jruby does not like the empty newline. MRI psych parser has no problem
with the empty line.

I verified this is the case by adding content onto that line, to yield this:

     history: |
      abc

So when I add something, psych parser in jruby is happy with it, and the whole .yml file
is parsed without a problem.

I do not know the specification of psych/yaml, but what I can say is that MRI psych
behaves differently than jruby psych does. Without knowing the specification, I believe
that it is more likely that jruby may be in the wrong, because at the least I think having
totally empty lines should be fine in this context. The | format I usually use when I
have to describe a longer text, with several newlines, and having an empty line instead
is usually just a placeholder for later change - at the least how I use it. At any rate, I
think having the two implementations misbehave is not ideal, even if the above is 
trivial, and my personal recommendation (again, without knowing the specification)
would be to align towards the behaviour of MRI here, which I think is more flexible.
But, again, perhaps there were reasons why the psych parser in jruby behaves differently
here; I just think being able to have empty lines is more useful than erroring out on it.

Edit: Actually I can simplify the above; take this .yml file:

    "StarSabre":
     location: in Weltenreisers Versteck in Ravenloft
     location_type: earth
     description: |
      Dieser Krummsäbel hat eine gezackte Klinge und eine metallisch
      rote Farbe, wie helles Blut oder dunkelrotes Kupfer. Er glänzt 
      schwach, und scheint aus schwarzrotem Stahl zu bestehen. Ein
      Rubin ist in seinem weissen Griff aus Elfenbein eingearbeitet,
      und es scheint als ob dieser Rubin ab und an leuchtet.
     weight: 3 # 
     length: 145 cm # Minimum.
     powers:
      - So gut wie unzerstörbar.
     history: |
      abc

This one works. But if you remove the last line, the one with "abc", and make it
totally empty, then this error is shown when I load it through jirb:

    x = YAML.load_file('aha.yml')

    org/jruby/ext/psych/PsychParser.java:305:in `_native_parse': (aha.yml):  the leading empty lines contain more spaces (2) than the first non-empty line. while scanning a block scalar at line 15 column 1 (Psych::SyntaxError)
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych/parser.rb:62:in `parse'
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych.rb:455:in `parse_stream'
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych.rb:399:in `parse'
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych.rb:323:in `safe_load'
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych.rb:369:in `load'
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych.rb:671:in `block in load_file'
            from org/jruby/RubyIO.java:1178:in `open'
            from /home/Programs/Jruby/9.4.3.0/lib/ruby/stdlib/psych.rb:670:in `load_file'
            from (irb):3:in `evaluate'
            from org/jruby/RubyKernel.java:1159:in `eval'
            from org/jruby/RubyKernel.java:1601:in `loop'
            from org/jruby/RubyKernel.java:1308:in `catch'
            from org/jruby/RubyKernel.java:1308:in `catch'
            from /usr/bin/jirb:13:in `<main>'

**Comment by rubyFeedback** [comment]
Trying to upload the problematic file next:
[test_file.log](https://github.com/jruby/jruby/files/12903439/test_file.log)

**Comment by headius** [comment]
Sorry for long time getting back to you on this!

JRuby uses a more strict parser than standard Ruby, so it's possible you're hitting that. Can you confirm that the YAML we raise an error for is strictly conformant to YAML 1.2 specification?

**Comment by headius** [comment]
This is probably a YAML 1.2 thing, so I'm closing this as invalid for now. If it turns out JRuby is in error, please let us know.
