### ISSUE TITLE
Range literals are recreated per visit in JIT

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#8019]
This is a failing spec in spec/ruby/language/range_spec.rb but it has potential performance concerns.  If you have something
like

```ruby
while (i < 1000)
  1...4
end
```

This 1...4 will get recreated every loop invocation instead of once.  Operand in interpreter works because it caches the live value in the operand itself.

**Comment by headius** [comment]
Yeah I think this is the same JIT effect again. Blocks currently don't execute the jitted code the first call even with `-Xjit.threshold=0` so it runs once in the interpreter and once in the JIT. Both create and cache an instance of the range.

```
[] jruby $ spec/mspec/bin/mspec run -T-Xjit.threshold=0 spec/ruby/language/range_spec.rb
$ /Users/headius/work/jruby/bin/jruby -Xbacktrace.style=mri -Xjit.threshold=0 /Users/headius/work/jruby/spec/mspec/bin/mspec-run spec/ruby/language/range_spec.rb
/Users/headius/work/jruby/spec/mspec/lib/mspec/commands/mspec.rb:112: warning: unsupported exec option: close_others
jruby 9.4.6.0-SNAPSHOT (3.1.4) 2023-11-29 725c5cba00 OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
                                                                                             
1)
Literal Ranges creates a simple range as an object literal FAILED
Expected 1..3.equal? 1..3
to be truthy but was false
/Users/headius/work/jruby/spec/ruby/language/range_spec.rb:18:in `block in <main>'
org/jruby/RubyBasicObject.java:2620:in `instance_exec'
org/jruby/RubyArray.java:4926:in `all?'
org/jruby/RubyArray.java:1989:in `each'
/Users/headius/work/jruby/spec/ruby/language/range_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1107:in `load'
org/jruby/RubyBasicObject.java:2620:in `instance_exec'
org/jruby/RubyArray.java:1989:in `each'
[| | ==================100%================== | 00:00:00]      1F      0E 

Finished in 0.183805 seconds

1 file, 5 examples, 7 expectations, 1 failure, 0 errors, 0 tagged
```

When running with -X+C, which will compile the entire spec file before executing it, the bug goes away.

```
[] jruby $ spec/mspec/bin/mspec run -T-X+C spec/ruby/language/range_spec.rb
$ /Users/headius/work/jruby/bin/jruby -Xbacktrace.style=mri -X+C /Users/headius/work/jruby/spec/mspec/bin/mspec-run spec/ruby/language/range_spec.rb
/Users/headius/work/jruby/spec/mspec/lib/mspec/commands/mspec.rb:112: warning: unsupported exec option: close_others
jruby 9.4.6.0-SNAPSHOT (3.1.4) 2023-11-29 725c5cba00 OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
[\ | ==================100%================== | 00:00:00]      0F      0E 

Finished in 0.017737 seconds

1 file, 5 examples, 7 expectations, 0 failures, 0 errors, 0 tagged
```

So this is an issue if you are depending on these "lazy literals" to be cached exactly once. There's no fix possible currently, since we'd have to be able to populate the jitted code's cache with whatever came from the interpreter. That could have value, since it would reduce the first-time cost of calling jitted code, but it may be a lot of work for very little return.

**Comment by headius** [comment]
JIT-after-interpret change was made by me here: https://github.com/jruby/jruby/commit/b178a234fa614b8a81bef3969e24c13e68426e3e

I need to review this to see if there's any other way to mitigate it, but I know there are still big differences between how a jitted block is set up versus how an interpreted block is set up.

**Comment by enebo** [comment]
@headius it might be worth adding an generic issue for this problem when putting that number in parens with the fails(#1337): so we know why at a glance.
