### ISSUE TITLE
Flakey tests around Tempfile and multithreaded behavior

### ISSUE THREAD

**Issue by mullermp** [jruby/jruby#8023]
**Environment Information**
JRuby 9.1 to 9.4, various linux OS provided via GitHub CI

**Expected Behavior**

Tests to pass.

**Actual Behavior**
We are seeing flakey tests in test files such as these:

https://github.com/aws/aws-sdk-ruby/blob/version-3/build_tools/spec/changelog_spec.rb#L6

https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/spec/object/download_file_spec.rb#L12

https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/spec/object/upload_stream_spec.rb#L11

https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/spec/aws/plugins/endpoint_discovery_spec.rb#L7

Most of these use Tempfile and I think also just some multithreaded nonsense. I believe the failures happen on JRuby 9.1 all the way to 9.4, so it’s probably a persisted issue. If these are fixed in the latest version, that is sufficient, and we can just keep retrying as we eventually deprecate older JRuby versions over time.
Here are some example failures:

JRuby 9.2
```
  1) BuildTools::Changelog adds entries under new unreleased section when not present
     Failure/Error:
       changelog.add_entry(
         type: :feature,
         text: 'API update.'
       )

     TypeError:
       no implicit conversion of nil into Array
     # ./build_tools/changelog.rb:56:in `add_entry'
     # ./build_tools/spec/changelog_spec.rb:115:in `block in BuildTools'
```

JRuby 9.3
```
  1) Aws::Plugins::EndpointDiscovery async makes requests to fetch endpoint when enabled but not required and :active_endpoint_cache is enabled
     Failure/Error: expect(c.api_requests.size).to eq(3)

       expected: 3
            got: 2

       (compared using ==)
     # ./gems/aws-sdk-core/spec/aws/plugins/endpoint_discovery_spec.rb:280:in `block in Plugins'
```

JRuby 9.2
```
  1) BuildTools::Changelog grabs unreleased changes correctly
     Failure/Error: expect(changelog.unreleased_changes.entries).to be_empty

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./build_tools/changelog.rb:241:in `close_entry'
     # ./build_tools/changelog.rb:236:in `close_change_set'
     # ./build_tools/changelog.rb:231:in `block in parse'
     # ./build_tools/changelog.rb:62:in `unreleased_changes'
     # ./build_tools/spec/changelog_spec.rb:130:in `block in BuildTools'
```

JRuby 9.3/9.4
```
  1) Aws::S3::Object#download_file calls on_checksum_validated on multipart
     Failure/Error: expect(callback_data[:called]).to eq(4)

       expected: 4
            got: 3

       (compared using ==)
     # ./gems/aws-sdk-s3/spec/object/download_file_spec.rb:260:in `block in S3'
```

JRuby 9.2/9.4
```
 1) Aws::S3::Object#download_file reports progress for files downloaded in parts
     Failure/Error: expect(n_calls).to eq(4)

       expected: 4
            got: 3
```

**Comment by headius** [comment]
@mullermp Thanks for filing this!

Background: I had a change to chat with @mullermp and his coworker at RubyConf and they mentioned some tests that appear to be unreliable on JRuby. Since this sometimes mean we have some concurrency-related bug, I asked that they file an issue.
