### ISSUE TITLE
getsockopt test failures on arm64

### ISSUE THREAD

**Issue by jcharaoui** [jruby/jruby#8041]
Running the JRuby 9.4.3.0 `test:jruby` on arm64 Debian [unstable](https://wiki.debian.org/DebianUnstable) (OpenJDK 17.0.9), I've been encountering these failures consistently, all related to `getsockopt`:

```                                                                                                                         
Failure: test_tcp_info(SocketTest)                                                                                                                                                                                   
/tmp/autopkgtest.LCcGF4/autopkgtest_tmp/test/jruby/test_socket.rb:60:in `block in test_tcp_info'                                                                                                                     
     57:           t.join                                                                                                                                                                                            
     58:           tcp_info = client.getsockopt(Socket::IPPROTO_TCP, Socket::TCP_INFO)                                                                                                                               
     59:           state = tcp_info.unpack("C")[0]                                                                                                                                                                   
  => 60:           assert_equal(8, state) # CLOSE_WAIT                                                                                                                                                               
     61:         ensure                                                                                                                                                                                              
     62:           server.close if server && !server.closed?                                                                                                                                                         
     63:         end                                                                                                                                                                                                 
/tmp/autopkgtest.LCcGF4/autopkgtest_tmp/test/jruby/test_socket.rb:49:in `test_tcp_info'
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
<8> expected but was
<nil>
===============================================================================
..E
===============================================================================
Error: test_tcp_socket_get_keep_cnt(SocketTest): TypeError: size differ.  expected as sizeof(int)=4 but 0
org/jruby/ext/socket/Option.java:201:in `int'
/tmp/autopkgtest.LCcGF4/autopkgtest_tmp/test/jruby/test_socket.rb:197:in `test_tcp_socket_get_keep_cnt'
     194: 
     195:     def test_tcp_socket_get_keep_cnt
     196:       socket = Socket.new(Socket::AF_INET, Socket::SOCK_STREAM, 0)
  => 197:       assert_instance_of(Integer, socket.getsockopt(Socket::SOL_TCP, Socket::TCP_KEEPCNT).int)
     198:     ensure
     199:       socket.close
     200:     end
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
===============================================================================
E
===============================================================================
Error: test_tcp_socket_get_keep_idle(SocketTest): TypeError: size differ.  expected as sizeof(int)=4 but 0 
org/jruby/ext/socket/Option.java:201:in `int'
/tmp/autopkgtest.LCcGF4/autopkgtest_tmp/test/jruby/test_socket.rb:183:in `test_tcp_socket_get_keep_idle'
     180:   if RbConfig::CONFIG['target_os'] == 'linux'
     181:     def test_tcp_socket_get_keep_idle
     182:       socket = Socket.new(Socket::AF_INET, Socket::SOCK_STREAM, 0)
  => 183:       assert_instance_of(Integer, socket.getsockopt(Socket::SOL_TCP, Socket::TCP_KEEPIDLE).int)
     184:     ensure
     185:       socket.close
     186:     end
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
===============================================================================
E
===============================================================================
Error: test_tcp_socket_get_keep_intvl(SocketTest): TypeError: size differ.  expected as sizeof(int)=4 but 0
org/jruby/ext/socket/Option.java:201:in `int'
/tmp/autopkgtest.LCcGF4/autopkgtest_tmp/test/jruby/test_socket.rb:190:in `test_tcp_socket_get_keep_intvl'
     187: 
     188:     def test_tcp_socket_get_keep_intvl
     189:       socket = Socket.new(Socket::AF_INET, Socket::SOCK_STREAM, 0)
  => 190:       assert_instance_of(Integer, socket.getsockopt(Socket::SOL_TCP, Socket::TCP_KEEPINTVL).int) 
     191:     ensure
     192:       socket.close
     193:     end
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
org/jruby/RubyKernel.java:1308:in `catch'
org/jruby/RubyKernel.java:1303:in `catch'
```

These failures we're present in 9.3.9.0 on arm64. I suspected perhaps 6f7bb7d737e7dfaeaebfbb755a6a3aa2db1e752a but reverting it didn't fix the test failures.

**Comment by ahorek** [comment]
this is a known issue for <= 9.3.9.0 (arm only) and fixed by https://github.com/jruby/jruby/pull/7590

9.4.0,0+ should already include the fix

**Comment by jcharaoui** [comment]
@ahorek In Debian we're a slightly ahead on some of these dependencies:

* `jffi` 1.3.12
* `jnr-enxio` 0.32.16
* `jnr-ffi` 2.2.15
* `jnr-posix` 3.1.18
* `jnr-unisocket` 0.38.21

It could be a regression from one of these?

**Comment by ahorek** [comment]
Could you try this script in your environment? Ideally, compare it with CRuby? Also, please double check with `jruby -v` that your JRuby version is really 9.3.10.0+,
```ruby
require 'socket'

has_tcp_info = Socket.const_defined?(:TCP_INFO)
puts "TCP_INFO => #{has_tcp_info}"

if has_tcp_info
  sock = TCPSocket.open("www.google.com", 80)
  skt = sock.to_io
  tcp_info = skt.getsockopt(Socket::IPPROTO_TCP, Socket::TCP_INFO)
  p tcp_info.data
  sock.close
end
```

expected results
```
aarch64
TCP_INFO => true
"\x01\x00\x00\x00"

x86_64
TCP_INFO => true
"\x01\x00\x00\x00\x00\ax\x00P4\x03\x00\x00\x00\x00\x00x\x05\x00\x00\x18\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xDC\x05\x00\x00X\xFA\x00\x00\x92\a\x00\x00\xC9\x03\x00\x00\xFF\xFF\xFF\x7F\n\x00\x00\x00\xA8\x05\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x908\x00\x00\x00\x00\x00\x00\fu\xDC\x00\x00\x00\x00\x00\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x92\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\xFF\x00\x00"
```

I wasn't able to replicate the failure on master (same dependencies as yours), but I'm testing it on ARM Ubuntu. Perhaps it's a different issue...

**Comment by jcharaoui** [comment]
On a aarch64 qemu instance with Debian unstable, jruby `9.4.3.0+ds-1~exp1` package:

    TCP_INFO => true
    ""

**Comment by jcharaoui** [comment]
I looked a bit closer at the dependencies in Debian and spotted this patch we carry in our `jnr-ffi` package:

https://salsa.debian.org/java-team/jnr-ffi/-/blob/master/debian/patches/no-ARM64.patch

I think the reason for this patch is because we don't have `jnr-a64asm` packaged, but this can be fixed if there's reason to believe its related to the problem.

**Comment by ahorek** [comment]
Could you try a standard build without patches? Just to confirm if the mentioned patch is causing the issue...

We should probably add more guards to detect if jnr support is available on the platform, otherwise don't report these socket constants as usable.

**Comment by jcharaoui** [comment]
> Could you try a standard build without patches? Just to confirm if the mentioned patch is causing the issue...

From a vanilla git checkout of `9.4.3.0`, it does work, both the `test/jruby/test_socket.rb` and the sample code.

**Comment by jcharaoui** [comment]
For the record, I've packaged `jnr-a64asm`, dropped the patch from the Debian package of `jnr-ffi`, but the error remains.

**Comment by jcharaoui** [comment]
Ok I narrowed it down, the problem seems to be in the `jffi` native extension. I'm able to reproduce the problem in a git checkout, if I replace the bundled `lib/jni/aarch64-Linux/libjffi-1.2.so` with the version built and shipped by Debian. Closing since it's unlikely to be an issue in JRuby itself.

**Comment by jcharaoui** [comment]
Filed on the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058703
