### ISSUE TITLE
native console on MacOS not supported yet on arm64, causing test failures

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#8271]
https://github.com/enkessler/childprocess/actions/runs/9294983550/job/25581168327

```
$ bundle exec rake spec
/Users/runner/.rubies/jruby-9.4.7.0/bin/jruby -I lib:spec -w -I/Users/runner/work/childprocess/childprocess/vendor/bundle/jruby/3.1.0/gems/rspec-core-3.13.0/lib:/Users/runner/work/childprocess/childprocess/vendor/bundle/jruby/3.1.0/gems/rspec-support-3.13.1/lib /Users/runner/work/childprocess/childprocess/vendor/bundle/jruby/3.1.0/gems/rspec-core-3.13.0/exe/rspec --pattern spec/\*\*/\*_spec.rb
failed to load native console support: native console on MacOS only supported on i386, x86_64
failed to load stty console support: native console on MacOS only supported on i386, x86_64
io/console not supported; tty will not be manipulated
............................................F.........................

Failures:

  1) ChildProcess can write to stdin interactively if duplex = true
     Failure/Error: raise msg

     RuntimeError:
       timed out after 10 seconds:
       expected "hello\ncat: stdin: Resource temporarily unavailable\n" to match /\Ahello\r?\n\z/m
       Diff:
       @@ -1,2 +1,3 @@
       -/\Ahello\r?\n\z/m
       +hello
       +cat: stdin: Resource temporarily unavailable
     # ./spec/spec_helper.rb:197:in `wait_until'
     # ./spec/io_spec.rb:121:in `block in <main>'
```

Notice these 3 warnings.
Any reason native/stty console are not supported yet on darwin-arm64?

It seems to work fine on x86_64.

**Comment by headius** [comment]
To be honest I have been unable to figure out what's wrong with it. It's either something wrong in the MacOS/AArch64 FFI or something I'm missing in the FFI-based io/console for MacOS/AArch64. In order to get it working reasonably well for people I opted to disable it for now.

**Comment by eregon** [comment]
I see, maybe the `stty` backend could be enabled on MacOS/AArch64? That should work fine I'd think as it just shells out.

**Comment by eregon** [comment]
Ah maybe there isn't a `stty` backend, I was confused by that `failed to load stty console support` line above.
TruffleRuby used to have a `stty` backend but these days it uses the io-console C extension.

**Comment by eregon** [comment]
There is one: https://github.com/ruby/io-console/blob/master/lib/ffi/io/console/stty_console.rb

https://github.com/ruby/io-console/blob/74c78afc243af6f3f0435afeb5ca3518287c7244/lib/ffi/io/console.rb#L57 is showing `ex` and not `$!` (the rescue above does not assign a variable), so not sure why the `stty` backend fails to be required, that seems worth fixing.

**Comment by headius** [comment]
I merged your exception-handling PR but I do not see any errors locally. Can you provide the error in whatever environment fails to load the stty backend?

**Comment by headius** [comment]
> I do not see any errors locally

That is, on my M1 MacBook Air.

Perhaps the failure is due to the CI job you referenced not running with a real tty? I suppose if the stty backend fails to load in that situation we could force it to do so, knowing that tty manipulation won't work (but won't work any worse than the native backend on JRuby or CRuby).

**Comment by eregon** [comment]
Ah right `stty` might not work in GitHub Actions, unsure.

Ultimately this is an unexpected behavior difference between amd64 and arm64, so I guess the real solution is to support/fix the native backend on aarch64.

For the CI of childprocess it's not an immediate issue, as I changed it to run on amd64, and that test could be excluded if necessary.

**Comment by headius** [comment]
We would love to have help getting the native backend working better! I'll circle back to it when I get a chance.
