### ISSUE TITLE
Compiled jsr223 scripts caused an ArrayIndexOutOfBounds exception

### ISSUE THREAD

**Issue by jimtng** [jruby/jruby#8346]
In an OSGi environment, jruby is invoked through `new org.jruby.embed.jsr223.JRubyEngineFactory()`. When the script was first compiled and then some context added to the scriptengine, calling `eval()` on the compiled script caused an AIOBE.

This occurred on jruby 9.4.8.0 but I suspect this issue exists in prior versions too. It just happened to be noticed now because we've just started using compiled scripts.

The exception:
```
javax.script.ScriptException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:263) ~[?:?]
	at org.jruby.embed.jsr223.JRubyEngine.doEval(JRubyEngine.java:104) ~[?:?]
	at org.jruby.embed.jsr223.JRubyCompiledScript.eval(JRubyCompiledScript.java:78) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.AbstractScriptModuleHandler.eval(AbstractScriptModuleHandler.java:214) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:80) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) [?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:78) [bundleFile:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1299) [bundleFile:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:1057) [bundleFile:?]
	at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:86) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.jruby.runtime.scope.ManyVarsDynamicScope.setValueDepthZeroVoid(ManyVarsDynamicScope.java:190) ~[?:?]
	at org.jruby.runtime.scope.ManyVarsDynamicScope.setValueVoid(ManyVarsDynamicScope.java:181) ~[?:?]
	at org.jruby.runtime.DynamicScope.setValue(DynamicScope.java:337) ~[?:?]
	at org.jruby.embed.variable.VariableInterceptor.inject(VariableInterceptor.java:144) ~[?:?]
	at org.jruby.embed.internal.BiVariableMap.inject(BiVariableMap.java:380) ~[?:?]
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:111) ~[?:?]
	at org.jruby.embed.jsr223.JRubyEngine.doEval(JRubyEngine.java:99) ~[?:?]
	... 14 more

```

~~A workaround was discovered by setting the context prior to compiling the script, whilst leaving the context also being set prior to eval().~~

However, a highly simplified case to try to demonstrate what's happening failed to reproduce the problem:

```
    public static String runScript(String input) throws javax.script.ScriptException {
        var script = """
            var1 = "rubified #{$ctx["input"]}"
            var1
        """;        

        var engine = new org.jruby.embed.jsr223.JRubyEngineFactory().getScriptEngine();

        // if the context was set here prior to compilation, it would avoid the exception

        var compiled = ((javax.script.Compilable) engine).compile(script);
        var context = engine.getContext();
        var contextNew = new java.util.HashMap<>();
        contextNew.put("input", input);
        context.setAttribute("$ctx", contextNew, javax.script.ScriptContext.ENGINE_SCOPE);
        return (String)compiled.eval();
    }
```

This problem doesn't exist when calling eval(script) instead of compile(script).eval().

~~Link to the workaround: https://github.com/openhab/openhab-core/pull/4372~~

**Comment by jimtng** [comment]
Upon closer inspection, the "workaround" above didn't actually work at all.

**Comment by headius** [comment]
Oh I think I spoke too soon... you are referring to the JSR-223 ScriptEngine "compile" yes? That code in JRuby just pre-parses the script. The errors you provided indicate to me that it's not setting up the dynamic scopes for that parsed context properly, and the scope is either not large enough or it is being set up for a different set of local variables.

**Comment by headius** [comment]
It seems like the "compiled" path is calling "preEval" twice; once before the parse and once again before actually evaluating the code. Otherwise the two paths do not seem very different except that the uncompiled path parses the script each time.

You might try this patch:

```diff
diff --git a/core/src/main/java/org/jruby/embed/jsr223/JRubyCompiledScript.java b/core/src/main/java/org/jruby/embed/jsr223/JRubyCompiledScript.java
index da5557c8ea..8d4f8e7186 100644
--- a/core/src/main/java/org/jruby/embed/jsr223/JRubyCompiledScript.java
+++ b/core/src/main/java/org/jruby/embed/jsr223/JRubyCompiledScript.java
@@ -56,7 +56,6 @@ public class JRubyCompiledScript extends CompiledScript {
     JRubyCompiledScript(ScriptingContainer container, JRubyEngine engine, String script) throws RaiseException {
         this.container = container;
         this.engine = engine;
-        Utils.preEval(container, engine.getContext());
         unit = container.parse(script);
     }
 
@@ -64,7 +63,6 @@ public class JRubyCompiledScript extends CompiledScript {
         this.container = container;
         this.engine = engine;
         String filename = System.getProperty(ScriptEngine.FILENAME);
-        Utils.preEval(container, engine.getContext());
         unit = container.parse(reader, filename, Utils.getLineNumber(engine.getContext()));
     }
 
```

**Comment by jimtng** [comment]
Removing the call to `Utils.preEval` in the constructors fixed the problem. Thank you!

**Comment by headius** [comment]
I'll turn it into a PR. If you come up with any way to reproduce that we could turn into a test, that would be super helpful!

**Comment by jimtng** [comment]
This is currently still an issue.
