### ISSUE TITLE
Rubocop depencency lookup issue + custom BUNDLE_PATH

### ISSUE THREAD

**Issue by ryudoawaru** [jruby/jruby#8353]
* JRuby version: 9.4.8.0
* OS and hardware env: M1 MacOS + X86 Docker + Arm Docker

Other relevant info you may wish to add:

- Rails 7+
- Rubocop 1.16
- Custom Bundle PATH like './vendor'

**Expected Behavior**

* When I run rubocop command, it should lookup only my config fiels.

**Actual Behavior**

* It lookups all inherit dependencies of all Gems installed and raise error when any gem is not installed, the error message looks like:

```
Unable to find gem panolint; is the gem installed? Gem::MissingSpecError
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_loader_resolver.rb:283:in `gem_config_path'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_loader_resolver.rb:65:in `block in resolve_inheritance_from_gems'
org/jruby/RubyArray.java:2063:in `reverse_each'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_loader_resolver.rb:63:in `block in resolve_inheritance_from_gems'
org/jruby/RubyHash.java:1615:in `each'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_loader_resolver.rb:57:in `resolve_inheritance_from_gems'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_loader.rb:56:in `load_file'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_loader.rb:111:in `configuration_from_file'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_store.rb:68:in `for_dir'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/config_store.rb:58:in `for'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:188:in `ruby_interpreters'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:180:in `ruby_executable?'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:150:in `ruby_file?'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:75:in `to_inspect?'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:49:in `block in target_files_in_dir'
org/jruby/RubyArray.java:2882:in `select'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:49:in `target_files_in_dir'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/target_finder.rb:18:in `find'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/runner.rb:115:in `find_target_files'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/runner.rb:72:in `run'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli/command.rb:11:in `run'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli/environment.rb:18:in `run'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:122:in `run_command'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:129:in `execute_runners'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:51:in `block in run'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:81:in `profile_if_needed'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:43:in `run'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/gems/rubocop-1.66.1/exe/rubocop:19:in `<main>'
org/jruby/RubyKernel.java:1220:in `load'
/Users/ryudo/RailsPrjs/Peoplenews/vendor/jruby/3.1.0/bin/rubocop:25:in `<main>'
org/jruby/RubyKernel.java:1220:in `load'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/cli/exec.rb:23:in `run'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/cli.rb:451:in `exec'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/cli.rb:34:in `dispatch'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/cli.rb:28:in `start'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/exe/bundle:28:in `block in <main>'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Users/ryudo/.rvm/gems/jruby-9.4.8.0/gems/bundler-2.5.7/exe/bundle:20:in `<main>'
org/jruby/RubyKernel.java:1220:in `load'
```
* For example, if you have simplecov gem installed by `Gemfile.lock` config, it depends on [docile gem](https://github.com/ms-ati/docile) and the Docile gem's [rubocop config](https://github.com/ms-ati/docile/blob/main/.rubocop.yml) is with `panolint` inheritance
* This issue does not happen when you use default bundle path config.
* This issue does not happen in CRuby with same config.

**Comment by ryudoawaru** [comment]
P.S. Seems the root cause is because Rubocop + JRuby will lookup all `.rubocop.yml` under current dir, I am finding the evidence.

**Comment by ryudoawaru** [comment]
Sorry, I find it's because the Rubocop config file's exclude config, when I convert a project from CRuby to JRuby, the Rubocop config:

```yml
AllCops:
  TargetRubyVersion: 3.1.6
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/seeds.rb
    - bin/*
    - vendor/ruby/**/*
```

should change to 

```yml

AllCops:
  TargetRubyVersion: 3.1.6
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/seeds.rb
    - bin/*
    - vendor/jruby/**/*
```

Thanks!
