### ISSUE TITLE
Jruby 9.4.8.0 fails to install psych 

### ISSUE THREAD

**Issue by hurricup** [jruby/jruby#8366]
Not sure what is wrong, it looks like passes on asdf and fails on other version managers (not sure if related). Anyway:
```
stdout: [ERROR] [ERROR] Some problems were encountered while processing the POMs:
stdout: [FATAL] Non-parseable POM /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:2)  @ line 1, column 2
stdout: @
stdout: [ERROR] The build could not read 1 project -> [Help 1]
stdout: [ERROR]
stdout: [ERROR]   The project  (/home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/gemspec_pom.rb) has 1 error
stdout: [ERROR]     Non-parseable POM /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:2)  @ line 1, column 2 -> [Help 2]
stdout: [ERROR]
stdout: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
stdout: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
stdout: [ERROR]
stdout: [ERROR] For more information about the errors and possible solutions, please read the following articles:
stdout: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
stdout: [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
stderr: 2024-10-09T07:22:22.577+03:00 [Ruby-0-Thread-7@Parallel Installer Worker #1: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/worker.rb:90] INFO TraceType : Exception raised: Errno::ENOENT : No such file or directory - /home/user/.gem/jruby/3.1.4/gems/psych-5.1.2-java/deps.lst
stderr: 2024-10-09T07:22:22.577+03:00 [Ruby-0-Thread-7@Parallel Installer Worker #1: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/worker.rb:90] INFO TraceType : Exception raised: Errno::ENOENT : No such file or directory - No such file or directory
stderr: /bin/bash: line 1: chruby: command not found
stderr: 2024-10-09T07:22:22.658+03:00 [main] INFO TraceType : Exception raised: Errno::ENOENT : No such file or directory - /mnt/agent/temp/buildTmp/unitTest_MinitestRailsTest_2nBY1KlfA5bH9l9qSlysZ6CyNDA/Gemfile.lock
stderr: --- ERROR REPORT TEMPLATE -------------------------------------------------------
stderr:
stderr: ```
stderr: Errno::ENOENT: No such file or directory - /home/user/.gem/jruby/3.1.4/gems/psych-5.1.2-java/deps.lst
stderr: org/jruby/RubyIO.java:1278:in `sysopen'
stderr: org/jruby/RubyIO.java:4264:in `read'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:69:in `load_from_maven'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:235:in `install_dependencies'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:224:in `do_install'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:170:in `vendor_jars'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in <main>'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/installer.rb:367:in `block in run_post_install_hooks'
stderr: org/jruby/RubyArray.java:1981:in `each'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/installer.rb:366:in `run_post_install_hooks'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/rubygems_gem_installer.rb:46:in `install'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/source/rubygems.rb:205:in `install'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/gem_installer.rb:55:in `install'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:133:in `do_install'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:124:in `block in worker_pool'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/worker.rb:62:in `apply_func'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/worker.rb:57:in `block in process_queue'
stderr: org/jruby/RubyKernel.java:1722:in `loop'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/worker.rb:54:in `process_queue'
stderr: /home/user/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/worker.rb:90:in `block in create_threads'
stderr:
stderr: ```
stderr:
stderr: ## Environment
stderr:
stderr: ```
stderr: Bundler       2.5.21
stderr: Platforms   ruby, universal-java-1.8
stderr: Ruby          3.1.4p0 (2024-07-02 revision 4d41e55a6700cc793c1f45d6b604beea5f6c9cd8) [universal-java-1.8]
stderr: Full Path   /home/user/.rubies/jruby-9.4.8.0/bin/jruby
stderr: Config Dir  /home/user/.rubies/jruby-9.4.8.0/etc
stderr: RubyGems      3.5.21
stderr: Gem Home    /home/user/.gem/jruby/3.1.4
stderr: Gem Path    /home/user/.gem/jruby/3.1.4:/home/user/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared
stderr: User Home   /home/user
stderr: User Path   /home/user/.gem/jruby/3.1.0
stderr: Bin Dir     /home/user/.gem/jruby/3.1.4/bin
stderr: OpenSSL
stderr: Compiled    JRuby-OpenSSL 0.15.0
stderr: Loaded      JRuby-OpenSSL 0.15.0
stderr: Cert File   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
stderr: Cert Dir    /etc/ssl/certs
stderr: Tools
stderr: Git         2.34.1
stderr: RVM         not installed
stderr: rbenv       not installed
stderr: chruby
stderr: ```
stderr:
stderr: ## Bundler Build Metadata
stderr:
stderr: ```
stderr: Built At          2024-10-03
stderr: Git SHA           5cc66a2380b
stderr: Released Version  true
stderr: ```
stderr:
stderr: ## Bundler settings
stderr:
stderr: ```
stderr: gemfile
stderr: Set via BUNDLE_GEMFILE: "/mnt/agent/temp/buildTmp/unitTest_MinitestRailsTest_2nBY1KlfA5bH9l9qSlysZ6CyNDA/Gemfile"
stderr: mirror.http://rubygems.org/
stderr: Set for the current user (/home/user/.bundle/config): "https://rubygems.org/"
stderr: mirror.https://rubygems.org/
stderr: Set for the current user (/home/user/.bundle/config): "https://rubygems.org/"
stderr: ```
stderr:
stderr: ## Gemfile
stderr:
stderr: ### Gemfile
stderr:
stderr: ```ruby
stderr: source 'https://rubygems.org'
stderr:
stderr: gem 'rails', '<= 7.0.8'
stderr: gem 'activesupport', '<= 7.0.8'
stderr: gem 'minitest'
stderr: gem 'shoulda'
stderr: gem 'minitest-spec-rails'
stderr: gem 'psych', "!= 5.1.1" if RUBY_PLATFORM == 'java'
stderr: ```
stderr:
stderr: ### Gemfile.lock
stderr:
stderr: ```
stderr: <No /mnt/agent/temp/buildTmp/unitTest_MinitestRailsTest_2nBY1KlfA5bH9l9qSlysZ6CyNDA/Gemfile.lock found>
stderr: ```
stderr:
stderr: --- TEMPLATE END ----------------------------------------------------------------
stderr:
stderr: Unfortunately, an unexpected error occurred, and Bundler cannot continue.
stderr:
stderr: First, try this link to see if there are any existing issue reports for this error:
stderr: https://github.com/rubygems/rubygems/search?q=No+such+file+or+directory+-+%2Fhome%2Fuser%2F.gem%2Fjruby%2F3.1.4%2Fgems%2Fpsych-5.1.2-java%2Fdeps.lst&type=Issues
stderr:
stderr: If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
stderr: 2024-10-09T07:22:22.667+03:00 [main] INFO TraceType : Exception raised: SystemExit : exit

```

**Comment by hurricup** [comment]
Unable to reproduce locally though :(

**Comment by hurricup** [comment]
Reproduced in test container. Seems some issue with particular dependencies, but error is unclear.
1. run `docker run --rm -it rubymine/test_environment:rvm-single-ssh-jruby bash -l`
2. create a Gemfile:
```
source 'https://rubygems.org'
gem 'rails', '<= 7.0.8'
gem 'psych', "!= 5.1.1" if RUBY_PLATFORM == 'java'
```
3. run `rvm use 9.4.8`
4. run `bundle install`

**Comment by hurricup** [comment]
when running `bundle install --jobs=1` to avoid output messing, it happens anyway:
```
Fetching psych 5.1.2 (java)
Installing psych 5.1.2 (java)
  jar dependencies for psych-5.1.2-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Installing gem 'ruby-maven-libs' . . .

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:2)  @ line 1, column 2
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/gemspec_pom.rb) has 1 error
[ERROR]     Non-parseable POM /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:2)  @ line 1, column 2 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
--- ERROR REPORT TEMPLATE -------------------------------------------------------
```
```
Errno::ENOENT: No such file or directory - /home/user/.rvm/gems/jruby-9.4.8.0/gems/psych-5.1.2-java/deps.lst
  org/jruby/RubyIO.java:1278:in `sysopen'
          org/jruby/RubyIO.java:4264:in `read'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:69:in `load_from_maven'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:235:in `install_dependencies'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:224:in `do_install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/installer.rb:170:in `vendor_jars'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in <main>'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/installer.rb:367:in `block in run_post_install_hooks'
          org/jruby/RubyArray.java:1981:in `each'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/installer.rb:366:in `run_post_install_hooks'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/rubygems_gem_installer.rb:46:in `install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/source/rubygems.rb:205:in `install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/gem_installer.rb:55:in `install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:133:in `do_install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:118:in `install_serially'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:94:in `call'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:66:in `call'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer.rb:201:in `install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer.rb:87:in `block in run'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/process_lock.rb:12:in `block in lock'
          org/jruby/RubyIO.java:1197:in `open'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/process_lock.rb:9:in `lock'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer.rb:71:in `run'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/installer.rb:23:in `install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/cli/install.rb:68:in `run'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/cli.rb:247:in `block in install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/settings.rb:158:in `temporary'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/cli.rb:246:in `install'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/cli.rb:35:in `dispatch'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/cli.rb:29:in `start'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.21/exe/bundle:28:in `block in <main>'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/stdlib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /home/user/.rvm/rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/bundler-2.5.21/exe/bundle:20:in `<main>'
          org/jruby/RubyKernel.java:1220:in `load'
          /home/user/.rvm/rubies/jruby-9.4.8.0/bin/bundle:25:in `<main>'
          org/jruby/RubyKernel.java:1274:in `eval'
          /home/user/.rvm/gems/jruby-9.4.8.0/bin/jruby_executable_hooks:22:in `<main>'

```

**Comment by headius** [comment]
Oh, to address your concern about the work around, there is a patch to Maven (they broke this) that is included in the latest ruby-maven-libs gem, so it's probably sufficient to upgrade just that gem. The long-term fix will be in ruby-maven soon.

**Comment by mufan1014** [comment]
I can solve it by install newest ruby-maven-libs gem.

**Comment by ryudoawaru** [comment]
I can solve this issue by install newest 3.9.9 ruby-maven-libs.

**Comment by bensheldon** [comment]
I think #7059 is the related issue.

**Comment by headius** [comment]
@bensheldon Right you are!

The current workaround is using the patched ruby-maven-libs gem, which fixes the issue in Maven preventing polyglot poms from being detected at the root path (as it frequently is inside a Docker container).

The long-term fix is a [patch to ruby-maven](https://github.com/jruby/ruby-maven/pull/11) to always load the polyglot extension, rather than lazily trying to install polyglot-ruby maven settings near the target pom file. Reviewing the state of that PR, it seems like it was fixed and I was attempting to verify it but got slowed down by jar-dependencies always fetching a specific version.

@mkristian I can try to pick up the verification again. Assuming I can get it to work, is there any other work needed for https://github.com/jruby/ruby-maven/pull/11?

**Comment by mkristian** [comment]
@headius I tested the PR but it was a bit hacky to do the testing in place.

Testing the command `rmvn` would be one thing. To use it with jar-dependencies another. But have no idea here how to achieve this kind of testing.

**Comment by headius** [comment]
Unfortunately, due to issues getting jar-dependencies updated (https://github.com/mkristian/jar-dependencies/issues/84) I think we need to punt this to the next release. jar-dependencies has a lot of old version dependencies and has not run integration tests in some time. I'd like to get it right when we update it.

**Comment by headius** [comment]
Should be fixed by the ruby-maven and jar-dependencies updates in #8477.

**Comment by ioquatix** [comment]
Thanks!
