### ISSUE TITLE
NullPointerException in CachingCallSite.pollAndGetClass

### ISSUE THREAD

**Issue by rb2k** [jruby/jruby#885]
I ran into this:
```
Exception in thread "RubyThread-4: crawler_00_launcher.rb:1" java.lang.NullPointerException
        at org.jruby.runtime.callsite.CachingCallSite.pollAndGetClass(CachingCallSite.java:433)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
        at rubyjit.DBInserter$$insert_domain_92F22C715B6840731C519D323FF0F42DB457A79D1067935966.block_2$RUBY$__file__(/opt/Crawler/Crawler/lib/lib/db_inserter.rb:344)
        at rubyjit$DBInserter$$insert_domain_92F22C715B6840731C519D323FF0F42DB457A79D1067935966$block_2$RUBY$__file__.call(rubyjit$DBInserter$$insert_domain_92F22C715B6840731C519D323FF0F42DB457A79D1067935966$block_2$RUBY$__file__)
        at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:159)
        at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:145)
        at org.jruby.runtime.Block.yieldArray(Block.java:158)
        at org.jruby.RubyHash$23.visit(RubyHash.java:1621)
        at org.jruby.RubyHash.visitAll(RubyHash.java:636)
        at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1296)
        at org.jruby.RubyHash.delete_ifInternal(RubyHash.java:1619)
        at org.jruby.RubyHash.delete_if(RubyHash.java:1632)
        at org.jruby.RubyHash$INVOKER$i$0$0$delete_if.call(RubyHash$INVOKER$i$0$0$delete_if.gen)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
        at rubyjit.DBInserter$$insert_domain_92F22C715B6840731C519D323FF0F42DB457A79D1067935966.__file__(/opt/Crawler/Crawler/lib/lib/db_inserter.rb:344)
        at rubyjit.DBInserter$$insert_domain_92F22C715B6840731C519D323FF0F42DB457A79D1067935966.__file__(/opt/Crawler/Crawler/lib/lib/db_inserter.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
        at crawler_00_launcher.block_6$RUBY$__file__(crawler_00_launcher.rb:182)
        at crawler_00_launcher$block_6$RUBY$__file__.call(crawler_00_launcher$block_6$RUBY$__file__)
        at org.jruby.runtime.CompiledBlock19.yieldSpecificInternal(CompiledBlock19.java:117)
        at org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:92)
        at org.jruby.runtime.Block.yieldSpecific(Block.java:111)
        at org.jruby.RubyKernel.loop(RubyKernel.java:1489)
        at org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
        at crawler_00_launcher.block_5$RUBY$__file__(crawler_00_launcher.rb:89)
        at crawler_00_launcher$block_5$RUBY$__file__.call(crawler_00_launcher$block_5$RUBY$__file__)
        at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:159)
        at org.jruby.runtime.CompiledBlock19.call(CompiledBlock19.java:87)
        at org.jruby.runtime.Block.call(Block.java:101)
        at org.jruby.RubyProc.call(RubyProc.java:274)
        at org.jruby.RubyProc.call(RubyProc.java:215)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:100)
        at java.lang.Thread.run(Thread.java:724)

```

The line 344 is this piece of code:

```
    # cleanup empty values, we don't need to save nils/empty strings in the database
    new_doc.delete_if { |key,value| value.to_s.empty? }
```

**Comment by enebo** [comment]
coming on 3 years with no more info to act on.  If this problem still exists then please open a new issue.
