### ISSUE TITLE
JRuby TLS Over TCP Bug in Presence of Cert Chain

### ISSUE THREAD

**Issue by yfeldblum** [jruby/jruby#910]
See https://gist.github.com/yfeldblum/e94697b20ee7a83b8e15.

The example sets up a TCP server in a thread (using Celluloid) and then connects to it from the main thread. The two threads then perform a TLS handshake.

In the first test case, the server has got a self-signed certificate; in the second, the server has got an end certificate and a signing chain of length 1.

In the first test case, the TLS handshake succeeds. In the second, the TLS handshake fails. The particular error differs each time, but it consistently is either `Invalid Padding length: <varying number>`, `Invalid TLS padding data`, and rarely a few others that are related.

Both test cases _pass_ reliably in MRI and RBX. The first test case passes reliably in JRuby and the second test case fails reliably in JRuby.

**Comment by kares** [comment]
recent JRuby 1.7.23 (using Celluloid 0.14) output :
```
FE, [2016-01-10T21:40:01.999000 #29270] ERROR -- : CelluloidServer crashed!
OpenSSL::SSL::SSLError: Received fatal alert: certificate_unknown
	org/jruby/ext/openssl/SSLSocket.java:277:in `accept_nonblock'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-io-0.14.1/lib/celluloid/io/ssl_socket.rb:26:in `accept'
	/home/kares/workspace/oss/jruby/ossl_test.rb:76:in `handle_connection'
	/home/kares/workspace/oss/jruby/ossl_test.rb:70:in `run'
	/home/kares/workspace/oss/jruby/ossl_test.rb:63:in `accept'
	/home/kares/workspace/oss/jruby/ossl_test.rb:70:in `run'
	org/jruby/RubyKernel.java:1930:in `public_send'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/calls.rb:125:in `dispatch'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `handle_message'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `initialize'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `create'
FE, [2016-01-10T21:40:02.202000 #29270] ERROR -- : CelluloidServer crashed!
OpenSSL::SSL::SSLError: Received fatal alert: certificate_unknown
	org/jruby/ext/openssl/SSLSocket.java:277:in `accept_nonblock'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-io-0.14.1/lib/celluloid/io/ssl_socket.rb:26:in `accept'
	/home/kares/workspace/oss/jruby/ossl_test.rb:76:in `handle_connection'
	/home/kares/workspace/oss/jruby/ossl_test.rb:70:in `run'
	/home/kares/workspace/oss/jruby/ossl_test.rb:63:in `accept'
	/home/kares/workspace/oss/jruby/ossl_test.rb:70:in `run'
	org/jruby/RubyKernel.java:1930:in `public_send'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/calls.rb:125:in `dispatch'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `handle_message'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `initialize'
	/home/kares/workspace/oss/jruby/lib/ruby/gems/shared/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `create'


Failures:

  1) connecting over ssl chainless with celluloid connects
     Failure/Error: ssl_socket.connect
     OpenSSL::SSL::SSLError:
       Certificates does not conform to algorithm constraints
     # ./ossl_test.rb:137:in `with_ssl_socket'
     # ./ossl_test.rb:190:in `(root)'
     # ./ossl_test.rb:187:in `(root)'
     # ./ossl_test.rb:186:in `(root)'
     # ./ossl_test.rb:185:in `(root)'

  2) connecting over ssl chained with celluloid behaves like a server connects
     Failure/Error: ssl_socket.connect
     OpenSSL::SSL::SSLError:
       Certificates does not conform to algorithm constraints
     Shared Example Group: "a server" called from ./ossl_test.rb:237
     # ./ossl_test.rb:137:in `with_ssl_socket'
     # ./ossl_test.rb:151:in `(root)'
     # ./ossl_test.rb:148:in `(root)'
     # ./ossl_test.rb:147:in `(root)'
     # ./ossl_test.rb:146:in `(root)'

Finished in 0.553 seconds
2 examples, 2 failures

Failed examples:

rspec ./ossl_test.rb:184 # connecting over ssl chainless with celluloid connects
rspec ./ossl_test.rb:145 # connecting over ssl chained with celluloid behaves like a server connects
D, [2016-01-10T21:40:02.214000 #29270] DEBUG -- : Shutdown completed cleanly

```

**Comment by headius** [comment]
This also fails on JRuby 9.1.2 with the same errors as @kares command above.

```
  1) connecting over ssl chainless with celluloid behaves like a server connects
     Failure/Error: ssl_socket.connect

     OpenSSL::SSL::SSLError:
       Certificates does not conform to algorithm constraints
     Shared Example Group: "a server" called from ./test.rb:182
     # ./test.rb:136:in `with_ssl_socket'
     # ./test.rb:150:in `block in (root)'
     # ./test.rb:147:in `block in (root)'
     # ./test.rb:146:in `block in (root)'
     # ./test.rb:145:in `block in (root)'

  2) connecting over ssl chained with celluloid behaves like a server connects
     Failure/Error: ssl_socket.connect

     OpenSSL::SSL::SSLError:
       Certificates does not conform to algorithm constraints
     Shared Example Group: "a server" called from ./test.rb:220
     # ./test.rb:136:in `with_ssl_socket'
     # ./test.rb:150:in `block in (root)'
     # ./test.rb:147:in `block in (root)'
     # ./test.rb:146:in `block in (root)'
     # ./test.rb:145:in `block in (root)'
```
